Repository kyma-project/busola, pull requests merged in 2021-04, with the labels that each got.

#75 Change master to main
  .github/pull-request-template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#110 (Config Map, Secrets) x (create, update)
  core-ui/src/components/Predefined/Create/ConfigMaps.create.js
  core-ui/src/components/Predefined/Create/Secrets/DecodeSecretSwitch.js
  core-ui/src/components/Predefined/Create/Secrets/SecretForm.js
  core-ui/src/components/Predefined/Create/Secrets/SecretForm.scss
  core-ui/src/components/Predefined/Create/Secrets/Secrets.create.js
  core-ui/src/components/Predefined/Create/Secrets/helpers.js
  core-ui/src/components/Predefined/Create/Secrets/test/DecodeSecretSwitch.test.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/ConfigMap.details.js
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
  core-ui/src/components/Predefined/Details/ConfigMap/EditConfigMapForm.js
  core-ui/src/components/Predefined/Details/Secret.details.js
  core-ui/src/components/Predefined/Details/Secret/EditSecretForm.js
  core-ui/src/components/Predefined/Details/Secret/Secret.details.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/index.scss
  core-ui/src/shared/components/ConfigMap/ConfigMapForm.js
  core-ui/src/shared/components/ConfigMap/createConfigMapInput.js
  core-ui/src/shared/components/Secret/SecretData.js
  core-ui/src/shared/components/Secret/test/SecretData.test.js
  core-ui/src/shared/helpers/index.js
  core-ui/src/shared/helpers/safeBase64.js
  core-ui/src/shared/helpers/tests/__snapshots__/safeBase64.test.js.snap
  core-ui/src/shared/helpers/tests/safeBase64.test.js
  resources/web/deployment.yaml
  shared/components/K8sNameInput/K8sNameInput.js
  shared/components/KeyValueForm/KeyValueForm.js
  shared/components/KeyValueForm/KeyValueForm.scss
  shared/components/KeyValueForm/helpers.js
  shared/components/KeyValueForm/test/KeyValueForm.test.js
  shared/components/LabelSelectorInput/LabelSelectorInput.js
  shared/components/LabelSelectorInput/test/LabelSelectorInput.test.js
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  shared/index.js
Labels: lgtm, size/XL

#112 Fix toggles
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/CodeAndDependencies.scss
  core-ui/src/index.scss
  resources/web/deployment.yaml
Labels: lgtm, size/S

#111 Fix role bindings modal, fix apps bindings modal
  core-ui/src/components/Predefined/Create/RoleBindings/RoleBindings.js
  core-ui/src/components/Predefined/Create/RoleBindings/RoleCombobox.js
  core-ui/src/components/Predefined/Create/RoleBindings/RoleCombobox.scss
  core-ui/src/components/Predefined/Details/Application/CreateBindingModal/CreateBindingModal.js
  core-ui/src/components/Predefined/Details/Application/CreateBindingModal/CreateBindingModal.scss
  core-ui/src/index.scss
  resources/web/deployment.yaml
Labels: lgtm, size/L

#116 Fix calls for external libs
  core-ui/src/components/Predefined/Details/ConfigMap.details.js
  core-ui/src/index.js
  core-ui/src/shared/components/Secret/SecretData.js
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  service-catalog-ui/src/index.js
  shared/components/KeyValueForm/KeyValueForm.js
  shared/components/KeyValueForm/KeyValueForm.scss
  shared/index.js
  shared/utils/setupMonaco.js
Labels: lgtm, size/M

#117 Bring back window title
  core/src/luigi-config/communication.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/settings.js
  resources/web/deployment.yaml
Labels: lgtm, size/M

#118 Fix function create, update & Fundamental warnings
  core-ui/src/components/App/App.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/RepositoryConfig/RepositoryConfig.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/ResourceManagement.js
  core-ui/src/components/Lambdas/components/ResourceNameInput/ResourceNameInput.js
  core-ui/src/components/Lambdas/hooks/useUpdateLambda.js
  core-ui/src/components/ModalWithForm/ModalWithForm.js
  core-ui/src/shared/helpers/getResourceUrl.js
  core-ui/src/shared/helpers/index.js
  resources/web/deployment.yaml
Labels: lgtm, size/M

#119 Whitesource
  backend/package-lock.json
  core-ui/package-lock.json
  core/package-lock.json
  logging/package-lock.json
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/package-lock.json
  shared/package.json
  tests/package-lock.json
Labels: lgtm, size/L

#121 Add gap between columns
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/RepositoryConfig/RepositoryConfig.js
  resources/web/deployment.yaml
Labels: lgtm, size/S

#120 Fix preferences bugs
  core-ui/src/components/Preferences/AdditionalSettings.js
  core-ui/src/components/Preferences/ExperimentalFunctionalities.js
  core-ui/src/components/Preferences/NamespaceSettings.js
  core-ui/src/components/Preferences/Preferences.js
  core-ui/src/components/Preferences/Preferences.scss
  core-ui/src/components/Preferences/test/ExperimentalFunctionalities.test.js
  core-ui/src/shared/components/Secret/SecretData.scss
  core/src/luigi-config/communication.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
Labels: lgtm, size/L

#122 Improve api rule form responsiveness
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/AccessStrategyForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.scss
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/InputWithSuffix/InputWithSuffix.scss
Labels: lgtm, size/L

#124 Namespace delete redirect
  core-ui/src/components/Predefined/Create/Namespaces/Namespaces.create.js
  core-ui/src/components/Predefined/Create/Secrets/SecretForm.js
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
  core-ui/src/components/Predefined/Details/Secret/Secret.details.js
  core-ui/src/shared/components/ConfigMap/ConfigMapForm.js
  shared/components/KeyValueForm/KeyValueForm.js
  shared/components/LabelSelectorInput/LabelSelectorInput.js
  shared/components/LabelSelectorInput/LabelSelectorInput.scss
  shared/components/ResourceDetails/ResourceDetails.js
  shared/hooks/navigate.js
Labels: lgtm, size/S

#125 Fix clusterRole spacing and ApiRules JWT spacing
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/JwtDetails/JwtDetails.js
  core-ui/src/components/Predefined/Details/RoleBindings/RoleBindings.js
  core-ui/src/components/Predefined/Details/Roles/Rules.js
Labels: lgtm, size/S
