Repository kyma-project/busola, pull requests merged in 2021-09, with the labels that each got.

#369 Warn on missing translation key
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
  core-ui/src/index.js
  core/src/luigi-config/luigi-config.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#373 Bump backend resources
  resources/backend/deployment.yaml
  resources/backend/hpa.yaml
Labels: size/S, lgtm

#375 Fix buttons translations for custom resources
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResources.details.js
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
Labels: size/XS, lgtm

#360 Create for BTP instances & bindings
  core-ui/src/components/Predefined/Create/Deployments/CreateDeploymentForm.js
  core-ui/src/components/Predefined/Create/ServiceBindings/AdvancedForm.js
  core-ui/src/components/Predefined/Create/ServiceBindings/SecretRefForm/SecretRefForm.js
  core-ui/src/components/Predefined/Create/ServiceBindings/SecretRefForm/SecretRefFrom.scss
  core-ui/src/components/Predefined/Create/ServiceBindings/ServiceBindingAdvancedForm.scss
  core-ui/src/components/Predefined/Create/ServiceBindings/ServiceBindings.create.js
  core-ui/src/components/Predefined/Create/ServiceBindings/SimpleForm.js
  core-ui/src/components/Predefined/Create/ServiceBindings/helpers.js
  core-ui/src/components/Predefined/Create/ServiceInstances/AdvancedForm.js
  core-ui/src/components/Predefined/Create/ServiceInstances/ServiceInstances.create.js
  core-ui/src/components/Predefined/Create/ServiceInstances/SimpleForm.js
  core-ui/src/components/Predefined/Create/ServiceInstances/helpers.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/ServiceBinding/ServiceBinding.details.js
  core-ui/src/index.scss
  core-ui/src/shared/components/BTPResourceStatus.js
  core-ui/src/shared/components/CreateForm/CollapsibleSection/CollapsibleSection.scss
  core-ui/src/shared/components/CreateForm/CreateForm.js
  core-ui/src/shared/components/CreateForm/JSONInputSection.js
  core-ui/src/shared/components/K8sResourceSelect.js
  core/src/i18n/en.yaml
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  shared/components/K8sNameInput/K8sNameInput.js
  shared/components/LabelSelectorInput/LabelSelectorInput.scss
  shared/index.js
  tests/support/login-commands.js
  tests/tests/create-a-deployment.spec.js
  tests/tests/invalid-kubeconfig.spec.js
  tests/tests/login-enkode.spec.js
  tests/tests/other-logins.spec.js
Labels: size/XXL, lgtm

#372 Sort staged on precommit
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#380 Remove redundant component & translate custom word
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/LambdaReplicas.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/LambdaResources.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement.scss
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagementTab.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/TableElements/Input.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/TableElements/Row.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/shared.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#355 Gateways
  core-ui/src/components/Predefined/Details/Gateway/Gateway.details.js
  core-ui/src/components/Predefined/Details/Gateway/GatewaySelector.js
  core-ui/src/components/Predefined/Details/Gateway/GatewayServers.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/Gateways.list.js
  core-ui/src/components/Predefined/List/index.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#383 Add i18n translations for core-ui shared components
  core-ui/src/shared/components/EventSubscriptions/CreateEventSubscriptionForm.js
  core-ui/src/shared/components/EventSubscriptions/CreateEventSubscriptionModal.js
  core-ui/src/shared/components/EventSubscriptions/EventSubscriptions.js
  core-ui/src/shared/components/OAuth2ClientStatus/OAuth2ClientStatus.js
  core-ui/src/shared/components/Secret/SecretData.js
  core-ui/src/shared/components/Secret/test/SecretData.test.js
  core-ui/src/shared/constants.js
  core-ui/src/shared/useShowNodeParamsError.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#371 Create certificate and issuer
  core-ui/src/components/Predefined/Create/Certificates/AdvancedForm.js
  core-ui/src/components/Predefined/Create/Certificates/Certificates.create.js
  core-ui/src/components/Predefined/Create/Certificates/SimpleForm.js
  core-ui/src/components/Predefined/Create/Certificates/SimpleForm.scss
  core-ui/src/components/Predefined/Create/Certificates/helpers.js
  core-ui/src/components/Predefined/Create/Deployments/AdvancedForm.js
  core-ui/src/components/Predefined/Create/Issuers/AdvancedForm.js
  core-ui/src/components/Predefined/Create/Issuers/Issuers.create.js
  core-ui/src/components/Predefined/Create/Issuers/PrivateKeyForm.js
  core-ui/src/components/Predefined/Create/Issuers/SimpleForm.js
  core-ui/src/components/Predefined/Create/Issuers/helpers.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/Certificate/Certificate.details.js
  core-ui/src/components/Predefined/Details/Certificate/CertificateRefs.js
  core-ui/src/components/Predefined/Details/Issuer/IssuerDomains.js
  core-ui/src/components/Predefined/List/Certificates.list.js
  core-ui/src/index.scss
  core-ui/src/shared/components/CreateForm/CreateForm.scss
  core-ui/src/shared/components/CreateForm/Editor/Editor.js
  core-ui/src/shared/components/CreateForm/Editor/Editor.scss
  core-ui/src/shared/components/CreateForm/ModeSelector/ModeSelector.js
  core-ui/src/shared/components/CreateForm/Presets.js
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.scss
  core-ui/src/shared/components/ResourceRef/IssuerRef.js
  core-ui/src/shared/components/ResourceRef/SecretRef.js
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  resources/web/deployment.yaml
Labels: size/XXL, lgtm

#385 Add read only mode to Function event subscriptions
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingModal.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#379 Create gateway
  core-ui/src/components/Predefined/Create/Gateways/CreateGatewayForm.js
  core-ui/src/components/Predefined/Create/Gateways/CreateGatewayForm.scss
  core-ui/src/components/Predefined/Create/Gateways/GatewaySelectorInput/GatewaySelectorInput.js
  core-ui/src/components/Predefined/Create/Gateways/GatewaySelectorInput/GatewaySelectorInput.scss
  core-ui/src/components/Predefined/Create/Gateways/Gateways.create.js
  core-ui/src/components/Predefined/Create/Gateways/HostsForm.js
  core-ui/src/components/Predefined/Create/Gateways/PortsForm.js
  core-ui/src/components/Predefined/Create/Gateways/ServersForm.js
  core-ui/src/components/Predefined/Create/Gateways/SimpleForm.js
  core-ui/src/components/Predefined/Create/Gateways/TlsForm.js
  core-ui/src/components/Predefined/Create/Gateways/helpers.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/Gateway/GatewayServers.js
  core-ui/src/shared/components/CreateForm/CollapsibleSection/CollapsibleSection.js
  core-ui/src/shared/components/CreateForm/CreateForm.scss
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  shared/components/StringInput/StringInput.js
Labels: size/XL, lgtm

#381 API Rules meet gateways
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.scss
  core-ui/src/components/ApiRules/ApiRuleForm/GatewayDropdown.js
  core-ui/src/components/ApiRules/ApiRuleForm/HostnameDropdown.js
  core-ui/src/components/ApiRules/ApiRulesList/components.js
  core-ui/src/components/ApiRules/helpers.js
  core-ui/src/components/ApiRules/hooks/useGetGatewayDomain.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ApiRules/ApiRules.js
  core-ui/src/components/Predefined/Details/ApiRules.details.js
  core-ui/src/components/Predefined/List/ApiRules.list.js
  core-ui/src/index.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/support/views/api-rules-view.js
Labels: size/L, lgtm

#389 Add create DNS providers
  core-ui/src/components/Predefined/Create/DNSProviders/AdvancedForm.js
  core-ui/src/components/Predefined/Create/DNSProviders/CreateDNSProviderForm.js
  core-ui/src/components/Predefined/Create/DNSProviders/CreateDNSProviderForm.scss
  core-ui/src/components/Predefined/Create/DNSProviders/DNSProviders.create.js
  core-ui/src/components/Predefined/Create/DNSProviders/SimpleForm.js
  core-ui/src/components/Predefined/Create/DNSProviders/helpers.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/shared/components/CreateForm/CreateForm.js
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#388 Add create DNS entries
  core-ui/src/components/Predefined/Create/DNSEntries/AdvancedForm.js
  core-ui/src/components/Predefined/Create/DNSEntries/CreateDNSEntryForm.js
  core-ui/src/components/Predefined/Create/DNSEntries/DNSEntries.create.js
  core-ui/src/components/Predefined/Create/DNSEntries/SimpleForm.js
  core-ui/src/components/Predefined/Create/DNSEntries/helpers.js
  core-ui/src/components/Predefined/Create/DNSProviders/ProviderTypeDropdown.js
  core-ui/src/components/Predefined/Create/DNSProviders/SimpleForm.js
  core-ui/src/components/Predefined/Create/DNSProviders/helpers.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/DNSEntries.details.js
  core-ui/src/components/Predefined/List/DNSEntries.list.js
  resources/web/deployment.yaml
  shared/utils/helpers.js
Labels: size/L, lgtm

#387 Certificates and issuers
  core-ui/src/components/Predefined/Details/Certificate/Certificate.details.js
  core-ui/src/components/Predefined/Details/Certificate/CertificateRefs.js
  core-ui/src/components/Predefined/Details/Certificate/CertificateStatus.js
  core-ui/src/components/Predefined/Details/Certificate/IssuerLink.js
  core-ui/src/components/Predefined/Details/Certificate/SecretLink.js
  core-ui/src/components/Predefined/Details/Issuer/Issuer.details.js
  core-ui/src/components/Predefined/Details/Issuer/IssuerStatus.js
  core-ui/src/components/Predefined/List/Certificates.list.js
  core-ui/src/components/Predefined/List/Issuers.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#390 Show Injected variables component only when catalog is present
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeTab.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#392 Upgrade alpine to 3.14.2 & improve backend logger
  Dockerfile
  Dockerfile.local
  backend/Dockerfile
  backend/common.js
  resources/backend/deployment.yaml
  tests/tests/test-crds.spec.js
Labels: size/S, lgtm

#393 Add cosign signing step
  Makefile
Labels: size/XS, lgtm

#397 Enable access strategy test
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/test/AccessStrategyForm.test.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#391 Fix Cypress test for CRDs
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResources.details.js
  resources/web/deployment.yaml
  tests/tests/test-crds.spec.js
Labels: size/M, lgtm

#399 Add pino-http logger to the backend
  backend/common.js
  backend/package-lock.json
  backend/package.json
  resources/backend/deployment.yaml
Labels: size/L, lgtm

#396 Add i18n for DNS providers and entries
  core-ui/src/components/Predefined/Create/DNSEntries/AdvancedForm.js
  core-ui/src/components/Predefined/Create/DNSEntries/CreateDNSEntryForm.js
  core-ui/src/components/Predefined/Create/DNSEntries/SimpleForm.js
  core-ui/src/components/Predefined/Create/DNSProviders/AdvancedForm.js
  core-ui/src/components/Predefined/Create/DNSProviders/CreateDNSProviderForm.js
  core-ui/src/components/Predefined/Create/DNSProviders/ProviderTypeDropdown.js
  core-ui/src/components/Predefined/Create/DNSProviders/SimpleForm.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#398 Don't remove status from code
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
Labels: size/S, lgtm

#403 Add owner reference to variables table
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeTab.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/serializeVariables.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/test/serializeVariables.test.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#402 Sentry POC
  core-ui/src/components/App/App.js
  core-ui/src/hooks/useSentry.js
  core/src/assets/config/config.json
  core/src/luigi-config/features.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/sentry/index.js
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/configmap.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#405 When api rule has simple host get data from gateway
  core-ui/src/components/ApiRules/ApiRulesList/components.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#404 Add filter for local ip addresses
  backend/common.js
  backend/request-filters.js
  resources/backend/deployment.yaml
Labels: size/S, lgtm

#407 Params a as Feature
  core/src/assets/config/config.json
  core/src/luigi-config/init-params/init-params.js
  resources/web/configmap.yaml
  resources/web/deployment.yaml
  tests/support/enkode.js
  tests/tests/cluster-configuration.spec.js
  tests/tests/login-enkode.spec.js
Labels: size/M, lgtm

#410 Reflect min replicas unavailable as unhelthy function status
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/helpers/lambdas/getLambdaStatus.js
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#411 React on SIGINT
  backend/index.js
  resources/backend/deployment.yaml
Labels: size/XS, lgtm

#409 Handle k3d cluster vs dockerized Busola
  README.md
  backend/common.js
  backend/docker-desktop-substitution.js
  resources/apply-resources.sh
  resources/backend/deployment.yaml
Labels: size/M, lgtm

#406 Don't use a call for root
  backend/request-filters.js
  core/src/assets/config/config.json
  core/src/luigi-config/features.js
  core/src/luigi-config/init-params/constants.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/queries.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/backend/deployment.yaml
  resources/web/configmap.yaml
  resources/web/deployment.yaml
  tests/support/views/functions-view.js
Labels: size/L, lgtm

#418 Cancel timeouts to not have multiple calls in the logs view
  resources/web/deployment.yaml
  shared/hooks/BackendAPI/useGet.js
Labels: size/M, lgtm

#414 Backend security fixes
  backend/common.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  core/src/luigi-config/auth/auth.js
  nginx/nginx.conf
  resources/backend/deployment.yaml
  resources/ingress.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#415 Fix kubeconfig id
  core/src/luigi-config/init-params/init-params.js
  resources/web/deployment.yaml
  tests/tests/login-enkode.spec.js
Labels: size/M, lgtm

#416 Small fixes
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
  resources/web/deployment.yaml
  shared/components/GenericList/actionHandlers/simpleDelete.js
  shared/components/GenericList/actionHandlers/test/handleDelete.test.js
  shared/components/GenericList/test/GenericList.test.js
  shared/components/KeyValueForm/test/KeyValueForm.test.js
  shared/components/LabelSelectorInput/test/LabelSelectorInput.test.js
  shared/components/ResourceNotFound/test/ResourceNotFound.test.js
Labels: size/M, lgtm

#419 Fix server creation
  core-ui/src/components/Predefined/Create/Deployments/templates.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#417 Resource form tweaks
  core-ui/src/components/Predefined/Create/DNSProviders/DNSProviders.create.js
  core-ui/src/components/Predefined/Create/Deployments/Containers.js
  core-ui/src/components/Predefined/Create/Deployments/Deployments.create.js
  core-ui/src/components/Predefined/Create/Deployments/templates.js
  core-ui/src/shared/ResourceForm/ResourceForm.js
  core-ui/src/shared/ResourceForm/components/FormComponents.js
  core-ui/src/shared/ResourceForm/components/Inputs.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#364 first draft Busola configuration
  README.md
Labels: documentation, size/M, lgtm

#413 Cluster wizard
  Dockerfile.local
  README.md
  core-ui/public/index.html
  core-ui/public/sapIllus-Fills.css
  core-ui/public/sapIllus-Layout.css
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.scss
  core-ui/src/components/Clusters/components/AddClusterDialog.js
  core-ui/src/components/Clusters/components/AddClusterDialog.scss
  core-ui/src/components/Clusters/components/AddClusterWizard.js
  core-ui/src/components/Clusters/components/AddClusterWizard.scss
  core-ui/src/components/Clusters/components/AuthForm.js
  core-ui/src/components/Clusters/components/ChooseStorage.js
  core-ui/src/components/Clusters/components/ChooseStorage.scss
  core-ui/src/components/Clusters/components/ClusterConfiguration.js
  core-ui/src/components/Clusters/components/ContextChooser/ContextChooser.js
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigTextArea/KubeconfigTextArea.js
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigTextArea/KubeconfigTextArea.scss
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.scss
  core-ui/src/components/Clusters/components/test/AuthForm.test.js
  core-ui/src/components/Clusters/shared.js
  core-ui/src/components/Clusters/views/AddCluster/AddCluster.js
  core-ui/src/components/Clusters/views/AddCluster/AddCluster.scss
  core-ui/src/components/Clusters/views/AddCluster/ChooseStorage.js
  core-ui/src/components/Clusters/views/AddCluster/ChooseStorage.scss
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Clusters/views/ClusterList.scss
  core-ui/src/shared/ResourceForm/ResourceForm.js
  core-ui/src/shared/ResourceForm/ResourceForm.scss
  core-ui/src/shared/components/CreateForm/CreateForm.js
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  core/src/luigi-config/cluster-management/clusters-storage.js
  core/src/luigi-config/navigation/navigation-data-init.js
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/configmap.yaml
  resources/web/deployment.yaml
  tests/support/login-commands.js
  tests/tests/cluster-configuration.spec.js
  tests/tests/download-a-kubeconfig.spec.js
  tests/tests/invalid-kubeconfig.spec.js
  tests/tests/login-enkode.spec.js
  tests/tests/other-logins.spec.js
Labels: size/XXL, lgtm

#425 Upgrade alpine to 3.14.2 version
  backend/Dockerfile
  resources/backend/deployment.yaml
Labels: size/XS, lgtm

#424 Fix translations for instance creation
  core-ui/src/components/Predefined/Create/ServiceBindings/ServiceBindings.create.js
  core-ui/src/components/Predefined/Create/ServiceInstances/ServiceInstances.create.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#422 Unify CM naming
  README.md
  resources/web/configmap.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#412 Gateway Create 2, but also deployment fixes
  core-ui/src/components/Predefined/Create/DNSProviders/DNSProviders.create.js
  core-ui/src/components/Predefined/Create/Deployments/Containers.js
  core-ui/src/components/Predefined/Create/Deployments/Deployments.create.js
  core-ui/src/components/Predefined/Create/Gateways/CreateGatewayForm.js
  core-ui/src/components/Predefined/Create/Gateways/CreateGatewayForm.scss
  core-ui/src/components/Predefined/Create/Gateways/Forms/HostsForm.js
  core-ui/src/components/Predefined/Create/Gateways/Forms/PortsForm.js
  core-ui/src/components/Predefined/Create/Gateways/Forms/ServersForm.js
  core-ui/src/components/Predefined/Create/Gateways/Forms/TlsForm.js
  core-ui/src/components/Predefined/Create/Gateways/GatewaySelectorInput/GatewaySelectorInput.js
  core-ui/src/components/Predefined/Create/Gateways/GatewaySelectorInput/GatewaySelectorInput.scss
  core-ui/src/components/Predefined/Create/Gateways/Gateways.create.js
  core-ui/src/components/Predefined/Create/Gateways/HostsForm.js
  core-ui/src/components/Predefined/Create/Gateways/PortsForm.js
  core-ui/src/components/Predefined/Create/Gateways/ServersForm.js
  core-ui/src/components/Predefined/Create/Gateways/SimpleForm.js
  core-ui/src/components/Predefined/Create/Gateways/TlsForm.js
  core-ui/src/components/Predefined/Create/Gateways/helpers.js
  core-ui/src/components/Predefined/Create/Gateways/templates.js
  core-ui/src/components/Predefined/List/Gateways.list.js
  core-ui/src/index.scss
  core-ui/src/shared/ResourceForm/ResourceForm.js
  core-ui/src/shared/ResourceForm/components/FormComponents.js
  core-ui/src/shared/ResourceForm/components/FormComponents.scss
  core-ui/src/shared/ResourceForm/components/Inputs.js
  core-ui/src/shared/components/K8sResourceSelect.js
  core-ui/src/shared/components/K8sResourceSelect.scss
  core-ui/src/shared/components/Select/Select.js
  core-ui/src/shared/components/Select/Select.scss
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/ModalWithForm/ModalWithForm.js
  shared/components/Tooltip/Tooltip.js
Labels: size/XXL, lgtm

#429 Move yaml-sort to devDependencies
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#426 Fix pending logs
  resources/web/deployment.yaml
  shared/hooks/BackendAPI/useGet.js
Labels: size/M, lgtm

#432 Move auth to custom header
  backend/common.js
  core/src/luigi-config/navigation/queries.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  shared/hooks/BackendAPI/createHeaders.js
Labels: size/S, lgtm

#438 Fix crashing cronjobs view
  core-ui/src/shared/components/CronJob/CronJobSchedule.js
  resources/web/deployment.yaml
  shared/contexts/ThemeContext.js
Labels: bug, size/S, lgtm

#439 Fix mouse cursor and translation
  core-ui/src/components/Predefined/Create/Certificates/SimpleForm.js
  core-ui/src/components/Predefined/Details/Application/ServicesBoundModal.js
  core-ui/src/index.scss
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
  shared/components/ResourcesList/ResourcesList.scss
Labels: size/S, lgtm

#435 disable CORS at the ingress level
  resources/ingress.yaml
Labels: size/XS, lgtm

#428 Issuers
  core-ui/src/components/Predefined/Create/Certificates/AdvancedForm.js
  core-ui/src/components/Predefined/Create/Certificates/SimpleForm.js
  core-ui/src/components/Predefined/Create/DNSProviders/DNSProviders.create.js
  core-ui/src/components/Predefined/Create/Issuers/AdvancedForm.js
  core-ui/src/components/Predefined/Create/Issuers/IssuerTypeDropdown.js
  core-ui/src/components/Predefined/Create/Issuers/Issuers.create.js
  core-ui/src/components/Predefined/Create/Issuers/PrivateKeyForm.js
  core-ui/src/components/Predefined/Create/Issuers/SimpleForm.js
  core-ui/src/components/Predefined/Create/Issuers/helpers.js
  core-ui/src/components/Predefined/Create/Issuers/templates.js
  core-ui/src/shared/ResourceForm/ResourceForm.js
  core-ui/src/shared/ResourceForm/components/FormComponents.js
  core-ui/src/shared/ResourceForm/components/FormComponents.scss
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
  core-ui/src/shared/components/ResourceRef/IssuerRef.js
  core-ui/src/shared/components/ResourceRef/SecretRef.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/Dropdown/Dropdown.js
Labels: size/XXL, lgtm
