Repository kyma-project/busola, pull requests merged in 2021-07, with the labels that each got.

#256 Remove auth from params
  core-ui/src/components/Clusters/components/ClusterConfiguration.js
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigTextArea/KubeconfigTextArea.js
  core-ui/src/components/Clusters/components/oidc-params.js
  core-ui/src/components/Clusters/components/test/ClusterConfiguration.test.js
  core-ui/src/components/Clusters/components/test/oidc-params.test.js
  core-ui/src/components/Clusters/params-version.js
  core-ui/src/components/Clusters/shared.js
  core-ui/src/components/Clusters/views/AddCluster/AddCluster.js
  core/src/luigi-config/auth/auth.js
  core/src/luigi-config/auth/oidc-params.js
  core/src/luigi-config/cluster-management.js
  core/src/luigi-config/init-params/init-params.js
  core/src/luigi-config/luigi-config.js
  resources/web/deployment.yaml
Labels: lgtm, size/XL

#258 Use configmap
  core-ui/src/components/Clusters/shared.js
  core/src/assets/config/config.json
  core/src/luigi-config/auth/auth.js
  core/src/luigi-config/cluster-management.js
  core/src/luigi-config/cluster-params.js
  core/src/luigi-config/communication.js
  core/src/luigi-config/init-params/init-params.js
  core/src/luigi-config/init-params/params-version.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/queries.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/configmap.yaml
  resources/web/deployment.yaml
  resources/web/kustomization.yaml
  shared/constants/constants.js
  tests/fixtures/kubeconfig.yaml
Labels: lgtm, size/L

#261 Add color coding to CRD schema
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  resources/web/deployment.yaml
Labels: lgtm, size/XS

#260 Fix removing active cluster
  core/src/luigi-config/auth/auth.js
  core/src/luigi-config/cluster-management.js
  resources/web/deployment.yaml
Labels: lgtm, size/S

#262 Rework modules to features
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/Clusters/params-version.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Predefined/Details/Namespace/DeployNewWorkload.js
  core-ui/src/components/Predefined/Details/Namespace/Namespace.details.js
  core-ui/src/components/Predefined/Details/Service/Service.details.js
  core-ui/src/components/Predefined/List/Function/Functions.list.js
  core/src/assets/config/config.json
  core/src/luigi-config/cluster-management.js
  core/src/luigi-config/features.js
  core/src/luigi-config/init-params/constants.js
  core/src/luigi-config/init-params/init-params.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/permissions.js
  core/src/luigi-config/navigation/static-navigation-model.js
  package-lock.json
  package.json
  resources/web/configmap.yaml
  resources/web/deployment.yaml
  shared/constants/constants.js
  shared/index.js
  shared/utils/modulesExist.js
  tests/support/enkode.js
  tests/tests/login-enkode.spec.js
Labels: lgtm, size/XL

#263 Handle kubeconfig ID param
  core/src/luigi-config/init-params/constants.js
  core/src/luigi-config/init-params/init-params.js
  core/src/luigi-config/kubeconfig-id.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/previous-location.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  tests/support/enkode.js
  tests/tests/login-enkode.spec.js
Labels: lgtm, size/L

#265 Remove unnecessary fields from subscription CR
  core-ui/src/shared/components/EventSubscriptions/createSubscriptionInput.js
  resources/web/deployment.yaml
Labels: lgtm, size/XS

#266 Add release-local to Makefile
  Dockerfile.local
  Makefile
Labels: lgtm, size/S

#239 Add python39 runtime
  core-ui/src/components/Lambdas/config.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/helpers/runtime/runtime.js
  core-ui/src/components/Lambdas/helpers/runtime/test/runtime.test.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: lgtm, size/S

#278 Fix dead link causing governance job to fail
  tests/README.md
Labels: documentation, lgtm, size/XS

#275 Upgrade Fundamental Library Styles & Luigi
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  shared/package-lock.json
  shared/package.json
Labels: lgtm, size/XXL

#277 Display a selected state for list items being edited
  resources/web/deployment.yaml
  shared/components/GenericList/GenericList.js
  shared/components/GenericList/GenericList.scss
  shared/components/GenericList/components.js
  shared/components/ResourcesList/ResourcesList.js
  shared/contexts/YamlEditorContext.js
Labels: lgtm, size/M

#271 Make sure we mark mandatory fields
  core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.js
  core-ui/src/components/Predefined/Create/OAuthClients/CheckboxFormControl.js
  core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
  core-ui/src/components/Predefined/Details/Application/ConnectApplicationModal.js
  core-ui/src/components/Predefined/Details/Application/CreateBindingModal/CreateBindingModal.js
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
  core-ui/src/components/Predefined/Details/DeploymentPods.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/ScalingData.js
  core-ui/src/components/Predefined/Details/Namespace/DeployNewWorkload.js
  core-ui/src/components/Predefined/Details/Secret/Secret.details.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  shared/components/Modal/Modal.js
  shared/components/ModalWithForm/ModalWithForm.js
  shared/components/ResourceDetails/ResourceDetails.js
Labels: lgtm, size/M

#279 Configuration reset endpoint
  core/src/luigi-config/cluster-management.js
  core/src/luigi-config/luigi-config.js
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
  tests/config.js
  tests/support/login-commands.js
  tests/tests/invalid-kubeconfig.spec.js
  tests/tests/login-enkode.spec.js
  tests/tests/other-logins.spec.js
Labels: lgtm, size/M

#264 Add Observability links
  core/src/assets/config/config.json
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/queries.js
  resources/web/configmap.yaml
  resources/web/deployment.yaml
Labels: lgtm, size/L

#276 Handle Kyma 1.0 clusters
  backend/Dockerfile
  backend/certs.pem
  backend/common.js
  backend/package.json
  core-ui/src/components/Predefined/Details/Namespace/ResourcesUsage.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/queries.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  shared/hooks/BackendAPI/createHeaders.js
  shared/hooks/BackendAPI/useFetch.js
Labels: lgtm, size/XXL

#281 Upgrade Cypress to 7.7.0 version
  tests/package-lock.json
  tests/package.json
Labels: lgtm, size/M

#274 Restyle the drawer
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  shared/components/SideDrawer/SideDrawer.js
  shared/components/SideDrawer/SideDrawer.scss
  shared/contexts/YamlEditorContext.js
  shared/contexts/YamlEditorContext/EditorActions.js
  shared/contexts/YamlEditorContext/EditorActions.scss
  shared/contexts/YamlEditorContext/YamlContent.js
  shared/contexts/YamlEditorContext/YamlEditorContext.js
  shared/contexts/YamlEditorContext/YamlEditorContext.scss
  shared/contexts/YamlEditorContext/isValidYaml.js
  shared/index.js
Labels: lgtm, size/XL

#280 First load optimisations
  core/src/luigi-config/auth/auth.js
  core/src/luigi-config/init-params/init-params.js
  core/src/luigi-config/kubeconfig-id.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/static-navigation-model.js
  core/webpack.config.js
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js
  shared/components/JSONEditor/JSONEditor.js
  shared/contexts/YamlEditorContext/YamlEditorContext.js
  shared/index.js
  shared/package-lock.json
  shared/package.json
Labels: lgtm, size/L

#273 Unify dropdowns
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/AccessStrategyForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/test/AccessStrategyForm.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.scss
  core-ui/src/components/ApiRules/ApiRuleForm/ServicesDropdown/ServicesDropdown.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingForm.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingModal.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/LambdaResources.js
  core-ui/src/components/Lambdas/LambdasList/Lambdas/CreateLambdaForm.js
  core-ui/src/components/Lambdas/LambdasList/Repositories/RepositoryForm.js
  core-ui/src/components/Lambdas/components/DropdownInput/DropdownInput.js
  core-ui/src/components/Lambdas/components/DropdownInput/DropdownInput.scss
  core-ui/src/components/Lambdas/components/LabelsInput/LabelsInput.js
  core-ui/src/components/Lambdas/components/ResourceNameInput/ResourceNameInput.js
  core-ui/src/components/Lambdas/components/index.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/BasicData.js
  core-ui/src/index.scss
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/PlanColumnContent.js
  service-catalog-ui/src/components/ServiceClassDetails/PlanSelector/PlanSelector.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingModal/CreateServiceBindingForm.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.js
  shared/components/Dropdown/Dropdown.js
  shared/components/Dropdown/Dropdown.scss
  shared/components/Tooltip/Tooltip.js
  shared/hooks/BackendAPI/useGet.js
  tests/support/views/api-rules-view.js
Labels: lgtm, size/XXL

#285 remove title dependency from ResourceCircle
  core-ui/src/components/Predefined/Details/Namespace/NamespaceWorkloads/NamespaceWorkloads.js
  resources/web/deployment.yaml
Labels: lgtm, size/S

#289 Remove custom validation tooltip
  resources/web/deployment.yaml
  shared/components/LabelSelectorInput/LabelSelectorInput.js
  shared/components/StringInput/StringInput.js
Labels: lgtm, size/XS

#287 Fix create service binding
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingModal.js
  core-ui/src/components/Predefined/Details/ApiRules.details.js
  resources/web/deployment.yaml
Labels: lgtm, size/M

#292 Remove HTML5 validation tooltips
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/Clusters/components/AuthForm.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/EditVariablesForm.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingForm.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/ResourceManagement.js
  core-ui/src/components/Lambdas/LambdasList/Lambdas/CreateLambdaForm.js
  core-ui/src/components/Lambdas/LambdasList/Repositories/RepositoryForm.js
  core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.js
  core-ui/src/components/Predefined/Create/Namespaces/Namespaces.create.js
  core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
  core-ui/src/components/Predefined/Create/RoleBindings/RoleBindings.js
  core-ui/src/components/Predefined/Create/Secrets/SecretForm.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/CreateWorkloadForm.js
  core-ui/src/components/Predefined/List/Application/CreateApplicationModal.js
  core-ui/src/shared/components/ConfigMap/ConfigMapForm.js
  core-ui/src/shared/components/EventSubscriptions/CreateEventSubscriptionForm.js
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingModal/CreateServiceBindingForm.js
Labels: lgtm, size/M

#288 Fail fast on invalid headers & fix search in Monaco
  backend/common.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  shared/contexts/YamlEditorContext/EditorActions.js
  shared/contexts/YamlEditorContext/YamlContent.js
Labels: lgtm, size/M

#295 Fix application crush when there is no existing bindings
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingForm.js
  resources/web/deployment.yaml
Labels: lgtm, size/XS

#293 Add tooltips to resource circles
  README.md
  core-ui/src/components/App/App.js
  core-ui/src/components/Predefined/Details/Namespace/NamespaceWorkloads/NamespaceWorkloads.js
  core-ui/src/components/Predefined/Details/Namespace/ResourcesUsage.js
  core/README.md
  core/package.json
  resources/web/deployment.yaml
  service-catalog-ui/src/components/App/App.js
  shared/components/Labels/Labels.js
  shared/components/MainFrameRedirection/MainFrameRedirection.js
  shared/index.js
  tests/config.js
Labels: lgtm, size/L

#291 add searching by labels
  logging/src/components/Shared/SearchInput/SearchInput.js
  resources/web/deployment.yaml
  shared/components/GenericList/SearchInput.js
  shared/components/GenericList/helpers.js
  shared/components/GenericList/test/GenericList.test.js
  shared/components/ResourcesList/ResourcesList.js
Labels: lgtm, size/L

#294 Remove the info icons
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
  core-ui/src/components/Lambdas/components/FormInput/FormInput.js
  core-ui/src/components/Lambdas/components/LabelsInput/LabelsInput.js
  core-ui/src/components/Lambdas/components/ResourceNameInput/ResourceNameInput.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Predefined/Create/Namespaces/Namespaces.create.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/BasicData.js
  resources/web/deployment.yaml
  shared/components/Dropdown/Dropdown.js
  shared/components/K8sNameInput/K8sNameInput.js
  shared/components/LabelSelectorInput/LabelSelectorInput.js
  shared/components/Tooltip/Tooltip.js
Labels: lgtm, size/L

#290 Add theming functionality
  .gitignore
  core-ui/package.json
  core-ui/public/themes/dark.css
  core-ui/public/themes/default.css
  core-ui/public/themes/hcb.css
  core-ui/public/themes/hcw.css
  core-ui/public/themes/light_dark.css
  core-ui/src/components/Preferences/Preferences.js
  core-ui/src/components/Preferences/ThemeChooser.js
  core-ui/webpack.config.js
  core/package-lock.json
  core/src/luigi-config/communication.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/utils/theme.js
  core/webpack.config.js
  gulpfile.js
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  shared/contexts/Microfrontend.js
  shared/contexts/ThemeContext.js
  shared/index.js
Labels: lgtm, size/XXL

#283 Edit variables
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/CreateVariable/CreateVariable.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/EditVariable/EditVariable.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/EditVariablesForm.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableForm/VariableForm.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableForm/VariableModal.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableInputs/CustomVariableInput.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableInputs/ResourceVariableInput.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableInputs/VariableInputs.scss
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/test/LambdaVariables.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/test/validation.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/validation.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/constants.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/newVariableModel.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/serializeVariables.js
  core-ui/src/components/Lambdas/helpers/lambdaVariables/test/serializeVariables.test.js
  core-ui/src/components/Lambdas/helpers/testing/mockData.js
  core-ui/src/index.scss
  resources/web/deployment.yaml
  shared/components/Dropdown/Dropdown.scss
  shared/components/GenericList/GenericList.scss
Labels: lgtm, size/XXL

#300 Rename themes according to Fiori Design Guidelines
  core-ui/src/components/Preferences/ThemeChooser.js
  core/package-lock.json
  resources/web/deployment.yaml
Labels: lgtm, size/L

#296 Sanitize and check backend headers and errors
  backend/common.js
  resources/backend/deployment.yaml
Labels: lgtm, size/M

#299 Set Editor theme, adjust lambda details view to theming, fix YAML drawer buttons
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/Editor.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/ResourceManagement.scss
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js
  shared/components/SideDrawer/SideDrawer.js
  shared/contexts/ThemeContext.js
  shared/contexts/YamlEditorContext/EditorActions.scss
  shared/contexts/YamlEditorContext/YamlContent.js
Labels: lgtm, size/M

#302 Fix logo visibility for high contrast white theme
  core/src/assets/logo-black.svg
  core/src/index.css
  core/src/luigi-config/settings.js
  core/src/luigi-config/utils/theme.js
  resources/web/deployment.yaml
Labels: lgtm, size/S

#301 Fix dark themes on Add Cluster view
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigTextArea/KubeconfigTextArea.scss
  core-ui/src/index.scss
  resources/web/deployment.yaml
  shared/components/FileInput/FileInput.scss
Labels: lgtm, size/M

#297 Adjust tooltips texts
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/AccessStrategyForm.js
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Predefined/Create/Namespaces/CreateNamespace.scss
  core-ui/src/components/Predefined/Create/Namespaces/Namespaces.create.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/BasicData.js
  core-ui/src/shared/components/EventSubscriptions/CreateEventSubscriptionForm.js
  resources/web/deployment.yaml
  shared/components/HeaderLabelsEditor/HeaderLabelsEditor.js
  shared/components/HeaderLabelsEditor/HeaderLabelsEditor.scss
  shared/components/HeaderLabelsEditor/test/HeaderLabelsEditor.test.js
  shared/components/KeyValueForm/KeyValueForm.js
  shared/components/LabelSelectorInput/LabelSelectorInput.js
  shared/components/Tooltip/Tooltip.scss
  shared/index.js
Labels: lgtm, size/L

#303 Upgrade Cypress to 8.0.0
  tests/package-lock.json
  tests/package.json
Labels: lgtm, size/S

#304 Upgrade Cypress to 8.0.0
  tests/package.json
Labels: lgtm, size/XS

#307 Fix function environments edit
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableForm/VariableForm.js
  resources/web/deployment.yaml
Labels: lgtm, size/XS

#306 Change colour for visited links in dark theme
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleFormHeader/ApiRuleFormHeader.js
  core-ui/src/components/ApiRules/ApiRulesList/components.js
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/NodeWarningsList.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/PodList/PodList.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
  core-ui/src/components/Predefined/Details/Application/ServicesBoundModal.js
  core-ui/src/components/Predefined/Details/Pod/Pod.details.js
  core-ui/src/components/Predefined/List/GitRepository/GitRepositories.list.js
  core-ui/src/components/Predefined/List/OAuth2Clients.list.js
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js
  service-catalog-ui/src/components/ServiceClassDetails/ServiceClassInstancesTable/ServiceClassInstancesTable.js
  service-catalog-ui/src/components/ServiceClassPlansList/ServiceClassPlansList.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.js
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceRowRenderer.js
  shared/components/Link/CopiableLink.js
  shared/components/ResourcesList/ResourcesList.js
Labels: lgtm, size/M

#308 Remove different tooltip for Access Strategies
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  resources/web/deployment.yaml
Labels: lgtm, size/XS

#298 i18n PoC
  core-ui/public/i18n
  core-ui/src/components/App/App.js
  core-ui/src/components/Predefined/Details/Namespace/NamespaceWorkloads/NamespaceWorkloads.js
  core-ui/src/components/Predefined/Details/Namespace/ResourcesUsage.js
  core-ui/src/components/Preferences/LanguageSettings.js
  core-ui/src/components/Preferences/Preferences.js
  core-ui/src/index.js
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  core/src/luigi-config/communication.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/static-navigation-model.js
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  service-catalog-ui/public/i18n
  service-catalog-ui/src/components/App/App.js
  service-catalog-ui/src/components/ServiceClassList/ServiceClassList.js
  service-catalog-ui/src/index.js
  shared/components/SideDrawer/SideDrawer.js
  shared/contexts/YamlEditorContext/YamlContent.js
Labels: lgtm, size/L

#311 Improve OAuth2 Clients view
  core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
  core-ui/src/components/Predefined/List/OAuth2Clients.list.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/tests/create-configuration-resources.spec.js
  tests/tests/login-enkode.spec.js
Labels: lgtm, size/S

#313 Improve theme naming
  core-ui/src/components/Preferences/ThemeChooser.js
  core-ui/src/index.scss
  core/src/luigi-config/utils/theme.js
  resources/web/deployment.yaml
  shared/contexts/ThemeContext.js
Labels: lgtm, size/M

#312 change collapse option
  core/src/luigi-config/settings.js
  resources/web/deployment.yaml
Labels: lgtm, size/XS

#305 Add themes to Service Catalog
  .gitignore
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/settings.js
  gulpfile.js
  resources/web/deployment.yaml
  service-catalog-ui/package.json
  service-catalog-ui/public/themes/dark.css
  service-catalog-ui/public/themes/default.css
  service-catalog-ui/public/themes/hcb.css
  service-catalog-ui/public/themes/hcw.css
  service-catalog-ui/public/themes/light_dark.css
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/JSONSchema/index.js
  service-catalog-ui/src/components/ServiceClassList/Cards/InstancesIndicator.scss
  service-catalog-ui/src/components/ServiceClassList/Cards/styled.js
  service-catalog-ui/src/components/ServiceClassList/styled.js
  shared/contexts/ThemeContext.js
Labels: lgtm, size/L
