Repository kyma-project/busola, pull requests merged in 2021-12, with the labels that each got.

#634 fix dns entries tests
  tests/tests/test-dns-entries.spec.js
Labels: size/XS, lgtm

#632 Add cypress tests for application settings
  tests/cypress.json
  tests/tests/test.settings.spec.js
Labels: size/L, lgtm

#616 Disable protected resources
  core-ui/src/components/Preferences/Preferences.js
  core-ui/src/components/Preferences/ProtectedSettings.js
  core/src/i18n/en.yaml
  core/src/luigi-config/communication.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/utils/feature-toggles.js
  resources/apply-resources.sh
  resources/web/deployment.yaml
  shared/hooks/useFeatureToggle.js
  shared/hooks/useProtectedResources.js
  tests/cypress.json
  tests/tests/test-protected-resources.js
Labels: size/L, lgtm

#633 fix services in deployments
  core-ui/src/components/Predefined/Create/Deployments/Deployments.create.js
  core-ui/src/shared/ResourceForm/components/Wrapper.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#610 Refactor namespace form to resource form
  core-ui/src/components/Predefined/Create/Namespaces/CreateNamespace.scss
  core-ui/src/components/Predefined/Create/Namespaces/MemoryQuotas.js
  core-ui/src/components/Predefined/Create/Namespaces/Namespaces.create.js
  core-ui/src/components/Predefined/Create/Namespaces/Presets.js
  core-ui/src/components/Predefined/Create/Namespaces/config.js
  core-ui/src/components/Predefined/Create/Namespaces/helpers.js
  core-ui/src/components/Predefined/Create/Namespaces/templates.js
  core-ui/src/components/Predefined/Create/Namespaces/test/__snapshots__/Namespaces.helpers.test.js.snap
  core-ui/src/shared/ResourceForm/components/Presets.js
  core-ui/src/shared/ResourceForm/fields/KeyValueField.js
  core-ui/src/shared/ResourceForm/useCreateResource.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/run-before.spec.js
Labels: size/XL, lgtm

#625 Fixes on warnings lists
  core-ui/src/components/App/App.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/NodeWarningsList.js
  core-ui/src/components/Nodes/NodeResources/NodeResources.js
  core-ui/src/components/Nodes/NodeWarnings.js
  core-ui/src/components/Nodes/nodeQueries.js
  core-ui/src/components/Predefined/List/Events.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#637 Add a wrapper to the class component to use a hook
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/SecretDataModal/SecretDataModal.component.js
Labels: bug, size/S, lgtm

#644 Fix bugs related to CSR and Secrets in Certificate
  core-ui/src/components/Predefined/Create/Certificates/Certificates.create.js
  core-ui/src/components/Predefined/Details/Certificate/Certificate.details.js
  core-ui/src/components/Predefined/Details/Certificate/CertificateRefs.js
  core-ui/src/shared/ResourceForm/inputs/Text.js
  resources/web/deployment.yaml
  shared/components/K8sNameInput/K8sNameInput.js
Labels: size/M, lgtm

#643 bump fundamental version
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#646 fix text bug in the Privacy Options step
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#648 Fix jest tests in shared repo
  resources/web/deployment.yaml
  shared/components/GenericList/Pagination/test/Pagination.test.js
  shared/components/GenericList/test/GenericList.test.js
Labels: size/M, lgtm

#645 Fix theme choose bug on Safari
  core-ui/src/components/Preferences/ThemePreview/ThemePreview.js
  core-ui/src/components/Preferences/ThemePreview/ThemePreview.scss
  resources/web/deployment.yaml
Labels: size/L, lgtm

#635 Test reduced permissions
  .gitignore
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
  tests/cypress.json
  tests/plugins/index.js
  tests/support/helpers.js
  tests/support/login-commands.js
  tests/tests/reduced-permissions.spec.js
Labels: size/L, lgtm

#642 Use manual selection type in all Comboboxes
  core-ui/src/components/Predefined/Details/Application/CreateBindingModal/CreateBindingModal.js
  core-ui/src/shared/ResourceForm/inputs/ComboboxInput.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#641 Fix scrolling page when mouse is over monaco container
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/Editor.js
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  core-ui/src/shared/ResourceForm/fields/Editor.js
  core-ui/src/shared/components/ReadonlyEditorPanel.js
  core/src/index.css
  resources/web/deployment.yaml
  shared/components/SideDrawer/SideDrawer.js
  shared/contexts/YamlEditorContext/YamlContent.js
Labels: size/M, lgtm

#666 Fix action buttons alignment on cluster list, add margin between buttons
  resources/web/deployment.yaml
  shared/components/GenericList/GenericList.scss
  shared/components/ListActions/ListActions.js
  shared/components/ListActions/ListActions.scss
Labels: size/S, lgtm

#665 Add jobs controlled by property
  core-ui/src/components/Predefined/Details/Job/Job.details.js
  core-ui/src/components/Predefined/List/Jobs.list.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#629 Make the status Labels translatable
  core-ui/src/components/ApiRules/ApiRuleStatus/ApiRuleStatus.js
  core-ui/src/components/ApiRules/ApiRuleStatus/test/ApiRuleStatus.test.js
  core-ui/src/components/Clusters/views/ClusterStorageType.js
  core-ui/src/components/Lambdas/LambdaStatusBadge/LambdaStatusBadge.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/helpers/lambdas/statusType.js
  core-ui/src/components/Predefined/Details/DNSProviders.details.js
  core-ui/src/components/Predefined/Details/Function.details.js
  core-ui/src/components/Predefined/List/Function/Functions.list.js
  core-ui/src/index.js
  core-ui/src/shared/components/OAuth2ClientStatus/test/OAuth2ClientStatus.test.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/StatusBadge/StatusBadge.js
  shared/components/StatusBadge/StatusBadge.scss
  shared/components/StatusBadge/test/StatusBadge.test.js
  tests/support/views/functions-view.js
  tests/tests/run-after.spec.js
  tests/tests/test-jobs.spec.js
  tests/tests/test-service-accounts.spec.js
Labels: size/L, lgtm

#647 Fix Luigi navigation bug
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/navigation-data-init.js
  resources/web/deployment.yaml
Labels: size/S, approved, lgtm, javascript

#652 Test multiple contexts kubeconfig
  core-ui/src/components/Clusters/components/AddClusterWizard.js
  core-ui/src/components/Clusters/shared.js
  core-ui/src/shared/ResourceForm/components/Single.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/support/loadKubeconfigFile.js
  tests/tests/multiple-context-kubeconfig.spec.js
Labels: size/L, lgtm

#671 Connect cluster button
  README.md
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/support/login-commands.js
  tests/tests/add-cluster-disabled.spec.js
  tests/tests/invalid-kubeconfig.spec.js
  tests/tests/multiple-context-kubeconfig.spec.js
  tests/tests/other-logins.spec.js
Labels: size/M, lgtm

#677 Fix test.settings to check for created config map
  tests/tests/test.settings.spec.js
Labels: size/XS, lgtm

#672 Add filtering and links to event messages
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodeMessages.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/components/Nodes/NodeDetails/NodeDetails.js
  core-ui/src/components/Nodes/NodeMessages.js
  core-ui/src/components/Predefined/List/Events.list.js
  core-ui/src/hooks/useMessageList.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/smoke-tests.spec.js
  tests/tests/test-cluster-overview.spec.js
Labels: size/L, lgtm

#670 Migrate discovery and network, namespaces, integration views to new translatable labels
  core-ui/src/components/ApiRules/ApiRuleStatus/ApiRuleStatus.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/CodeAndDependencies.js
  core-ui/src/components/Lambdas/components/TabsWithActions/TabsWithActions.scss
  core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.js
  core-ui/src/components/Predefined/Details/AddonsConfiguration.details.js
  core-ui/src/components/Predefined/Details/Application/ApplicationStatus.js
  core-ui/src/components/Predefined/Details/Namespace/NamespaceStatus.js
  core-ui/src/components/Predefined/List/AddonsConfigurations.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/StatusBadge/StatusBadge.js
  shared/hooks/useProtectedResources.js
Labels: size/M, lgtm

#675 Fix blur issue at the git repos URL field
  core-ui/src/components/Predefined/Create/GitRepositories/GitRepositories.create.js
  resources/web/deployment.yaml
  tests/tests/test-git-repositories.spec.js
Labels: size/M, lgtm

#674 Migrate service catalog and service management views to new translatable labels
  core-ui/src/components/Predefined/Details/AddonsConfiguration.details.js
  core-ui/src/components/Predefined/Details/ServiceBinding/ServiceBinding.details.js
  core-ui/src/components/Predefined/Details/ServiceInstance/ServiceInstance.details.js
  core-ui/src/components/Predefined/List/AddonsConfigurations.list.js
  core-ui/src/components/Predefined/List/ServiceBindings.list.js
  core-ui/src/components/Predefined/List/ServiceBrokers.list.js
  core-ui/src/components/Predefined/List/ServiceInstances.list.js
  core-ui/src/shared/components/BTPResourceStatus.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.js
  service-catalog-ui/src/shared/ServiceInstanceStatus.js
  shared/components/StatusBadge/StatusBadge.js
Labels: size/L, lgtm

#678 Protect resources controlled by
  docs/features.md
  resources/web/deployment.yaml
  shared/hooks/useProtectedResources.js
  tests/cypress.json
  tests/tests/test-protected-resources.spec.js
Labels: size/M, lgtm

#676 Translate configuration views labels
  core-ui/src/components/Predefined/Details/AddonsConfiguration.details.js
  core-ui/src/components/Predefined/Details/Certificate/Certificate.details.js
  core-ui/src/components/Predefined/Details/Certificate/CertificateStatus.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  core-ui/src/components/Predefined/Details/DNSEntries.details.js
  core-ui/src/components/Predefined/Details/DNSProviders.details.js
  core-ui/src/components/Predefined/Details/GitRepositories.details.js
  core-ui/src/components/Predefined/Details/Issuer/Issuer.details.js
  core-ui/src/components/Predefined/Details/Issuer/IssuerStatus.js
  core-ui/src/components/Predefined/List/AddonsConfigurations.list.js
  core-ui/src/components/Predefined/List/Certificates.list.js
  core-ui/src/components/Predefined/List/DNSEntries.list.js
  core-ui/src/components/Predefined/List/DNSProviders.list.js
  core-ui/src/components/Predefined/List/GitRepository/GitRepositories.list.js
  core-ui/src/components/Predefined/List/Issuers.list.js
  core-ui/src/shared/components/OAuth2ClientStatus/OAuth2ClientStatus.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/ResourceStatus/ResourceStatus.js
  shared/components/StatusBadge/StatusBadge.js
  shared/index.js
Labels: size/L, lgtm

#681 Add option to create any resource by yaml
  core-ui/src/components/Predefined/Create/DaemonSets/DaemonSets.create.js
  core-ui/src/components/Predefined/Create/DaemonSets/templates.js
  core-ui/src/components/Predefined/Create/Pods/Pods.create.js
  core-ui/src/components/Predefined/Create/Pods/templates.js
  core-ui/src/components/Predefined/Create/Services/Services.create.js
  core-ui/src/components/Predefined/Create/Services/templates.js
  core-ui/src/components/Predefined/Create/StatefulSets/StatefulSets.create.js
  core-ui/src/components/Predefined/Create/StatefulSets/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/components/Wrapper.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#685 Fix editing yaml in Namespace bug and improve placeholders
  core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.create.js
  core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.js
  core-ui/src/components/Predefined/Create/Jobs/Jobs.create.js
  core-ui/src/components/Predefined/Create/Namespaces/Namespaces.create.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#686 introduce an ISTIO feature for istio resources
  core/src/luigi-config/kubeconfig-id/constants.js
  core/src/luigi-config/navigation/static-navigation-model.js
  docs/features.md
  resources/web/deployment.yaml
Labels: size/L, lgtm

#688 Show Kyma version
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
  core-ui/src/components/Clusters/views/ClusterOverview/useKymaVersionQuery.js
  core/src/i18n/en.yaml
  core/src/luigi-config/cluster-management/cluster-management.js
  core/src/luigi-config/kubeconfig-id/constants.js
  core/src/luigi-config/kubeconfig-id/kubeconfig-id.js
  docs/features.md
  resources/web/deployment.yaml
  tests/cypress.json
  tests/plugins/index.js
  tests/support/commands.js
  tests/support/login-commands.js
  tests/tests/add-cluster-disabled.spec.js
  tests/tests/cluster-configuration.spec.js
  tests/tests/kyma-version.spec.js
  tests/tests/login-kubeconfigID.spec.js
  tests/tests/multiple-context-kubeconfig.spec.js
  tests/tests/other-logins.spec.js
  tests/tests/reduced-permissions.spec.js
  tests/tests/run-after.spec.js
  tests/tests/run-before.spec.js
  tests/tests/test-dns-providers.spec.js
  tests/tests/test-issuers.spec.js
  tests/tests/test.settings.spec.js
Labels: size/L, lgtm

#679 translate statuses for workload resources
  core-ui/src/components/Predefined/Details/CronJobs/CronJobConcurrencyPolicy.js
  core-ui/src/components/Predefined/Details/DaemonSet.details.js
  core-ui/src/components/Predefined/Details/Job/JobCompletions.js
  core-ui/src/components/Predefined/Details/Job/JobConditions.js
  core-ui/src/components/Predefined/Details/Pod/PodStatus.js
  core-ui/src/components/Predefined/Details/Replicaset.details.js
  core-ui/src/components/Predefined/Details/StatefulSet/StatefulSetReplicas.js
  core-ui/src/components/Predefined/List/DaemonSets.list.js
  core-ui/src/components/Predefined/List/Deployments.list.js
  core-ui/src/components/Predefined/List/ReplicaSets.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/StatusBadge/StatusBadge.js
Labels: size/L, lgtm

#691 Create CRD Modal and tests for it
  core-ui/src/components/Predefined/Create/CustomResourceDefinitions/CustomResourceDefinitons.create.js
  core-ui/src/components/Predefined/Create/CustomResourceDefinitions/templates.js
  core-ui/src/components/Predefined/Create/index.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/fixtures/test-customresourcedefinisions.yaml
  tests/support/loadCRD.js
  tests/tests/test-crds.spec.js
  tests/tests/test-custom-resource-definitions.spec.js
Labels: size/L, lgtm

#683 Add a possibility to edit a deployment using new edit modal
  core-ui/src/components/Predefined/Create/Deployments/Deployments.create.js
  resources/web/deployment.yaml
  tests/tests/create-a-deployment.spec.js
Labels: size/L, lgtm

#692 Fix dropdown height in the plan chooser
  resources/web/deployment.yaml
  service-catalog-ui/src/index.scss
Labels: bug, size/S, lgtm

#698 Fix bug when clicking enter in Token input
  core-ui/src/components/Clusters/components/AddClusterWizard.js
  core-ui/src/components/Clusters/components/AuthForm.js
  core-ui/src/components/Clusters/components/oidc-params.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#710 Update cert
  backend/certs.pem
  resources/backend/deployment.yaml
Labels: size/M, lgtm

#695 Certificate Secret details
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/Predefined/Details/DNSEntries.details.js
  core-ui/src/components/Predefined/Details/Pod/ContainersData.js
  core-ui/src/components/Predefined/Details/Secret/CertificateData.js
  core-ui/src/components/Predefined/Details/Secret/CertificatePanel.js
  core-ui/src/components/Predefined/Details/Secret/Secret.details.js
  core-ui/src/components/Predefined/Details/ServiceAccount/useDownloadSecretKubeconfig.js
  core-ui/src/index.scss
  core-ui/src/shared/components/LayoutPanelRow/LayoutPanelRow.js
  core-ui/src/shared/components/LayoutPanelRow/LayoutPanelRow.scss
  core-ui/src/shared/components/Secret/SecretData.js
  core-ui/src/shared/components/Secret/SecretData.scss
  core/src/i18n/en.yaml
  core/src/luigi-config/cluster-management/cluster-management.js
  resources/web/deployment.yaml
  tests/support/login-commands.js
  tests/tests/reduced-permissions.spec.js
  tests/tests/test-dns-entries.spec.js
  tests/tests/test-jobs.spec.js
  tests/tests/test-replica-sets.spec.js
  tests/tests/test-secrets.spec.js
Labels: size/XL, lgtm

#711 Add error tolerancy for useGet
  Dockerfile
  Dockerfile.local
  resources/web/deployment.yaml
  shared/components/KeyValueForm/test/KeyValueForm.test.js
  shared/components/StatusBadge/test/StatusBadge.test.js
  shared/hooks/BackendAPI/tests/useGet.test.js
  shared/hooks/BackendAPI/useGet.js
Labels: size/M, lgtm

#715 Link to secret in Gateways
  core-ui/package-lock.json
  core-ui/src/components/Predefined/Details/Gateway/GatewayServers.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#716 Repair Close and Decode button
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/SecretDataModal/SecretDataModal.component.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/SecretDataModal/styled.js
Labels: size/M, lgtm

#717 Decode secrets on instance details
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/SecretDataModal/SecretDataModal.component.js
Labels: size/XS, lgtm

#699 Add missing tooltips, adjust statuses
  core-ui/src/components/ApiRules/ApiRuleStatus/ApiRuleStatus.js
  core-ui/src/components/Lambdas/LambdaStatusBadge/LambdaStatusBadge.js
  core-ui/src/components/Predefined/Details/CronJobs/CronJobConcurrencyPolicy.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  core-ui/src/components/Predefined/Details/DaemonSet/DaemonSet.details.js
  core-ui/src/components/Predefined/Details/DaemonSet/DaemonSetStatus.js
  core-ui/src/components/Predefined/Details/Deployment/Deployment.details.js
  core-ui/src/components/Predefined/Details/Deployment/DeploymentStatus.js
  core-ui/src/components/Predefined/Details/GitRepositories.details.js
  core-ui/src/components/Predefined/Details/Job/JobCompletions.js
  core-ui/src/components/Predefined/Details/Job/JobConditions.js
  core-ui/src/components/Predefined/Details/ReplicaSet/ReplicaSetStatus.js
  core-ui/src/components/Predefined/Details/ReplicaSet/Replicaset.details.js
  core-ui/src/components/Predefined/Details/StatefulSet/StatefulSetPods.js
  core-ui/src/components/Predefined/Details/StatefulSet/StatefulSetReplicas.js
  core-ui/src/components/Predefined/Details/StatefulSet/StatefulSets.details.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/DaemonSets.list.js
  core-ui/src/components/Predefined/List/Deployments.list.js
  core-ui/src/components/Predefined/List/GitRepository/GitRepositories.list.js
  core-ui/src/components/Predefined/List/Pod/PodRestarts.js
  core-ui/src/components/Predefined/List/ReplicaSets.list.js
  core-ui/src/components/Predefined/List/StatefulSets.list.js
  core-ui/src/shared/components/BTPResourceStatus.js
  core-ui/src/shared/components/OAuth2ClientStatus/OAuth2ClientStatus.js
  core-ui/src/shared/components/RunningPodsStatus.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/ResourceStatus/ResourceStatus.js
  shared/components/StatusBadge/StatusBadge.js
  shared/components/StatusBadge/test/StatusBadge.test.js
  shared/components/TooltipBadge/TooltipBadge.js
  shared/components/TooltipBadge/TooltipBadge.scss
  shared/index.js
Labels: size/XL, lgtm

#696 Add destination rule feature
  core-ui/src/components/Predefined/Create/DestinationRules/DestinationRules.create.js
  core-ui/src/components/Predefined/Create/DestinationRules/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/DestinationRule/ConnectionPoolHTTP.js
  core-ui/src/components/Predefined/Details/DestinationRule/ConnectionPoolTCP.js
  core-ui/src/components/Predefined/Details/DestinationRule/DestinationRule.details.js
  core-ui/src/components/Predefined/Details/DestinationRule/DestinationRuleRefs.js
  core-ui/src/components/Predefined/Details/DestinationRule/DestinationRuleRefs.scss
  core-ui/src/components/Predefined/Details/DestinationRule/LoadBalancer.js
  core-ui/src/components/Predefined/Details/DestinationRule/OutlierDetection.js
  core-ui/src/components/Predefined/Details/DestinationRule/Subset.js
  core-ui/src/components/Predefined/Details/DestinationRule/TlsSettings.js
  core-ui/src/components/Predefined/Details/DestinationRule/TrafficPolicy.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/DestinationRules.list.js
  core-ui/src/components/Predefined/List/index.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  shared/components/GenericList/GenericList.js
  tests/cypress.json
  tests/fixtures/test-custom-destination-rule.yaml
  tests/support/loadDR.js
  tests/tests/test-destination-rules.spec.js
  tests/tests/test-gateways.spec.js
Labels: size/XL, lgtm

#714 Ingresses
  core-ui/src/components/Predefined/Create/Ingresses/Ingresses.create.js
  core-ui/src/components/Predefined/Create/Ingresses/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/Ingress/DefaultBackendPanel.js
  core-ui/src/components/Predefined/Details/Ingress/Ingress.details.js
  core-ui/src/components/Predefined/Details/Ingress/Rules.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/Ingresses.list.js
  core-ui/src/components/Predefined/List/index.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  shared/components/ControlledBy/ControlledBy.js
  shared/components/GenericList/GenericList.scss
  shared/index.js
  tests/cypress.json
  tests/fixtures/test-ingress.yaml
  tests/support/loadIngress.js
  tests/tests/test-ingresses.spec.js
Labels: size/XL, lgtm

#730 Manual Kyma Dashboard installation
  README.md
  docs/install-kyma-dashboard-manually.md
  milv.config.yaml
Labels: size/M, lgtm

#741 Fix api rules
  tests/support/views/functions-view.js
  tests/tests/create-an-api-rule.spec.js
Labels: size/L, lgtm

#742 Repair ingress tests
  tests/tests/test-ingresses.spec.js
Labels: size/S, lgtm

#743 Improve protected res tooltip
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#738 Fix link in config map
  core-ui/src/components/Predefined/Details/Pod/Pod.details.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#739 Fix double slash in event link list
  core-ui/src/hooks/useMessageList.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#744 Repair protected resource and service accounts test
  tests/tests/test-protected-resources.spec.js
  tests/tests/test-service-accounts.spec.js
Labels: size/XS, lgtm, test-case

#740 Fix no-repos bug at function create form
  core-ui/src/shared/ResourceForm/components/Wrapper.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#737 Feature create event subscription and list with details
  core-ui/src/components/Predefined/Create/EventSubscriptions/EventSubscriptions.create.js
  core-ui/src/components/Predefined/Create/EventSubscriptions/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/EventSubscriptions/EventFilters.scss
  core-ui/src/components/Predefined/Details/EventSubscriptions/EventSubscriptionConditions.js
  core-ui/src/components/Predefined/Details/EventSubscriptions/EventSubscriptions.details.js
  core-ui/src/components/Predefined/Details/Job/JobConditions.js
  core-ui/src/components/Predefined/Details/Service/Service.details.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/EventSubscriptions.list.js
  core-ui/src/components/Predefined/List/index.js
  core-ui/src/hooks/useMessageList.js
  core-ui/src/shared/components/EventSubscriptionConditionStatus.js
  core-ui/src/shared/components/EventSubscriptions/EventSubscriptions.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  tests/fixtures/test-eventsubscription.yaml
  tests/support/loadCRD.js
  tests/support/loadFile.js
  tests/tests/in-cluster-eventing.spec.js
  tests/tests/test-custom-resource-definitions.spec.js
Labels: enhancement, size/XL, lgtm

#750 Show only stored CRD
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#752 Add copy etc buttons to the create resource yaml editor
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/fields/Editor.js
  core-ui/src/shared/ResourceForm/fields/Editor.scss
  resources/web/deployment.yaml
  shared/contexts/YamlEditorContext/EditorActions.js
  shared/index.js
Labels: size/M, lgtm

#753 Create codeql-analysis.yml for Dependabot
  .github/workflows/codeql-analysis.yml
Labels: size/M, lgtm

#757 Kyma Dashboard Version with link
  core/src/i18n/en.yaml
  core/src/luigi-config/nav-footer.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/test-dashboard-version.spec.js
Labels: enhancement, size/M, lgtm

#749 Fix create form button
  core-ui/src/components/Predefined/Create/ApiRules/JwtStrategyConfig.js
  core-ui/src/components/Predefined/Create/Gateways/Gateways.create.js
  core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
  core-ui/src/components/Predefined/Create/ServiceBindings/SecretRefForm/SecretRefForm.js
  core-ui/src/shared/ResourceForm/fields/ComboboxArrayInput.js
  core-ui/src/shared/ResourceForm/fields/KeyValueField.js
  core-ui/src/shared/ResourceForm/fields/MultiInput.js
  core-ui/src/shared/ResourceForm/fields/SelectArrayInput.js
  core-ui/src/shared/ResourceForm/fields/TextArrayInput.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#748 Adjust statuses and tooltips for functions and pods
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/StatusBadge/StatusBadge.js
Labels: size/L, lgtm

#729 Istio virtual services
  core-ui/src/components/Predefined/Create/VirtualServices/VirtualServices.create.js
  core-ui/src/components/Predefined/Create/VirtualServices/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/ApiRule/ApiRules.details.js
  core-ui/src/components/Predefined/Details/ApiRule/Services.js
  core-ui/src/components/Predefined/Details/VirtualServices/HttpRoutes.js
  core-ui/src/components/Predefined/Details/VirtualServices/ServiceGateways.js
  core-ui/src/components/Predefined/Details/VirtualServices/ServiceHosts.js
  core-ui/src/components/Predefined/Details/VirtualServices/TcpRoutes.js
  core-ui/src/components/Predefined/Details/VirtualServices/TlsRoutes.js
  core-ui/src/components/Predefined/Details/VirtualServices/VirtualServices.details.js
  core-ui/src/components/Predefined/Details/VirtualServices/VirtualServicesDetails.scss
  core-ui/src/components/Predefined/Details/VirtualServices/common.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/VirtualServices.list.js
  core-ui/src/components/Predefined/List/index.js
  core-ui/src/shared/components/DefinitionList/DefinitionList.scss
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/fixtures/test-virtual-service.yaml
  tests/tests/test-virtual-services.spec.js
Labels: size/XXL, lgtm

#751 New creation modal for event subscriptions
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Predefined/Create/ApiRules/ApiRules.create.js
  core-ui/src/components/Predefined/Create/EventSubscriptions/EventSubscriptions.create.js
  core-ui/src/components/Predefined/Create/EventSubscriptions/helpers.js
  core-ui/src/components/Predefined/Create/EventSubscriptions/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/EventSubscriptions/EventSubscriptionConditions.js
  core-ui/src/components/Predefined/Details/EventSubscriptions/EventSubscriptions.details.js
  core-ui/src/components/Predefined/Details/Service/Service.details.js
  core-ui/src/components/Predefined/List/EventSubscription/EventSubscriptions.list.js
  core-ui/src/components/Predefined/List/EventSubscription/EventSubscriptions.scss
  core-ui/src/components/Predefined/List/index.js
  core-ui/src/shared/ResourceForm/components/ModeSelector.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/useCreateResource.js
  core-ui/src/shared/components/EventSubscriptions/CreateEventSubscriptionForm.js
  core-ui/src/shared/components/EventSubscriptions/CreateEventSubscriptionForm.scss
  core-ui/src/shared/components/EventSubscriptions/CreateEventSubscriptionModal.js
  core-ui/src/shared/components/EventSubscriptions/EventSubscriptions.js
  core-ui/src/shared/components/EventSubscriptions/createSubscriptionInput.js
  core-ui/src/shared/components/EventSubscriptionsList.js
  core/src/i18n/en.yaml
  core/src/luigi-config/nav-footer.js
  resources/web/deployment.yaml
  tests/fixtures/test-eventsubscription.yaml
  tests/support/loadFile.js
  tests/tests/in-cluster-eventing.spec.js
  tests/tests/run-after.spec.js
  tests/tests/run-before.spec.js
Labels: enhancement, size/XXL, lgtm

#762 Added plural and singular form for running pods
  core-ui/src/shared/components/RunningPodsStatus.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#763 Add list, create & delete for ServiceBindings
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingForm.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingModal.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingUsageForm/CreateServiceBindingUsageForm.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingUsageForm/CreateServiceBindingUsageModal.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.js
  service-catalog-ui/src/index.scss
Labels: size/L, lgtm
