Repository kyma-project/busola, pull requests merged in 2021-05, with the labels that each got.

#126 Add pointer cursor to the link on the generic list
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
  shared/components/ResourcesList/ResourcesList.scss
Labels: lgtm, size/XS

#127 Make access strategies inputs bigger
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/AccessStrategyForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.scss
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.js
Labels: lgtm, size/S

#128 Remove one leftover
  shared/utils/randomNamesGenerator/words.js
Labels: lgtm, size/XS

#129 Improve Service Class details
  core/src/luigi-config/navigation/static-navigation-model.js
  service-catalog-ui/src/components/App/App.js
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/JSONSchema/index.js
  service-catalog-ui/src/components/ServiceClassDetails/ServiceClassDetails.container.js
  service-catalog-ui/src/components/ServiceClassDetails/ServiceClassDetails.js
  service-catalog-ui/src/components/ServiceClassList/Cards/Cards.component.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceHeader/ServiceInstanceHeader.js
  shared/components/Spinner/Spinner.js
  shared/hooks/BackendAPI/useGet.js
Labels: lgtm, size/L

#130 Fix search suggestion styles
  core-ui/src/components/Predefined/Details/Application/Application.details.js
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/GenericList/GenericList.scss
  shared/components/GenericList/SearchInput.js
Labels: lgtm, size/M

#123 Remove backend modules dependencies
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetailsWrapper.js
  core-ui/src/components/Lambdas/LambdaDetails/test/LambdaDetails.test.js
  core-ui/src/components/Lambdas/LambdaDetails/test/LambdaDetailsWrapper.test.js
  core-ui/src/components/Lambdas/LambdasList/Lambdas/CreateLambdaForm.js
  core-ui/src/components/Lambdas/helpers/misc/backendModulesExist.js
  core-ui/src/components/Lambdas/helpers/misc/constants.js
  core-ui/src/components/Lambdas/helpers/misc/index.js
  core-ui/src/components/Predefined/Details/AddonsConfiguration.details.js
  core-ui/src/components/Predefined/Details/ApiRules.details.js
  core-ui/src/components/Predefined/Details/Application/Application.details.js
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
  core-ui/src/components/Predefined/Details/Deployment.details.js
  core-ui/src/components/Predefined/Details/Function.details.js
  core-ui/src/components/Predefined/Details/Namespace/DeployNewWorkload.js
  core-ui/src/components/Predefined/Details/Namespace/Namespace.details.js
  core-ui/src/components/Predefined/Details/OAuth2Clients/OAuth2Clients.details.js
  core-ui/src/components/Predefined/Details/Pod/Pod.details.js
  core-ui/src/components/Predefined/Details/Replicaset.details.js
  core-ui/src/components/Predefined/Details/RoleBindings/RoleBindings.details.js
  core-ui/src/components/Predefined/Details/Roles/Roles.details.js
  core-ui/src/components/Predefined/Details/Secret/Secret.details.js
  core-ui/src/components/Predefined/Details/Service/Service.details.js
  core-ui/src/components/Predefined/List/AddonsConfigurations.list.js
  core-ui/src/components/Predefined/List/ApiRules.list.js
  core-ui/src/components/Predefined/List/Application/Applications.list.js
  core-ui/src/components/Predefined/List/Deployments.list.js
  core-ui/src/components/Predefined/List/Events.list.js
  core-ui/src/components/Predefined/List/Function/CreateNewFunction.js
  core-ui/src/components/Predefined/List/Function/Functions.list.js
  core-ui/src/components/Predefined/List/GitRepository/GitRepositories.list.js
  core-ui/src/components/Predefined/List/LimitRanges.list.js
  core-ui/src/components/Predefined/List/Namespaces.list.js
  core-ui/src/components/Predefined/List/OAuth2Clients.list.js
  core-ui/src/components/Predefined/List/Pod/Pods.list.js
  core-ui/src/components/Predefined/List/ReplicaSets.list.js
  core-ui/src/components/Predefined/List/ResourceQuotas.list.js
  core-ui/src/components/Predefined/List/RoleBindings.list.js
  core-ui/src/components/Predefined/List/Secrets.list.js
  core-ui/src/components/Predefined/List/ServiceBrokers.list.js
  core-ui/src/components/Predefined/List/Services.list.js
  core/src/assets/login.js
  core/src/luigi-config/constants.js
  core/src/luigi-config/init-params.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/permissions.js
  core/src/luigi-config/navigation/queries.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  service-catalog-ui/src/helpers/index.js
  shared/contexts/MicrofrontendContext.js
  shared/index.js
  shared/utils/getComponentForResource.js
  shared/utils/modulesExist.js
Labels: lgtm, size/L

#131 Cypress smoke tests
  .gitignore
  core/Makefile
  core/package.json
  core/src/luigi-config/init-params.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/queries.js
  shared/hooks/BackendAPI/createHeaders.js
  shared/hooks/BackendAPI/useFetch.js
  tests/Dockerfile
  tests/README.md
  tests/config.js
  tests/cypress.json
  tests/fixtures/kubeconfig.yaml
  tests/package-lock.json
  tests/package.json
  tests/plugins/index.js
  tests/scripts/apply-prettier.sh
  tests/support/commands.js
  tests/support/iframe-commands.js
  tests/tests/busola-login-failed.spec.js
  tests/tests/busola-smoke-tests.spec.js
  tests/tests/console-smoke-tests.spec.js
Labels: lgtm, size/XXL

#135 Remove 'quota exceeded' code leftovers
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/luigi-event-handlers.js
  core/src/luigi-config/navigation/navigation-helpers.js
  resources/web/deployment.yaml
Labels: lgtm, size/M

#139 Rework navigation contexts
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleFormHeader/ApiRuleFormHeader.js
  core-ui/src/components/ApiRules/ApiRulesList/ApiRulesList.js
  core-ui/src/components/ApiRules/ApiRulesList/components.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
  core-ui/src/components/Lambdas/hooks/useCreateLambda.js
  core-ui/src/components/Predefined/Details/ApiRules.details.js
  core-ui/src/components/Predefined/Details/Application/ApplicationServices.js
  core-ui/src/components/Predefined/Details/Application/NamespaceBindings.js
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/CreateWorkloadForm.js
  core-ui/src/components/Predefined/Details/Namespace/NamespaceWorkloads/NamespaceWorkloads.js
  core-ui/src/components/Predefined/Details/OAuth2Clients/OAuthClientSpecPanel.js
  core-ui/src/components/Predefined/Details/Pod/ContainersLogs.js
  core-ui/src/components/Predefined/Details/Pod/Pod.details.js
  core-ui/src/components/Predefined/Details/RoleBindings/RoleBindings.js
  core-ui/src/components/Predefined/Details/Roles/Rules.js
  core-ui/src/components/Predefined/List/ApiRules.list.js
  core-ui/src/components/Predefined/List/Function/Functions.list.js
  core-ui/src/components/Predefined/List/GitRepository/GitRepositories.list.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js
  service-catalog-ui/src/components/ServiceClassDetails/ServiceClassInstancesTable/ServiceClassInstancesTable.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceHeader/ServiceInstanceHeader.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceInfo/ServiceInstanceInfo.js
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceRowRenderer.js
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceTable.js
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/StringInput/StringInput.js
Labels: lgtm, size/M

#137 Fix api rules modal
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/test/ApiRuleForm.test.js
  core-ui/src/components/ApiRules/CreateApiRule/test/CreateApiRule.test.js
  core-ui/src/components/ApiRules/EditApiRule/test/EditApiRule.test.js
  core-ui/src/components/Lambdas/LambdaDetails/test/LambdaDetailsWrapper.test.js
  core-ui/src/components/Lambdas/LambdasList/Lambdas/CreateLambdaForm.js
  core-ui/src/components/Lambdas/LambdasList/Repositories/RepositoryForm.js
  core-ui/src/components/Predefined/Details/Service/Service.details.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
  shared/hooks/navigate.js
Labels: lgtm, size/M

#141 Fix modules for init params
  core/src/luigi-config/auth/auth.js
  core/src/luigi-config/init-params.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
Labels: lgtm, size/S

#138 Test deployments
  core-ui/src/index.scss
  service-catalog-ui/src/index.scss
  tests/cypress.json
  tests/tests/busola-create-a-deployment.spec.js
Labels: lgtm, size/L

#132 Logs UI changes, Fix logs connection closed issue
  core-ui/src/components/Predefined/Details/Pod/ContainersLogs.js
  core-ui/src/components/Predefined/Details/Pod/ContainersLogs.scss
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/GenericList/GenericList.js
  shared/components/GenericList/SearchInput.js
  shared/hooks/BackendAPI/useGet.js
  shared/index.js
Labels: lgtm, size/L

#143 move cypress to optional dependency
  tests/package-lock.json
  tests/package.json
Labels: lgtm, size/L

#142 Upgrade alpine to 3.13.5 version
  backend/Dockerfile
  core-ui/Dockerfile
  logging/Dockerfile
  service-catalog-ui/Dockerfile
Labels: lgtm, size/XS

#136 Unify messaging
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/ApiRules/hooks/useDeleteApiRule.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingForm.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/hooks/useCreateLambda.js
  core-ui/src/components/Lambdas/hooks/useCreateRepository.js
  core-ui/src/components/Lambdas/hooks/useUpdateLambda.js
  core-ui/src/components/ModalWithForm/ModalWithForm.js
  core-ui/src/components/Predefined/Create/Secrets/DecodeSecretSwitch.js
  core-ui/src/components/Predefined/Details/AddonsConfiguration.details.js
  core-ui/src/components/Predefined/Details/Application/CreateBindingModal/CreateBindingModal.js
  core-ui/src/components/Predefined/Details/Application/NamespaceBindings.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/CreateWorkloadForm.js
  core-ui/src/shared/components/EventSubscriptions/EventSubscriptions.js
  core/src/luigi-config/communication.js
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingModal/CreateServiceBindingForm.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/constants.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceHeader/ServiceInstanceHeader.js
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceList.js
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceTable.js
  shared/components/GenericList/actionHandlers/simpleDelete.js
  shared/components/GenericList/actionHandlers/test/handleDelete.test.js
  shared/components/ModalWithForm/ModalWithForm.js
  shared/components/Notification/Notification.js
  shared/components/Notification/Notification.scss
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  shared/components/ResourcesList/helpers.js
  shared/contexts/MicrofrontendContext.js
  shared/contexts/NotificationContext.js
  shared/hooks/BackendAPI/config.js
  shared/hooks/BackendAPI/useFetch.js
  shared/hooks/BackendAPI/useMutation.js
  shared/hooks/BackendAPI/usePost.js
  shared/hooks/navigate.js
  shared/hooks/useCreateServiceBindingUsage.js
  shared/utils/helpers.js
Labels: lgtm, size/XL

#147 Fix missing resource links
  core-ui/src/components/Lambdas/Checkbox/Checkbox.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingForm.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingModal.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
  core-ui/src/components/Predefined/Details/Application/EditNamespaceBinding.js
  core-ui/src/components/Predefined/Details/Application/NamespaceBindings.js
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingModal/CreateServiceBindingForm.js
Labels: lgtm, size/M

#146 Update dockerfiles
  backend/Dockerfile
  core-ui/Dockerfile
  logging/Dockerfile
  service-catalog-ui/Dockerfile
Labels: lgtm, size/S

#149 Set higher limits to the requests
  backend/index.js
  resources/backend/deployment.yaml
Labels: lgtm, size/XS

#144 Handle roles with restricted permission set
  core-ui/src/components/ApiRules/ApiRulesList/ApiRulesList.js
  core-ui/src/components/App/App.js
  core-ui/src/components/NoPermissions/NoPermissions.js
  core-ui/src/components/NoPermissions/NoPermissions.scss
  core-ui/src/components/Predefined/Details/Namespace/NamespaceWorkloads/NamespaceWorkloads.js
  core-ui/src/shared/constants.js
  core/src/assets/download.svg
  core/src/assets/external.svg
  core/src/assets/logo_old.svg
  core/src/assets/sample_icon.svg
  core/src/assets/sprite.svg
  core/src/assets/static-views.js
  core/src/assets/trigger.svg
  core/src/assets/user.svg
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/permissions.js
  core/src/luigi-config/navigation/queries.js
  core/src/luigi-config/navigation/static-navigation-model.js
  core/src/luigi-config/navigation/test/permissions.test.js
  core/src/luigi-config/navigation/test/rbac-rules-matcher.test.js
  core/src/nopermissions.html
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/hooks/BackendAPI/useGet.js
Labels: lgtm, size/XL

#150 Expose function test
  .gitignore
  package-lock.json
  package.json
  resources/web/deployment.yaml
  shared/components/GenericList/SearchInput.js
  tests/README.md
  tests/cypress.json
  tests/fixtures/orders-function.js
  tests/package.json
  tests/support/iframe-commands.js
  tests/tests/busola-create-a-deployment.spec.js
  tests/tests/busola-create-a-function.spec.js
Labels: lgtm, size/L

#152 Add support for external links from enkode params
  backend/npx.js
  core-ui/src/components/Clusters/shared.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/navigation-helpers.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: lgtm, size/M

#154 Return empty arrays instead of undefined in external links
  core/src/luigi-config/navigation/navigation-helpers.js
  resources/web/deployment.yaml
Labels: lgtm, size/XS

#151 Refactor tests
  tests/config.js
  tests/cypress.json
  tests/plugins/index.js
  tests/support/index.js
  tests/support/login.js
  tests/tests/busola-create-a-deployment.spec.js
  tests/tests/busola-create-a-function.spec.js
  tests/tests/busola-smoke-tests.spec.js
  tests/tests/z-busola-login-failed.spec.js
  tests/tests/z-run-after.spec.js
Labels: lgtm, size/L

#155 Remove function preset values
  core-ui/src/components/Lambdas/hooks/createLambdaInput.js
  core-ui/src/components/Lambdas/hooks/useCreateLambda.js
  resources/web/deployment.yaml
Labels: lgtm, size/M

#156 Hide drawer on namespace change
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  shared/contexts/YamlEditorContext.js
Labels: lgtm, size/M

#160 Cluster overview
  core-ui/src/components/App/App.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.scss
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/NodeDetails.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/useNodesQuery.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverview.scss
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
  core-ui/src/components/Predefined/List/Events.list.js
  core-ui/src/shared/constants.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/CircleProgress/CircleProgress.js
  shared/hooks/BackendAPI/useGet.js
Labels: lgtm, size/L

#159 Encode plus kubeconfig
  backend/package-lock.json
  backend/package.json
  core-ui/src/components/Clusters/components/KubeconfigUpload.js
  core-ui/src/components/Clusters/shared.js
  core/package-lock.json
  core/package.json
  core/src/luigi-config/init-params.js
  core/src/luigi-config/luigi-config.js
  package-lock.json
  package.json
  shared/constants/constants.js
Labels: lgtm, size/L

#164 Deep merge params
  core-ui/src/components/Clusters/components/KubeconfigTextArea/KubeconfigTextArea.js
  core-ui/src/components/Clusters/components/KubeconfigUpload.js
  core-ui/src/components/Clusters/shared.js
Labels: lgtm, size/XS

#162 Bring back core lint
  .prettierignore
  core/package-lock.json
  core/package.json
  core/src/luigi-config/auth/auth.js
  core/src/luigi-config/cluster-management.js
  core/src/luigi-config/communication.js
  core/src/luigi-config/init-params.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/navigation-helpers.js
  core/src/luigi-config/navigation/permissions.js
  core/src/luigi-config/navigation/previous-location.js
  core/src/luigi-config/navigation/queries.js
  core/src/luigi-config/navigation/rbac-rules-matcher.js
  core/src/luigi-config/navigation/static-navigation-model.js
  core/src/luigi-config/navigation/test/permissions.test.js
  core/src/luigi-config/navigation/test/rbac-rules-matcher.test.js
Labels: lgtm, size/L

#163 Lambda fixes
  core-ui/src/components/Lambdas/LambdasList/Lambdas/CreateLambdaForm.js
  core-ui/src/components/Lambdas/LambdasList/Lambdas/CreateLambdaModal.js
  core-ui/src/components/Lambdas/LambdasList/Lambdas/test/CreateLambdaModal.test.js
  core-ui/src/components/Lambdas/components/FormInput/FormInput.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/helpers/lambdas/validateFunctionName.js
  core-ui/src/components/Lambdas/helpers/misc/validateResourceName.js
  core-ui/src/components/Lambdas/hooks/useUpdateLambda.js
  core-ui/src/components/Predefined/List/Function/CreateNewFunction.js
  resources/web/deployment.yaml
  shared/components/ModalWithForm/ModalWithForm.js
Labels: lgtm, size/M

#165 Bump resources images in deployments
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
Labels: lgtm, size/XS

#168 Fix web deployment
  resources/web/deployment.yaml
Labels: lgtm, size/XS

#169 Remove bebEnabled
  backend/npx.js
  core-ui/src/components/Clusters/shared.js
  core-ui/src/components/Preferences/AdditionalSettings.js
  core-ui/src/components/Preferences/Preferences.js
  core-ui/src/components/Preferences/test/AdditionalParams.test.js
  core/src/luigi-config/communication.js
  core/src/luigi-config/navigation/navigation-data-init.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: lgtm, size/M

#170 Enable videos recording for Cypress tests
  tests/cypress.json
Labels: lgtm, size/XS

#166 Better cluster overview
  backend/common.js
  core-ui/src/components/App/App.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.scss
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/NodeWarningsList.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/useNodesQuery.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  core-ui/src/components/Nodes/MachineInfo/MachineInfo.js
  core-ui/src/components/Nodes/MachineInfo/MachineInfo.scss
  core-ui/src/components/Nodes/NodeDetails/NodeDetails.js
  core-ui/src/components/Nodes/NodeDetails/NodeDetails.scss
  core-ui/src/components/Nodes/NodeDetailsHeader.js
  core-ui/src/components/Nodes/NodeResources/NodeResources.js
  core-ui/src/components/Nodes/NodeResources/NodeResources.scss
  core-ui/src/components/Nodes/NodeWarnings.js
  core-ui/src/components/Nodes/nodeQueries.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/index.js
Labels: lgtm, size/XL

#167 Configuration tests
  tests/tests/busola-create-a-configuration-resources.spec.js
  tests/tests/busola-create-a-deployment.spec.js
Labels: lgtm, size/L

#172 Whitesource package update
  backend/package-lock.json
  package-lock.json
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/package-lock.json
  tests/support/login.js
  tests/tests/busola-create-a-configuration-resources.spec.js
  tests/tests/busola-create-a-deployment.spec.js
Labels: lgtm, size/M

#157 Improve luigi-config; improve test stability
  core-ui/src/components/Clusters/components/KubeconfigUpload.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/BasicData.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/test/BasicData.test.js
  core/src/luigi-config/cluster-management.js
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/Notification/Notification.js
  tests/config.js
  tests/cypress.json
  tests/package-lock.json
  tests/package.json
  tests/plugins/index.js
  tests/support/commands.js
  tests/support/iframe-commands.js
  tests/support/index.js
  tests/support/local-storage.js
  tests/support/login-commands.js
  tests/support/login.js
  tests/tests/a-run-before.spec.js
  tests/tests/create-a-deployment.spec.js
  tests/tests/create-a-function.spec.js
  tests/tests/create-configuration-resources.spec.js
  tests/tests/smoke-tests.spec.js
  tests/tests/z-run-after.spec.js
  tests/tests/zzz-invalid-kubeconfig.spec.js
Labels: lgtm, size/L

#158 In-cluster eventing UI test without checking of Pod's logs
  .gitignore
  tests/Dockerfile
  tests/Makefile
  tests/fixtures/in-cluster-eventing-publisher-dependencies.json
  tests/fixtures/in-cluster-eventing-publisher.js
  tests/fixtures/in-cluster-eventing-receiver-dependencies.json
  tests/fixtures/in-cluster-eventing-receiver.js
  tests/support/commands.js
  tests/support/index.js
  tests/support/views/api-rules-view.js
  tests/support/views/functions-view.js
  tests/tests/create-a-deployment.spec.js
  tests/tests/create-a-function.spec.js
  tests/tests/create-configuration-resources.spec.js
  tests/tests/in-cluster-eventing.spec.js
  tests/tests/smoke-tests.spec.js
Labels: lgtm, size/L

#175 Fix pagination on polling
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/GenericList/GenericList.js
Labels: lgtm, size/S

#176 Order integration tests
  CODEOWNERS
  tests/cypress.json
  tests/tests/invalid-kubeconfig.spec.js
  tests/tests/run-after.spec.js
  tests/tests/run-before.spec.js
Labels: lgtm, size/S

#177 Enable smoke tests for namespace details
  tests/support/login-commands.js
  tests/tests/create-configuration-resources.spec.js
  tests/tests/smoke-tests.spec.js
Labels: lgtm, size/M

#174 Restructuring enkode
  backend/npx.js
  core-ui/src/components/Clusters/components/AuthForm/AuthForm.js
  core-ui/src/components/Clusters/components/KubeconfigTextArea/KubeconfigTextArea.js
  core-ui/src/components/Clusters/components/KubeconfigUpload.js
  core-ui/src/components/Clusters/components/getConfigFromParams.js
  core-ui/src/components/Clusters/shared.js
  core-ui/src/components/Clusters/views/AddCluster/AddCluster.js
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
  core-ui/src/components/Predefined/Details/Application/CreateBindingModal/CreateBindingModal.js
  core-ui/src/components/Predefined/List/Namespaces.list.js
  core-ui/src/components/Preferences/NamespaceSettings.js
  core-ui/src/components/Preferences/test/NamespaceSettings.test.js
  core/src/luigi-config/auth/auth.js
  core/src/luigi-config/cluster-management.js
  core/src/luigi-config/communication.js
  core/src/luigi-config/init-params.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/navigation-helpers.js
  core/src/luigi-config/navigation/queries.js
  core/src/luigi-config/settings.js
  core/src/luigi-config/utils/hidden-namespaces-toggle.js
  core/src/luigi-config/utils/system-namespaces-toggle.js
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/GenericList/GenericList.js
  shared/hooks/BackendAPI/checkForTokenExpiration.js
  shared/hooks/BackendAPI/createHeaders.js
  shared/hooks/BackendAPI/useFetch.js
  shared/hooks/index.js
  shared/hooks/test/useShowSystemNamespaces.test.js
  shared/hooks/useShowHiddenNamespaces.js
Labels: lgtm, size/XL

#178 Use highlighted search on the Logs view
  core-ui/src/components/Predefined/Details/Pod/ContainersLogs.js
  core-ui/src/components/Predefined/Details/Pod/ContainersLogs.scss
  shared/components/GenericList/SearchInput.js
Labels: lgtm, size/L
