Repository kyma-project/busola, pull requests merged in 2021-08, with the labels that each got.

#310 Fix close add variable dropdown
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/CreateVariable/CreateVariable.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableForm/VariableModal.js
  resources/web/deployment.yaml
  shared/components/ModalWithForm/ModalWithForm.js
Labels: lgtm, size/L

#317 Cron Jobs
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/Predefined/Details/CronJobs/CronJob.details.js
  core-ui/src/components/Predefined/Details/CronJobs/CronJobConcurrencyPolicy.js
  core-ui/src/components/Predefined/Details/CronJobs/CronJobJobs.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/CronJobs.list.js
  core-ui/src/components/Predefined/List/index.js
  core-ui/src/shared/components/CronJob/CronJobLastScheduleTime.js
  core-ui/src/shared/components/CronJob/CronJobSchedule.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  shared/contexts/YamlEditorContext/isValidYaml.js
Labels: lgtm, size/L

#319 Job workloads
  core-ui/src/components/Predefined/Details/CronJobs/CronJob.details.js
  core-ui/src/components/Predefined/Details/CronJobs/CronJobJobs.js
  core-ui/src/components/Predefined/Details/Deployment.details.js
  core-ui/src/components/Predefined/Details/Job/Job.details.js
  core-ui/src/components/Predefined/Details/Job/JobCompletions.js
  core-ui/src/components/Predefined/Details/Job/JobConditions.js
  core-ui/src/components/Predefined/Details/Replicaset.details.js
  core-ui/src/components/Predefined/Details/ResourcePods.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/Jobs.list.js
  core-ui/src/components/Predefined/List/index.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
Labels: lgtm, size/L

#315 Move menu texts to i18n yaml file
  CODEOWNERS
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassList/ServiceClassList.js
  shared/components/K8sNameInput/K8sNameInput.js
Labels: lgtm, size/L

#316 Delete confirmation
  core-ui/src/components/Predefined/List/Namespaces.list.js
  core-ui/src/components/Preferences/ConfirmationSettings.js
  core-ui/src/components/Preferences/LanguageSettings.js
  core-ui/src/components/Preferences/NamespaceSettings.js
  core-ui/src/components/Preferences/Preferences.js
  core-ui/src/components/Preferences/test/NamespaceSettings.test.js
  core-ui/src/shared/getComponents.js
  core/src/i18n/en.yaml
  core/src/luigi-config/communication.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/utils/feature-toggles.js
  core/src/luigi-config/utils/hidden-namespaces-toggle.js
  resources/web/deployment.yaml
  shared/components/ListActions/ListActions.js
  shared/components/ResourcesList/ResourcesList.js
  shared/hooks/index.js
  shared/hooks/test/useFeatureToggle.test.js
  shared/hooks/useFeatureToggle.js
  shared/hooks/useShowHiddenNamespaces.js
  shared/utils/getComponentForResource.js
  tests/tests/run-after.spec.js
Labels: lgtm, size/L

#318 Polish dark theming
  core-ui/public/themes/dark.css
  core-ui/public/themes/light_dark.css
  core-ui/src/components/Clusters/views/AddCluster/AddCluster.js
  core-ui/src/index.scss
  core/package-lock.json
  core/package.json
  core/src/index.css
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  service-catalog-ui/public/themes/dark.css
  service-catalog-ui/public/themes/light_dark.css
  service-catalog-ui/src/index.scss
  shared/components/CircleProgress/CircleProgress.js
  shared/components/Notification/Notification.js
  shared/components/Notification/Notification.scss
  shared/components/Tabs/Tab.js
  shared/contexts/NotificationContext.js
  shared/contexts/ThemeContext.js
  shared/contexts/YamlEditorContext/YamlEditorContext.scss
Labels: lgtm, size/XL

#322 Stateful sets
  core-ui/src/components/Predefined/Details/StatefulSet/StatefulSetReplicas.js
  core-ui/src/components/Predefined/Details/StatefulSet/StatefulSets.details.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/StatefulSets.list.js
  core-ui/src/components/Predefined/List/index.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#326 Automatically close success notifications
  core-ui/src/components/Clusters/views/AddCluster/AddCluster.js
  resources/web/deployment.yaml
  shared/contexts/NotificationContext.js
Labels: size/XS, lgtm

#325 Move tooltips messages to i18n en yaml file
  CODEOWNERS
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/AccessStrategyForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/ApiRules/ApiRulesList/components.js
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
  core-ui/src/components/Lambdas/components/ResourceNameInput/ResourceNameInput.js
  core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.js
  core-ui/src/components/Predefined/Create/Namespaces/Namespaces.create.js
  core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
  core-ui/src/components/Predefined/Create/Secrets/SecretForm.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/BasicData.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/test/BasicData.test.js
  core-ui/src/components/Predefined/List/Application/CreateApplicationModal.js
  core-ui/src/shared/components/ConfigMap/ConfigMapForm.js
  core-ui/src/shared/components/EventSubscriptions/CreateEventSubscriptionForm.js
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js
  shared/components/CopiableText/CopiableText.js
  shared/components/K8sNameInput/K8sNameInput.js
  shared/components/KeyValueForm/KeyValueForm.js
  shared/components/LabelSelectorInput/LabelSelectorInput.js
  shared/components/Link/CopiableLink.js
  shared/components/SideDrawer/SideDrawer.js
  tests/package-lock.json
  tests/package.json
  tests/tests/in-cluster-eventing.spec.js
Labels: size/XL, lgtm

#328 Fix translations for menu categories
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#329 Reorder Workloads menu
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#327 Tooltips translations for Drawer buttons
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  resources/web/deployment.yaml
  shared/components/CopiableText/CopiableText.js
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  shared/contexts/YamlEditorContext/EditorActions.js
  shared/contexts/YamlEditorContext/YamlContent.js
  shared/contexts/YamlEditorContext/YamlEditorContext.js
Labels: size/M, lgtm

#330 Fix lists refresh & CM create styles
  resources/web/deployment.yaml
  shared/components/KeyValueForm/KeyValueForm.js
  shared/components/KeyValueForm/KeyValueForm.scss
  shared/hooks/BackendAPI/useGet.js
Labels: size/S, lgtm

#324 Handle params from target cluster
  core/src/luigi-config/busola-cluster-params.js
  core/src/luigi-config/cluster-management.js
  core/src/luigi-config/kubeconfig-id.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/utils/target-cluster-config.js
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  shared/contexts/ThemeContext.js
  tests/cypress.json
  tests/tests/cluster-configuration.spec.js
Labels: size/L, lgtm

#331 Fix logs
  resources/web/deployment.yaml
  shared/hooks/BackendAPI/useGet.js
Labels: size/M, lgtm

#323 Add Daemon Sets views
  core-ui/src/components/Predefined/Details/DaemonSet.details.js
  core-ui/src/components/Predefined/Details/Job/Job.details.js
  core-ui/src/components/Predefined/Details/ResourcePods.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/DaemonSets.list.js
  core-ui/src/components/Predefined/List/Pod/Pods.list.js
  core-ui/src/components/Predefined/List/index.js
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  tests/support/views/api-rules-view.js
  tests/tests/create-configuration-resources.spec.js
  tests/tests/smoke-tests.spec.js
Labels: size/L, lgtm

#333 Move preferences view to modal
  core-ui/src/components/Preferences/Preferences.js
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  core/src/luigi-config/communication.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  resources/web/deployment.yaml
  shared/contexts/ThemeContext.js
  tests/tests/download-a-kubeconfig.spec.js
Labels: size/M, lgtm

#336 Add qbalukom to CODEOWNERS instead of parostatkiem
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/S, lgtm

#337 Fix local Busola Docker build
  Dockerfile.local
Labels: size/XS, lgtm

#332 enable luigi backdrop and add info
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
Labels: size/S, lgtm

#339 Add local and latest tag to local docker image
  Makefile
Labels: size/XS, lgtm

#334 API Rules translations
  core-ui/src/components/ApiRules/AccessStrategies/test/AccessStrategies.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/AccessStrategyForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/test/AccessStrategyForm.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleFormHeader/ApiRuleFormHeader.js
  core-ui/src/components/ApiRules/ApiRuleForm/ServicesDropdown/ServicesDropdown.js
  core-ui/src/components/ApiRules/ApiRuleForm/ServicesDropdown/test/ServicesDropdown.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/test/ApiRuleForm.test.js
  core-ui/src/components/ApiRules/ApiRulesList/test/ApiRulesListWrapper.test.js
  core-ui/src/components/ApiRules/CreateApiRule/test/CreateApiRule.test.js
  core-ui/src/components/ApiRules/EditApiRule/test/EditApiRule.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ApiRules/test/ApiRules.test.js
  core-ui/src/components/Predefined/List/ApiRules.list.js
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  resources/web/deployment.yaml
  shared/components/K8sNameInput/K8sNameInput.js
  shared/components/ResourcesList/ResourcesList.js
  tests/support/views/api-rules-view.js
  tests/tests/smoke-tests.spec.js
Labels: size/XXL, lgtm

#341 New Preferences look
  core-ui/src/components/Preferences/ConfirmationSettings.js
  core-ui/src/components/Preferences/LanguageSettings.js
  core-ui/src/components/Preferences/NamespaceSettings.js
  core-ui/src/components/Preferences/Preferences.js
  core-ui/src/components/Preferences/Preferences.scss
  core-ui/src/components/Preferences/ThemeChooser.js
  core-ui/src/components/Preferences/ThemePreview/ThemePreview.js
  core-ui/src/components/Preferences/ThemePreview/ThemePreview.scss
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  resources/web/deployment.yaml
  shared/components/TileButton/TileButton.js
  shared/components/TileButton/TileButton.scss
  shared/components/VerticalTabs/VerticalTabs.js
  shared/components/VerticalTabs/VerticalTabs.scss
  shared/index.js
Labels: size/XL, lgtm

#340 Extra services info
  core-ui/src/components/Predefined/Details/Service/Service.details.js
  core-ui/src/components/Predefined/List/Services.list.js
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  resources/web/deployment.yaml
  shared/utils/helpers.js
Labels: size/L, lgtm

#343 Remove vulnerable npm package tar
  backend/package-lock.json
  backend/package.json
  resources/backend/deployment.yaml
Labels: size/XXL, lgtm

#342 Storage configuration
  core-ui/src/components/Clusters/components/ClusterConfiguration.js
  core-ui/src/components/Clusters/views/AddCluster/AddCluster.js
  core-ui/src/components/Clusters/views/AddCluster/ChooseStorage.js
  core-ui/src/components/Clusters/views/AddCluster/ChooseStorage.scss
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
  core-ui/src/components/Clusters/views/ClusterStorageType.js
  core-ui/src/components/Preferences/ConfirmationSettings.js
  core-ui/src/components/Preferences/NamespaceSettings.js
  core-ui/src/components/Preferences/ThemePreview/ThemePreview.scss
  core/src/assets/config/config.json
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  core/src/luigi-config/auth/auth.js
  core/src/luigi-config/cluster-management/cluster-management.js
  core/src/luigi-config/cluster-management/clusters-storage.js
  core/src/luigi-config/communication.js
  core/src/luigi-config/init-params/init-params.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/queries.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/configmap.yaml
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  tests/tests/cluster-configuration.spec.js
  tests/tests/download-a-kubeconfig.spec.js
Labels: size/L, lgtm

#338 use MessageBox instead of Dialog
  core-ui/src/index.scss
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
Labels: size/M, lgtm

#344 Add more i18n translations
  core-ui/src/components/ApiRules/AccessStrategies/AccessStrategies.js
  core-ui/src/components/ApiRules/ApiRules.js
  core-ui/src/components/ApiRules/ApiRulesList/ApiRulesList.js
  core-ui/src/components/ApiRules/constants.js
  core-ui/src/components/App/App.js
  core-ui/src/components/Clusters/components/AuthForm.js
  core-ui/src/components/Clusters/components/ClusterConfiguration.js
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigTextArea/KubeconfigTextArea.js
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core-ui/src/components/Clusters/components/test/AuthForm.test.js
  core-ui/src/components/Clusters/views/AddCluster/AddCluster.js
  core-ui/src/components/EntryNotFound/EntryNotFound.js
  core-ui/src/components/Lambdas/components/LabelsInput/LabelsInput.js
  core-ui/src/components/Lambdas/components/ResourceNameInput/ResourceNameInput.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/NoPermissions/NoPermissions.js
  core-ui/src/components/Nodes/MachineInfo/MachineInfo.js
  core-ui/src/components/Nodes/NodeDetails/NodeDetails.js
  core-ui/src/components/Nodes/NodeDetailsHeader.js
  core-ui/src/components/Nodes/NodeResources/NodeResources.js
  core-ui/src/components/Nodes/NodeWarnings.js
  core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.js
  core-ui/src/components/Predefined/Details/ApiRules.details.js
  core-ui/src/components/Predefined/List/ApiRules.list.js
  core-ui/src/shared/constants.js
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  tests/package-lock.json
  tests/package.json
  tests/support/views/api-rules-view.js
  tests/tests/invalid-kubeconfig.spec.js
Labels: size/XL, lgtm

#347 Store configuration in sessionStorage in Docker
  Dockerfile.local
  core/src/luigi-config/cluster-management/cluster-management.js
  core/src/luigi-config/cluster-management/clusters-storage.js
  core/src/luigi-config/init-params/init-params.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#345 New create modal
  core-ui/src/components/App/App.js
  core-ui/src/components/Lambdas/components/LabelsInput/LabelsInput.js
  core-ui/src/components/Predefined/Create/Deployments.create.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/BasicData.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/CreateWorkloadForm.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/CreateWorkloadForm.scss
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/ScalingData.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/ServiceData.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/helpers.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/test/BasicData.test.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/test/ServiceData.test.js
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/test/__snapshots__/helpers.test.js.snap
  core-ui/src/components/Predefined/Details/Namespace/CreateWorkloadForm/test/helpers.test.js
  core-ui/src/components/Predefined/Details/Namespace/DeployNewWorkload.js
  core-ui/src/components/Predefined/List/Deployments.list.js
  core-ui/src/shared/components/CreateDeploymentForm/AdvancedForm.js
  core-ui/src/shared/components/CreateDeploymentForm/AdvancedForm.scss
  core-ui/src/shared/components/CreateDeploymentForm/CreateDeploymentForm.js
  core-ui/src/shared/components/CreateDeploymentForm/SimpleForm.js
  core-ui/src/shared/components/CreateDeploymentForm/helpers.js
  core-ui/src/shared/components/CreateModal/CollapsibleSection/CollapsibleSection.js
  core-ui/src/shared/components/CreateModal/CollapsibleSection/CollapsibleSection.scss
  core-ui/src/shared/components/CreateModal/CreateModal.js
  core-ui/src/shared/components/CreateModal/CreateModal.scss
  core-ui/src/shared/components/CreateModal/Editor/Editor.js
  core-ui/src/shared/components/CreateModal/Editor/Editor.scss
  core-ui/src/shared/components/CreateModal/ModeSelector/ModeSelector.js
  core-ui/src/shared/components/CreateModal/ModeSelector/ModeSelector.scss
  core-ui/src/shared/components/CreateModal/Presets.js
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  resources/web/deployment.yaml
  shared/components/Dropdown/Dropdown.js
  shared/components/K8sNameInput/K8sNameInput.js
  shared/components/LabelSelectorInput/LabelSelectorInput.js
  shared/components/LabelSelectorInput/LabelSelectorInput.scss
  shared/components/TextFormItem/TextFormItem.js
  tests/tests/create-a-deployment.spec.js
Labels: size/XXL, lgtm

#346 Fix the 'delete confirmation' settings bug
  core-ui/src/components/Preferences/ConfirmationSettings.js
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
Labels: size/S, lgtm

#348 BTP ServiceBindings & ServiceInstances
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
  core-ui/src/components/Predefined/Details/ServiceBinding/ServiceBinding.details.js
  core-ui/src/components/Predefined/Details/ServiceBinding/ServiceBindingData.js
  core-ui/src/components/Predefined/Details/ServiceInstance/ServiceBindingList.js
  core-ui/src/components/Predefined/Details/ServiceInstance/ServiceInstance.details.js
  core-ui/src/components/Predefined/Details/ServiceInstance/ServiceInstanceData.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/ServiceBindings.list.js
  core-ui/src/components/Predefined/List/ServiceInstances.list.js
  core-ui/src/components/Predefined/List/index.js
  core-ui/src/shared/components/BTPResourceStatus.js
  core-ui/src/shared/components/DefinitionList/DefinitionList.js
  core-ui/src/shared/components/DefinitionList/DefinitionList.scss
  core-ui/src/shared/components/ReadonlyEditorPanel.js
  core/src/assets/config/config.json
  core/src/i18n/en.yaml
  core/src/luigi-config/features.js
  core/src/luigi-config/init-params/constants.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/configmap.yaml
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  shared/hooks/BackendAPI/useGet.js
  shared/typechecking/CustomPropTypes.js
  tests/support/enkode.js
Labels: size/XL, lgtm

#352 Fix translations & create modal styles
  core-ui/src/components/Predefined/List/Pod/Pods.list.js
  core-ui/src/index.scss
  core-ui/src/shared/components/CreateDeploymentForm/SimpleForm.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/K8sNameInput/K8sNameInput.js
Labels: size/S, lgtm

#353 fix preferences and feature toggles
  core-ui/src/components/Preferences/Preferences.js
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
  shared/hooks/useFeatureToggle.js
Labels: size/S, lgtm

#367 Use sink in EventSubscriptions
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/EventSubscriptions/EventSubscriptionsWrapper.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Predefined/Details/Service/Service.details.js
  core-ui/src/shared/components/EventSubscriptions/EventSubscriptions.js
  core-ui/src/shared/components/EventSubscriptions/createSubscriptionInput.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#354 Add advances secret creation modal
  core-ui/src/components/Predefined/Create/Secrets/AdvancedForm.js
  core-ui/src/components/Predefined/Create/Secrets/CreateSecretForm.js
  core-ui/src/components/Predefined/Create/Secrets/DecodeSecretSwitch.js
  core-ui/src/components/Predefined/Create/Secrets/SecretForm.js
  core-ui/src/components/Predefined/Create/Secrets/SecretForm.scss
  core-ui/src/components/Predefined/Create/Secrets/Secrets.create.js
  core-ui/src/components/Predefined/Create/Secrets/SimpleForm.js
  core-ui/src/components/Predefined/Create/Secrets/helpers.js
  core-ui/src/components/Predefined/Create/Secrets/test/DecodeSecretSwitch.test.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/Secret/EditSecretForm.js
  core-ui/src/shared/components/CreateForm/CreateForm.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/KeyValueForm/KeyValueForm.js
Labels: size/XL, lgtm
