Repository kyma-project/busola, pull requests merged in 2021-11, with the labels that each got.

#502 Add test:smoke-local-docker npm command
  resources/web/deployment.yaml
  tests/package.json
Labels: size/XS, lgtm, hacktoberfest-accepted, hacktoberfest

#506 Fix radio buttons and yaml next button being disabled until you unfoc…
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core-ui/src/index.scss
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#505 Allow change of NODE_ENV env variable in runtime
  backend/webpack.config.js
  resources/backend/deployment.yaml
Labels: size/XS, lgtm

#500 Function resources
  core-ui/src/components/Predefined/Create/CronJobs/Containers.js
  core-ui/src/components/Predefined/Create/CronJobs/CronJobs.create.js
  core-ui/src/components/Predefined/Create/Deployments/Containers.js
  core-ui/src/components/Predefined/Create/Deployments/Deployments.create.js
  core-ui/src/components/Predefined/Create/Functions/Functions.create.js
  core-ui/src/components/Predefined/Create/Functions/helpers.js
  core-ui/src/components/Predefined/Create/Gateways/Forms/TlsForm.js
  core-ui/src/components/Predefined/Create/Gateways/Gateways.create.js
  core-ui/src/components/Predefined/Create/GitRepositories/GitRepositories.create.js
  core-ui/src/components/Predefined/Create/Issuers/Issuers.create.js
  core-ui/src/components/Predefined/Create/RoleBindings/RoleBindings.js
  core-ui/src/components/Predefined/Create/Roles/GenericRoleCreate.js
  core-ui/src/components/Predefined/Create/ServiceAccounts/SecretForm.js
  core-ui/src/components/Predefined/Create/ServiceAccounts/ServiceAccounts.create.js
  core-ui/src/shared/ResourceForm/ResourceForm.js
  core-ui/src/shared/ResourceForm/components/FormComponents.js
  core-ui/src/shared/ResourceForm/components/Inputs.js
  core-ui/src/shared/ResourceForm/components/RuntimeResources.js
  core-ui/src/shared/components/MemoryInput.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#507 Fix ExternalResourceRef input
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#503 Fix catalog delete error
  backend/certs.pem
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceTable.js
Labels: size/L, lgtm

#498 Add a view for jobs creation
  core-ui/src/components/Predefined/Create/CronJobs/CronJobs.create.js
  core-ui/src/components/Predefined/Create/Jobs/Containers.js
  core-ui/src/components/Predefined/Create/Jobs/ContainersSection.js
  core-ui/src/components/Predefined/Create/Jobs/ContainersSection.scss
  core-ui/src/components/Predefined/Create/Jobs/CronJobs.create.js
  core-ui/src/components/Predefined/Create/Jobs/Jobs.create.js
  core-ui/src/components/Predefined/Create/Jobs/ScheduleSection.js
  core-ui/src/components/Predefined/Create/Jobs/SpecSection.js
  core-ui/src/components/Predefined/Create/Jobs/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/Job/JobCompletions.js
  core-ui/src/components/Predefined/List/Deployments.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#504 add workload components definitions
  core-ui/src/components/Predefined/List/ApiRules.list.js
  core-ui/src/components/Predefined/List/CronJobs.list.js
  core-ui/src/components/Predefined/List/DaemonSets.list.js
  core-ui/src/components/Predefined/List/Deployments.list.js
  core-ui/src/components/Predefined/List/Function/Functions.list.js
  core-ui/src/components/Predefined/List/Gateways.list.js
  core-ui/src/components/Predefined/List/Jobs.list.js
  core-ui/src/components/Predefined/List/Pod/Pods.list.js
  core-ui/src/components/Predefined/List/ReplicaSets.list.js
  core-ui/src/components/Predefined/List/ServiceBindings.list.js
  core-ui/src/components/Predefined/List/ServiceInstances.list.js
  core-ui/src/components/Predefined/List/StatefulSets.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/Link/Link.js
Labels: size/L, lgtm

#509 Protected resources
  core-ui/src/components/Predefined/Create/ConfigMaps/helpers.js
  core/src/i18n/en.yaml
  core/src/luigi-config/features.js
  resources/web/deployment.yaml
  shared/components/ListActions/ListActions.js
  shared/components/PageHeader/PageHeader.scss
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  shared/contexts/YamlEditorContext/EditorActions.js
  shared/contexts/YamlEditorContext/YamlContent.js
  shared/contexts/YamlEditorContext/YamlEditorContext.js
  shared/hooks/index.js
  shared/hooks/useProtectedResources.js
Labels: size/L, lgtm

#508 Enable observability for Docker Busola
  Dockerfile.local
  core-ui/src/components/Predefined/Details/Pod/ContainersLogs.scss
  core/src/assets/config/config.json
  resources/web/deployment.yaml
Labels: size/S, lgtm

#512 add Service definition
  core-ui/src/components/Predefined/List/Services.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#513 add integration components defintions
  core-ui/src/components/Predefined/List/AddonsConfigurations.list.js
  core-ui/src/components/Predefined/List/Application/Applications.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#515 add defintions of service management items
  core-ui/src/components/Predefined/List/AddonsConfigurations.list.js
  core-ui/src/components/Predefined/List/ServiceBrokers.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassList/ServiceClassList.js
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceList.js
Labels: size/M, lgtm

#517 Refactor oauth
  core-ui/src/components/Predefined/Create/OAuthClients/CheckboxFormControl.js
  core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
  core-ui/src/components/Predefined/Create/OAuthClients/createOAuthClient.js
  core-ui/src/components/Predefined/Create/OAuthClients/helpers.js
  core-ui/src/components/Predefined/Create/OAuthClients/test/CheckboxFormControl.test.js
  core-ui/src/components/Predefined/Create/OAuthClients/test/__snapshots__/createOAuthClient.test.js.snap
  core-ui/src/components/Predefined/Create/OAuthClients/test/createOAuthClient.test.js
  core-ui/src/components/Predefined/Details/OAuth2Clients/OAuthClientSpecPanel.js
  core-ui/src/shared/ResourceForm/ResourceForm.js
  core-ui/src/shared/ResourceForm/components/FormComponents.js
  core-ui/src/shared/ResourceForm/components/Inputs.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#520 Add searchable dropdown to functions secret modal
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableInputs/ResourceVariableInput.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableInputs/VariableInputs.scss
  resources/web/deployment.yaml
Labels: size/M, lgtm

#519 Create replica set form
  core-ui/src/components/Predefined/Create/Deployments/Deployments.create.js
  core-ui/src/components/Predefined/Create/ReplicaSets/ReplicaSets.create.js
  core-ui/src/components/Predefined/Create/ReplicaSets/ReplicaSets.create.scss
  core-ui/src/components/Predefined/Create/ReplicaSets/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/shared/components/Deployment/Containers.js
  core-ui/src/shared/components/Deployment/Containers.scss
  core-ui/src/shared/components/Deployment/ContainersViews.js
  core-ui/src/shared/components/K8sResourceSelect.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#521 use natural language for CR components
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/smoke-tests.spec.js
Labels: size/M, lgtm

#523 add defintion to Namespace component
  core-ui/src/components/Predefined/List/Namespaces.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#514 Refactor api rule Create
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/AccessStrategyForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/JwtDetails/JwtDetails.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/JwtDetails/JwtDetails.scss
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/JwtDetails/test/JwtDetails.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/StringListInput.js
  core-ui/src/components/ApiRules/ApiRuleForm/AccessStrategyForm/test/AccessStrategyForm.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleForm.scss
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleFormHeader/ApiRuleFormHeader.js
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleFormHeader/ApiRuleFormHeader.scss
  core-ui/src/components/ApiRules/ApiRuleForm/ApiRuleFormHeader/test/ApiRuleFormHeader.test.js
  core-ui/src/components/ApiRules/ApiRuleForm/GatewayDropdown.js
  core-ui/src/components/ApiRules/ApiRuleForm/HostnameDropdown.js
  core-ui/src/components/ApiRules/ApiRuleForm/ServicesDropdown/ServicesDropdown.js
  core-ui/src/components/ApiRules/ApiRules.js
  core-ui/src/components/ApiRules/ApiRulesList.js
  core-ui/src/components/ApiRules/ApiRulesList/ApiRulesList.js
  core-ui/src/components/ApiRules/ApiRulesList/ApiRulesListWrapper.js
  core-ui/src/components/ApiRules/components.js
  core-ui/src/components/App/App.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ApiRules/ApiRules.js
  core-ui/src/components/Predefined/Create/ApiRules/AccessStrategyForm.js
  core-ui/src/components/Predefined/Create/ApiRules/ApiRules.create.js
  core-ui/src/components/Predefined/Create/ApiRules/GatewayDropdown.js
  core-ui/src/components/Predefined/Create/ApiRules/HostAndSubdomain.js
  core-ui/src/components/Predefined/Create/ApiRules/JwtStrategyConfig.js
  core-ui/src/components/Predefined/Create/ApiRules/Rules.js
  core-ui/src/components/Predefined/Create/ApiRules/ServiceDropdown.js
  core-ui/src/components/Predefined/Create/ApiRules/helpers.js
  core-ui/src/components/Predefined/Create/ApiRules/templates.js
  core-ui/src/components/Predefined/Create/ServiceBindings/SecretRefForm/SecretRefForm.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/ApiRules.details.js
  core-ui/src/components/Predefined/Details/Service/Service.details.js
  core-ui/src/components/Predefined/List/ApiRules.list.js
  core-ui/src/shared/ResourceForm/ResourceForm.js
  core-ui/src/shared/ResourceForm/components/FormComponents.js
  core-ui/src/shared/ResourceForm/components/Inputs.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/Dropdown/Dropdown.js
  shared/components/K8sNameInput/K8sNameInput.js
  shared/components/ResourcesList/ResourcesList.js
  tests/support/iframe-commands.js
  tests/support/views/api-rules-view.js
Labels: size/XXL, lgtm

#556 Upgrade Cypress to 9.0.0 version
  tests/package-lock.json
  tests/package.json
Labels: size/L, lgtm

#524 Update OAuth details list with missing details
  core-ui/src/components/Predefined/Details/OAuth2Clients/OAuthClientSpecPanel.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#539 Cluster config items
  core-ui/src/components/Predefined/List/CustomResourceDefinitions.list.js
  core-ui/src/components/Predefined/List/RoleBindings.list.js
  core-ui/src/components/Predefined/List/Roles.list.js
  core-ui/src/components/Predefined/List/index.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#561 Fix size of env variable modal
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableForm/VariableModal.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#522 Handle multiple AccessStrategies
  core-ui/src/components/ApiRules/AccessStrategies/AccessStrategies.js
  core-ui/src/components/ApiRules/AccessStrategies/AccessStrategies.scss
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#511 use create forms for editing resources
  core-ui/src/components/App/App.js
  core-ui/src/components/Predefined/Create/ConfigMaps/ConfigMaps.create.js
  core-ui/src/components/Predefined/Create/Secrets/Secrets.create.js
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
  core-ui/src/components/Predefined/Details/Secret/Secret.details.js
  core-ui/src/shared/ResourceForm/components/FormComponents.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
Labels: size/L, lgtm

#570 Oauth2 test
  core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/create-configuration-resources.spec.js
  tests/tests/test-oauth2.spec.js
Labels: enhancement, size/L, lgtm

#569 Test Jobs
  core-ui/src/components/Predefined/Create/GitRepositories/GitRepositories.create.js
  core-ui/src/components/Predefined/Create/Jobs/Containers.js
  core-ui/src/components/Predefined/Create/Jobs/ContainersSection.js
  core-ui/src/components/Predefined/Create/Jobs/Jobs.create.js
  core-ui/src/shared/ResourceForm/components/FormComponents.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/ControlledBy/ControlledBy.js
  tests/cypress.json
  tests/tests/test-git-repositories.spec.js
  tests/tests/test-jobs.spec.js
  tests/tests/test-oauth2.spec.js
Labels: size/L, lgtm

#574 Downgrade Cypress to 8.7.0
  backend/index.js
  resources/backend/deployment.yaml
  tests/package-lock.json
  tests/package.json
Labels: size/M, lgtm

#576 Test dns provider
  core-ui/src/components/Predefined/Create/DNSProviders/DNSProviders.create.js
  core-ui/src/components/Predefined/Create/DNSProviders/templates.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/test-dns-providers.spec.js
Labels: size/L, lgtm

#578 Cronjobs test
  core-ui/src/components/Predefined/Create/Jobs/CronJobs.create.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/test-cron-jobs.spec.js
Labels: enhancement, size/L, lgtm

#571 Test gateways
  core-ui/src/components/Predefined/Create/Gateways/Forms/TlsForm.js
  core-ui/src/components/Predefined/Create/Gateways/Gateways.create.js
  core-ui/src/components/Predefined/Create/Gateways/helpers.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/test-gateways.spec.js
Labels: size/L, lgtm

#567 Add api-rules tests, fix link, remove redirection after creation
  core-ui/src/components/ApiRules/ApiRulesList.js
  core-ui/src/components/Predefined/Create/ApiRules/AccessStrategyForm.js
  core-ui/src/components/Predefined/Create/ApiRules/ApiRules.create.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/support/views/functions-view.js
  tests/tests/create-an-api-rule.spec.js
Labels: size/L, lgtm

#573 add defintion of namespace config items
  core-ui/src/components/Predefined/List/Certificates.list.js
  core-ui/src/components/Predefined/List/ConfigMaps.list.js
  core-ui/src/components/Predefined/List/DNSEntries.list.js
  core-ui/src/components/Predefined/List/DNSProviders.list.js
  core-ui/src/components/Predefined/List/GitRepository/GitRepositories.list.js
  core-ui/src/components/Predefined/List/Issuers.list.js
  core-ui/src/components/Predefined/List/OAuth2Clients.list.js
  core-ui/src/components/Predefined/List/Secrets.list.js
  core-ui/src/components/Predefined/List/ServiceAccount/ServiceAccounts.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#584 Change logs extensivity on production and development
  backend/common.js
  resources/backend/deployment.yaml
Labels: size/XS, lgtm

#582 Automated tests for Replica sets
  core-ui/src/components/Predefined/Create/ReplicaSets/ReplicaSets.create.js
  core-ui/src/shared/components/Deployment/ContainersViews.js
  core/src/i18n/en.yaml
  core/src/luigi-config/communication.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/test-replica-sets.spec.js
Labels: size/L, lgtm

#585 test issuers
  core-ui/src/components/Predefined/Create/Issuers/Issuers.create.js
  core-ui/src/components/Predefined/Create/Secrets/Secrets.create.js
  core-ui/src/shared/ResourceForm/ResourceForm.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/test-issuers.spec.js
Labels: size/L, lgtm

#586 test stateful sets
  tests/cypress.json
  tests/support/iframe-commands.js
  tests/tests/test-statefulsets.spec.js
Labels: size/M, lgtm

#589 Test daemon sets
  tests/cypress.json
  tests/tests/test-daemon-sets.spec.js
Labels: size/M, lgtm

#593 Role bindings tests
  core-ui/src/components/Predefined/Create/RoleBindings/RoleBindings.create.js
  core-ui/src/components/Predefined/Create/RoleBindings/RoleBindings.js
  core-ui/src/shared/ResourceForm/useCreateResource.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/create-configuration-resources.spec.js
  tests/tests/test-cluster-role-bindings.spec.js
  tests/tests/test-cron-jobs.spec.js
  tests/tests/test-oauth2.spec.js
Labels: enhancement, size/L, lgtm

#594 Test secrets
  core-ui/src/components/Predefined/Create/Secrets/Secrets.create.js
  core-ui/src/shared/ResourceForm/components/FormComponents.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/test-secrets.spec.js
Labels: size/L, lgtm

#590 Rename Tracing label to be consistent
  core/src/assets/config/config.json
  resources/web/configmap.yaml
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#575 Add cypress tests for adding and deleting certificates
  core-ui/src/components/Predefined/Create/Certificates/Certificates.create.js
  core-ui/src/components/Predefined/Details/Certificate/CertificateRefs.js
  core-ui/src/components/Predefined/Details/OAuth2Clients/OAuthClientSpecPanel.js
  core-ui/src/shared/components/Tokens.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/certificates.spec.js
Labels: size/L, lgtm

#597 Repair client name in test
  tests/tests/test-cluster-role-bindings.spec.js
Labels: bug, size/XS, lgtm

#581 Fix for DNS Entries Target dropdown
  core-ui/src/components/Predefined/Create/DNSEntries/DNSEntries.create.js
  core-ui/src/components/Predefined/Create/DNSEntries/DNSNameRef.js
  core-ui/src/components/Predefined/Create/DNSEntries/TargetsRef.js
  core-ui/src/components/Predefined/Create/DNSEntries/TextRef.js
  core-ui/src/shared/ResourceForm/ResourceForm.js
  core-ui/src/shared/ResourceForm/components/FormComponents.js
  core-ui/src/shared/ResourceForm/components/Inputs.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#596 Upgrade alpine to 3.14.3 version
  Dockerfile
  Dockerfile.local
  backend/Dockerfile
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#598 Send the CA in the preflight call for new cluster
  core/src/luigi-config/navigation/queries.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#599 Remove the apiGroups Features from the config map
  README.md
  core/src/assets/config/config.json
  core/src/luigi-config/cluster-management/cluster-management.js
  core/src/luigi-config/features.js
  resources/web/configmap.yaml
  resources/web/deployment.yaml
  tests/tests/cluster-configuration.spec.js
Labels: size/L, lgtm

#583 Roles tests
  README.md
  core-ui/src/components/Predefined/Create/ConfigMaps/ConfigMaps.create.js
  core-ui/src/components/Predefined/Create/Roles/GenericRoleCreate.js
  core-ui/src/components/Predefined/Create/Roles/Roles.create.js
  core-ui/src/components/Predefined/Create/Roles/useResourcesForApiGroups.js
  core-ui/src/components/Predefined/Details/Roles/Rules.js
  core-ui/src/shared/ResourceForm/components/FormComponents.js
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
  core-ui/src/shared/components/ResourceRef/SecretRef.js
  core-ui/src/shared/components/ResourceRef/ServiceAccountRef.js
  core/src/luigi-config/kubeconfig-id/constants.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/create-a-role.spec.js
  tests/tests/create-configuration-resources.spec.js
Labels: size/L, lgtm

#572 Cypress tests for DNS Entries
  core-ui/src/components/Predefined/Create/DNSEntries/DNSEntries.create.js
  core-ui/src/components/Predefined/Create/DNSEntries/TargetsRef.js
  core-ui/src/components/Predefined/Details/DNSEntries.details.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/test-dns-entries.spec.js
  tests/tests/test-replica-sets.spec.js
Labels: size/L, lgtm

#602 fix ff form submit
  core-ui/src/shared/ResourceForm/useCreateResource.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#613 Set restartPolicy in Jobs as read only
  core-ui/src/components/Predefined/Create/Jobs/Jobs.create.js
  core-ui/src/components/Predefined/Create/Jobs/SpecSection.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#605 Adjust the pagination
  core-ui/src/components/Predefined/Create/DNSEntries/DNSEntries.create.js
  core-ui/src/components/Preferences/OtherSettings.js
  core-ui/src/components/Preferences/Preferences.js
  core-ui/src/shared/ResourceForm/inputs/ComboboxInput.js
  core/src/i18n/en.yaml
  core/src/luigi-config/communication.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/settings/pagination.js
  resources/web/deployment.yaml
  shared/components/GenericList/GenericList.js
  shared/components/GenericList/Pagination/Pagination.js
  shared/components/GenericList/Pagination/Pagination.scss
  shared/components/GenericList/components.js
  shared/components/ResourcesList/ResourcesList.js
  tests/tests/cluster-configuration.spec.js
Labels: size/L, lgtm

#618 Upgrade Luigi to 1.19.0 version
  core-ui/src/components/Preferences/Preferences.js
  core/package-lock.json
  core/package.json
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#621 Fix cron job update
  core-ui/src/components/Predefined/Create/ConfigMaps/ConfigMaps.create.js
  core-ui/src/components/Predefined/Create/Jobs/SpecSection.js
  core-ui/src/components/Predefined/Create/Secrets/Secrets.create.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#603 add doc describing Busola features
  README.md
  core/src/i18n/en.yaml
  docs/features.md
  resources/web/deployment.yaml
Labels: size/L, lgtm

#622 Fix nameinput edition between simple/advanced tabs
  resources/web/deployment.yaml
  shared/components/K8sNameInput/K8sNameInput.js
Labels: size/XS, lgtm

#626 csmall change in the feature elements
  README.md
Labels: size/XS, lgtm
