Repository kyma-project/busola, pull requests merged in 2021-10, with the labels that each got.

#427 update cluster wizard navigation to improved wizard flow
  core-ui/src/components/Clusters/components/AddClusterDialog.scss
  core-ui/src/components/Clusters/components/AddClusterWizard.js
  core/src/i18n/en.yaml
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#443 Fix a dead link
  .github/pull-request-template.md
Labels: documentation, size/XS, lgtm

#433 Upgrade Cypress to 8.5.0 version
  tests/package-lock.json
  tests/package.json
Labels: size/M, lgtm

#446 Don't send empty authorization header
  backend/common.js
  resources/backend/deployment.yaml
Labels: size/XS, lgtm

#440 Remove init encode params
  Dockerfile
  README.md
  core-ui/src/components/Clusters/params-version.js
  core-ui/src/components/Clusters/shared.js
  core-ui/src/components/Clusters/views/AddCluster/AddCluster.js
  core-ui/src/components/Clusters/views/ClusterList.js
  core/src/assets/config/config.json
  core/src/i18n/en.yaml
  core/src/luigi-config/cluster-management/cluster-management.js
  core/src/luigi-config/init-params/init-params.js
  core/src/luigi-config/init-params/params-version.js
  core/src/luigi-config/init-params/tests/params-version.test.js
  core/src/luigi-config/kubeconfig-id.js
  core/src/luigi-config/kubeconfig-id/constants.js
  core/src/luigi-config/kubeconfig-id/kubeconfig-id.js
  core/src/luigi-config/luigi-config.js
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  shared/constants/constants.js
  tests/cypress.json
  tests/package-lock.json
  tests/package.json
  tests/support/enkode.js
  tests/tests/cluster-configuration.spec.js
  tests/tests/login-enkode.spec.js
  tests/tests/login-kubeconfigID.spec.js
Labels: size/XXL, lgtm

#449 Add commit hash(version) to Busola UI
  Makefile
  core/src/assets/version.json
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/settings.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#450 Add Cluster as a feature
  core-ui/src/components/App/App.js
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Clusters/views/ClusterList.scss
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
  core-ui/src/components/Predefined/Create/Gateways/Forms/TlsForm.js
  core/src/assets/config/config.json
  core/src/i18n/en.yaml
  core/src/luigi-config/cluster-management/clusters-storage.js
  core/src/luigi-config/features.js
  core/src/luigi-config/kubeconfig-id/constants.js
  core/src/luigi-config/kubeconfig-id/kubeconfig-id.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/static-navigation-model.js
  core/src/luigi-config/settings.js
  core/src/luigi-config/utils/showAlert.js
  resources/web/configmap.yaml
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/add-cluster-disabled.spec.js
Labels: size/XL, lgtm

#442 refactor certificates to use ResourceForm
  core-ui/src/components/Predefined/Create/Certificates/AdvancedForm.js
  core-ui/src/components/Predefined/Create/Certificates/Certificates.create.js
  core-ui/src/components/Predefined/Create/Certificates/CreateCertificate.scss
  core-ui/src/components/Predefined/Create/Certificates/SimpleForm.js
  core-ui/src/components/Predefined/Create/Certificates/SimpleForm.scss
  core-ui/src/components/Predefined/Create/Certificates/helpers.js
  core-ui/src/components/Predefined/Create/Certificates/templates.js
  core-ui/src/components/Predefined/Create/DNSProviders/DNSProviders.create.js
  core-ui/src/components/Predefined/Create/Deployments/Deployments.create.js
  core-ui/src/components/Predefined/Create/Gateways/Gateways.create.js
  core-ui/src/components/Predefined/Create/Issuers/Issuers.create.js
  core-ui/src/index.scss
  core-ui/src/shared/ResourceForm/ResourceForm.js
  core-ui/src/shared/ResourceForm/ResourceForm.scss
  core-ui/src/shared/ResourceForm/components/FormComponents.js
  core-ui/src/shared/ResourceForm/components/Inputs.js
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.scss
  core/src/i18n/en.yaml
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#463 Improve issuers by adding templates
  core-ui/src/components/Predefined/Create/Issuers/Issuers.create.js
  core-ui/src/components/Predefined/Create/Issuers/templates.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm, hacktoberfest-accepted, hacktoberfest

#462 Show no permissions
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/permissions.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#471 Fix disabling of create button on create binding modal
  core-ui/src/components/Predefined/Create/ServiceBindings/ServiceBindings.create.js
  resources/web/deployment.yaml
Labels: size/S, lgtm, hacktoberfest-accepted, hacktoberfest

#470 Refactor config maps
  core-ui/src/components/Predefined/Create/ConfigMaps.create.js
  core-ui/src/components/Predefined/Create/ConfigMaps/ConfigMaps.create.js
  core-ui/src/components/Predefined/Create/ConfigMaps/helpers.js
  core-ui/src/components/Predefined/Create/Secrets/CreateSecretForm.js
  core-ui/src/components/Predefined/Create/Secrets/Secrets.create.js
  core-ui/src/components/Predefined/Create/Secrets/SecretsCreate.scss
  core-ui/src/components/Predefined/Create/Secrets/helpers.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
  core-ui/src/components/Predefined/Details/ConfigMap/EditConfigMapForm.js
  core-ui/src/components/Predefined/Details/Secret/EditSecretForm.js
  core-ui/src/components/Predefined/Details/Secret/Secret.details.js
  core-ui/src/shared/ResourceForm/ResourceForm.js
  core-ui/src/shared/ResourceForm/components/FormComponents.js
  core-ui/src/shared/ResourceForm/components/FormComponents.scss
  core-ui/src/shared/ResourceForm/useCreateResource.js
  core-ui/src/shared/components/ConfigMap/ConfigMapForm.js
  core-ui/src/shared/components/ConfigMap/createConfigMapInput.js
  core-ui/src/shared/helpers/getResourceDefs.js
  core-ui/src/shared/helpers/index.js
  core-ui/src/shared/helpers/readFromFile.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#476 Fix bugs
  core-ui/src/components/Predefined/Create/DNSEntries/TargetsRef.js
  core-ui/src/components/Predefined/Create/Gateways/Forms/TlsForm.js
  resources/web/deployment.yaml
Labels: size/M, lgtm, hacktoberfest-accepted, hacktoberfest
