Repository kyma-project/busola, pull requests merged in 2021-06, with the labels that each got.

#181 Bump resources
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
Labels: lgtm, size/XS

#179 Fix for invalid-kubeconfig flow
  tests/support/index.js
  tests/support/local-storage.js
  tests/tests/create-a-function.spec.js
  tests/tests/invalid-kubeconfig.spec.js
Labels: lgtm, size/M

#183 Test cluster overview
  CODEOWNERS
  tests/cypress.json
  tests/tests/test-cluster-overview.spec.js
Labels: lgtm, size/M

#187 Upgrade lerna library to 4.0.0 version
  lerna.json
  package-lock.json
  package.json
Labels: lgtm, size/XXL

#186 Add Kubeconfig download
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Predefined/Details/Pod/ContainersLogs.js
  core/src/luigi-config/cluster-management.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/ListActions/ListActions.js
  tests/cypress.json
  tests/plugins/index.js
  tests/tests/download-a-kubeconfig.spec.js
Labels: lgtm, size/L

#180 Kubeconfig context chooser, UI tests
  core-ui/src/components/Clusters/components/AuthForm.js
  core-ui/src/components/Clusters/components/AuthForm/AuthForm.js
  core-ui/src/components/Clusters/components/AuthForm/AuthForm.scss
  core-ui/src/components/Clusters/components/ClusterConfiguration.js
  core-ui/src/components/Clusters/components/ContextChooser/ContextChooser.js
  core-ui/src/components/Clusters/components/ContextChooser/ContextChooser.scss
  core-ui/src/components/Clusters/components/KubeconfigTextArea/KubeconfigTextArea.js
  core-ui/src/components/Clusters/components/KubeconfigUpload.js
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigFileUpload.js
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigTextArea/KubeconfigTextArea.js
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigTextArea/KubeconfigTextArea.scss
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core-ui/src/components/Clusters/components/getConfigFromParams.js
  core-ui/src/components/Clusters/shared.js
  core-ui/src/components/Clusters/views/AddCluster/AddCluster.js
  core-ui/src/components/Clusters/views/AddCluster/AddCluster.scss
  core/src/luigi-config/init-params.js
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/FileInput/FileInput.js
  shared/components/FileInput/FileInput.scss
  shared/components/Notification/Notification.scss
  tests/cypress.json
  tests/fixtures/kubeconfig--invalid.txt
  tests/package-lock.json
  tests/package.json
  tests/support/enkode.js
  tests/support/loadKubeconfigFile.js
  tests/tests/invalid-kubeconfig.spec.js
  tests/tests/login-enkode.spec.js
  tests/tests/other-logins.spec.js
Labels: lgtm, size/XXL

#188 Upgrade dependencies for backend module
  backend/package-lock.json
  backend/package.json
  package-lock.json
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
Labels: lgtm, size/L

#189 Fix missing token scenario
  core/src/luigi-config/cluster-management.js
  resources/web/deployment.yaml
Labels: lgtm, size/S

#190 Bump images to newest versions
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
Labels: lgtm, size/XS

#197 Create screenshots folder for every Cypress run
  tests/tests/run-before.spec.js
Labels: lgtm, size/XS

#191 Fix navigation to pods details
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/hooks/navigate.js
  tests/cypress.json
  tests/tests/create-a-deployment.spec.js
Labels: lgtm, size/S

#184 Check logs for the test Function
  core-ui/src/components/Predefined/Details/Pod/ContainersData.js
  core-ui/src/components/Predefined/Details/Pod/ContainersLogs.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/hooks/BackendAPI/useGet.js
  tests/config.js
  tests/cypress.json
  tests/package-lock.json
  tests/package.json
  tests/plugins/index.js
  tests/support/commands.js
  tests/tests/create-a-function.spec.js
  tests/tests/in-cluster-eventing.spec.js
  tests/tests/run-after.spec.js
  tests/tests/run-before.spec.js
Labels: lgtm, size/XL

#193 Check if user had permissions to get customresourcesdefinitions
  core-ui/src/components/Predefined/Details/Namespace/DeployNewWorkload.js
  core-ui/src/components/Predefined/List/Function/Functions.list.js
  core/src/luigi-config/init-params.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  shared/constants/constants.js
  tests/support/enkode.js
Labels: lgtm, size/S

#185 Namespace preselection
  core/src/luigi-config/cluster-management.js
  core/src/luigi-config/init-params.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/permissions.js
  core/src/luigi-config/navigation/previous-location.js
  core/src/luigi-config/navigation/queries.js
  core/src/luigi-config/navigation/static-navigation-model.js
  core/src/luigi-config/navigation/test/permissions.test.js
  resources/web/deployment.yaml
  tests/support/enkode.js
  tests/tests/login-enkode.spec.js
Labels: lgtm, size/L

#199 Don't make screenshot at tests start
  tests/tests/run-before.spec.js
Labels: lgtm, size/XS

#196 Fix empty hidden namespaces issue, Use defaults only if hiddenNamespaces are empty
  backend/npx.js
  core-ui/src/components/Clusters/shared.js
  core-ui/src/components/Predefined/Details/Application/CreateBindingModal/CreateBindingModal.js
  core-ui/src/components/Predefined/List/Namespaces.list.js
  core/src/luigi-config/init-params.js
  core/src/luigi-config/navigation/navigation-data-init.js
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/constants/constants.js
  tests/support/enkode.js
  tests/tests/login-enkode.spec.js
Labels: lgtm, size/L

#195 Update README for Cypress tests and fix md linter
  .github/ISSUE_TEMPLATE/documentation-improvement.md
  .github/ISSUE_TEMPLATE/security-vulnerability.md
  .github/pull-request-template.md
  CONTRIBUTING.md
  NOTICE.md
  package-lock.json
  package.json
  tests/README.md
Labels: lgtm, size/L

#203 Get proper replica set to filter pods
  core-ui/src/components/Predefined/Details/DeploymentPods.js
  resources/web/deployment.yaml
Labels: lgtm, size/XS

#204 Fix getting namespace from config in tests
  tests/tests/login-enkode.spec.js
Labels: lgtm, size/L

#205 Add padding to service ports
  core-ui/src/components/Predefined/Details/Service/Service.details.js
  core-ui/src/components/Predefined/Details/Service/Service.details.scss
  resources/web/deployment.yaml
Labels: lgtm, size/S

#200 Improve handling auth errors
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/shared/useShowNodeParamsError.js
  core/src/luigi-config/auth/auth.js
  core/src/luigi-config/communication.js
  resources/web/deployment.yaml
Labels: lgtm, size/M

#202 Improve useGetHook
  core-ui/src/components/Nodes/nodeQueries.js
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/hooks/BackendAPI/useGet.js
Labels: lgtm, size/M

#208 Functions configmaps UI
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.scss
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/RepositoryConfig/RepositoryConfig.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement/ResourceManagement.js
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
  core-ui/src/components/Predefined/Details/Pod/ContainersData.js
  core-ui/src/shared/components/ConfigMap/ConfigMapForm.js
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/KeyValueForm/KeyValueForm.js
  shared/components/KeyValueForm/KeyValueForm.scss
Labels: lgtm, size/M

#214 Fix deployments
  core-ui/src/components/Predefined/Details/Deployment.details.js
  core-ui/src/components/Predefined/Details/DeploymentPods.js
  resources/web/deployment.yaml
Labels: lgtm, size/M

#212 Remove outline from the labels input
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/LabelSelectorInput/LabelSelectorInput.scss
Labels: lgtm, size/XS

#210 Make variables modal wider
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/EditVariablesForm.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/EditVariablesModal.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/test/LambdaVariables.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingModal.js
  core-ui/src/components/Lambdas/LambdasList/Repositories/RepositoryModal.js
  core-ui/src/components/ModalWithForm/ModalWithForm.js
  core-ui/src/components/ModalWithForm/test/ModalWithForm.test.js
  core-ui/src/index.scss
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/ModalWithForm/ModalWithForm.js
Labels: lgtm, size/L

#213 Remove pagination if is not needed
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  resources/web/deployment.yaml
Labels: lgtm, size/S

#209 Show a prettier metrics error
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/ErrorPanel/ErrorPanel.js
  shared/components/Spinner/Spinner.js
  shared/hooks/BackendAPI/config.js
  shared/index.js
Labels: lgtm, size/M

#211 Path-based routing
  core-ui/package.json
  core-ui/src/index.js
  core/src/luigi-config/config.js
  core/webpack.config.js
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  resources/web/ingress.yaml
  service-catalog-ui/package.json
  service-catalog-ui/src/index.js
  shared/utils/getClusterConfig.js
  shared/utils/setupMonaco.js
  tests/config.js
Labels: lgtm, size/M

#215 Migrate to node 14 and fix WhiteSource security scans
  README.md
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/package-lock.json
  shared/package.json
Labels: lgtm, size/XXL

#217 Fix application mapping edit button
  resources/web/deployment.yaml
  shared/components/GenericList/GenericList.scss
Labels: lgtm, size/S

#218 Move copy-webpack-plugin to devDependencies
  core/package-lock.json
  core/package.json
Labels: lgtm, size/L

#222 Fix shared build
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/package.json
Labels: lgtm, size/S

#220 Modal validation
  core-ui/src/components/Lambdas/Checkbox/Checkbox.js
  core-ui/src/components/Lambdas/Checkbox/test/Checkbox.test.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingForm.js
  core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
  core-ui/src/index.scss
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingModal/CreateServiceBindingForm.js
  shared/components/Checkbox/Checkbox.js
  shared/components/LabelSelectorInput/LabelSelectorInput.scss
  shared/components/StringInput/StringInput.js
Labels: lgtm, size/L

#227 Remove broken default links from diagnostics sections, hide diagnosti…
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/tests/smoke-tests.spec.js
Labels: lgtm, size/M

#224 Remove unused file
  core/src/assets/config/config.js
  resources/web/deployment.yaml
Labels: lgtm, size/XS

#229 Prefill oidc scope with openid
  core-ui/src/components/Clusters/components/AuthForm.js
  core-ui/src/components/Clusters/components/test/AuthForm.test.js
  resources/web/deployment.yaml
  scripts/makefile-node-common.mk
Labels: lgtm, size/M

#221 Fix too wide deployment list
  core-ui/src/components/Predefined/List/Deployments.list.js
  core-ui/src/components/Predefined/List/ReplicaSets.list.js
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/styled.js
  shared/components/CopiableText/CopiableText.scss
  shared/components/Labels/Labels.js
  shared/components/Labels/Labels.scss
  shared/components/ResourcesList/ResourcesList.js
Labels: lgtm, size/M

#232 Add list of replicas to Function details view
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Replicas.js
  shared/components/ResourcesList/ResourcesList.js
Labels: lgtm, size/M

#237 Introduce Function pod list in the code tab
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeTab.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/PodList/PodList.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/PodList/PodList.scss
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Replicas.js
  resources/web/deployment.yaml
Labels: lgtm, size/M

#234 Improve logging funcionality
  core-ui/src/components/Predefined/Details/Pod/ContainersLogs.js
  core-ui/src/components/Predefined/Details/Pod/ContainersLogs.scss
  resources/apply-resources.sh
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/hooks/BackendAPI/useGet.js
Labels: lgtm, size/M

#238 Remove webpack-merge from dependencies
  backend/package-lock.json
  backend/package.json
  resources/backend/deployment.yaml
Labels: lgtm, size/XXL

#233 Adjust auth2Client responseTypes validation
  core-ui/src/components/Predefined/Create/OAuthClients/createOAuthClient.js
  core-ui/src/components/Predefined/Create/OAuthClients/helpers.js
  core-ui/src/components/Predefined/Details/OAuth2Clients/OAuthClientSpecPanel.js
  resources/web/deployment.yaml
Labels: lgtm, size/M

#235 Optimize requests on Function details view
  core-ui/src/components/ApiRules/ApiRulesList/ApiRulesListWrapper.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeTab.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/PodList/PodList.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ApiRules/ApiRules.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/EventSubscriptions/EventSubscriptionsWrapper.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingModal.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindingsWrapper.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Replicas.js
  resources/web/deployment.yaml
  shared/components/ModalWithForm/ModalWithForm.js
  shared/components/ResourcesList/ResourcesList.js
  shared/hooks/BackendAPI/useGet.js
Labels: lgtm, size/L

#244 Use Function built in logs button in tests
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
  tests/tests/in-cluster-eventing.spec.js
Labels: lgtm, size/S

#245 force the ingress to use https
  resources/web/ingress--single.yaml
  resources/web/ingress.yaml
Labels: lgtm, size/XS

#240 Auto-fill OIDC data when available in the kubeconfig
  core-ui/src/components/Clusters/components/AuthForm.js
  core-ui/src/components/Clusters/components/ClusterConfiguration.js
  core-ui/src/components/Clusters/components/test/ClusterConfiguration.test.js
  resources/web/deployment.yaml
Labels: lgtm, size/L

#236 Single deployment
  Dockerfile.local
  Makefile
  backend/common.js
  backend/index.js
  core/Makefile
  core/package.json
  core/src/luigi-config/config.js
  core/webpack.config.js
  resources/backend/deployment.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment.yaml
Labels: lgtm, size/L

#242 Cleanup Dockerfiles, Makefiles etc of microfrontends
  Makefile
  core-ui/Dockerfile
  core-ui/Makefile
  core-ui/nginx.conf
  core/Dockerfile
  core/Makefile
  core/nginx/conf.d/default.conf
  core/nginx/mime.types
  core/nginx/nginx.conf
  logging/Dockerfile
  logging/Makefile
  logging/nginx.conf
  resources/ingress.yaml
  resources/kubernetes-dashboard-admin.yaml
  resources/kustomization.yaml
  resources/web/deployment-service-catalog.yaml
  resources/web/deployment-single.yaml
  resources/web/deployment.yaml
  resources/web/ingress.yaml
  resources/web/kustomization.yaml
  resources/web/service-core-ui.yaml
  resources/web/service-core.yaml
  resources/web/service-service-catalog.yaml
  service-catalog-ui/Dockerfile
  service-catalog-ui/Makefile
  service-catalog-ui/nginx.conf
Labels: lgtm, size/XL

#246 Upgrade Cypress to 7.6.0 version
  tests/package-lock.json
  tests/package.json
Labels: lgtm, size/L

#231 Crds lists
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/App/App.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.scss
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitions.details.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResources.details.js
  core-ui/src/components/Predefined/Details/Pod/PodStatus.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/CustomResourceDefinitions.list.js
  core-ui/src/components/Predefined/List/index.js
  core-ui/src/shared/helpers/getResourceUrl.js
  core/src/index.css
  core/src/index.html
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  shared/components/Labels/Labels.js
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  shared/hooks/navigate.js
  tests/cypress.json
  tests/tests/create-configuration-resources.spec.js
  tests/tests/smoke-tests.spec.js
  tests/tests/test-crds.spec.js
Labels: lgtm, size/XL

#247 Fix bad OIDC cluster redirection
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/previous-location.js
  resources/web/deployment.yaml
Labels: lgtm, size/S

#254 Fix monaco
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/Editor.js
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  core-ui/src/index.js
  core-ui/webpack.config.js
  package-lock.json
  package.json
  resources/web/deployment.yaml
  service-catalog-ui/src/index.js
  shared/index.js
  shared/package-lock.json
  shared/package.json
Labels: lgtm, size/M

#248 Error handling
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/PodList/PodList.js
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassDetails/ServiceClassDetails.container.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceDetails.js
  shared/components/DetailsError/DetailsError.js
  shared/components/DetailsError/test/DetailsError.test.js
  shared/components/ErrorPanel/ErrorPanel.js
  shared/components/GenericList/GenericList.js
  shared/components/PageHeader/PageHeader.scss
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourceNotFound/ResourceNotFound.js
  shared/components/ResourceNotFound/test/ResourceNotFound.test.js
  shared/components/ResourcesList/ResourcesList.js
  shared/index.js
  shared/utils/helpers.js
Labels: lgtm, size/L
