Repository kyma-project/busola, pull requests merged in 2022-02, with the labels that each got.

#898 update connect disabled text
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#897 Bump luigi-client
  core/package-lock.json
  core/package.json
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#896 fix missing skr configmap error
  core-ui/src/components/Predefined/Details/Application/tests/useIsSKR.test.js
  core-ui/src/components/Predefined/Details/Application/useIsSKR.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#905 Add job for cleaning Busola e2e tests on nkyma
  tests/busola-e2e-cleaner.yaml
Labels: size/L, lgtm

#904 Stabilise tests
  core-ui/src/components/ApiRules/ApiRuleStatus/ApiRuleStatus.js
  core-ui/src/components/ApiRules/ApiRuleStatus/test/ApiRuleStatus.test.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/in-cluster-eventing.spec.js
  tests/tests/run-after.spec.js
  tests/tests/test-issuers.spec.js
Labels: size/M, lgtm, test-enhancement

#908 Clone configmaps and roles
  core-ui/src/components/Predefined/Create/ConfigMaps/ConfigMaps.create.js
  core-ui/src/components/Predefined/Create/Roles/GenericRoleCreate.js
  core-ui/src/components/Predefined/Create/Roles/Roles.create.js
  core-ui/src/shared/ResourceForm/useCreateResource.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
  shared/extend-jsonpath.js
  shared/index.js
  tests/cypress.json
  tests/tests/create-a-role.spec.js
  tests/tests/test-config-maps.spec.js
Labels: size/L, lgtm

#923 Add default selector for Gateways
  core-ui/src/components/Predefined/Create/Gateways/templates.js
  resources/web/deployment.yaml
  tests/tests/test-gateways.spec.js
Labels: size/S, lgtm

#925 Fix bug of concurrency policy in the Cron Jobs
  core-ui/src/components/Predefined/Create/Jobs/CronJobs.create.js
  core-ui/src/components/Predefined/Create/Jobs/templates.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#932 Fix config map not updating, fix encoded config map data
  core-ui/src/shared/ResourceForm/fields/KeyValueField.js
  resources/web/deployment.yaml
Labels: bug, size/S, lgtm

#917 Option to login through OIDC during tests
  core-ui/src/components/Clusters/views/EditCluster/EditCluster.js
  resources/web/deployment.yaml
  tests/README.md
  tests/support/login-commands.js
  tests/tests/test-replica-sets.spec.js
Labels: size/L, lgtm

#934 Repair creating Jobs and CronJobs
  core-ui/src/components/Predefined/Create/Jobs/Containers.js
  core-ui/src/components/Predefined/Create/Jobs/CronJobs.create.js
  core-ui/src/components/Predefined/Create/Jobs/Jobs.create.js
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#936 Add events list to the CRDS general views
  core-ui/src/components/Predefined/Details/CronJobs/CronJob.details.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitions.details.js
  core-ui/src/components/Predefined/Details/Job/Job.details.js
  core-ui/src/components/Predefined/Details/Subscriptions/Subscriptions.details.js
  resources/web/deployment.yaml
Labels: kind/feature, size/M, lgtm

#933 Fix bug when choosing different runtime
  core-ui/src/components/Predefined/Create/Functions/Functions.create.js
  core-ui/src/shared/ResourceForm/components/Wrapper.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#938 Add hpa list as a subcomponent to applicable workload resources
  core-ui/src/components/Predefined/Details/Deployment/Deployment.details.js
  core-ui/src/components/Predefined/Details/HPA/HPASubcomponent.js
  core-ui/src/components/Predefined/Details/HPA/helpers.js
  core-ui/src/components/Predefined/Details/ReplicaSet/Replicaset.details.js
  core-ui/src/components/Predefined/Details/StatefulSet/StatefulSets.details.js
  core-ui/src/components/Predefined/List/HPA.list.js
  resources/web/deployment.yaml
  tests/tests/test-HPA.spec.js
Labels: size/L, lgtm

#916 implement storage of hiding read-only fields
  resources/web/deployment.yaml
  shared/contexts/YamlEditorContext/EditorActions.js
Labels: size/M, lgtm

#940 Add possibility to disable sidecars for jobs and cronjobs
  core-ui/src/components/Predefined/Create/Jobs/CronJobs.create.js
  core-ui/src/components/Predefined/Create/Jobs/Jobs.create.js
  core-ui/src/components/Predefined/Create/Jobs/templates.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#955 Add deeplinks for secrets and persistent volume claims
  core-ui/src/components/Predefined/Details/Pod/Pod.details.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#479 Remove python 38
  core-ui/src/components/Lambdas/config.js
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/helpers/runtime/runtime.js
  core-ui/src/components/Lambdas/helpers/runtime/test/runtime.test.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#957 Add links to CRs with custom busola pages
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#958 Set gzip proxied to all for web
  nginx/nginx.conf
Labels: size/XS, lgtm

#949 Add error boundary to monaco editors
  core-ui/src/components/Clusters/components/AddClusterDialog.js
  core-ui/src/components/Clusters/components/AddClusterDialog.scss
  core-ui/src/components/Clusters/components/AddClusterWizard.js
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Clusters/views/EditCluster/EditCluster.js
  core-ui/src/components/Predefined/List/OAuth2Clients.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/ErrorBoundary/ErrorBoundary.js
  shared/components/ErrorBoundary/test/ErrorBoundary.test.js
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  shared/contexts/YamlEditorContext/YamlContent.js
  shared/index.js
Labels: size/L, lgtm

#965 Add wchrapka to CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#956 Change Back to Namespaces to Back to Cluster Overview, add namespaces…
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/navigation-helpers.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/tests/run-before.spec.js
  tests/tests/test-reduced-permissions.spec.js
  tests/tests/test-settings.spec.js
Labels: size/M, lgtm

#962 Introduce Istio Sidecars
  core-ui/src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.js
  core-ui/src/components/Predefined/Create/Sidecars/Sidecars.create.js
  core-ui/src/components/Predefined/Create/Sidecars/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/PersistentVolumeClaims/PersistentVolumeClaims.details.js
  core-ui/src/components/Predefined/Details/PersistentVolumeClaims/RelatedPods.js
  core-ui/src/components/Predefined/Details/Sidecars/IstioListeners.js
  core-ui/src/components/Predefined/Details/Sidecars/IstioListeners.scss
  core-ui/src/components/Predefined/Details/Sidecars/Sidecars.details.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/Sidecars.list.js
  core-ui/src/components/Predefined/List/index.js
  core-ui/src/shared/components/RelatedPods.js
  core-ui/src/shared/components/WorkloadSelector/WorkloadSelector.js
  core-ui/src/shared/components/WorkloadSelector/WorkloadSelector.scss
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/fixtures/test-sidecar.yaml
  tests/tests/test-sidecars.spec.js
  tests/tests/test-virtual-services.spec.js
Labels: kind/feature, size/XL, lgtm

#963 Introduce Network Policies feature
  core-ui/src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.js
  core-ui/src/components/Predefined/Create/NetworkPolicies/NetworkPolicies.create.js
  core-ui/src/components/Predefined/Create/NetworkPolicies/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/NetworkPolicy/LabelSelector.js
  core-ui/src/components/Predefined/Details/NetworkPolicy/NetworkPolicy.details.js
  core-ui/src/components/Predefined/Details/NetworkPolicy/Peers.js
  core-ui/src/components/Predefined/Details/NetworkPolicy/Ports.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/NetworkPolicies.list.js
  core-ui/src/components/Predefined/List/index.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/fixtures/test-network-policy.yaml
  tests/tests/test-network-policies.spec.js
Labels: size/L, lgtm

#960 adjust texts to Fiori standards
  core-ui/src/components/Predefined/Details/ApiRule/Services.js
  core-ui/src/components/Predefined/Details/HPA/helpers.js
  core-ui/src/shared/components/Secret/SecretData.js
  core-ui/src/shared/components/Secret/test/SecretData.test.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/support/views/api-rules-view.js
  tests/support/views/functions-view.js
  tests/tests/run-before.spec.js
  tests/tests/test-HPA.spec.js
  tests/tests/test-api-rules.spec.js
  tests/tests/test-applications.spec.js
  tests/tests/test-certificates.spec.js
  tests/tests/test-cluster-overview.spec.js
  tests/tests/test-cluster-role-bindings.spec.js
  tests/tests/test-command-palette.spec.js
  tests/tests/test-config-maps.spec.js
  tests/tests/test-cron-jobs.spec.js
  tests/tests/test-deployments.spec.js
  tests/tests/test-dns-entries.spec.js
  tests/tests/test-dns-providers.spec.js
  tests/tests/test-gateways.spec.js
  tests/tests/test-git-repositories.spec.js
  tests/tests/test-in-cluster-eventing.spec.js
  tests/tests/test-invalid-kubeconfig.spec.js
  tests/tests/test-issuers.spec.js
  tests/tests/test-jobs.spec.js
  tests/tests/test-oauth2.spec.js
  tests/tests/test-protected-resources.spec.js
  tests/tests/test-reduced-permissions.spec.js
  tests/tests/test-replica-sets.spec.js
  tests/tests/test-roles.spec.js
  tests/tests/test-secrets.spec.js
  tests/tests/test-service-accounts.spec.js
  tests/tests/test-settings.spec.js
Labels: size/XL, lgtm

#966 Introduce Authorization Policies view
  core-ui/src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.js
  core-ui/src/components/Predefined/Create/AuthorizationPolicies/AuthorizationPolicies.create.js
  core-ui/src/components/Predefined/Create/AuthorizationPolicies/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/AuthorizationPolicies/AuthorizationPolicies.details.js
  core-ui/src/components/Predefined/Details/AuthorizationPolicies/Rules.js
  core-ui/src/components/Predefined/Details/StorageClasses/StorageClasses.details.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/AuthorizationPolicies.list.js
  core-ui/src/components/Predefined/List/index.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/fixtures/test-authorization-policies.yaml
  tests/tests/test-HPA.spec.js
  tests/tests/test-authorization-policies.spec.js
Labels: size/L, lgtm

#968 Introduce Istio Service Entries
  core-ui/src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.js
  core-ui/src/components/Predefined/Create/ServiceEntries/ServiceEntries.create.js
  core-ui/src/components/Predefined/Create/ServiceEntries/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/PersistentVolumeClaims/PersistentVolumeClaims.details.js
  core-ui/src/components/Predefined/Details/ServiceEntries/Endpoints.js
  core-ui/src/components/Predefined/Details/ServiceEntries/ServiceEntries.details.js
  core-ui/src/components/Predefined/Details/Sidecars/IstioListeners.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/ServiceEntries.list.js
  core-ui/src/components/Predefined/List/index.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/fixtures/test-service-entry.yaml
  tests/tests/test-service-entries.spec.js
Labels: kind/feature, size/L, lgtm

#964 Prometheus stats
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/components/Predefined/Details/Namespace/ResourcesUsage.js
  core-ui/src/components/Predefined/Details/Pod/Pod.details.js
  core-ui/src/components/Predefined/Details/Pod/PodStatsGraph.js
  core-ui/src/shared/components/StatsGraph/StatsGraph.js
  core-ui/src/shared/components/StatsGraph/StatsGraph.scss
  core-ui/src/shared/components/StatsGraph/StatsPanel.js
  core-ui/src/shared/components/StatsGraph/StatsPanel.scss
  core-ui/src/shared/components/StatsGraph/index.js
  core-ui/src/shared/helpers/siPrefixes.js
  core-ui/src/shared/hooks/usePrometheus.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#967 Added pod selector and added title as props to workload selector
  core-ui/src/components/Predefined/Details/AuthorizationPolicies/AuthorizationPolicies.details.js
  core-ui/src/components/Predefined/Details/NetworkPolicy/NetworkPolicy.details.js
  core-ui/src/shared/components/WorkloadSelector/WorkloadSelector.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/test-network-policies.spec.js
Labels: size/M, lgtm

#983 Fix bug when choosing plan in Instances
  core-ui/src/components/Predefined/Create/ServiceInstances/ServiceInstances.create.js
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/PlanColumnContent.js
Labels: kind/bug, size/S, lgtm

#988 fix switching focus on enter in textarea in config maps
  core-ui/src/shared/ResourceForm/fields/DataField.js
  core-ui/src/shared/ResourceForm/fields/DataField.scss
  resources/web/deployment.yaml
  tests/tests/test-secrets.spec.js
Labels: size/S, lgtm

#992 Remove kubernetes-dashboard from the hidden namespaces
  README.md
  core/src/luigi-config/constants.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#973 Update stale.yml
  .github/stale.yml
Labels: size/XS, lgtm

#924 Update node and npm
  README.md
  backend/package-lock.json
  backend/package.json
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/App/App.js
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core-ui/src/components/Clusters/views/AddCluster/AddCluster.js
  core-ui/src/components/Clusters/views/AddCluster/AddCluster.scss
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/CodeAndDependencies.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/CodeAndDependencies/Editor.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableInputs/CustomVariableInput.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/VariableInputs/ResourceVariableInput.js
  core-ui/src/components/Nodes/NodeDetails/NodeDetails.js
  core-ui/src/components/Predefined/Details/Namespace/YamlUpload/YamlUpload.js
  core-ui/src/components/Preferences/Preferences.js
  core-ui/src/setupTests.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/fields/Editor.js
  core-ui/src/shared/ResourceForm/fields/MultiInput.js
  core/.gitignore
  core/package-lock.json
  core/package.json
  core/src/i18n/en.yaml
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  service-catalog-ui/package-lock.json
  service-catalog-ui/src/components/App/App.js
  service-catalog-ui/src/components/ModalWithForm/ModalWithForm.js
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js
  service-catalog-ui/src/components/ServiceClassDetails/CreateInstanceForm/SchemaData.js
  service-catalog-ui/src/setupTests.js
  shared/components/GenericList/SearchInput.js
  shared/components/ModalWithForm/ModalWithForm.js
  shared/components/SideDrawer/SideDrawer.js
  shared/contexts/YamlEditorContext/YamlContent.js
  shared/hooks/useWindowTitle.js
  shared/index.js
  shared/jestSetup.js
  shared/package-lock.json
  shared/package.json
  shared/utils/setupMonaco.js
  shared/webpack.config.js
  tests/package-lock.json
  tests/package.json
Labels: size/XXL, lgtm

#997 Fix vulnerabilities
  backend/package-lock.json
  core-ui/package-lock.json
  core-ui/package.json
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/XXL, lgtm

#995 Resolve upload yaml issues
  core-ui/src/components/Predefined/Details/Application/ConnectApplicationModal.js
  core-ui/src/components/Predefined/Details/Namespace/YamlUpload/YamlResourcesList.js
  core-ui/src/components/Predefined/Details/Namespace/YamlUpload/YamlUpload.js
  core-ui/src/components/Predefined/Details/Namespace/YamlUpload/YamlUploadDialog.js
  core-ui/src/components/Predefined/Details/Namespace/YamlUpload/YamlUploadDialog.scss
  core-ui/src/components/Predefined/Details/Namespace/YamlUpload/useUploadResources.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/SecretDataModal/SecretDataModal.component.js
  tests/tests/test-resource-upload.spec.js
Labels: size/L, lgtm

#1002 Added kind and apiVersion to Secrets create template
  core-ui/src/components/Predefined/Create/Secrets/helpers.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1003 Added inserting function name to dependencies
  core-ui/src/components/Predefined/Create/Functions/Functions.create.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1008 Repair deleting crd
  core-ui/src/components/ApiRules/hooks/useDeleteApiRule.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  shared/hooks/navigate.js
Labels: kind/bug, size/M, lgtm

#1015 Changed description to long description in service classes
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassDetails/ServiceClassInfo/ServiceClassInfo.js
Labels: kind/bug, size/XS, lgtm

#993 Lighthouse optimization
  core-ui/public/index.html
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/shared/components/Skeleton/Skeleton.js
  core-ui/src/shared/components/StatsGraph/StatsGraph.js
  core-ui/src/shared/components/StatsGraph/StatsPanel.scss
  core/src/index.css
  core/src/index.html
  nginx/nginx.conf
  resources/web/deployment.yaml
Labels: size/M, lgtm

#998 Add Selector with labels and expressions feature
  core-ui/src/components/Predefined/Details/AuthorizationPolicies/AuthorizationPolicies.details.js
  core-ui/src/components/Predefined/Details/DaemonSet/DaemonSet.details.js
  core-ui/src/components/Predefined/Details/Deployment/Deployment.details.js
  core-ui/src/components/Predefined/Details/Gateway/Gateway.details.js
  core-ui/src/components/Predefined/Details/Job/Job.details.js
  core-ui/src/components/Predefined/Details/NetworkPolicy/NetworkPolicy.details.js
  core-ui/src/components/Predefined/Details/PersistentVolumeClaims/PersistentVolumeClaims.details.js
  core-ui/src/components/Predefined/Details/ReplicaSet/Replicaset.details.js
  core-ui/src/components/Predefined/Details/ResourcePods.js
  core-ui/src/components/Predefined/Details/ServiceEntries/ServiceEntries.details.js
  core-ui/src/components/Predefined/Details/Sidecars/Sidecars.details.js
  core-ui/src/components/Predefined/Details/StatefulSet/StatefulSets.details.js
  core-ui/src/components/Predefined/List/PersistentVolumes.list.js
  core-ui/src/shared/components/MatchExpressionsList.js
  core-ui/src/shared/components/RelatedPods.js
  core-ui/src/shared/components/Selector/Selector.js
  core-ui/src/shared/components/Selector/Selector.scss
  core-ui/src/shared/components/Selector/tests/Selector.test.js
  core-ui/src/shared/components/WorkloadSelector/WorkloadSelector.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: kind/feature, size/XL, lgtm

#1022 Changed default pod status
  core-ui/src/components/Predefined/Details/Pod/PodStatus.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm
