Repository kyma-project/busola, pull requests merged in 2022-06, with the labels that each got.

#1382 update ajv
  core-ui/package-lock.json
  core-ui/package.json
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1380 custom links in monaco tooltips
  core-ui/src/command-pallette/CommandPaletteProvider.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/shared/components/MonacoEditorESM/Editor.js
  core-ui/src/shared/components/MonacoEditorESM/getSchemaLink.js
  core-ui/src/shared/components/MonacoEditorESM/useAutocompleteWorker.js
  core-ui/src/shared/constants.js
  core/src/luigi-config/cluster-management/cluster-management.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1393 Prevent layout shifts on cluster overview
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/CommitmentGraph.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/queries.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1383 Fix autocompletion when format is int-or-string
  core-ui/src/shared/components/MonacoEditorESM/monaco-autocomplete.worker.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1417 Fix realoding on navigation, fix breaking views
  core-ui/src/components/App/App.js
  core/src/luigi-config/navigation/customPaths.js
  core/src/luigi-config/navigation/navigation-data-init.js
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1418 Fix breadcrumbs
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1396 Memory and CPU values are not interchanged anymore
  core-ui/src/resources/ConfigMaps/ConfigMapDetails.js
  core-ui/src/shared/components/StatsGraph/StatsGraph.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1416 EXT: Window titles are the same on list and details views
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/resources/Events/EventList.js
  core-ui/src/shared/components/EventsList.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1424 added props for displaying button in ErrorBoundary
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/shared/components/ErrorBoundary/ErrorBoundary.js
  resources/web/deployment.yaml
Labels: size/M, lgtm, extensibility

#1395 minor fixes
  core-ui/package-lock.json
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core/src/luigi-config/feature-discovery.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1429 fix link for Event
  core-ui/src/resources/Events/EventList.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1423 Fix crashing view if a user puts an object instead of an array
  core-ui/src/components/App/App.js
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/ResourceSchema.js
  core-ui/src/components/Extensibility/components/Panel.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1446 Fix translations bug for extensibility
  core-ui/src/components/Extensibility/ResourceSchema.js
  core-ui/src/components/Extensibility/helpers.js
  core-ui/src/index.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/customPaths.js
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1449 Allow title for table
  core-ui/src/components/Extensibility/components/Table.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1444 Extensibility form sync
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/ResourceSchema.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1451 Extensibility: merge navigation into resource
  core-ui/src/components/App/App.js
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/useGetCRbyPath.js
  core/package-lock.json
  core/package.json
  core/src/luigi-config/customResources.js
  core/src/luigi-config/navigation/customPaths.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1452 Fix incorrect Table Widget to not break the page
  core-ui/src/components/Extensibility/components/Plain.js
  core-ui/src/components/Extensibility/components/Table.js
  core-ui/src/shared/components/GenericList/GenericList.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1399 Extensibility docs
  docs/extensibility/display-widgets.md
  docs/extensibility/form-widgets.md
  docs/extensibility/resources.md
Labels: size/L, lgtm, area/documentation

#1456 Update UI-Schema to prevent console errors
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/Extensibility/ResourceSchema.js
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1459 Fix for editing labels in extensibility
  core-ui/src/components/Extensibility/components-form/KeyValuePairRenderer.js
  core-ui/src/components/Extensibility/metadataSchema.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm, extensibility

#1467 Handle errors
  core/src/luigi-config/customResources.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1477 Fix displaying very big csr
  core-ui/src/resources/Certificates/CertificateRefs.js
  core-ui/src/resources/Certificates/CertificateRefs.scss
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1430 Logpipelines ext
  core-ui/src/components/Extensibility/SchemaRulesInjector.js
  core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRefRenderer.js
  core-ui/src/components/Extensibility/components-form/index.js
  core-ui/src/components/Extensibility/components/CodeViewer.js
  core-ui/src/components/Extensibility/components/ResourceRefs.js
  core-ui/src/components/Extensibility/components/index.js
  core-ui/src/shared/components/Dropdown/Dropdown.js
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
  core/src/i18n/en.yaml
  docs/extensibility/display-widgets.md
  docs/extensibility/form-widgets.md
  docs/extensibility/resources.md
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1478 Fix slash shortcut
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/resources/createResourceRoutes.js
  resources/web/deployment.yaml
  tests/tests/namespace/test-api-rules.spec.js
Labels: kind/bug, size/S, lgtm

#1441 Add screenshots for extensibility docs
  docs/extensibility/assets/display-widgets/Badge.png
  docs/extensibility/assets/display-widgets/CodeViewer.png
  docs/extensibility/assets/display-widgets/Columns.png
  docs/extensibility/assets/display-widgets/Panel.png
  docs/extensibility/assets/display-widgets/Table.png
  docs/extensibility/assets/display-widgets/Text.png
  docs/extensibility/assets/form-widgets/FormGroup.png
  docs/extensibility/assets/form-widgets/KeyValue.png
  docs/extensibility/assets/form-widgets/Name.png
  docs/extensibility/assets/form-widgets/Text.png
  docs/extensibility/display-widgets.md
  docs/extensibility/form-widgets.md
  examples/README.md
  examples/pizzas/README.md
  examples/pizzas/pizzas-configmap.yaml
  examples/pizzas/pizzas-crd.yaml
Labels: size/L, lgtm, area/console, area/documentation

#1482 remove nodejs16
  core-ui/src/components/Functions/config.js
  core-ui/src/components/Functions/constants.js
  core-ui/src/components/Functions/helpers/runtime/runtime.js
  core-ui/src/components/Functions/helpers/runtime/test/runtime.test.js
  docs/extensibility/form-widgets.md
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1483 EXT: Fixed read-only name input in form
  core-ui/src/components/Extensibility/components-form/NameRenderer.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm, extensibility

#1466 Add ControlledBy widgets, fix empty group bug
  core-ui/src/components/Extensibility/components/ControlledBy.js
  core-ui/src/components/Extensibility/components/index.js
  core-ui/src/components/Extensibility/helpers.js
  core-ui/src/shared/components/ControlledBy/ControlledBy.js
  core/src/luigi-config/navigation/customPaths.js
  docs/extensibility/assets/display-widgets/ControlledBy.png
  docs/extensibility/assets/display-widgets/ControlledByKind.png
  docs/extensibility/display-widgets.md
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1468 Refactor Edit Config Map to allow code editors
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
  core-ui/src/resources/ConfigMaps/ConfigMapCreate.js
  core-ui/src/shared/ResourceForm/fields/Editor.js
  core-ui/src/shared/ResourceForm/fields/RichEditorDataField/RichEditorDataField.js
  core-ui/src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.js
  core-ui/src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.scss
  core-ui/src/shared/ResourceForm/fields/index.js
  core-ui/src/shared/components/Dropdown/Dropdown.scss
  core-ui/src/shared/components/MonacoEditorESM/Editor.js
  core-ui/src/shared/components/ReadonlyEditorPanel.js
  core-ui/src/shared/utils/detectLanguage.js
  core-ui/src/styles/index.scss
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/namespace/test-config-maps.spec.js
Labels: size/L, lgtm

#1485 updated ext docs
  docs/extensibility/README.md
  docs/extensibility/display-widgets.md
  docs/extensibility/resources.md
Labels: size/L, lgtm, area/console, area/documentation

#1498 Adjust tests after some components have been removed from kyma
  core-ui/src/shared/helpers/universalLinks.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/cluster/test-cluster-role-bindings.spec.js
  tests/tests/cluster/test-custom-resources.spec.js
  tests/tests/cluster/test-navigation-features.spec.js
  tests/tests/namespace/test-service-catalog.spec.js
Labels: size/M, lgtm

#1469 read extensions from all namespaces
  core/src/luigi-config/customResources.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1497 Fix no translations for forms
  core-ui/src/components/Extensibility/components-form/CollapsibleRenderer.js
  core-ui/src/components/Extensibility/components-form/GenericList.js
  core-ui/src/components/Extensibility/components-form/KeyValuePairRenderer.js
  core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
  core-ui/src/components/Extensibility/components-form/NumberRenderer.js
  core-ui/src/components/Extensibility/components-form/StringRenderer.js
  core-ui/src/components/Extensibility/components-form/SwitchRenderer.js
  core-ui/src/components/Extensibility/helpers.js
  core-ui/src/resources/CustomResourceDefinitions/ExtensibilityStarterModal/helpers.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1513 Remove also application connector components if service catalog is disabled
  core-ui/src/components/Functions/FunctionDetails/Tabs/Code/CodeTab.js
  core-ui/src/resources/Applications/ApplicationDetails.js
  core-ui/src/resources/Namespaces/NamespaceDetails.js
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1496 Simple list widget
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Extensibility/ResourceSchema.js
  core-ui/src/components/Extensibility/components-form/NumberRenderer.js
  core-ui/src/components/Extensibility/components-form/SimpleList.js
  core-ui/src/components/Extensibility/components-form/StringRenderer.js
  core-ui/src/components/Extensibility/components-form/SwitchRenderer.js
  core-ui/src/components/Extensibility/components-form/index.js
  core-ui/src/components/Extensibility/components/Plain.js
  core-ui/src/shared/ResourceForm/components/FormField.js
  core-ui/src/shared/ResourceForm/fields/MultiInput.scss
  docs/extensibility/assets/form-widgets/GenericList.png
  docs/extensibility/assets/form-widgets/SimpleList.png
  docs/extensibility/form-widgets.md
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1522 Revert "Refactor Edit Config Map to allow code editors (#1468)"
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
  core-ui/src/resources/ConfigMaps/ConfigMapCreate.js
  core-ui/src/shared/ResourceForm/fields/Editor.js
  core-ui/src/shared/ResourceForm/fields/RichEditorDataField/RichEditorDataField.js
  core-ui/src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.js
  core-ui/src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.scss
  core-ui/src/shared/ResourceForm/fields/index.js
  core-ui/src/shared/components/Dropdown/Dropdown.scss
  core-ui/src/shared/components/MonacoEditorESM/Editor.js
  core-ui/src/shared/components/ReadonlyEditorPanel.js
  core-ui/src/shared/utils/detectLanguage.js
  core-ui/src/styles/index.scss
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/namespace/test-config-maps.spec.js
  tests/tests/namespace/test-daemon-sets.spec.js
Labels: size/L, lgtm

#1489 Uplaod multiple clusters through kubeconfigID
  core/src/assets/defaultConfig.json
  core/src/luigi-config/kubeconfig-id/index.js
  core/src/luigi-config/kubeconfig-id/loadKubeconfigById.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1525 Fix for too long event types
  core-ui/src/resources/Subscriptions/SubscriptionCreate.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm
