Repository kyma-project/busola, pull requests merged in 2022-04, with the labels that each got.

#1183 fix graph-viz bug
  core-ui/src/shared/components/ResourceGraph/buildGraph/buildNetworkGraph.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1185 Adjust owners
  OWNERS_ALIASES
Labels: size/XS, lgtm

#1187 Fix function resources form
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/LambdaReplicas.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/LambdaResources.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/ResourceManagement.scss
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/ResourceManagement/TableElements/Input.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1190 Clean up npm start commands
  backend/Dockerfile
  backend/package.json
  core-ui/package.json
  core/package.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1188 Fix deleting all Pods in namespace via details view
  core-ui/src/components/Predefined/Details/PersistentVolumeClaims/PersistentVolumeClaims.details.js
  core-ui/src/components/Predefined/List/PersistentVolumes.list.js
  core-ui/src/shared/components/RelatedPods.js
  core-ui/src/shared/components/Selector/Selector.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1186 Remove Service Catalog leftovers
  resources/web/deployment.yaml
  service-catalog-ui/package.json
  service-catalog-ui/public/themes/@sap-theming/dark.css
  service-catalog-ui/public/themes/@sap-theming/default.css
  service-catalog-ui/public/themes/@sap-theming/hcb.css
  service-catalog-ui/public/themes/@sap-theming/hcw.css
  service-catalog-ui/public/themes/@sap-theming/light_dark.css
Labels: size/XXL, lgtm, kind/cleanup

#1178 faster tooltip appearance
  core-ui/src/shared/components/Tooltip/Tooltip.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1201 Upgrade qs package and certs
  backend/certs.pem
  backend/package-lock.json
  backend/package.json
  resources/backend/deployment.yaml
Labels: size/L, lgtm

#1191 Upload multiple yaml files
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigFileUpload.js
  core-ui/src/components/Predefined/Details/Namespace/YamlUpload/YamlFileUploader.js
  core-ui/src/components/Predefined/Details/Namespace/YamlUpload/YamlResourcesList.js
  core-ui/src/components/Predefined/Details/Namespace/YamlUpload/YamlUploadDialog.js
  core-ui/src/shared/components/FileInput/FileInput.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1218 Remove Wojtek from codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#1217 Added VS to Service
  core-ui/src/components/Predefined/Create/Services/Services.create.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1151 Add stats for deployments
  core-ui/src/components/Predefined/Details/Deployment/Deployment.details.js
  core-ui/src/components/Predefined/Details/Pod/PodStatsGraph.js
  core-ui/src/shared/components/StatsGraph/StatsGraph.js
  core-ui/src/shared/components/StatsGraph/StatsPanel.js
  core-ui/src/shared/components/StatsGraph/StatsPanel.scss
  core-ui/src/shared/hooks/usePrometheus.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1209 Introduce a name generator
  core-ui/src/components/ApiRules/ApiRulesList.js
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.js
  core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.scss
  core-ui/src/components/Predefined/Create/ApiRules/ApiRules.create.js
  core-ui/src/components/Predefined/Create/Functions/Functions.create.js
  core-ui/src/components/Predefined/Create/Functions/helpers.js
  core-ui/src/components/Predefined/Create/Gateways/Forms/PortsForm.js
  core-ui/src/components/Predefined/Create/Jobs/Containers.js
  core-ui/src/components/Predefined/Create/Jobs/Jobs.create.js
  core-ui/src/components/Predefined/Create/RoleBindings/RoleBindings.js
  core-ui/src/components/Predefined/Create/Secrets/Secrets.create.js
  core-ui/src/components/Predefined/Create/Subscriptions/Subscriptions.create.js
  core-ui/src/components/Predefined/Details/CronJobs/CronJobJobs.js
  core-ui/src/components/Predefined/Details/Service/Service.details.js
  core-ui/src/components/Predefined/Details/ServiceAccount/GenericSecrets.js
  core-ui/src/components/Predefined/Details/ServiceAccount/ServiceAccount.details.js
  core-ui/src/shared/ResourceForm/components/CollapsibleSection.js
  core-ui/src/shared/ResourceForm/fields/K8sNameField.js
  core-ui/src/shared/ResourceForm/fields/K8sNameField.scss
  core-ui/src/shared/components/Deployment/Containers.js
  core-ui/src/shared/components/K8sNameInput/K8sNameInput.js
  core-ui/src/shared/components/SubscriptionsList.js
  core-ui/src/shared/utils/randomNamesGenerator/words.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/support/views/functions-view.js
  tests/tests/namespace/test-api-rules.spec.js
Labels: kind/feature, size/L, lgtm

#1212 Handle CRs on Command Palette
  core-ui/src/command-pallette/CommandPalletteUI/components/components.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/crHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/crListHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/index.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.js
  core-ui/src/components/CustomResources/CustomResources.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitions.details.js
  core-ui/src/shared/utils/helpers.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/cluster/test-command-palette.spec.js
  tests/tests/cluster/test-custom-resources.spec.js
Labels: size/L, lgtm

#1235 Clusters overview info
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/support/login-commands.js
  tests/tests/cluster/test-invalid-kubeconfig.spec.js
  tests/tests/cluster/test-multiple-context-kubeconfig.spec.js
  tests/tests/cluster/test-other-login-options.spec.js
Labels: size/S, lgtm

#1231 Handle builtin resource aliases on Command Palette
  core-ui/src/command-pallette/CommandPalletteUI/ResultsList/ResultsList.js
  core-ui/src/command-pallette/CommandPalletteUI/components/components.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/crHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/crListHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/crdHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/helpers.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/logsHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/nodesHandler.js
  core/src/i18n/en.yaml
  core/src/luigi-config/communication.js
  core/src/luigi-config/navigation/navigation-helpers.js
  resources/web/deployment.yaml
  tests/tests/cluster/test-command-palette.spec.js
Labels: size/L, lgtm

#1237 Update "async", dep of express-jwt
  backend/package-lock.json
  backend/package.json
  resources/backend/deployment.yaml
Labels: size/M, lgtm

#1239 fix getResourceDefs functions
  core-ui/src/resources/Secrets/helpers.js
  core-ui/src/shared/helpers/getResourceDefs.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1236 Make sure subscription on graphs is pointing to service
  core-ui/src/resources/Subscriptions/index.js
  core-ui/src/shared/components/ResourceGraph/buildGraph/buildNetworkGraph.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1175 Change base image to unprivileged nginx
  Dockerfile
Labels: size/XS, lgtm

#1245 Fix dockerfile
  Dockerfile
Labels: size/XS, lgtm

#1240 Open search shortcut
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/CustomResources/CRDList.js
  core-ui/src/components/CustomResources/CustomResources.js
  core-ui/src/components/CustomResources/CustomResourcesByGroup.js
  core-ui/src/components/CustomResources/GroupingListPage.js
  core-ui/src/components/CustomResources/GroupingListPage/GroupingListPage.scss
  core-ui/src/components/HelmReleases/HelmReleasesList.js
  core-ui/src/hooks/useCustomMessageListener.js
  core-ui/src/resources/Events/EventList.js
  core-ui/src/resources/createResourceRoutes.js
  core-ui/src/shared/components/GenericList/GenericList.js
  core-ui/src/shared/components/GenericList/SearchInput.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core/src/luigi-config/communication.js
  resources/web/deployment.yaml
  tests/tests/cluster/test-custom-resources.spec.js
  tests/tests/namespace/test-custom-resources.spec.js
Labels: kind/feature, size/L, lgtm

#1241 Improve caching for static files
  core-ui/public/favicon.ico
  core-ui/public/index.html
  core-ui/public/manifest.json
  core-ui/src/index.js
  core-ui/src/styles/fiori-helpers.scss
  core-ui/src/styles/index.scss
  core-ui/src/styles/reset.css
  core-ui/src/styles/sapIllus-Fills.css
  core-ui/src/styles/sapIllus-Layout.css
  core/src/luigi-config/luigi-config.js
  core/src/template.html
  nginx/nginx.conf
  resources/web/deployment.yaml
Labels: kind/feature, size/M, lgtm

#1247 Fix DNSProviders and Isssuers Details' page layout
  core-ui/src/resources/Issuers/IssuerDomains.js
  core-ui/src/resources/Namespaces/NamespaceDetails.scss
  core-ui/src/styles/index.scss
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1252 Remove messages on OAuth details view. Display a link to secret if it exists
  core-ui/src/resources/OAuth2Clients/OAuth2ClientDetails.js
  core-ui/src/resources/OAuth2Clients/OAuthClientSpecPanel.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1246 Try unprivileged container again
  Dockerfile
  core-ui/src/resources/Deployments/DeploymentList.js
  nginx/nginx.conf
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1243 Pod templates component
  core-ui/src/resources/CronJobs/CronJobDetails.js
  core-ui/src/resources/DaemonSets/DaemonSetDetails.js
  core-ui/src/resources/Deployments/DeploymentDetails.js
  core-ui/src/resources/HorizontalPodAutoscalers/helpers.js
  core-ui/src/resources/Jobs/JobDetails.js
  core-ui/src/resources/Jobs/SpecSection.js
  core-ui/src/resources/Pods/ContainersData.js
  core-ui/src/resources/ReplicaSets/ReplicaSetDetails.js
  core-ui/src/resources/StatefulSets/StatefulSetDetails.js
  core-ui/src/shared/components/GetContainersPorts.js
  core-ui/src/shared/components/Labels/Labels.js
  core-ui/src/shared/components/PodTemplate/PodTemplate.js
  core-ui/src/shared/components/PodTemplate/PodTemplate.scss
  core-ui/src/shared/components/PodTemplate/components.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/namespace/test-cron-jobs.spec.js
  tests/tests/namespace/test-daemon-sets.spec.js
Labels: kind/feature, size/L, lgtm

#1251 Add x value to prometheus tooltips
  core-ui/src/shared/components/StatsGraph/StatsGraph.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1249 Remove presets in the Edit Mode
  core-ui/src/resources/CronJobs/CronJobCreate.js
  core-ui/src/resources/Deployments/DeploymentCreate.js
  core-ui/src/resources/Gateways/GatewayCreate.js
  core-ui/src/resources/Issuers/IssuerCreate.js
  core-ui/src/resources/Jobs/JobCreate.js
  core-ui/src/resources/Roles/GenericRoleCreate.js
  core-ui/src/resources/Secrets/SecretCreate.js
  core-ui/src/resources/Secrets/helpers.js
  core-ui/src/shared/helpers/getResourceDefs.js
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1266 Load graphs when 20% of the graph container is visible
  core-ui/src/shared/components/PodTemplate/PodTemplate.js
  core-ui/src/shared/components/PodTemplate/components.js
  core-ui/src/shared/hooks/useIntersectionObserver.js
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1011 Add SSL Option to Backend Service
  backend/index.js
  docs/install-kyma-dashboard-manually.md
  resources/backend/deployment.yaml
  resources/istio/destinationrule-busola-backend.yaml
  resources/istio/kustomization.yaml
Labels: size/M, lgtm, ok-to-test

#1271 Add an option to upload resources at a namespace level
  core-ui/src/resources/Namespaces/DeployNewWorkload.js
  core-ui/src/resources/Namespaces/NamespaceDetails.js
  core-ui/src/resources/Namespaces/YamlUpload/YamlResourcesList.js
  core-ui/src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
  core-ui/src/resources/Namespaces/YamlUpload/helpers.js
  core-ui/src/resources/Namespaces/YamlUpload/useUploadResources.js
  core/src/i18n/en.yaml
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1277 Fix too many connections in the SA graphs
  core-ui/src/resources/ServiceAccounts/index.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1262 Add support for non-public OIDC clients
  core-ui/src/components/Clusters/components/AuthForm.js
  core-ui/src/components/Clusters/components/oidc-params.js
  core-ui/src/components/Clusters/components/test/oidc-params.test.js
  core-ui/src/components/Clusters/views/EditCluster/EditCluster.js
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  core/src/luigi-config/auth/auth.js
  core/src/luigi-config/auth/oidc-params.js
  core/src/luigi-config/auth/sso.js
  docs/features.md
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1265 Monaco autocomplete
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/resources/CustomResourceDefinitions/CRCreate.js
  core-ui/src/resources/CustomResourceDefinitions/CustomResourceDefinitionCreate.js
  core-ui/src/resources/Jobs/JobCreate.js
  core-ui/src/resources/Jobs/JobDetails.js
  core-ui/src/resources/Jobs/SpecSection.js
  core-ui/src/resources/Namespaces/NamespaceCreate.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/fields/Editor.js
  core-ui/src/shared/ResourceForm/fields/Editor.scss
  core-ui/src/shared/components/MonacoEditorESM/Editor.js
  core-ui/src/shared/components/MonacoEditorESM/Editor.scss
  core-ui/src/shared/components/MonacoEditorESM/monaco-autocomplete.worker.js
  core-ui/src/shared/components/MonacoEditorESM/useAutocompleteWorker.js
  core/src/assets/defaultConfig.json
  core/src/i18n/en.yaml
  docs/features.md
  nginx/core-ui.conf
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#1278 Bump fundamental to bump moment library
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm, area/security

#1285 Remove the setting to accept unauthorized in backend
  backend/index.js
  resources/backend/deployment.yaml
Labels: size/XS, lgtm, area/security

#1280 Keep edit form open after a server error
  core-ui/src/resources/APIRules/APIRuleCreate.js
  core-ui/src/resources/Applications/ApplicationCreate.js
  core-ui/src/resources/AuthorizationPolicies/AuthorizationPolicyCreate.js
  core-ui/src/resources/Certificates/CertificateCreate.js
  core-ui/src/resources/ConfigMaps/ConfigMapCreate.js
  core-ui/src/resources/CronJobs/CronJobCreate.js
  core-ui/src/resources/CustomResourceDefinitions/CustomResourceDefinitionCreate.js
  core-ui/src/resources/DaemonSets/DaemonSetCreate.js
  core-ui/src/resources/Deployments/DeploymentCreate.js
  core-ui/src/resources/DestinationRules/DestinationRuleCreate.js
  core-ui/src/resources/DnsEntries/DnsEntryCreate.js
  core-ui/src/resources/DnsProviders/DnsProviderCreate.js
  core-ui/src/resources/Functions/FunctionCreate.js
  core-ui/src/resources/Gateways/GatewayCreate.js
  core-ui/src/resources/GitRepositories/GitRepositoryCreate.js
  core-ui/src/resources/HorizontalPodAutoscalers/HorizontalPodAutoscalerCreate.js
  core-ui/src/resources/Ingresses/IngressCreate.js
  core-ui/src/resources/Issuers/IssuerCreate.js
  core-ui/src/resources/Jobs/JobCreate.js
  core-ui/src/resources/LimitRanges/LimitRangeCreate.js
  core-ui/src/resources/Namespaces/DeployNewWorkload.js
  core-ui/src/resources/Namespaces/NamespaceCreate.js
  core-ui/src/resources/NetworkPolicies/NetworkPolicyCreate.js
  core-ui/src/resources/OAuth2Clients/OAuth2ClientCreate.js
  core-ui/src/resources/PersistentVolumeClaims/PersistentVolumeClaimCreate.js
  core-ui/src/resources/PersistentVolumes/PersistentVolumeCreate.js
  core-ui/src/resources/Pods/PodCreate.js
  core-ui/src/resources/ReplicaSets/ReplicaSetCreate.js
  core-ui/src/resources/ResourceQuotas/ResourceQuotaCreate.js
  core-ui/src/resources/RoleBindings/GenericRoleBindingCreate.js
  core-ui/src/resources/Roles/GenericRoleCreate.js
  core-ui/src/resources/Secrets/SecretCreate.js
  core-ui/src/resources/ServiceAccounts/ServiceAccountCreate.js
  core-ui/src/resources/ServiceBindings/ServiceBindingCreate.js
  core-ui/src/resources/ServiceEntries/ServiceEntryCreate.js
  core-ui/src/resources/ServiceInstances/ServiceInstanceCreate.js
  core-ui/src/resources/Services/ServiceCreate.js
  core-ui/src/resources/Sidecars/SidecarCreate.js
  core-ui/src/resources/StatefulSets/StatefulSetCreate.js
  core-ui/src/resources/StorageClasses/StorageClassCreate.js
  core-ui/src/resources/Subscriptions/SubscriptionCreate.js
  core-ui/src/resources/VirtualServices/VirtualServiceCreate.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/useCreateResource.js
  core-ui/src/shared/components/ModalWithForm/ModalWithForm.js
  core-ui/src/shared/components/ResourceDetails/ResourceDetails.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core-ui/src/shared/contexts/NotificationContext.js
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1270 Introduce Volume Usage Graph for PVCs
  core-ui/src/resources/PersistentVolumeClaims/PersistentVolumeClaimDetails.js
  core-ui/src/shared/components/StatsGraph/StatsPanel.js
  core-ui/src/shared/components/StatsGraph/StatsPanel.scss
  core-ui/src/shared/hooks/usePrometheus.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: kind/feature, size/L, lgtm

#1281 Fix some sentry errors
  core-ui/src/command-pallette/CommandPaletteProvider.js
  core-ui/src/components/Functions/FunctionDetails/Tabs/ResourceManagement/ResourceManagement.js
  core-ui/src/resources/AddonsConfigurations/GenericAddonsConfigurationDetails.js
  core-ui/src/shared/components/BTPResourceStatus.js
  core-ui/src/shared/components/GenericList/GenericList.js
  core/src/luigi-config/communication.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1293 Repair calling prettifyNamePlural function
  core-ui/src/resources/DnsEntries/DnsEntryList.js
  core-ui/src/shared/components/ResourceDetails/ResourceDetails.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1292 Repair pvc to pv connect
  core-ui/src/resources/PersistentVolumeClaims/index.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1290 Fix bug when changing a handler in Api Rule
  core-ui/src/resources/APIRules/AccessStrategyForm.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm
