Repository kyma-project/busola, pull requests merged in 2022-09, with the labels that each got.

#1685 Ext: Added a sortBy feature
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/components/ResourceList.js
  core-ui/src/components/Extensibility/components/ResourceRefs.js
  core-ui/src/components/Extensibility/components/Table.js
  core-ui/src/components/Extensibility/components/helpers.js
  core-ui/src/components/Extensibility/components/tests/Table.test.js
  core-ui/src/components/Extensibility/components/tests/Widget.test.js
  core-ui/src/components/Extensibility/contexts/DataSources.js
  core-ui/src/components/Extensibility/helpers.js
  core-ui/src/components/Extensibility/jsonataWrapper.js
  core-ui/src/shared/components/GenericList/GenericList.js
  core-ui/src/shared/components/GenericList/SortModalPanel.js
  core-ui/src/shared/helpers/sortingfunctions.js
  core/src/i18n/en.yaml
  docs/extensibility/assets/display-widgets/ResourceList.png
  docs/extensibility/assets/display-widgets/ResourceListChildren.png
  docs/extensibility/assets/display-widgets/Table.png
  docs/extensibility/display-widgets.md
  docs/extensibility/jsonata.md
  docs/extensibility/resources.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  examples/services/configuration.yaml
  resources/web/deployment.yaml
  tests/tests/extensibility/ext-test-pizzas.spec.js
Labels: kind/feature, size/L, lgtm

#1806 Proxy: change 503 to 502
  backend/common.js
  resources/backend/deployment.yaml
Labels: size/XS, lgtm

#1790 Extensibility: Custom form fields
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/ResourceSchema.js
  core-ui/src/components/Extensibility/SchemaRulesInjector.js
  core-ui/src/components/Extensibility/components-form/StringRenderer.js
  core-ui/src/components/Extensibility/jsonataWrapper.js
  docs/extensibility/resources.md
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1816 Reverse sidecar
  core-ui/src/resources/Deployments/DeploymentCreate.js
  core-ui/src/resources/Deployments/templates.js
  core-ui/src/resources/Jobs/JobCreate.js
  core-ui/src/resources/Namespaces/NamespaceCreate.js
  core-ui/src/shared/hooks/useSidecarInjection.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1792 Ext sidecars
  examples/resources/configuration/istio/sidecars.yaml
Labels: size/L, lgtm

#1758 Ext: Istio Virtual Services
  core-ui/src/components/Extensibility/components-form/KeyValuePairRenderer.js
  core-ui/src/components/Extensibility/components-form/KeyValuePairRenderer.scss
  core-ui/src/shared/ResourceForm/fields/DataField.js
  core-ui/src/shared/ResourceForm/fields/KeyValueField.js
  core-ui/src/shared/ResourceForm/fields/KeyValueField.scss
  docs/extensibility/form-widgets.md
  examples/resources/configuration/istio/virtual-services.yaml
  resources/web/deployment.yaml
Labels: size/XXL, lgtm

#1822 Fix remaining paths for extensions created via UI
  core-ui/src/components/BusolaExtensions/helpers.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1800 Improve Sample Code of Kyma Functions
  core-ui/src/components/Functions/config.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1821 Allow users to create function without dependencies
  core-ui/src/components/Functions/FunctionDetails/Tabs/Code/CodeAndDependencies/CodeAndDependencies.js
  core-ui/src/components/Functions/helpers/runtime/runtime.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm, area/serverless

#1798 resource ref children
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/ResourceSchema.js
  core-ui/src/components/Extensibility/SchemaRulesInjector.js
  core-ui/src/components/Extensibility/components-form/ResourceRefRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
  core-ui/src/components/Extensibility/components-form/index.js
  core-ui/src/components/Extensibility/components/Badge.js
  core-ui/src/components/Extensibility/components/PendingWrapper.js
  core-ui/src/components/Extensibility/components/ResourceLink.js
  core-ui/src/components/Extensibility/components/Widget.js
  core-ui/src/components/Extensibility/components/tests/Widget.test.js
  core-ui/src/components/Extensibility/contexts/DataSources.js
  core-ui/src/components/Extensibility/contexts/VarStore.js
  core-ui/src/components/Extensibility/helpers/index.js
  core-ui/src/components/Extensibility/helpers/jsonataWrapper.js
  core-ui/src/components/Extensibility/helpers/prepareSchemaRules.js
  core-ui/src/components/Extensibility/hooks/useJsonata.js
  core-ui/src/components/Extensibility/hooks/useVariables.js
  core-ui/src/components/Extensibility/plugins/EnumHandler.js
  core-ui/src/components/Extensibility/plugins/SchemaRulesInjector.js
  core-ui/src/components/Extensibility/plugins/VisibilityHandler.js
  core-ui/src/index.js
  core-ui/src/shared/components/ResourceGraph/getResourceGraphConfig.js
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
  docs/extensibility/assets/form-widgets/ResourceRef.png
  docs/extensibility/form-widgets.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#1830 Fix Sentry vulnerabilities
  core-ui/src/shared/utils/helpers.js
  core/src/luigi-config/navigation/customPaths.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1826 Ext docs tweeks
  docs/extensibility/README.md
  docs/extensibility/display-section.md
  docs/extensibility/form-section.md
  docs/extensibility/resources.md
Labels: size/XL, lgtm

#1808 Create Destination Rules UI in the EXT
  core-ui/src/components/Extensibility/components-form/KeyValuePairRenderer.js
  core-ui/src/resources/DestinationRules/Subset.js
  core-ui/src/resources/DestinationRules/TrafficPolicy.js
  core/src/luigi-config/customResources.js
  core/src/luigi-config/customResources/destinationRules/details/connectionPool.js
  core/src/luigi-config/customResources/destinationRules/details/index.js
  core/src/luigi-config/customResources/destinationRules/details/loadBalancer.js
  core/src/luigi-config/customResources/destinationRules/details/outlierDetection.js
  core/src/luigi-config/customResources/destinationRules/details/portLevelSettings.js
  core/src/luigi-config/customResources/destinationRules/details/subsets.js
  core/src/luigi-config/customResources/destinationRules/details/tls.js
  core/src/luigi-config/customResources/destinationRules/details/trafficPolicy.js
  core/src/luigi-config/customResources/destinationRules/details/tunnel.js
  core/src/luigi-config/customResources/destinationRules/form/index.js
  core/src/luigi-config/customResources/destinationRules/form/subsets.js
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/connectionPool.js
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/loadBalancer.js
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/outlierDetection.js
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/portLevelSettings.js
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/tls.js
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/tunnel.js
  core/src/luigi-config/customResources/destinationRules/index.js
  core/src/luigi-config/customResources/destinationRules/translations.js
  core/src/luigi-config/customResources/index.js
  docs/extensibility/display-section.md
  docs/extensibility/form-section.md
  docs/extensibility/resources.md
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#1827 Create list view for functions using extensibility
  core-ui/src/components/Extensibility/components/Badge.js
  core-ui/src/components/Extensibility/components/Badge.scss
  core-ui/src/components/Extensibility/components/tests/Badge.test.js
  docs/extensibility/assets/display-widgets/Badge.png
  docs/extensibility/assets/display-widgets/Bagde2.png
  docs/extensibility/display-section.md
  examples/resources/istio/gateways.yaml
  examples/resources/istio/sidecars.yaml
  examples/resources/istio/virtual-services.yaml
  examples/resources/serverless/functions.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1840 Restricted RoleBinding create
  core-ui/src/hooks/useHasPermissionsFor.js
  core-ui/src/resources/RoleBindings/GenericRoleBindingCreate.js
  core-ui/src/shared/hooks/BackendAPI/useGet.js
  core/src/luigi-config/navigation/navigation-data-init.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1844 Fixed ResourceList widget to allow delete listed resources
  core-ui/src/components/Extensibility/components/ResourceList.js
  docs/extensibility/resources.md
  examples/resources/istio/gateways.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1817 Ext: Add showInfos and tooltips to the forms
  core-ui/src/components/Extensibility/components-form/GenericList.js
  core-ui/src/components/Extensibility/components-form/KeyValuePairRenderer.js
  core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
  core-ui/src/components/Extensibility/components-form/NameRenderer.js
  core-ui/src/components/Extensibility/components-form/NumberRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
  core-ui/src/components/Extensibility/components-form/SimpleList.js
  core-ui/src/components/Extensibility/components-form/SimpleList.scss
  core-ui/src/components/Extensibility/components-form/StringRenderer.js
  core-ui/src/components/Extensibility/components-form/SwitchRenderer.js
  core-ui/src/components/Extensibility/components/Badge.js
  core-ui/src/components/Extensibility/components/tests/Badge.test.js
  core-ui/src/components/Extensibility/helpers/index.js
  core-ui/src/resources/APIRules/Rules.js
  core-ui/src/resources/GitRepositories/GitRepositoryCreate.js
  core-ui/src/resources/Subscriptions/FiltersSection.js
  core-ui/src/resources/Subscriptions/SubscriptionCreate.js
  core-ui/src/shared/ResourceForm/components/CollapsibleSection.scss
  core-ui/src/shared/ResourceForm/components/FormField.js
  core-ui/src/shared/ResourceForm/components/Label.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/components/Title.js
  core-ui/src/shared/ResourceForm/fields/K8sNameField.js
  core-ui/src/shared/ResourceForm/fields/MultiInput.js
  core-ui/src/shared/components/K8sNameInput/K8sNameInput.js
  docs/extensibility/README.md
  docs/extensibility/assets/form-widgets/CodeEditor.png
  docs/extensibility/assets/form-widgets/Dropdown.png
  docs/extensibility/assets/form-widgets/Dropdown2.png
  docs/extensibility/assets/form-widgets/KeyValue.png
  docs/extensibility/display-section.md
  docs/extensibility/form-section.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  examples/resources/istio/gateways.yaml
  examples/resources/istio/sidecars.yaml
  examples/resources/serverless/functions.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1854 Fix translations for tooltips in simple list and monaco
  core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
  core-ui/src/components/Extensibility/components-form/SimpleList.js
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1855 Fix translations
  core-ui/src/components/Extensibility/helpers/index.js
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1831 EXT: Move Istio Service Entries to an extenstion
  docs/extensibility/display-section.md
  examples/resources/istio/gateways.yaml
  examples/resources/istio/service-entries.yaml
Labels: kind/feature, size/L, lgtm

#1845 Added region and zone information on nodes' details and list
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverview.scss
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
  core-ui/src/components/Clusters/views/ClusterOverview/useGetGardenerProvider.js
  core-ui/src/components/Clusters/views/ClusterOverview/useGetVersions.js
  core-ui/src/components/Clusters/views/ClusterOverview/useKymaVersionQuery.js
  core-ui/src/components/Nodes/NodeDetailsHeader.js
  core/src/i18n/en.yaml
  docs/features.md
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/cluster/test-gardener-provider.spec.js
  tests/tests/cluster/test-kyma-version.spec.js
Labels: kind/feature, size/L, lgtm

#1852 Fix RoleBindings form & EventsList
  core-ui/src/resources/Events/EventList.js
  core-ui/src/resources/RoleBindings/GenericRoleBindingCreate.js
  core-ui/src/resources/RoleBindings/RoleForm.js
  core-ui/src/resources/RoleBindings/templates.js
  core-ui/src/resources/Roles/RuleInput.js
  core-ui/src/resources/Roles/helpers.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/cluster/test-cluster-role-bindings.spec.js
  tests/tests/namespace/test-reduced-permissions.spec.js
Labels: size/L, lgtm

#1857 Checkmarx and sentry
  backend/package-lock.json
  backend/package.json
  core-ui/src/shared/helpers/universalLinks.js
  core-ui/src/shared/hooks/navigate.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1841 Presets
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/helpers/index.js
  core-ui/src/resources/ClusterRoles/helpers.js
  core-ui/src/resources/ConfigMaps/helpers.js
  core-ui/src/resources/Deployments/templates.js
  core-ui/src/resources/Gateways/templates.js
  core-ui/src/resources/Issuers/templates.js
  core-ui/src/resources/Jobs/templates.js
  core-ui/src/resources/Roles/helpers.js
  core-ui/src/resources/Secrets/helpers.js
  core/src/i18n/en.yaml
  docs/extensibility/assets/Presets.png
  docs/extensibility/presets-section.md
  docs/extensibility/resources.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  examples/pizzas/configuration/pizzas-crd.yaml
  examples/pizzas/samples/pizzas-samples.yaml
  examples/resources/istio/gateways.yaml
  resources/web/deployment.yaml
  tests/tests/extensibility/ext-test-pizzas.spec.js
  tests/tests/namespace/run-before.spec.js
Labels: size/L, lgtm

#1851 apply changes in the extensibility docs
  docs/extensibility/README.md
  docs/extensibility/datasources-section.md
  docs/extensibility/display-section.md
  docs/extensibility/form-section.md
  docs/extensibility/resources.md
  docs/extensibility/translations-section.md
Labels: documentation, size/L, lgtm, area/console

#1850 dynamic values
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/components-form/ResourceRefRenderer.js
  core-ui/src/components/Extensibility/contexts/VarStore.js
  core-ui/src/components/Extensibility/hooks/useVariables.js
  core-ui/src/components/Extensibility/plugins/SchemaRulesInjector.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core/src/i18n/en.yaml
  docs/extensibility/datasources-section.md
  docs/extensibility/display-section.md
  docs/extensibility/form-section.md
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1872 Update Copyright
  LICENSE
Labels: size/XS, lgtm

#1842 Ext function form
  core-ui/src/components/Extensibility/components-form/CollapsibleRenderer.js
  core-ui/src/components/Extensibility/components-form/CollapsibleRenderer.scss
  core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
  core-ui/src/components/Extensibility/components-form/NumberRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
  core-ui/src/components/Extensibility/components-form/StringRenderer.js
  core-ui/src/components/Extensibility/plugins/VisibilityHandler.js
  core-ui/src/resources/Roles/RuleInput.js
  core-ui/src/shared/components/K8sResourceSelect.js
  core/src/luigi-config/navigation/customPaths.js
  docs/extensibility/form-section.md
  examples/resources/serverless/functions.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1876 ExternalLink widget
  core-ui/src/components/Extensibility/components/ExternalLink.js
  core-ui/src/components/Extensibility/components/ResourceLink.js
  core-ui/src/components/Extensibility/components/index.js
  docs/extensibility/assets/display-widgets/ExternalLink.png
  docs/extensibility/assets/display-widgets/ExternalLink2.png
  docs/extensibility/display-section.md
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1884 Split SchemaRuleInjector
  core-ui/src/components/Extensibility/components-form/index.js
  core-ui/src/components/Extensibility/helpers/prepareSchemaRules.js
  core-ui/src/components/Extensibility/plugins/CustomFieldInjector.js
  core-ui/src/components/Extensibility/plugins/SchemaRulesInjector.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1861 EXT form: remove doubled form state
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/helpers/immutableConverter.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1883 Change code blocks from the Example sections to YAML
  docs/extensibility/datasources-section.md
  docs/extensibility/display-section.md
  docs/extensibility/form-section.md
  docs/extensibility/jsonata.md
  docs/extensibility/presets-section.md
  docs/extensibility/resources.md
Labels: documentation, kind/feature, size/XXL, lgtm, area/busola/extensibility

#1892 EXT: add disableEdit and Delete flag
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/shared/components/ResourceDetails/ResourceDetails.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  docs/extensibility/resources.md
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1894 Widgets in joined array
  core-ui/src/components/Extensibility/components/ExternalLink.js
  core-ui/src/components/Extensibility/components/JoinedArray.js
  core-ui/src/components/Extensibility/components/tests/JoinedArray.test.js
  docs/extensibility/display-section.md
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1888 improve $item handling in display arrays
  core-ui/src/components/Extensibility/components/ExternalLink.js
  core-ui/src/components/Extensibility/components/Table.js
  core-ui/src/components/Extensibility/components/Widget.js
  core-ui/src/shared/components/Link/Link.js
  core/src/i18n/en.yaml
  docs/extensibility/assets/display-widgets/ExternalLink.png
  docs/extensibility/assets/display-widgets/ExternalLink2.png
  docs/extensibility/display-section.md
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1900 Add extensibility feature documentation
  docs/features.md
Labels: size/S, lgtm

#1859 Add widget for notofications
  core-ui/src/components/Extensibility/components-form/AlertRenderer.js
  core-ui/src/components/Extensibility/components-form/index.js
  core-ui/src/components/Extensibility/components/Alert.js
  core-ui/src/components/Extensibility/components/index.js
  core-ui/src/components/Extensibility/hooks/useVariables.js
  core-ui/src/components/Extensibility/plugins/CustomFieldInjector.js
  docs/extensibility/assets/form-widgets/Alert.png
  docs/extensibility/display-section.md
  docs/extensibility/form-section.md
  examples/resources/istio/gateways.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1874 Extensibility: Possibility to search for resources in the List widgets
  core-ui/src/components/BusolaExtensions/BusolaExtensionList.js
  core-ui/src/components/CustomResources/CustomResources.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/components/ResourceList.js
  core-ui/src/components/Extensibility/components/Table.js
  core-ui/src/components/Extensibility/components/helpers.js
  core-ui/src/components/Extensibility/components/tests/Table.test.js
  core-ui/src/components/Extensibility/helpers/index.js
  core-ui/src/shared/components/GenericList/helpers.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  docs/extensibility/display-section.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  examples/resources/istio/authorization-policies.yaml
  resources/web/deployment.yaml
Labels: kind/feature, size/L, lgtm
