Repository kyma-project/busola, pull requests merged in 2022-08, with the labels that each got.

#1659 Add button to load default kubeconfig
  core-ui/src/components/App/useLoginWithKubeconfigID.js
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Functions/helpers/functions/getFunctionStatus.js
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  core/src/luigi-config/communication.js
  core/src/luigi-config/kubeconfig-id/loadKubeconfigById.js
  resources/web/deployment.yaml
  tests/tests/cluster/test-login-kubeconfigID.spec.js
Labels: size/M, lgtm

#1661 Lazy load extensibility
  core-ui/src/components/App/App.js
  core-ui/src/components/App/ExtensibilityRoutes.js
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/shared/components/Deployment/Containers.scss
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1682 Fix sentry errors
  core-ui/src/hooks/useVersionWarning.js
  core-ui/src/resources/ConfigMaps/ConfigMapDetails.js
  core-ui/src/resources/ServiceInstances/ServiceInstanceData.js
  core-ui/src/shared/utils/helpers.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1646 Extensibility UI
  core-ui/src/components/BusolaExtensions/BusolaExtensionCreate.js
  core-ui/src/components/BusolaExtensions/BusolaExtensionDetails.js
  core-ui/src/components/BusolaExtensions/BusolaExtensionEdit.js
  core-ui/src/components/BusolaExtensions/BusolaExtensionList.js
  core-ui/src/components/BusolaExtensions/ColumnsInput.js
  core-ui/src/components/BusolaExtensions/ExtensibilityStarterForm.scss
  core-ui/src/components/BusolaExtensions/ExtensibilityStarterModal.js
  core-ui/src/components/BusolaExtensions/helpers.js
  core-ui/src/components/BusolaExtensions/index.js
  core-ui/src/components/Extensibility/migration.js
  core-ui/src/resources/ConfigMaps/ConfigMapDetails.js
  core-ui/src/resources/CustomResourceDefinitions/CustomResourceDefinitionDetails.js
  core-ui/src/resources/CustomResourceDefinitions/ExtensibilityStarterModal/ExtensibilityStarterForm.js
  core-ui/src/resources/other.js
  core-ui/src/resources/other/BusolaExtensions.routes.js
  core-ui/src/shared/ResourceForm/fields/Editor.js
  core-ui/src/shared/ResourceForm/fields/index.js
  core-ui/src/shared/components/MonacoEditorESM/Editor.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#1665 Err boundary for EXT
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityErrBoundary.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/components/Widget.js
  core-ui/src/components/Extensibility/components/tests/Widget.test.js
  core-ui/src/components/Extensibility/errors.md
  core-ui/src/components/Extensibility/helpers.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1684 Fix extensibility creation form in firefox
  core-ui/src/components/Extensibility/SchemaRulesInjector.js
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1673 EventList refactor
  core-ui/src/components/CustomResources/CustomResources.js
  core-ui/src/hooks/useMessageList.js
  core-ui/src/resources/CustomResourceDefinitions/CurrentCRDVersion.js
  core-ui/src/resources/Events/EventList.js
  core-ui/src/shared/components/GenericList/GenericList.scss
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  resources/web/deployment.yaml
  tests/tests/namespace/test-events.spec.js
Labels: kind/bug, size/L, lgtm

#1688 Extensibility UI highlight
  core-ui/src/components/BusolaExtensions/BusolaExtensionDetails.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1691 Adjust Extensibility documentation to current status
  docs/extensibility/README.md
  docs/extensibility/resources.md
Labels: documentation, size/S, lgtm, area/console

#1703 Move version to labels
  core-ui/src/components/BusolaExtensions/BusolaExtensionDetails.js
  core-ui/src/components/BusolaExtensions/BusolaExtensionEdit.js
  core-ui/src/components/BusolaExtensions/constants.js
  core-ui/src/components/BusolaExtensions/helpers.js
  core-ui/src/components/Extensibility/migration.js
  core/src/i18n/en.yaml
  core/src/luigi-config/customResources.js
  docs/extensibility/resources.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  examples/resources/configuration/certificates.yaml
  examples/resources/configuration/gitrepositories.yaml
  examples/resources/configuration/services.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1706 Add nodejs16 runtime
  core-ui/src/components/Functions/config.js
  core-ui/src/components/Functions/constants.js
  core-ui/src/components/Functions/helpers/runtime/runtime.js
  core-ui/src/components/Functions/helpers/runtime/test/runtime.test.js
  resources/web/deployment.yaml
Labels: kind/feature, size/S, lgtm

#1704 Remove support for translations-xx format
  core-ui/src/components/BusolaExtensions/BusolaExtensionDetails.js
  core-ui/src/components/BusolaExtensions/BusolaExtensionEdit.js
  core/src/luigi-config/customResources.js
  docs/extensibility/resources.md
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1695 Fix name validation
  core-ui/src/shared/components/K8sNameInput/K8sNameInput.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1716 Filter the EXT list with JSONata
  core-ui/src/components/Extensibility/ExtensibilityList.js
  docs/extensibility/resources.md
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1707 Extensibility: convert "relations" section to "dataSources"
  core-ui/src/components/BusolaExtensions/helpers.js
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/components/PendingWrapper.js
  core-ui/src/components/Extensibility/components/ResourceList.js
  core-ui/src/components/Extensibility/components/Widget.js
  core-ui/src/components/Extensibility/components/tests/Table.test.js
  core-ui/src/components/Extensibility/components/tests/Widget.test.js
  core-ui/src/components/Extensibility/contexts/DataSources.js
  core/src/i18n/en.yaml
  docs/extensibility/display-widgets.md
  docs/extensibility/resources.md
  examples/pizzas/configuration/pizzas-configmap.yaml
  examples/resources/configuration/services.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1705 EXT: Convert "resource" section to "general"
  core-ui/src/components/App/ExtensibilityRoutes.js
  core-ui/src/components/BusolaExtensions/BusolaExtensionCreate.js
  core-ui/src/components/BusolaExtensions/helpers.js
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/helpers.js
  core-ui/src/components/Extensibility/tests/useGetCRDByPath.test.js
  core-ui/src/components/Extensibility/useGetCRbyPath.js
  core-ui/src/hooks/useGetSchema.js
  core/src/i18n/en.yaml
  core/src/luigi-config/customResources.js
  core/src/luigi-config/navigation/customPaths.js
  docs/extensibility/resources.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  examples/resources/configuration/certificates.yaml
  examples/resources/configuration/gitrepositories.yaml
  examples/resources/configuration/services.yaml
  resources/web/deployment.yaml
Labels: kind/feature, size/L, lgtm

#1683 added simple widget for inline components
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/components/Columns.js
  core-ui/src/components/Extensibility/components/InlineDisplay.scss
  core-ui/src/components/Extensibility/components/Panel.js
  docs/extensibility/display-widgets.md
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1719 Handle "required" prop
  core-ui/src/components/Extensibility/components-form/KeyValuePairRenderer.js
  core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
  core-ui/src/components/Extensibility/components-form/NameRenderer.js
  core-ui/src/components/Extensibility/components-form/NumberRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRefRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
  core-ui/src/components/Extensibility/components-form/SimpleList.js
  core-ui/src/components/Extensibility/components-form/StringRenderer.js
  core-ui/src/resources/Functions/FunctionCreate.js
  core-ui/src/shared/ResourceForm/components/CollapsibleSection.js
  core-ui/src/shared/ResourceForm/components/CollapsibleSection.scss
  core-ui/src/shared/ResourceForm/fields/KeyValueField.js
  core-ui/src/shared/ResourceForm/fields/RuntimeResources.js
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
  core/src/i18n/en.yaml
  docs/extensibility/assets/form-widgets/ResourceRefs.png
  examples/pizzas/configuration/pizza-orders-crd.yaml
  examples/pizzas/configuration/pizzas-crd.yaml
  resources/web/deployment.yaml
  tests/support/views/functions-view.js
  tests/tests/cluster/test-applications.spec.js
  tests/tests/namespace/test-deployments.spec.js
  tests/tests/namespace/test-dns-providers.spec.js
  tests/tests/namespace/test-git-repositories.spec.js
  tests/tests/namespace/test-jobs.spec.js
  tests/tests/namespace/test-service-accounts.spec.js
Labels: size/L, lgtm

#1723 Hide the protected resources toggle if the feature is disabled
  core-ui/src/components/Preferences/ProtectedSettings.js
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1721 Fix titles and messages in the extensibility views
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/helpers.js
  core-ui/src/shared/components/ResourceDetails/ResourceDetails.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core-ui/src/shared/hooks/useDeleteResource.js
  examples/pizzas/configuration/pizzas-configmap.yaml
  resources/web/deployment.yaml
  tests/fixtures/examples
Labels: size/M, lgtm

#1720 move resource to separated object in schema form
  core-ui/src/components/BusolaExtensions/BusolaExtensionList.js
  core-ui/src/components/Extensibility/components-form/ResourceRefRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
  docs/extensibility/form-widgets.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1739 fix pizzas configmap and editing extensibility
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  examples/pizzas/configuration/pizzas-configmap.yaml
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1740 fix for no refreshing monaco for presets
  core-ui/src/shared/ResourceForm/components/Presets.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1718 change natural lg to camelCase
  core/src/i18n/en.yaml
  docs/extensibility/README.md
  docs/extensibility/display-widgets.md
  docs/extensibility/form-widgets.md
  docs/extensibility/resources.md
  docs/features.md
  resources/web/deployment.yaml
  tests/support/views/api-rules-view.js
  tests/tests/cluster/test-cluster-role-bindings.spec.js
  tests/tests/namespace/test-api-rules.spec.js
  tests/tests/namespace/test-config-maps.spec.js
  tests/tests/namespace/test-cron-jobs.spec.js
  tests/tests/namespace/test-dns-entries.spec.js
  tests/tests/namespace/test-dns-providers.spec.js
  tests/tests/namespace/test-git-repositories.spec.js
  tests/tests/namespace/test-protected-resources.spec.js
  tests/tests/namespace/test-reduced-permissions.spec.js
  tests/tests/namespace/test-replica-sets.spec.js
  tests/tests/namespace/test-service-accounts.spec.js
  tests/tests/namespace/test-settings.spec.js
Labels: size/L, lgtm, area/console, area/documentation

#1680 EXT Pizza tests
  .gitignore
  core-ui/src/components/Extensibility/components-form/NumberRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
  core-ui/src/components/Extensibility/components-form/StringRenderer.js
  core-ui/src/components/Extensibility/components-form/SwitchRenderer.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/support/commands.js
  tests/support/createNamespace.js
  tests/support/iframe-commands.js
  tests/support/index.js
  tests/support/loadFile.js
  tests/support/mockConfig.js
  tests/tests/cluster/test-pizzas.spec.js
Labels: size/L, lgtm

#1745 Fix git Function edit
  core-ui/src/resources/Functions/FunctionCreate.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1737 Fix schema inferring
  core-ui/src/components/App/resourceSchemas/resourceSchemas.worker.js
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core-ui/src/components/Functions/FunctionDetails/Tabs/Code/CodeAndDependencies/CodeAndDependencies.js
  core-ui/src/components/Functions/FunctionDetails/Tabs/Code/CodeAndDependencies/Editor.js
  core-ui/src/hooks/useGetSchema.js
  core-ui/src/resources/Namespaces/NamespaceCreate.js
  core-ui/src/resources/Namespaces/templates.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/fields/Editor.js
  core-ui/src/shared/components/MonacoEditorESM/Editor.js
  core-ui/src/shared/components/MonacoEditorESM/autocompletion/useAutocompleteWorker.js
  core-ui/src/shared/components/SchemaViewer/SchemaViewer.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1748 Namespaces ResourceRef
  core-ui/src/components/Extensibility/components/ResourceRefs.js
  core-ui/src/shared/helpers/universalLinks.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1752 Many monacos
  core-ui/src/components/App/resourceSchemas/resourceSchemas.worker.js
  core-ui/src/hooks/useGetSchema.js
  core-ui/src/shared/components/MonacoEditorESM/Editor.js
  core-ui/src/shared/components/MonacoEditorESM/Editor.scss
  core-ui/src/shared/components/MonacoEditorESM/autocompletion/getSchemaLink.js
  core-ui/src/shared/components/MonacoEditorESM/autocompletion/useAutocompleteWorker.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useCreateEditor.js
  resources/web/deployment.yaml
  tests/tests/namespace/run-after.spec.js
Labels: size/L, lgtm

#1742 fix for run-after namespace test
  tests/tests/namespace/run-after.spec.js
Labels: size/XS, lgtm, area/tests

#1747 apply camelCase to remaining elements
  README.md
  core-ui/src/components/Extensibility/errors.md
  core/src/i18n/en.yaml
  docs/extensibility/README.md
  docs/extensibility/display-widgets.md
  examples/pizzas/README.md
  examples/resources/README.md
  resources/web/deployment.yaml
  tests/tests/namespace/test-dns-entries.spec.js
Labels: size/M, lgtm

#1727 Jsonata sources
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/SchemaRulesInjector.js
  core-ui/src/components/Extensibility/components-form/CollapsibleRenderer.js
  core-ui/src/components/Extensibility/components-form/GenericList.js
  core-ui/src/components/Extensibility/components-form/KeyValuePairRenderer.js
  core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
  core-ui/src/components/Extensibility/components-form/NumberRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRefRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
  core-ui/src/components/Extensibility/components-form/SimpleList.js
  core-ui/src/components/Extensibility/components-form/StringRenderer.js
  core-ui/src/components/Extensibility/components-form/SwitchRenderer.js
  core-ui/src/components/Extensibility/components/CodeViewer.js
  core-ui/src/components/Extensibility/components/ResourceList.js
  core-ui/src/components/Extensibility/components/Table.js
  core-ui/src/components/Extensibility/components/Widget.js
  core-ui/src/components/Extensibility/components/tests/Widget.test.js
  core-ui/src/components/Extensibility/contexts/DataSources.js
  core-ui/src/components/Extensibility/helpers.js
  core-ui/src/components/Extensibility/useJsonata.js
  core-ui/src/index.js
  core-ui/src/resources/Namespaces/YamlUpload/helpers.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core/src/assets/customResources/schema-details.json
  core/src/luigi-config/customResources.js
  core/src/luigi-config/navigation/navigation-data-init.js
  docs/extensibility/display-widgets.md
  docs/extensibility/resources.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  examples/resources/configuration/gitrepositories.yaml
  examples/resources/configuration/services.yaml
  resources/web/deployment.yaml
  tests/tests/cluster/test-pizzas.spec.js
Labels: size/XL, lgtm

#1760 Fixed Certificates and the ResourceLink widget
  core-ui/src/components/Extensibility/components/ResourceLink.js
  examples/resources/configuration/certificates.yaml
  examples/resources/configuration/gitrepositories.yaml
  examples/resources/configuration/services.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1746 EXT: Resource Graph
  core-ui/src/components/Extensibility/contexts/DataSources.js
  core-ui/src/resources/APIRules/index.js
  core-ui/src/resources/ClusterRoleBindings/index.js
  core-ui/src/resources/ClusterRoles/index.js
  core-ui/src/resources/ConfigMaps/index.js
  core-ui/src/resources/CronJobs/index.js
  core-ui/src/resources/DaemonSets/index.js
  core-ui/src/resources/Deployments/DeploymentDetails.js
  core-ui/src/resources/Deployments/index.js
  core-ui/src/resources/Functions/index.js
  core-ui/src/resources/Gateways/index.js
  core-ui/src/resources/HorizontalPodAutoscalers/index.js
  core-ui/src/resources/Ingresses/index.js
  core-ui/src/resources/Jobs/index.js
  core-ui/src/resources/NetworkPolicies/index.js
  core-ui/src/resources/OAuth2Clients/index.js
  core-ui/src/resources/PersistentVolumeClaims/index.js
  core-ui/src/resources/PersistentVolumes/index.js
  core-ui/src/resources/Pods/index.js
  core-ui/src/resources/ReplicaSets/index.js
  core-ui/src/resources/RoleBindings/index.js
  core-ui/src/resources/Roles/index.js
  core-ui/src/resources/Secrets/index.js
  core-ui/src/resources/ServiceAccounts/index.js
  core-ui/src/resources/Services/index.js
  core-ui/src/resources/StatefulSets/index.js
  core-ui/src/resources/StorageClasses/index.js
  core-ui/src/resources/Subscriptions/index.js
  core-ui/src/resources/VirtualServices/index.js
  core-ui/src/resources/helpers.js
  core-ui/src/shared/components/ResourceGraph/buildGraph/buildStructuralGraph.js
  core-ui/src/shared/components/ResourceGraph/buildGraph/helpers.js
  core-ui/src/shared/components/ResourceGraph/getResourceGraphConfig.js
  core-ui/src/shared/components/ResourceGraph/useRelatedResources.js
  docs/extensibility/assets/ResourceGraph.png
  docs/extensibility/resources.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  examples/resources/configuration/services.yaml
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#1776 fix generated extension code
  core-ui/src/components/BusolaExtensions/helpers.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1783 allow placeholders in extensibility
  core-ui/src/components/Extensibility/components-form/GenericList.js
  core-ui/src/components/Extensibility/components-form/NumberRenderer.js
  core-ui/src/components/Extensibility/components-form/SimpleList.js
  core-ui/src/components/Extensibility/components-form/StringRenderer.js
  docs/extensibility/form-widgets.md
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1768 update docs and examples to use the "children" parameter in forms
  core-ui/src/components/Extensibility/SchemaRulesInjector.js
  docs/extensibility/form-widgets.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1791 Fix ResourceLink widget and Table's docs
  core-ui/src/components/Extensibility/components/ResourceLink.js
  core-ui/src/components/Extensibility/contexts/DataSources.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  docs/extensibility/display-widgets.md
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1799 fix for empty selector
  core-ui/src/resources/Gateways/GatewayDetails.js
  core-ui/src/resources/Gateways/GatewayList.js
  core-ui/src/resources/Gateways/GatewaySelector.js
  core-ui/src/shared/components/Selector/Selector.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1802 Adjust codeowners
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/XS, lgtm

#1756 Move Destination Rules to Ext
  core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
  core/src/assets/customResources/customResources.json
  core/src/luigi-config/navigation/mergeInExtensibilityNav.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/static-navigation-model.js
  docs/extensibility/display-widgets.md
  docs/extensibility/resources.md
  resources/web/deployment.yaml
  tests/tests/namespace/test-destination-rules.spec.js
Labels: size/L, lgtm

#1796 Fix the bug of not showing item's data
  core-ui/src/components/Extensibility/components-form/KeyValuePairRenderer.js
  core-ui/src/components/Extensibility/helpers.js
  core-ui/src/components/Extensibility/useJsonata.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1757 Ext gateways
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/SchemaRulesInjector.js
  core-ui/src/components/Extensibility/components-form/KeyValuePairRenderer.js
  core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
  core-ui/src/components/Extensibility/components-form/NameRenderer.js
  core-ui/src/components/Extensibility/components-form/NumberRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRefRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
  core-ui/src/components/Extensibility/components-form/SimpleList.js
  core-ui/src/components/Extensibility/components-form/StringRenderer.js
  core-ui/src/components/Extensibility/components-form/SwitchRenderer.js
  core-ui/src/components/Extensibility/components/Badge.js
  core-ui/src/components/Extensibility/components/JoinedArray.js
  core-ui/src/components/Extensibility/components/Panel.js
  core-ui/src/components/Extensibility/components/ResourceLink.js
  core-ui/src/components/Extensibility/components/Widget.js
  core-ui/src/components/Extensibility/contexts/DataSources.js
  core-ui/src/components/Extensibility/helpers.js
  core-ui/src/components/Extensibility/jsonataWrapper.js
  core-ui/src/components/Extensibility/useJsonata.js
  core-ui/src/shared/components/K8sResourceSelect.js
  core-ui/src/shared/components/ResourceGraph/getResourceGraphConfig.js
  core-ui/src/styles/index.scss
  docs/extensibility/assets/form-widgets/Dropdown.png
  docs/extensibility/assets/form-widgets/Name.png
  docs/extensibility/display-widgets.md
  docs/extensibility/form-widgets.md
  docs/extensibility/jsonata.md
  docs/extensibility/resources.md
  examples/resources/configuration/istio/gateways.yaml
  resources/web/deployment.yaml
  tests/tests/extensibility/ext-test-pizzas.spec.js
Labels: size/XL, lgtm

#1803 Sentry fixes
  core-ui/src/command-pallette/CommandPaletteProvider.js
  core-ui/src/components/BusolaExtensions/BusolaExtensionCreate.js
  core-ui/src/components/NoPermissions/NoPermissions.js
  core-ui/src/resources/Roles/RuleInput.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1804 Handle gateways on ResourceGraph
  core-ui/src/shared/components/ResourceGraph/buildGraph/helpers.js
  core-ui/src/shared/components/ResourceGraph/getResourceGraphConfig.js
  core-ui/src/styles/index.scss
  examples/resources/configuration/istio/gateways.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1805 Fix extensibility on reduced permissions
  core/src/luigi-config/navigation/permissions.js
  core/src/luigi-config/navigation/test/permissions.test.js
  resources/web/deployment.yaml
Labels: size/S, lgtm
