Repository kyma-project/busola, pull requests merged in 2022-05, with the labels that each got.

#1295 Improve default presets
  core-ui/src/resources/ClusterRoles/helpers.js
  core-ui/src/resources/CronJobs/CronJobCreate.js
  core-ui/src/resources/GitRepositories/helpers.js
  core-ui/src/resources/Jobs/JobCreate.js
  core-ui/src/resources/Jobs/templates.js
  core-ui/src/resources/Roles/helpers.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1294 Fix function's configuration bug
  core-ui/src/components/Functions/FunctionDetails/Tabs/ResourceManagement/FunctionResources.js
  core-ui/src/components/Functions/FunctionDetails/Tabs/ResourceManagement/ResourceManagement.js
  core-ui/src/components/Functions/FunctionDetails/Tabs/ResourceManagement/shared.js
  core-ui/src/components/Functions/helpers/resources/cpuHelpers.js
  core-ui/src/components/Functions/helpers/resources/memoryHelpers.js
  resources/web/deployment.yaml
Labels: kind/bug, size/L, lgtm

#1297 External nodes as a feature
  core/src/luigi-config/cluster-management/cluster-management.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/navigation-helpers.js
  resources/web/deployment.yaml
  tests/tests/cluster/test-cluster-configuration.spec.js
Labels: size/M, lgtm

#1291 Editor Actions for Monaco ESM
  core-ui/src/components/HelmReleases/tests/HelmReleaseData.test.js
  core-ui/src/service-catalog-ui/Wrapper.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/components/MonacoEditorESM/Editor.js
  core-ui/src/shared/components/MonacoEditorESM/Editor.scss
  core-ui/src/shared/components/MonacoEditorESM/monaco-autocomplete.worker.js
  core-ui/src/shared/components/ReadonlyEditorPanel.js
  core-ui/src/shared/contexts/YamlEditorContext/EditorActions.js
  core-ui/src/shared/contexts/YamlEditorContext/YamlContent.js
  core/src/i18n/en.yaml
  grep
  resources/web/deployment.yaml
  tests/tests/namespace/test-network-policies.spec.js
  tests/tests/namespace/test-virtual-services.spec.js
Labels: size/L, lgtm

#1298 Fix deleting and navigating to the Role Bindings
  core-ui/src/shared/ResourceForm/useCreateResource.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core-ui/src/shared/hooks/index.js
  core-ui/src/shared/hooks/navigate.js
  resources/web/deployment.yaml
  tests/tests/cluster/test-cluster-role-bindings.spec.js
Labels: kind/bug, size/M, lgtm

#1302 Add docs for EXTERNAL_FEATURES
  README.md
  docs/features.md
Labels: size/M, lgtm

#1301 Fix problems with create form UI
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core-ui/src/resources/Deployments/DeploymentCreate.js
  core-ui/src/resources/Deployments/DeploymentCreate.scss
  core-ui/src/shared/ResourceForm/fields/Editor.scss
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1308 Fix breaking views when no conifg for protected resources is provided
  core-ui/src/shared/hooks/useProtectedResources.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1307 Fix automatically adding null to yaml editor
  core-ui/src/components/Clusters/components/AddClusterWizard.js
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core-ui/src/components/Clusters/shared.js
  core-ui/src/resources/Namespaces/YamlUpload/YamlUpload.js
  core-ui/src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1306 Replace monaco react
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/public/vs
  core-ui/src/components/Clusters/components/AddClusterWizard.js
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core-ui/src/components/Clusters/views/EditCluster/EditCluster.js
  core-ui/src/components/Functions/FunctionDetails/Tabs/Code/CodeAndDependencies/CodeAndDependencies.js
  core-ui/src/components/Functions/FunctionDetails/Tabs/Code/CodeAndDependencies/Editor.js
  core-ui/src/resources/Deployments/DeploymentCreate.scss
  core-ui/src/resources/Namespaces/NamespaceCreate.js
  core-ui/src/resources/Namespaces/YamlUpload/YamlUpload.js
  core-ui/src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
  core-ui/src/resources/ServiceBindings/ServiceBindingCreate.js
  core-ui/src/resources/ServiceInstances/ServiceInstanceCreate.js
  core-ui/src/service-catalog-ui/components/ServiceClassDetails/CreateInstanceForm/CreateInstanceForm.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/fields/Editor.js
  core-ui/src/shared/ResourceForm/fields/Editor.scss
  core-ui/src/shared/ResourceForm/fields/index.js
  core-ui/src/shared/components/MonacoEditor/MonacoEditor.js
  core-ui/src/shared/components/MonacoEditorESM/Editor.js
  core-ui/src/shared/components/MonacoEditorESM/Editor.scss
  core-ui/src/shared/components/MonacoEditorESM/useAutocompleteWorker.js
  core-ui/src/shared/components/ReadonlyEditorPanel.js
  core-ui/src/shared/components/SchemaViewer/SchemaViewer.js
  core-ui/src/shared/components/SideDrawer/SideDrawer.js
  core-ui/src/shared/components/SideDrawer/test/SideDrawer.test.js
  core-ui/src/shared/contexts/YamlEditorContext/YamlContent.js
  core-ui/src/shared/contexts/YamlEditorContext/YamlEditorContext.js
  core-ui/src/shared/utils/setupMonaco.js
  core/webpack.config.js
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#1310 Cluster interaction toggles
  core/package-lock.json
  core/package.json
  core/src/luigi-config/communication.js
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  tests/tests/namespace/test-namespace-overview.spec.js
  tests/tests/namespace/test-protected-resources.spec.js
Labels: size/M, lgtm

#1317 Fix limits creation
  core-ui/src/resources/LimitRanges/templates.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1322 Fix PR version on dev
  nginx/nginx.conf
Labels: size/XS, lgtm

#1327 bump-version
  core-ui/src/shared/components/MonacoEditorESM/useAutocompleteWorker.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1305 Fix usePrometheus bug that sends unnecessary requests
  core-ui/src/shared/components/StatsGraph/StatsPanel.js
  core-ui/src/shared/hooks/usePrometheus.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1333 Disable create for related resources
  core-ui/src/resources/PersistentVolumeClaims/PersistentVolumeClaimDetails.js
  core-ui/src/shared/components/RelatedPods.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1339 Handle CMs & Secrets connected to Pod via volume
  core-ui/src/resources/Pods/index.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1337 Remove Kyma version auto-detection when Kyma 2.1.1. is live on all clusters
  core-ui/src/shared/hooks/usePrometheus.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1316 Hidden namespaces, disabled nodes as features
  README.md
  core-ui/src/command-pallette/CommandPalletteUI/useSearchResults.js
  core-ui/src/resources/Applications/CreateBindingModal/CreateBindingModal.js
  core-ui/src/resources/Namespaces/NamespaceList.js
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
  core-ui/src/shared/helpers/getHiddenNamespaces.js
  core/src/assets/defaultConfig.json
  core/src/luigi-config/cluster-management/cluster-management.js
  core/src/luigi-config/constants.js
  core/src/luigi-config/kubeconfig-id/index.js
  core/src/luigi-config/navigation/navigation-data-init.js
  docs/features.md
  resources/web/deployment.yaml
  tests/tests/cluster/test-cluster-configuration.spec.js
Labels: size/L, lgtm

#1342 Fix service instances and service bindings details layout
  core-ui/src/shared/components/DefinitionList/DefinitionList.js
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1346 Added case for wrong accesstrategy type
  core-ui/src/components/ApiRules/AccessStrategies/AccessStrategies.js
  core-ui/src/resources/APIRules/helpers.js
  core-ui/src/shared/components/StatusBadge/StatusBadge.scss
  core-ui/src/styles/index.scss
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1258 Service discovery
  core-ui/src/shared/components/StatsGraph/StatsPanel.js
  core-ui/src/shared/hooks/useFeature.js
  core-ui/src/shared/hooks/usePrometheus.js
  core/src/assets/defaultConfig.json
  core/src/luigi-config/auth/auth.js
  core/src/luigi-config/auth/sso.js
  core/src/luigi-config/busola-cluster-params.js
  core/src/luigi-config/cache/fetch-cache.js
  core/src/luigi-config/cache/storage.js
  core/src/luigi-config/cluster-management/cluster-management.js
  core/src/luigi-config/cluster-management/clusters-storage.js
  core/src/luigi-config/communication.js
  core/src/luigi-config/constants.js
  core/src/luigi-config/feature-checks.js
  core/src/luigi-config/feature-discovery.js
  core/src/luigi-config/features.js
  core/src/luigi-config/kubeconfig-id/loadKubeconfigById.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/navigation-helpers.js
  core/src/luigi-config/navigation/queries.js
  core/src/luigi-config/navigation/static-navigation-model.js
  core/src/luigi-config/sentry/index.js
  core/src/luigi-config/settings/pagination.js
  core/src/luigi-config/utils/configChanged.js
  core/src/luigi-config/utils/extractGroupVersions.js
  core/src/luigi-config/utils/target-cluster-config.js
  core/webpack.config.js
  docs/features.md
  resources/web/configmap.yaml
  resources/web/deployment.yaml
  tests/tests/cluster/test-command-palette.spec.js
  tests/tests/namespace/test-namespace-overview.spec.js
  tests/tests/namespace/test-protected-resources.spec.js
  tests/tests/namespace/test-reduced-permissions.spec.js
Labels: size/XXL, lgtm

#1355 Remove kube-public from hidden namespaces
  core/src/assets/defaultConfig.json
  docs/features.md
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1360 Fix nav nodes flow
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1351 Removal of old Application Connector flow from Busola
  core-ui/src/resources/Applications/ApplicationDetails.js
  core-ui/src/resources/Applications/ApplicationList.js
  core/src/luigi-config/constants.js
  core/src/luigi-config/feature-checks.js
  resources/web/deployment.yaml
  tests/tests/cluster/test-applications.spec.js
  tests/tests/cluster/test-command-palette.spec.js
Labels: size/L, lgtm

#1357 Fix sentry
  core-ui/src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/crdHandler.js
  core-ui/src/commons/helpers.js
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Clusters/views/EditCluster/EditCluster.js
  core-ui/src/resources/ClusterRoles/helpers.js
  core-ui/src/resources/Deployments/DeploymentDetails.js
  core-ui/src/resources/Ingresses/DefaultBackendPanel.js
  core-ui/src/resources/Ingresses/Rules.js
  core-ui/src/resources/Jobs/JobConditions.js
  core-ui/src/resources/Namespaces/YamlUpload/YamlFileUploader.js
  core-ui/src/resources/Pods/ContainersLogs.js
  core-ui/src/resources/RoleBindings/GenericRoleBindingList.js
  core-ui/src/resources/Roles/RuleInput.js
  core-ui/src/resources/Roles/useResourcesForApiGroups.js
  core-ui/src/resources/ServiceBrokers/ServiceBrokerList.js
  core-ui/src/resources/Services/ServiceDetails.js
  core-ui/src/resources/Subscriptions/SubscriptionList.js
  core-ui/src/resources/VirtualServices/HttpRoutes.js
  core-ui/src/service-catalog-ui/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.js
  core-ui/src/service-catalog-ui/helpers/index.js
  core-ui/src/shared/ResourceForm/fields/KeyValueField.js
  core-ui/src/shared/components/DefinitionList/DefinitionList.js
  core-ui/src/shared/components/FileInput/FileInput.js
  core-ui/src/shared/components/GenericList/helpers.js
  core/src/i18n/en.yaml
  core/src/luigi-config/cluster-management/cluster-management.js
  core/src/luigi-config/communication.js
  core/src/luigi-config/feature-discovery.js
  core/src/luigi-config/navigation/navigation-data-init.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1368 Fix problems with create form UI
  core-ui/src/shared/components/MonacoEditorESM/Editor.scss
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1366 Removed service yaml in deployment
  core-ui/src/resources/Deployments/DeploymentCreate.js
  core-ui/src/resources/Deployments/DeploymentCreate.scss
  core-ui/src/resources/Deployments/templates.js
  core-ui/src/resources/Namespaces/NamespaceCreate.js
  core-ui/src/resources/ReplicaSets/ReplicaSetCreate.scss
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/cypress.json
  tests/fixtures/test-services.yaml
  tests/tests/namespace/test-deployments.spec.js
  tests/tests/namespace/test-services.spec.js
Labels: size/L, lgtm

#1362 Clean json packages
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core/package-lock.json
  core/package.json
  core/src/luigi-config/cluster-management/clusters-storage.js
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  tests/tests/cluster/test-invalid-kubeconfig.spec.js
  tests/tests/namespace/test-reduced-permissions.spec.js
Labels: size/XXL, lgtm

#1369 Remove Simple mode when editing a resource
  core-ui/src/components/Functions/FunctionDetails/Tabs/Code/FunctionVariables/VariableInputs/VariableInputs.scss
  core-ui/src/components/Functions/components/FormInput/FormInput.scss
  core-ui/src/components/Preferences/Preferences.scss
  core-ui/src/resources/AddonsConfigurations/GenericAddonsConfigurationCreate.scss
  core-ui/src/resources/Applications/CreateBindingModal/CreateBindingModal.scss
  core-ui/src/resources/Pods/ContainersLogs.scss
  core-ui/src/shared/ResourceForm/components/ModeSelector.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.scss
  core-ui/src/shared/components/Dropdown/Dropdown.scss
  core-ui/src/shared/components/K8sResourceSelect.js
  core-ui/src/shared/components/K8sResourceSelect.scss
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.scss
  core-ui/src/shared/components/Select/Select.js
  core-ui/src/shared/components/Select/Select.scss
  core-ui/src/styles/index.scss
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/cluster/test-applications.spec.js
  tests/tests/cluster/test-cluster-role-bindings.spec.js
  tests/tests/namespace/run-before.spec.js
  tests/tests/namespace/test-api-rules.spec.js
  tests/tests/namespace/test-certificates.spec.js
  tests/tests/namespace/test-cron-jobs.spec.js
  tests/tests/namespace/test-custom-resources.spec.js
  tests/tests/namespace/test-deployments.spec.js
  tests/tests/namespace/test-dns-entries.spec.js
  tests/tests/namespace/test-dns-providers.spec.js
  tests/tests/namespace/test-gateways.spec.js
  tests/tests/namespace/test-git-repositories.spec.js
  tests/tests/namespace/test-in-cluster-eventing.spec.js
  tests/tests/namespace/test-issuers.spec.js
  tests/tests/namespace/test-jobs.spec.js
  tests/tests/namespace/test-oauth2.spec.js
  tests/tests/namespace/test-replica-sets.spec.js
  tests/tests/namespace/test-service-accounts.spec.js
Labels: kind/feature, size/L, lgtm

#1350 Show cpu and memory usage in a table
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/components/Nodes/nodeQueries.js
  core-ui/src/shared/components/ProgressBar/ProgressBar.js
  core-ui/src/shared/components/ProgressBar/ProgressBar.scss
  core-ui/src/shared/components/StatsGraph/StatsPanel.js
  core-ui/src/shared/hooks/usePrometheus.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/cluster/test-cluster-overview.spec.js
Labels: size/XL, lgtm

#1354 Introduce Prometheus Metrics regarding CPU and Memory Limits at Cluster Level
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.scss
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/CommitmentGraph.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/GraphLegend/GraphLegend.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/GraphLegend/GraphLegend.scss
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/ResourceCommitment.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/ResourceCommitment.scss
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/queries.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/useMetricsQuery.js
  core-ui/src/hooks/useCssVariables.js
  core-ui/src/shared/components/StatsGraph/StatsPanel.js
  core-ui/src/shared/components/StatsGraph/StatsPanel.scss
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/XL, lgtm
