Repository kyma-project/busola, pull requests merged in 2022-10, with the labels that each got.

#1901 Fix upload YAML
  core-ui/src/resources/Namespaces/YamlUpload/YamlResourcesList.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1889 Eventslist
  core-ui/src/components/Clusters/views/EditCluster/EditCluster.js
  core-ui/src/components/Extensibility/components/EventList.js
  core-ui/src/components/Extensibility/components/hooks/useJsonataEvaluate.js
  core-ui/src/components/Extensibility/components/index.js
  core-ui/src/components/Extensibility/helpers/jsonataWrapper.js
  core-ui/src/components/Extensibility/hooks/useJsonata.js
  core-ui/src/resources/Events/EventList.js
  docs/extensibility/assets/display-widgets/EventList.png
  docs/extensibility/assets/display-widgets/EventListHiddenField.png
  docs/extensibility/display-section.md
  docs/extensibility/jsonata.md
  examples/resources/serverless/functions.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1908 Sentry20220904
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core/src/luigi-config/utils/configChanged.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1869 A solution on how to embed Kyma extensions in Busola
  .gitignore
  Dockerfile.extensions.local
  Dockerfile.local
  Makefile
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/migration.js
  core/src/assets/extensions/extensions.yaml
  core/src/luigi-config/customResources.js
  docs/extensibility/README.md
  examples/resources/istio/authorization-policies.yaml
  examples/resources/istio/service-entries.yaml
  examples/resources/istio/sidecars.yaml
  examples/resources/istio/virtual-services.yaml
  extensions/extensions.json
  gulpfile.js
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/extensions-patch/builtin-resource-extensions.configmap.yaml
  resources/extensions-patch/kustomization.yaml
  resources/extensions-patch/web-deployment.patch.yaml
  resources/web/deployment.yaml
Labels: size/L, hacktoberfest-accepted

#1906 Remove missing translations warnings for extensibility
  core-ui/src/components/Extensibility/components/tests/Table.test.js
  core-ui/src/components/Extensibility/helpers/index.js
  core-ui/src/resources/helpers.js
  core-ui/src/setupTests.js
  core-ui/src/shared/components/GenericList/GenericList.js
  core-ui/src/shared/components/GenericList/SortModalPanel.js
  core-ui/src/shared/components/StatusBadge/StatusBadge.js
  core-ui/src/shared/contexts/YamlEditorContext/EditorActions.js
  resources/web/deployment.yaml
Labels: size/M, lgtm, hacktoberfest-accepted, technical-task

#1893 Ext init phase
  core-ui/src/commons/helpers.js
  core-ui/src/components/App/resourceSchemas/useResourceSchemas.js
  core/__mocks__/styleMock.js
  core/package.json
  core/src/assets/customResources/customResources.json
  core/src/luigi-config/cluster-management/cluster-management.js
  core/src/luigi-config/loading-state/index.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/clusterOpenApi.js
  core/src/luigi-config/navigation/excludeNavigationNode.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/permissions.js
  core/src/luigi-config/navigation/rbac-rules-matcher.js
  core/src/luigi-config/navigation/static-navigation-model.js
  core/src/luigi-config/navigation/test/permissions.test.js
  core/src/luigi-config/navigation/test/rbac-rules-matcher.test.js
  core/src/template.html
  resources/web/deployment.yaml
  tests/tests/cluster/test-cluster-overview.spec.js
  tests/tests/namespace/test-resource-upload.spec.js
Labels: size/XXL, lgtm

#1917 Remove cy.wait() from tests
  core-ui/src/components/App/App.js
  resources/web/deployment.yaml
  tests/tests/cluster/test-cluster-overview.spec.js
  tests/tests/namespace/test-resource-upload.spec.js
Labels: size/XS, lgtm

#1905 Introduce Reset form button
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
  core-ui/src/components/Extensibility/helpers/index.js
  core-ui/src/resources/Certificates/CertificateCreate.js
  core-ui/src/resources/ClusterRoles/helpers.js
  core-ui/src/resources/ConfigMaps/helpers.js
  core-ui/src/resources/CronJobs/CronJobCreate.js
  core-ui/src/resources/Deployments/templates.js
  core-ui/src/resources/Gateways/templates.js
  core-ui/src/resources/Issuers/templates.js
  core-ui/src/resources/Jobs/JobCreate.js
  core-ui/src/resources/Jobs/templates.js
  core-ui/src/resources/Namespaces/NamespaceCreate.js
  core-ui/src/resources/Roles/helpers.js
  core-ui/src/resources/Secrets/helpers.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/inputs/Checkboxes.js
  core-ui/src/shared/ResourceForm/inputs/ComboboxInput.js
  core-ui/src/shared/ResourceForm/inputs/Number.js
  core-ui/src/shared/components/Deployment/ContainersViews.js
  core-ui/src/shared/components/ModalWithForm/ModalWithForm.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm, hacktoberfest-accepted

#1912 Migrate Subscriptions to Extensibility
  core-ui/src/components/Extensibility/components-form/GenericList.js
  core-ui/src/components/Extensibility/components/ControlledBy.js
  core-ui/src/components/Extensibility/components/ResourceLink.js
  core-ui/src/components/Extensibility/helpers/jsonataWrapper.js
  docs/extensibility/form-section.md
  docs/extensibility/jsonata.md
  examples/resources/configuration/subscriptions.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm, hacktoberfest-accepted

#1930 Simplelist examples
  docs/extensibility/form-section.md
  examples/pizzas/configuration/pizzas-configmap.yaml
  examples/resources/istio/authorization-policies.yaml
  examples/resources/istio/gateways.yaml
  examples/resources/istio/service-entries.yaml
  examples/resources/istio/sidecars.yaml
  examples/resources/istio/virtual-services.yaml
Labels: size/L, lgtm

#1928 Luigi create store + TS
  core-ui/config-overrides.js
  core-ui/jsconfig.json
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/App/App.js
  core-ui/src/components/App/AppContext.js
  core-ui/src/components/App/resourceSchemas/useResourceSchemas.js
  core-ui/src/components/App/resourceSchemas/useResourceSchemas.ts
  core-ui/src/hooks/useGetSchema.js
  core-ui/src/index.js
  core-ui/src/state/openapiSchemasAtom.ts
  core-ui/tsconfig.json
  core/src/luigi-config/navigation/navigation-helpers.js
  core/src/luigi-config/navigation/rbac-rules-matcher.js
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#1936 change schema validation library
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/shared/hooks/useValidateResourceBySchema/useValidateResourceBySchema.js
  resources/web/deployment.yaml
Labels: size/M, lgtm, hacktoberfest-accepted

#1933 Creates a node generator to convert DR to yaml
  core/src/luigi-config/customResources/destinationRules/.gitignore
  core/src/luigi-config/customResources/destinationRules/details/connectionPool.mjs
  core/src/luigi-config/customResources/destinationRules/details/index.mjs
  core/src/luigi-config/customResources/destinationRules/details/loadBalancer.mjs
  core/src/luigi-config/customResources/destinationRules/details/outlierDetection.mjs
  core/src/luigi-config/customResources/destinationRules/details/portLevelSettings.mjs
  core/src/luigi-config/customResources/destinationRules/details/subsets.mjs
  core/src/luigi-config/customResources/destinationRules/details/tls.mjs
  core/src/luigi-config/customResources/destinationRules/details/trafficPolicy.mjs
  core/src/luigi-config/customResources/destinationRules/details/tunnel.mjs
  core/src/luigi-config/customResources/destinationRules/form/index.mjs
  core/src/luigi-config/customResources/destinationRules/form/subsets.mjs
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/connectionPool.mjs
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/loadBalancer.mjs
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/outlierDetection.mjs
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/portLevelSettings.mjs
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/tls.mjs
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/tunnel.mjs
  core/src/luigi-config/customResources/destinationRules/generator.mjs
  core/src/luigi-config/customResources/destinationRules/index.mjs
  core/src/luigi-config/customResources/destinationRules/translations.mjs
  core/src/luigi-config/customResources/index.js
  examples/resources/istio/destination-rules.yaml
  resources/web/deployment.yaml
Labels: size/XXL, lgtm

#1910 Extensibility: ResourcesList widget uses the List view from other Ext. resources if exist
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/components/ResourceList.js
  core-ui/src/components/Extensibility/useGetCRbyPath.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/tests/useCreateResource.test.js
  core-ui/src/shared/ResourceForm/useCreateResource.js
  core-ui/src/shared/components/ControlledBy/ControlledBy.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core-ui/src/shared/hooks/navigate.js
  core/src/luigi-config/cluster-management/cluster-management.js
  docs/extensibility/display-section.md
  examples/pizzas/configuration/pizzas-configmap.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm, hacktoberfest-accepted

#1932 Change configs from json to yaml
  Dockerfile.local
  Makefile
  backend/config/config.json
  backend/config/config.yaml
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/settings/defaultConfig.json
  backend/settings/defaultConfig.yaml
  core/src/assets/config/config.yaml
  core/src/assets/defaultConfig.json
  core/src/assets/defaultConfig.yaml
  core/src/assets/version.json
  core/src/assets/version.yaml
  core/src/luigi-config/busola-cluster-params.js
  core/src/luigi-config/nav-footer.js
  core/src/luigi-config/utils/target-cluster-config.js
  examples/resources/istio/sidecars.yaml
  nginx/nginx.conf
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  tests/tests/cluster/test-login-kubeconfigID.spec.js
  tests/tests/cluster/test-navigation-features.spec.js
Labels: size/L, lgtm, hacktoberfest-accepted

#1941 Fix fetching configs
  core/src/luigi-config/busola-cluster-params.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1942 Update docs with config - json to yaml changes
  README.md
Labels: size/XS, lgtm

#1913 Applications as extension
  core-ui/src/components/Extensibility/components/Badge.js
  core-ui/src/components/Extensibility/components/ExternalLink.js
  core-ui/src/components/Extensibility/components/JoinedArray.js
  core-ui/src/components/Extensibility/components/Table.js
  core-ui/src/components/Extensibility/components/Text.js
  core-ui/src/components/Extensibility/components/Widget.js
  core-ui/src/components/Extensibility/components/tests/Widget.copyable.test.js
  core-ui/src/shared/components/CopiableText/CopiableText.js
  docs/extensibility/display-section.md
  examples/resources/applicationconnector/applications.yaml
  nginx/nginx.conf
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1945 Sentry fix 17.10.22
  core-ui/src/components/ApiRules/components.js
  core/src/luigi-config/customResources.js
  core/src/luigi-config/navigation/clusterOpenApi.js
  core/src/luigi-config/navigation/queries.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1962 remove workaround for json to yaml
  backend/config-yaml/config.yaml
  backend/config/config.yaml
  backend/index.js
  core/src/assets/config/config.yaml
  core/src/luigi-config/busola-cluster-params.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  tests/tests/cluster/test-login-kubeconfigID.spec.js
Labels: size/M, lgtm

#1967 align docs to new yaml configs
  docs/features.md
Labels: size/L, lgtm

#1948 remove deprecated nodejs12 (and nodejs10)
  core-ui/src/components/Functions/config.js
  core-ui/src/components/Functions/constants.js
  core-ui/src/components/Functions/helpers/runtime/runtime.js
  core-ui/src/components/Functions/helpers/runtime/test/runtime.test.js
  examples/resources/serverless/functions.yaml
  resources/web/deployment.yaml
  tests/tests/namespace/run-prepare-functions.spec.js
Labels: size/M, lgtm

#1971 Add types for some packages
  core-ui/package-lock.json
  core-ui/package.json
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1974 remove customResource.json
  core-ui/src/components/Extensibility/errors.md
  core/src/assets/customResources/customResources.json
  core/src/luigi-config/customResources.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1965 Add code guidelines for devs
  CONTRIBUTING.md
Labels: size/S, lgtm, hacktoberfest-accepted

#1977 Fix colors in command pallete help
  core-ui/src/command-pallette/CommandPalletteUI/components/components.scss
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1980 Removing myself as CODEOWNER
  CODEOWNERS
Labels: size/XS, lgtm

#1969 Rewrite Luigi's navigation footer
  core-ui/public/assets/version.yaml
  core-ui/src/shared/components/Link/Link.tsx
  core-ui/src/sidebar/Footer/Footer.tsx
  core-ui/src/sidebar/Footer/useGetBusolaVersion.ts
  core-ui/src/sidebar/Footer/useGetLegalLinks.ts
  core-ui/src/sidebar/Sidebar.js
  core-ui/src/sidebar/SidebarNavigation.js
  resources/web/deployment.yaml
Labels: kind/feature, size/L, lgtm

#1981 Luigi: createRrl, kubernetesUrl and luigiNavigate fn
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/resources/createResourceRoutes.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1978 Handle navigation custom nodes
  core-ui/src/components/BusolaExtensions/extensionsNode.ts
  core-ui/src/components/Clusters/views/ClusterOverview/clusterDetailsNode.ts
  core-ui/src/components/CustomResources/customResourcesNode.ts
  core-ui/src/components/HelmReleases/helmReleasesNode.ts
  core-ui/src/resources/ClusterEvents/index.js
  core-ui/src/resources/Events/index.js
  core-ui/src/resources/Namespaces/index.js
  core-ui/src/resources/Namespaces/namespaceOverviewNode.ts
  core-ui/src/resources/index.js
  core-ui/src/sidebar/SidebarNavigation.js
  core-ui/src/state/navigation/addAdditionalNodes.ts
  core-ui/src/state/navigation/assignToCategories.ts
  core-ui/src/state/navigation/clusterAndNsNodesSelector.ts
  core-ui/src/state/navigation/filters/areNodeFeaturesEnabled.ts
  core-ui/src/state/navigation/filters/doesNodeResourceExist.ts
  core-ui/src/state/navigation/filters/filterScopeNodes.ts
  core-ui/src/state/navigation/filters/hasCurrentScope.ts
  core-ui/src/state/navigation/filters/isNodeResourcePermitted.ts
  core-ui/src/state/navigation/filters/shouldNodeBeVisible.ts
  core-ui/src/state/navigation/navigationNodesSelector.ts
  core-ui/src/state/navigation/sidebarNavigationNodesSelector.ts
  core-ui/src/state/resourceList/mapBusolaResourceToNavNode.ts
  core-ui/src/state/resourceList/mapExtResourceToNavNode.ts
  core-ui/src/state/resourceList/resourceListSelector.ts
  core-ui/src/state/types.ts
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1931 Move Preferences to core-ui
  core-ui/src/command-pallette/CommandPalletteUI/handlers/nonResourceHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/useSearchResults.js
  core-ui/src/components/App/useLuigiContextMigrator.js
  core-ui/src/components/Extensibility/components/tests/Table.test.js
  core-ui/src/components/Preferences/ConfirmationSettings.tsx
  core-ui/src/components/Preferences/LanguageSettings.js
  core-ui/src/components/Preferences/NamespaceSettings.tsx
  core-ui/src/components/Preferences/OtherSettings.tsx
  core-ui/src/components/Preferences/Preferences.js
  core-ui/src/components/Preferences/Preferences.scss
  core-ui/src/components/Preferences/ProtectedSettings.js
  core-ui/src/components/Preferences/test/NamespaceSettings.test.js
  core-ui/src/enzymeUtils.tsx
  core-ui/src/index.js
  core-ui/src/reactTestingUtils.tsx
  core-ui/src/resources/Namespaces/NamespaceList.js
  core-ui/src/resources/other.js
  core-ui/src/resources/other/preferences.routes.js
  core-ui/src/shared/components/GenericList/GenericList.js
  core-ui/src/shared/components/GenericList/test/GenericList.test.js
  core-ui/src/shared/components/ResourceDetails/tests/ResourceDetails.test.js
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
  core-ui/src/shared/components/Selector/tests/Selector.test.js
  core-ui/src/shared/helpers/getHiddenNamespaces.js
  core-ui/src/shared/hooks/useDeleteResource.js
  core-ui/src/shared/hooks/useGetHiddenNamespaces.ts
  core-ui/src/shared/hooks/useProtectedResources.js
  core-ui/src/state/groupsAtom.ts
  core-ui/src/state/preferences/disableResourceProtectionAtom.ts
  core-ui/src/state/preferences/dontConfirmDeleteAtom.ts
  core-ui/src/state/preferences/isPreferencesModalOpenAtom.ts
  core-ui/src/state/preferences/pageSizeAtom.ts
  core-ui/src/state/preferences/showHiddenNamespacesAtom.ts
  core-ui/src/state/utils/effects.ts
  core-ui/src/testing/enzymeUtils.tsx
  core-ui/src/testing/reactTestingUtils.tsx
  core/src/luigi-config/communication.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/nav-footer.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/static-navigation-model.js
  core/src/luigi-config/settings.js
  core/src/luigi-config/settings/pagination.js
  resources/web/deployment.yaml
  tests/tests/cluster/test-cluster-configuration.spec.js
  tests/tests/cluster/test-command-palette.spec.js
  tests/tests/namespace/test-daemon-sets.spec.js
  tests/tests/namespace/test-protected-resources.spec.js
  tests/tests/namespace/test-settings.spec.js
  tests/tests/namespace/test-stateful-sets.spec.js
Labels: kind/feature, size/XL, lgtm

#1987 Luigi separate secondary config
  core-ui/src/components/App/useLuigiContextMigrator.js
  core-ui/src/shared/hooks/BackendAPI/useFetch.ts
  core-ui/src/shared/hooks/useGetHiddenNamespaces.ts
  core-ui/src/sidebar/Footer/useGetLegalLinks.ts
  core-ui/src/state/authDataAtom.ts
  core-ui/src/state/clusterAtom.ts
  core-ui/src/state/clusterConfigAtom.ts
  core-ui/src/state/configFeatures/configFeaturesAtom.ts
  core-ui/src/state/configFeatures/lazyConfigFeaturesAtom.ts
  core-ui/src/state/extResourcesAtom.ts
  core-ui/src/state/navigation/categories.ts
  core-ui/src/state/navigation/clusterAndNsNodesSelector.ts
  core-ui/src/state/navigation/filters/isNodeResourcePermitted.ts
  core-ui/src/state/navigation/filters/shouldNodeBeVisible.ts
  core-ui/src/state/navigation/observabilityNodesSelector.ts
  core-ui/src/state/navigation/sidebarNavigationNodesSelector.ts
  core-ui/src/state/openapi/openapiAtom.ts
  core-ui/src/state/openapi/openapiPathIdSelector.ts
  core-ui/src/state/permissionSetsSelector.ts
  core-ui/src/state/resourceList/resourceListSelector.ts
  core-ui/src/state/types.ts
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1993 Luigi nav external nodes
  core-ui/src/state/navigation/addAdditionalNodes.ts
  core-ui/src/state/navigation/clusterAndNsNodesSelector.ts
  core-ui/src/state/navigation/observabilityNodesSelector.ts
  resources/web/deployment.yaml
Labels: size/XS, lgtm
