Repository kyma-project/busola, pull requests merged in 2022-03, with the labels that each got.

#1012 implement grafana logs link
  core-ui/src/components/Predefined/Details/Pod/ContainersLogs.js
  core-ui/src/components/Predefined/Details/Pod/ContainersLogs.scss
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/LogsLink/LogsLink.js
  shared/components/LogsLink/LogsLink.scss
  shared/index.js
Labels: size/L, lgtm

#1023 Fix routing params bug in instance details
  resources/web/deployment.yaml
  service-catalog-ui/src/components/App/App.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceDetails.js
Labels: kind/bug, size/S, lgtm

#1032 disable gzip for requests with follow=
  backend/index.js
  resources/backend/deployment.yaml
Labels: size/S, lgtm

#1021 Fix repeating status names in tooltips
  core-ui/src/components/Predefined/List/ServiceBrokers.list.js
  resources/web/deployment.yaml
  shared/components/StatusBadge/StatusBadge.js
Labels: kind/bug, size/M, lgtm

#1016 Fix bug with Prometheus graph when error occured
  core-ui/src/shared/components/StatsGraph/StatsPanel.js
  core-ui/src/shared/components/StatsGraph/StatsPanel.scss
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#999 remove unnecessary texts from placeholders
  core-ui/src/components/Predefined/Create/AddonsConfigurations/AddonsConfigurations.js
  core-ui/src/components/Predefined/Create/Certificates/Certificates.create.js
  core-ui/src/components/Predefined/Create/Gateways/Forms/HostsForm.js
  core-ui/src/components/Predefined/Create/Gateways/Forms/PortsForm.js
  core-ui/src/components/Predefined/Create/Issuers/Issuers.create.js
  core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
  core-ui/src/components/Predefined/Create/RoleBindings/RoleBindings.js
  core-ui/src/components/Predefined/Create/RoleBindings/SubjectForm.js
  core-ui/src/components/Predefined/Create/Roles/RuleInput.js
  core-ui/src/components/Predefined/Create/ServiceBindings/ServiceBindings.create.js
  core-ui/src/components/Predefined/Create/ServiceInstances/ServiceInstances.create.js
  core-ui/src/components/Predefined/Create/Subscriptions/FiltersSection.js
  core-ui/src/shared/ResourceForm/fields/TextArrayInput.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/K8sNameInput/K8sNameInput.js
  tests/support/views/api-rules-view.js
  tests/support/views/functions-view.js
  tests/tests/run-before.spec.js
  tests/tests/test-HPA.spec.js
  tests/tests/test-api-rules.spec.js
  tests/tests/test-applications.spec.js
  tests/tests/test-cluster-role-bindings.spec.js
  tests/tests/test-config-maps.spec.js
  tests/tests/test-cron-jobs.spec.js
  tests/tests/test-deployments.spec.js
  tests/tests/test-dns-entries.spec.js
  tests/tests/test-dns-providers.spec.js
  tests/tests/test-gateways.spec.js
  tests/tests/test-git-repositories.spec.js
  tests/tests/test-in-cluster-eventing.spec.js
  tests/tests/test-issuers.spec.js
  tests/tests/test-jobs.spec.js
  tests/tests/test-oauth2.spec.js
  tests/tests/test-protected-resources.spec.js
  tests/tests/test-reduced-permissions.spec.js
  tests/tests/test-replica-sets.spec.js
  tests/tests/test-roles.spec.js
  tests/tests/test-secrets.spec.js
  tests/tests/test-service-accounts.spec.js
  tests/tests/test-settings.spec.js
Labels: size/L, lgtm

#1035 populate lists with apiVersion/kind if missing
  resources/web/deployment.yaml
  shared/hooks/BackendAPI/useGet.js
Labels: size/S, lgtm

#1036 Fix Virtual Services navigation
  core-ui/src/components/Predefined/Details/ApiRule/Services.js
  core-ui/src/components/Predefined/List/VirtualServices.list.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1037 Fix https redirect on the Gateways
  core-ui/src/components/Predefined/Create/Gateways/Forms/TlsForm.js
  core-ui/src/components/Predefined/Create/Gateways/helpers.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/test-gateways.spec.js
Labels: kind/bug, size/M, lgtm

#1033 Longer cache for static files
  Dockerfile
  core-ui/public/index.html
  core-ui/src/index.js
  nginx/core-ui.conf
  nginx/core.conf
  nginx/nginx.conf
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1025 Adjust prometheus metrics
  core-ui/src/components/Nodes/NodeResources/NodeResources.js
  core-ui/src/components/Nodes/nodeQueries.js
  core-ui/src/shared/components/StatsGraph/StatsPanel.js
  core-ui/src/shared/components/StatsGraph/StatsPanel.scss
  core-ui/src/shared/hooks/usePrometheus.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1039 Refactor of pod and containers statuses
  core-ui/src/components/Predefined/Details/Pod/ContainerStatus.js
  core-ui/src/components/Predefined/Details/Pod/ContainersData.js
  core-ui/src/components/Predefined/Details/Pod/Pod.details.js
  core-ui/src/components/Predefined/Details/Pod/PodStatus.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/test-jobs.spec.js
  tests/tests/test-replica-sets.spec.js
Labels: kind/bug, size/L, lgtm

#1034 merge Busola's defaultConfig with ConfigMap
  Dockerfile.local
  README.md
  backend/Dockerfile
  backend/index.js
  backend/jwtCheck.js
  backend/package-lock.json
  backend/package.json
  backend/settings/defaultConfig.json
  core/src/assets/config/config.json
  core/src/assets/defaultConfig.json
  core/src/luigi-config/busola-cluster-params.js
  core/src/luigi-config/features.js
  docs/features.md
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1067 Add tooltip for service account download kubeconfig button
  core-ui/src/components/Predefined/Details/ServiceAccount/GenericSecrets.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1070 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: size/XS, lgtm

#1074 Stats graph for the Nodes amount
  core-ui/src/shared/components/StatsGraph/StatsPanel.js
  core-ui/src/shared/hooks/usePrometheus.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1010 Graphs
  core-ui/src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/helpers.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/index.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.js
  core-ui/src/components/App/App.js
  core-ui/src/components/Predefined/Create/ApiRules/ApiRules.create.js
  core-ui/src/components/Predefined/Create/ConfigMaps/ConfigMaps.create.js
  core-ui/src/components/Predefined/Create/ConfigMaps/helpers.js
  core-ui/src/components/Predefined/Create/Deployments/Deployments.create.js
  core-ui/src/components/Predefined/Create/Functions/Functions.create.js
  core-ui/src/components/Predefined/Create/Gateways/Gateways.create.js
  core-ui/src/components/Predefined/Create/HPAs/HPAs.create.js
  core-ui/src/components/Predefined/Create/Jobs/CronJobs.create.js
  core-ui/src/components/Predefined/Create/Jobs/Jobs.create.js
  core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
  core-ui/src/components/Predefined/Create/Pods/Pods.create.js
  core-ui/src/components/Predefined/Create/ReplicaSets/ReplicaSets.create.js
  core-ui/src/components/Predefined/Create/RoleBindings/RoleBindings.create.js
  core-ui/src/components/Predefined/Create/Roles/Roles.create.js
  core-ui/src/components/Predefined/Create/Secrets/Secrets.create.js
  core-ui/src/components/Predefined/Create/ServiceAccounts/ServiceAccounts.create.js
  core-ui/src/components/Predefined/Create/Services/Services.create.js
  core-ui/src/components/Predefined/Create/VirtualServices/VirtualServices.create.js
  core-ui/src/components/Predefined/Details/Roles/Roles.details.js
  core-ui/src/hooks/useMessageList.js
  core-ui/src/shared/helpers/getResourceDefs.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourceGraph/ResourceGraph.js
  shared/components/ResourceGraph/ResourceGraph.scss
  shared/components/ResourceGraph/SaveGraphControls.js
  shared/components/ResourceGraph/buildGraph/buildNetworkGraph.js
  shared/components/ResourceGraph/buildGraph/buildStructuralGraph.js
  shared/components/ResourceGraph/buildGraph/helpers.js
  shared/components/ResourceGraph/buildGraph/index.js
  shared/components/ResourceGraph/useRelatedResources.js
  shared/hooks/navigate.js
  shared/jestSetup.js
  shared/package-lock.json
  shared/package.json
  shared/utils/helpers.js
  shared/utils/test/helpers.test.js
Labels: size/XXL, lgtm

#1069 Repair uppercase name for Role Bindigs
  core-ui/src/components/Predefined/Details/ApiRule/ApiRules.details.js
  core-ui/src/components/Predefined/Details/DNSEntries.details.js
  core-ui/src/components/Predefined/Details/DNSProviders.details.js
  core-ui/src/components/Predefined/Details/OAuth2Clients/OAuth2Clients.details.js
  core-ui/src/components/Predefined/List/AddonsConfigurations.list.js
  core-ui/src/components/Predefined/List/AuthorizationPolicies.list.js
  core-ui/src/components/Predefined/List/ConfigMaps.list.js
  core-ui/src/components/Predefined/List/CustomResourceDefinitions.list.js
  core-ui/src/components/Predefined/List/GitRepository/GitRepositories.list.js
  core-ui/src/components/Predefined/List/NetworkPolicies.list.js
  core-ui/src/components/Predefined/List/PersistentVolumeClaims.list.js
  core-ui/src/components/Predefined/List/ReplicaSets.list.js
  core-ui/src/components/Predefined/List/RoleBindings.list.js
  core-ui/src/components/Predefined/List/Roles.list.js
  core-ui/src/components/Predefined/List/ServiceEntries.list.js
  core-ui/src/components/Predefined/List/StorageClasses.list.js
  core-ui/src/shared/helpers/getResourceUrl.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  shared/hooks/navigate.js
Labels: kind/bug, size/L, lgtm

#1082 Removed specialCharacter validation for eventType
  core-ui/src/components/Predefined/Create/Subscriptions/FiltersSection.js
  resources/web/deployment.yaml
  tests/cypress.json
Labels: size/S, lgtm

#1084 Add specific version of node and npm to dockerfile
  Dockerfile
  Dockerfile.local
  backend/Dockerfile
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1086 Visual Resources for Storage Objects
  core-ui/src/components/Predefined/Create/Gateways/Gateways.create.js
  core-ui/src/components/Predefined/Create/OAuthClients/OAuthClients.create.js
  core-ui/src/components/Predefined/Create/PersistentVolumeClaims/PersistentVolumeClaims.create.js
  core-ui/src/components/Predefined/Create/PersistentVolumes/PersistentVolumes.create.js
  core-ui/src/components/Predefined/Create/Pods/Pods.create.js
  core-ui/src/components/Predefined/Create/Secrets/Secrets.create.js
  core-ui/src/components/Predefined/Create/ServiceAccounts/ServiceAccounts.create.js
  core-ui/src/components/Predefined/Create/StorageClasses/StorageClasses.create.js
  core-ui/src/shared/helpers/getResourceDefs.js
  resources/web/deployment.yaml
Labels: kind/feature, size/L, lgtm

#1091 Graph colors
  core-ui/src/components/Predefined/Details/ApiRule/ApiRules.details.js
  core-ui/src/components/Predefined/Details/ApiRule/ApiRulesDetails.scss
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMap.details.js
  core-ui/src/components/Predefined/Details/ConfigMap/ConfigMapsDetails.scss
  core-ui/src/components/Predefined/Details/CronJobs/CronJob.details.js
  core-ui/src/components/Predefined/Details/CronJobs/CronJobsDetails.scss
  core-ui/src/components/Predefined/Details/Function/Function.details.js
  core-ui/src/components/Predefined/Details/Function/FunctionsDetails.scss
  core-ui/src/components/Predefined/Details/Gateway/Gateway.details.js
  core-ui/src/components/Predefined/Details/Gateway/GatewaysDetails.scss
  core-ui/src/components/Predefined/Details/HPA/HPA.details.js
  core-ui/src/components/Predefined/Details/HPA/HorizontalPodAutoscalersDetails.scss
  core-ui/src/components/Predefined/Details/Job/Job.details.js
  core-ui/src/components/Predefined/Details/Job/JobsDetails.scss
  core-ui/src/components/Predefined/Details/OAuth2Clients/OAuth2Clients.details.js
  core-ui/src/components/Predefined/Details/OAuth2Clients/OAuth2ClientsDetails.scss
  core-ui/src/components/Predefined/Details/Pod/Pod.details.js
  core-ui/src/components/Predefined/Details/Pod/PodDetails.scss
  core-ui/src/components/Predefined/Details/ReplicaSet/Replicaset.details.js
  core-ui/src/components/Predefined/Details/ReplicaSet/ReplicasetsDetails.scss
  core-ui/src/components/Predefined/Details/RoleBindings/RoleBindings.details.js
  core-ui/src/components/Predefined/Details/RoleBindings/RoleBindingsDetails.scss
  core-ui/src/components/Predefined/Details/Roles/Roles.details.js
  core-ui/src/components/Predefined/Details/Roles/RolesDetails.scss
  core-ui/src/components/Predefined/Details/Secret/Secret.details.js
  core-ui/src/components/Predefined/Details/Secret/SecretsDetails.scss
  core-ui/src/components/Predefined/Details/Service/Service.details.scss
  core-ui/src/components/Predefined/Details/ServiceAccount/ServiceAccount.details.js
  core-ui/src/components/Predefined/Details/ServiceAccount/ServiceAccountsDetails.scss
  core-ui/src/components/Predefined/Details/VirtualServices/VirtualServicesDetails.scss
  core-ui/src/components/Predefined/Details/index.js
  resources/web/deployment.yaml
  shared/components/ResourceGraph/ResourceGraph.scss
  shared/components/ResourceGraph/buildGraph/buildNetworkGraph.js
  shared/components/ResourceGraph/buildGraph/helpers.js
  shared/components/ResourceGraph/buildGraph/index.js
  shared/components/ResourceGraph/mixins.scss
Labels: size/L, lgtm

#1087 Fix lowercase in the 'resource not found page'
  core-ui/src/components/Predefined/Details/AddonsConfiguration.details.js
  core-ui/src/components/Predefined/Details/CronJobs/CronJob.details.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitions.details.js
  core-ui/src/components/Predefined/Details/DaemonSet/DaemonSet.details.js
  core-ui/src/components/Predefined/Details/GitRepositories.details.js
  core-ui/src/components/Predefined/Details/HPA/HPA.details.js
  core-ui/src/components/Predefined/Details/HPA/HPASubcomponent.js
  core-ui/src/components/Predefined/Details/NetworkPolicy/NetworkPolicy.details.js
  core-ui/src/components/Predefined/Details/PersistentVolume/PersistentVolumes.details.js
  core-ui/src/components/Predefined/Details/PersistentVolumeClaims/PersistentVolumeClaims.details.js
  core-ui/src/components/Predefined/Details/ReplicaSet/Replicaset.details.js
  core-ui/src/components/Predefined/Details/RoleBindings/RoleBindings.details.js
  core-ui/src/components/Predefined/Details/Roles/Roles.details.js
  core-ui/src/components/Predefined/Details/ServiceAccount/ServiceAccount.details.js
  core-ui/src/components/Predefined/Details/StatefulSet/StatefulSets.details.js
  core-ui/src/components/Predefined/Details/StorageClasses/StorageClasses.details.js
  core-ui/src/components/Predefined/List/DNSEntries.list.js
  core-ui/src/components/Predefined/List/DNSProviders.list.js
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  shared/utils/helpers.js
Labels: kind/bug, size/L, lgtm

#1076 Add graph configuration for workloads
  core-ui/src/components/Predefined/Create/DaemonSets/DaemonSets.create.js
  core-ui/src/components/Predefined/Create/Deployments/Deployments.create.js
  core-ui/src/components/Predefined/Create/HPAs/HPAs.create.js
  core-ui/src/components/Predefined/Create/Jobs/CronJobs.create.js
  core-ui/src/components/Predefined/Create/Jobs/Jobs.create.js
  core-ui/src/components/Predefined/Create/PersistentVolumeClaims/PersistentVolumeClaims.create.js
  core-ui/src/components/Predefined/Create/PersistentVolumes/PersistentVolumes.create.js
  core-ui/src/components/Predefined/Create/Pods/Pods.create.js
  core-ui/src/components/Predefined/Create/ReplicaSets/ReplicaSets.create.js
  core-ui/src/components/Predefined/Create/StatefulSets/StatefulSets.create.js
  core-ui/src/components/Predefined/Create/StorageClasses/StorageClasses.create.js
  resources/web/deployment.yaml
  shared/components/ResourceGraph/buildGraph/buildNetworkGraph.js
  shared/components/ResourceGraph/useRelatedResources.js
Labels: size/L, lgtm

#1094 add visual resources feature flag
  core/src/assets/defaultConfig.json
  resources/web/configmap.yaml
  resources/web/deployment.yaml
  shared/components/ResourceGraph/ResourceGraph.js
Labels: size/S, lgtm

#1059 Parallelise tests
  tests/cypress-smoke.json
  tests/cypress.json
  tests/package-lock.json
  tests/package.json
  tests/plugins/index.js
  tests/tests/cluster/run-after.spec.js
  tests/tests/cluster/run-before.spec.js
  tests/tests/cluster/test-applications.spec.js
  tests/tests/cluster/test-cluster-configuration.spec.js
  tests/tests/cluster/test-cluster-overview.spec.js
  tests/tests/cluster/test-cluster-role-bindings.spec.js
  tests/tests/cluster/test-command-palette.spec.js
  tests/tests/cluster/test-dashboard-version.spec.js
  tests/tests/cluster/test-download-a-kubeconfig.spec.js
  tests/tests/cluster/test-edit-cluster.spec.js
  tests/tests/cluster/test-invalid-kubeconfig.spec.js
  tests/tests/cluster/test-kyma-version.spec.js
  tests/tests/cluster/test-login-kubeconfigID.spec.js
  tests/tests/cluster/test-multiple-context-kubeconfig.spec.js
  tests/tests/cluster/test-other-login-options.spec.js
  tests/tests/cluster/test-persistent-volumes.spec.js
  tests/tests/cluster/test-storage-classes.spec.js
  tests/tests/namespace/run-after.spec.js
  tests/tests/namespace/run-before.spec.js
  tests/tests/namespace/run-prepare-functions.spec.js
  tests/tests/namespace/test-HPA.spec.js
  tests/tests/namespace/test-api-rules.spec.js
  tests/tests/namespace/test-authorization-policies.spec.js
  tests/tests/namespace/test-certificates.spec.js
  tests/tests/namespace/test-config-maps.spec.js
  tests/tests/namespace/test-cron-jobs.spec.js
  tests/tests/namespace/test-custom-resource-definitions.spec.js
  tests/tests/namespace/test-daemon-sets.spec.js
  tests/tests/namespace/test-deployments.spec.js
  tests/tests/namespace/test-destination-rules.spec.js
  tests/tests/namespace/test-dns-entries.spec.js
  tests/tests/namespace/test-dns-providers.spec.js
  tests/tests/namespace/test-events.spec.js
  tests/tests/namespace/test-gateways.spec.js
  tests/tests/namespace/test-git-repositories.spec.js
  tests/tests/namespace/test-in-cluster-eventing.spec.js
  tests/tests/namespace/test-ingresses.spec.js
  tests/tests/namespace/test-issuers.spec.js
  tests/tests/namespace/test-jobs.spec.js
  tests/tests/namespace/test-namespace-overview.spec.js
  tests/tests/namespace/test-network-policies.spec.js
  tests/tests/namespace/test-oauth2.spec.js
  tests/tests/namespace/test-persistent-volume-claims.spec.js
  tests/tests/namespace/test-protected-resources.spec.js
  tests/tests/namespace/test-reduced-permissions.spec.js
  tests/tests/namespace/test-replica-sets.spec.js
  tests/tests/namespace/test-resource-upload.spec.js
  tests/tests/namespace/test-roles.spec.js
  tests/tests/namespace/test-secrets.spec.js
  tests/tests/namespace/test-service-accounts.spec.js
  tests/tests/namespace/test-service-entries.spec.js
  tests/tests/namespace/test-settings.spec.js
  tests/tests/namespace/test-sidecars.spec.js
  tests/tests/namespace/test-stateful-sets.spec.js
  tests/tests/namespace/test-virtual-services.spec.js
Labels: size/XXL, lgtm

#1098 Add yml extension to the accepted file formats
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigFileUpload.js
  core-ui/src/components/Predefined/Details/Namespace/YamlUpload/YamlFileUploader.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1101 Add simple role presets
  core-ui/src/components/Predefined/Create/Roles/GenericRoleCreate.js
  core-ui/src/components/Predefined/Create/Roles/Roles.create.js
  core-ui/src/components/Predefined/Create/Roles/helpers.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1093 check for prometheus and set a feature flag
  core-ui/src/shared/components/StatsGraph/StatsPanel.js
  core/src/assets/defaultConfig.json
  core/src/luigi-config/constants.js
  resources/web/configmap.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1097 Graphs for Networking Objects
  core-ui/src/components/Predefined/Create/Gateways/Gateways.create.js
  core-ui/src/components/Predefined/Create/Ingresses/Ingresses.create.js
  core-ui/src/components/Predefined/Create/Secrets/Secrets.create.js
  core-ui/src/components/Predefined/Create/Services/Services.create.js
  core-ui/src/components/Predefined/Create/Subscriptions/Subscriptions.create.js
  core-ui/src/components/Predefined/Create/VirtualServices/VirtualServices.create.js
  resources/web/deployment.yaml
  shared/components/ResourceGraph/buildGraph/buildNetworkGraph.js
Labels: size/L, lgtm

#1102 Improve User Experience for users with Namespace Access only
  core-ui/src/components/NoPermissions/NoPermissions.js
  core-ui/src/components/NoPermissions/NoPermissions.scss
  core-ui/src/index.scss
  core/src/i18n/en.yaml
  core/src/luigi-config/communication.js
  core/src/luigi-config/navigation/navigation-data-init.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1116 Remove search for CRDs names
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitions.details.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1120 Update repository owners
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/S, lgtm

#1121 Update repository owners
  OWNERS
  OWNERS_ALIASES
  core/src/i18n/OWNERS
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1105 Fix useGet test
  core-ui/src/service-catalog-ui/setupTests.js
  core-ui/src/shared-repo/components/KeyValueForm/test/KeyValueForm.test.js
  core-ui/src/shared-repo/hooks/BackendAPI/tests/useGet.test.js
  core-ui/src/shared-repo/hooks/BackendAPI/useGet.js
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1118 raise namespace memory limit and test timeout
  tests/cypress.json
  tests/tests/namespace/run-before.spec.js
Labels: size/S, lgtm

#1117 Remove nodes graph from pod level
  core-ui/src/shared/components/StatsGraph/StatsPanel.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1072 Lighthouse CI
  lighthouse/.gitignore
  lighthouse/README.md
  lighthouse/fixtures/.gitkeep
  lighthouse/lighthouse.spec.js
  lighthouse/package-lock.json
  lighthouse/package.json
  lighthouse/playwright.config.js
Labels: size/XXL, lgtm

#1107 Added inspecting list function and added inspecting with deleting to tests
  tests/cypress.json
  tests/support/commands.js
  tests/support/helpers.js
  tests/support/index.js
  tests/support/inspect-list.js
  tests/tests/cluster/run-after.spec.js
  tests/tests/cluster/test-persistent-volumes.spec.js
  tests/tests/cluster/test-storage-classes.spec.js
  tests/tests/namespace/test-HPA.spec.js
  tests/tests/namespace/test-api-rules.spec.js
  tests/tests/namespace/test-authorization-policies.spec.js
  tests/tests/namespace/test-certificates.spec.js
  tests/tests/namespace/test-config-maps.spec.js
  tests/tests/namespace/test-cron-jobs.spec.js
  tests/tests/namespace/test-custom-resource-definitions.spec.js
  tests/tests/namespace/test-daemon-sets.spec.js
  tests/tests/namespace/test-destination-rules.spec.js
  tests/tests/namespace/test-dns-entries.spec.js
  tests/tests/namespace/test-dns-providers.spec.js
  tests/tests/namespace/test-gateways.spec.js
  tests/tests/namespace/test-in-cluster-eventing.spec.js
  tests/tests/namespace/test-ingresses.spec.js
  tests/tests/namespace/test-issuers.spec.js
  tests/tests/namespace/test-jobs.spec.js
  tests/tests/namespace/test-network-policies.spec.js
  tests/tests/namespace/test-oauth2.spec.js
  tests/tests/namespace/test-persistent-volume-claims.spec.js
  tests/tests/namespace/test-reduced-permissions.spec.js
  tests/tests/namespace/test-roles.spec.js
  tests/tests/namespace/test-secrets.spec.js
  tests/tests/namespace/test-service-accounts.spec.js
  tests/tests/namespace/test-service-entries.spec.js
  tests/tests/namespace/test-sidecars.spec.js
  tests/tests/namespace/test-stateful-sets.spec.js
  tests/tests/namespace/test-virtual-services.spec.js
Labels: size/XL, lgtm, test-enhancement

#1133 Fix blocked requests
  core-ui/src/service-catalog-ui/components/ServiceClassDetails/CreateInstanceForm/PlanColumnContent.js
  core-ui/src/shared-repo/components/Dropdown/Dropdown.js
  core-ui/src/shared-repo/hooks/BackendAPI/useGet.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/namespace/test-service-catalog.spec.js
Labels: kind/bug, size/M, lgtm

#1125 Prometheus namespace graphs
  core-ui/src/components/Predefined/Details/Namespace/Namespace.details.js
  core-ui/src/shared/hooks/usePrometheus.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1139 Add default prometheus address
  core-ui/src/shared/hooks/usePrometheus.js
  core/src/assets/defaultConfig.json
  docs/features.md
  resources/web/configmap.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1137 Fix Sentry issues, update certs.pem
  backend/certs.pem
  core-ui/src/command-pallette/CommandPaletteProvider.js
  core-ui/src/components/Predefined/Details/HPA/helpers.js
  core-ui/src/service-catalog-ui/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceBindingStatus.js
  core-ui/src/shared-repo/contexts/YamlEditorContext/EditorActions.js
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
  core-ui/src/shared/components/StatsGraph/StatsGraph.js
  core/src/luigi-config/communication.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  tests/support/paste-to-monaco.js
Labels: size/L, lgtm

#1103 Webpack hash
  core/.babelrc
  core/.gitignore
  core/package-lock.json
  core/package.json
  core/src/index.html
  core/src/luigi-config/luigi-config.js
  core/src/template.html
  core/webpack.config.js
  nginx/nginx.conf
  resources/web/deployment.yaml
Labels: kind/feature, size/XXL, lgtm

#1145 Fix yaml-sort bug
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: kind/bug, size/L, lgtm

#1150 Use fallback prometheus paths
  core-ui/src/shared-repo/hooks/BackendAPI/useGet.js
  core-ui/src/shared/hooks/usePrometheus.js
  core/src/assets/defaultConfig.json
  core/src/luigi-config/communication.js
  core/src/luigi-config/settings/prometheus.js
  resources/web/configmap.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1146 change name Cluster Overview to Cluster Details
  core/src/i18n/en.yaml
  docs/features.md
  lighthouse/lighthouse.spec.js
  resources/web/deployment.yaml
  tests/tests/cluster/test-cluster-configuration.spec.js
  tests/tests/cluster/test-cluster-overview.spec.js
  tests/tests/cluster/test-command-palette.spec.js
  tests/tests/cluster/test-multiple-context-kubeconfig.spec.js
  tests/tests/namespace/test-reduced-permissions.spec.js
  tests/tests/namespace/test-resource-upload.spec.js
  tests/tests/namespace/test-settings.spec.js
Labels: size/M, lgtm

#1160 Fix graph
  core-ui/src/shared/hooks/usePrometheus.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1153 Added more connections and change graphs for networking
  core-ui/src/components/Predefined/Create/ApiRules/ApiRules.create.js
  core-ui/src/components/Predefined/Create/Gateways/Gateways.create.js
  core-ui/src/components/Predefined/Create/Ingresses/Ingresses.create.js
  core-ui/src/components/Predefined/Create/NetworkPolicies/NetworkPolicies.create.js
  core-ui/src/components/Predefined/Create/PersistentVolumeClaims/PersistentVolumeClaims.create.js
  core-ui/src/components/Predefined/Create/PersistentVolumes/PersistentVolumes.create.js
  core-ui/src/components/Predefined/Create/Pods/Pods.create.js
  core-ui/src/components/Predefined/Create/Services/Services.create.js
  core-ui/src/components/Predefined/Create/StorageClasses/StorageClasses.create.js
  core-ui/src/components/Predefined/Create/VirtualServices/VirtualServices.create.js
  resources/web/deployment.yaml
Labels: kind/feature, size/M, lgtm

#1140 CRDs should be visible at Cluster Level Only
  core-ui/src/command-pallette/CommandPalletteUI/CommandPaletteUI.js
  core-ui/src/command-pallette/CommandPalletteUI/CommandPaletteUI.scss
  core-ui/src/command-pallette/CommandPalletteUI/handlers/crHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/crdHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/index.js
  core-ui/src/components/App/App.js
  core-ui/src/components/CustomResources/CRDList.js
  core-ui/src/components/CustomResources/CustomResources.js
  core-ui/src/components/CustomResources/CustomResourcesByGroup.js
  core-ui/src/components/CustomResources/CustomResourcesOfType.js
  core-ui/src/components/CustomResources/GroupingListPage/GroupingListPage.js
  core-ui/src/components/CustomResources/GroupingListPage/GroupingListPage.scss
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CRCreate.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CurrentCRDVersion.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CurrentCRDVersion.scss
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitions.details.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResources.details.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/RelatedCRDsList.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/templates.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/useNavigateToCustomResource.js
  core-ui/src/components/Predefined/List/CustomResourceDefinitions.list.js
  core-ui/src/index.scss
  core-ui/src/routing/other.js
  core-ui/src/routing/other/CRDetails.routes.js
  core-ui/src/routing/other/CustomResourceDefinitions.routes.js
  core-ui/src/routing/other/CustomResourceDetails.routes.js
  core-ui/src/routing/other/CustomResourceListOfType.routes.js
  core-ui/src/routing/other/CustomResourcesByGroup.routes.js
  core-ui/src/shared-repo/components/ResourcesList/ResourcesList.js
  core-ui/src/shared/components/ReadonlyEditorPanel.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/cluster/test-custom-resources.spec.js
  tests/tests/namespace/test-custom-resource-definitions.spec.js
  tests/tests/namespace/test-custom-resources.spec.js
Labels: size/XXL, lgtm

#1123 All api groups
  core-ui/src/components/Predefined/Create/Roles/Roles.create.js
  core-ui/src/components/Predefined/Create/Roles/RuleInput.js
  core-ui/src/components/Predefined/Create/Roles/helpers.js
  core-ui/src/components/Predefined/Create/Roles/useResourcesForApiGroups.js
  core-ui/src/shared/ResourceForm/components/CollapsibleSection.js
  core-ui/src/shared/ResourceForm/components/CollapsibleSection.scss
  core-ui/src/shared/ResourceForm/fields/ComboboxArrayInput.js
  core-ui/src/shared/ResourceForm/fields/MultiInput.js
  core-ui/src/shared/ResourceForm/fields/MultiInput.scss
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/namespace/test-reduced-permissions.spec.js
  tests/tests/namespace/test-roles.spec.js
Labels: size/L, lgtm

#1168 improve roles i18n
  core-ui/src/components/Predefined/Create/Roles/RuleInput.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1161 Upgrade graphs queries
  core-ui/src/shared/hooks/usePrometheus.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1157 Added validation if storage class and pvc exist
  core-ui/src/components/Predefined/Details/PersistentVolume/PersistentVolumes.details.js
  core-ui/src/components/Predefined/List/PersistentVolumes.list.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1162 Added validation if service exist
  core-ui/src/components/Predefined/Details/Ingress/DefaultBackendPanel.js
  core-ui/src/components/Predefined/Details/Ingress/Ingress.details.js
  core-ui/src/components/Predefined/Details/Ingress/Rules.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1174 Fix error handling for graph
  core-ui/src/shared/hooks/usePrometheus.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1172 Api groups - move load button
  core-ui/src/components/Predefined/Create/Roles/RuleInput.js
  core-ui/src/shared/ResourceForm/fields/ComboboxArrayInput.js
  core-ui/src/shared/ResourceForm/fields/ComboboxArrayInput.scss
  core-ui/src/shared/ResourceForm/fields/MultiInput.js
  core-ui/src/shared/ResourceForm/fields/MultiInput.scss
  resources/web/deployment.yaml
  tests/tests/namespace/test-reduced-permissions.spec.js
  tests/tests/namespace/test-roles.spec.js
Labels: size/M, lgtm

#1167 fix namespaced user navigation
  core/src/luigi-config/cluster-management/cluster-management.js
  core/src/luigi-config/navigation/navigation-data-init.js
  resources/web/deployment.yaml
  tests/tests/cluster/test-edit-cluster.spec.js
Labels: size/S, lgtm

#1177 Fix displaying ResourceGraphs on Safari
  core-ui/src/shared/components/ResourceGraph/ResourceGraph.scss
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1180 Improve styling for ResourceGraphs
  core-ui/src/shared/components/ResourceGraph/ResourceGraph.js
  resources/web/deployment.yaml
Labels: kind/feature, size/M, lgtm

#1169 Add expiration info in the Certificates
  core-ui/src/components/Predefined/Details/Certificate/Certificate.details.js
  core-ui/src/components/Predefined/Details/Secret/CertificatePanel.js
  core-ui/src/components/Predefined/List/Certificates.list.js
  core-ui/src/shared/components/CertificateDate/CertificateDate.js
  core-ui/src/shared/components/CertificateDate/CertificateDate.scss
  core-ui/src/shared/components/FormattedDate/FormattedDate.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: kind/feature, size/L, lgtm

#1158 load graphviz-react async
  core-ui/src/hooks/useMinWidth.js
  core-ui/src/shared/components/ResourceDetails/ResourceDetails.js
  core-ui/src/shared/components/ResourceGraph/ResourceGraph.js
  core-ui/src/shared/components/ResourceGraph/ResourceGraph.scss
  core-ui/src/shared/hooks/useIntersectionObserver.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1182 fix no permissions namespace entry
  core-ui/src/components/NoPermissions/NoPermissions.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm
