Repository kyma-project/busola, pull requests merged in 2022-01, with the labels that each got.

#758 Protect Applications on SKRs
  core-ui/src/components/Predefined/Details/Application/ConnectApplicationModal.js
  core-ui/src/components/Predefined/Details/Application/CreateBindingModal/CreateBindingModal.js
  core-ui/src/components/Predefined/Details/Application/tests/useIsSKR.test.js
  core-ui/src/components/Predefined/Details/Application/useIsSKR.js
  core-ui/src/components/Predefined/List/Application/CreateApplicationModal.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/test-protected-resources.spec.js
Labels: size/L, lgtm

#760 Display categories on the list view, details view and crds with relat…
  core-ui/src/components/Predefined/Create/CustomResourceDefinitions/templates.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitions.details.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/RelatedCRDsList.js
  core-ui/src/components/Predefined/List/CustomResourceDefinitions.list.js
  core-ui/src/shared/components/Tokens.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/Labels/Labels.scss
  shared/components/ResourcesList/ResourcesList.js
Labels: size/M, lgtm

#770 Fix CRD search
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitions.details.js
  core-ui/src/components/Predefined/List/CustomResourceDefinitions.list.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#765 Hide read only lines from editor
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/contexts/YamlEditorContext/EditorActions.js
Labels: size/M, lgtm

#766 Fix tests by waiting for the footer to show up
  core/src/luigi-config/nav-footer.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/test-dashboard-version.spec.js
Labels: size/M, lgtm

#769 Refactor of Subscriptions
  core-ui/src/components/Lambdas/LambdaDetails/LambdaDetails.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/EventSubscriptions/EventSubscriptionsWrapper.js
  core-ui/src/components/Predefined/Create/Subscriptions/Subscriptions.create.js
  core-ui/src/components/Predefined/Create/Subscriptions/helpers.js
  core-ui/src/components/Predefined/Create/Subscriptions/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/Service/Service.details.js
  core-ui/src/components/Predefined/Details/Subscriptions/EventFilters.scss
  core-ui/src/components/Predefined/Details/Subscriptions/SubscriptionConditions.js
  core-ui/src/components/Predefined/Details/Subscriptions/Subscriptions.details.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/Subscription/Subscriptions.list.js
  core-ui/src/components/Predefined/List/Subscription/Subscriptions.scss
  core-ui/src/components/Predefined/List/index.js
  core-ui/src/hooks/useMessageList.js
  core-ui/src/shared/ResourceForm/components/FormField.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/useCreateResource.js
  core-ui/src/shared/components/SubscriptionConditionStatus.js
  core-ui/src/shared/components/SubscriptionsList.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/tests/in-cluster-eventing.spec.js
  tests/tests/run-after.spec.js
Labels: bug, size/XL, lgtm

#778 Fix for bindings
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingForm.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceBindingStatus.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.js
Labels: size/L, lgtm

#781 Fix bug related to pasting yaml in function
  core-ui/src/components/Predefined/Create/Functions/Functions.create.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#790 Fix the creation of Limit ranges and Resource quotas
  core-ui/src/components/Predefined/Create/Namespaces/Namespaces.create.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#793 Tiny fix to make validation work properly
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingForm.js
Labels: bug, size/XS, lgtm

#773 Visualize crds
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  core-ui/src/shared/components/SchemaViewer/JSONSchema.js
  core-ui/src/shared/components/SchemaViewer/ObjectProperties.js
  core-ui/src/shared/components/SchemaViewer/SchemaViewer.js
  core-ui/src/shared/components/SchemaViewer/SchemaViewer.scss
  core-ui/src/shared/components/SchemaViewer/handlers.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#796 Deleted double subscription export from index
  core-ui/src/components/Predefined/Create/index.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#791 Refactor and repair checking logs for eventing
  tests/tests/in-cluster-eventing.spec.js
  tests/tests/run-before.spec.js
Labels: size/M, lgtm, test-case

#797 Create/edit application form
  core-ui/src/components/Predefined/Create/Applications/Applications.create.js
  core-ui/src/components/Predefined/Create/Applications/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/List/Application/Applications.list.js
  core-ui/src/components/Predefined/List/Application/CreateApplicationModal.js
  core-ui/src/components/Predefined/List/Application/test/CreateApplicationModal.test.js
  core-ui/src/components/Predefined/List/Application/test/__snapshots__/CreateApplicationModal.test.js.snap
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
  tests/cypress.json
  tests/tests/run-before.spec.js
  tests/tests/test-application.spec.js
Labels: size/L, lgtm

#802 Fix problem with creation of service binding
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingForm.js
Labels: size/XS, lgtm

#792 Add an option to create, edit and delete limits and quotas
  core-ui/src/components/Predefined/Create/LimitRanges/LimitRanges.create.js
  core-ui/src/components/Predefined/Create/LimitRanges/templates.js
  core-ui/src/components/Predefined/Create/Namespaces/Namespaces.create.js
  core-ui/src/components/Predefined/Create/Namespaces/Presets.js
  core-ui/src/components/Predefined/Create/Namespaces/templates.js
  core-ui/src/components/Predefined/Create/ResourceQuotas/ResourceQuotas.create.js
  core-ui/src/components/Predefined/Create/ResourceQuotas/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/Namespace/Namespace.details.js
  core-ui/src/components/Predefined/Details/Namespace/ResourcesUsage.js
  core-ui/src/components/Predefined/List/LimitRanges.list.js
  core-ui/src/components/Predefined/List/ResourceQuotas.list.js
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
  shared/hooks/navigate.js
  tests/cypress.json
  tests/tests/create-a-deployment.spec.js
  tests/tests/in-cluster-eventing.spec.js
  tests/tests/run-before.spec.js
  tests/tests/smoke-tests.spec.js
  tests/tests/test-namespace-overview.spec.js
  tests/tests/test-virtual-services.spec.js
Labels: size/L, lgtm

#803 Fix CRD details
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitions.details.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#805 Add an option to add also event sources, small translation cleanups
  core-ui/src/components/Predefined/Create/Subscriptions/FiltersSection.js
  core-ui/src/components/Predefined/Create/Subscriptions/Subscriptions.create.js
  core-ui/src/components/Predefined/Create/Subscriptions/helpers.js
  core-ui/src/components/Predefined/Create/Subscriptions/templates.js
  core-ui/src/components/Predefined/Details/Subscriptions/SubscriptionConditions.js
  core-ui/src/components/Predefined/Details/Subscriptions/Subscriptions.details.js
  core-ui/src/components/Predefined/List/Subscription/Subscriptions.list.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/tests/in-cluster-eventing.spec.js
Labels: size/L, lgtm

#809 Introduce storage classes
  core-ui/src/components/Predefined/Create/StorageClasses/StorageClasses.create.js
  core-ui/src/components/Predefined/Create/StorageClasses/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/StorageClasses/StorageClasses.details.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/StorageClasses.list.js
  core-ui/src/components/Predefined/List/index.js
  core-ui/src/shared/components/PersistentVolumeClaimsList.js
  core-ui/src/shared/components/PersistentVolumesList.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/fixtures/test-storage-classes.yaml
  tests/support/loadFile.js
  tests/tests/test-storage-classes.spec.js
Labels: enhancement, size/L, lgtm

#764 Command Palette
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/command-pallette/CommandPaletteProvider.js
  core-ui/src/command-pallette/CommandPalletteUI/CommandPaletteUI.js
  core-ui/src/command-pallette/CommandPalletteUI/CommandPaletteUI.scss
  core-ui/src/command-pallette/CommandPalletteUI/ResultsList/Result.js
  core-ui/src/command-pallette/CommandPalletteUI/ResultsList/ResultsList.js
  core-ui/src/command-pallette/CommandPalletteUI/ResultsList/ResultsList.scss
  core-ui/src/command-pallette/CommandPalletteUI/components/components.js
  core-ui/src/command-pallette/CommandPalletteUI/components/components.scss
  core-ui/src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/crdHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/helpers.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/index.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/logsHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/nodesHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/nonResourceHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/tests/helpers.test.js
  core-ui/src/command-pallette/CommandPalletteUI/search-history.js
  core-ui/src/command-pallette/CommandPalletteUI/useResourceCache.js
  core-ui/src/command-pallette/CommandPalletteUI/useSearchResults.js
  core-ui/src/components/Nodes/NodeMessages.js
  core-ui/src/components/Predefined/List/RoleBindings.list.js
  core-ui/src/hooks/useCustomMessageListener.js
  core-ui/src/hooks/useEventListener.js
  core-ui/src/index.js
  core-ui/src/index.scss
  core/src/i18n/en.yaml
  core/src/luigi-config/cluster-management/cluster-management.js
  core/src/luigi-config/communication.js
  core/src/luigi-config/navigation/navigation-data-init.js
  resources/web/deployment.yaml
  shared/components/GenericList/GenericList.js
  shared/components/GenericList/SearchInput.js
  shared/hooks/BackendAPI/index.js
  tests/cypress.json
  tests/tests/test-command-palette.spec.js
Labels: size/XXL, lgtm

#808 Introduce Persistent Volume Claims
  core-ui/src/components/Predefined/Create/CustomResourceDefinitions/CustomResourceDefinitons.create.js
  core-ui/src/components/Predefined/Create/PersistentVolumeClaims/PersistentVolumeClaims.create.js
  core-ui/src/components/Predefined/Create/PersistentVolumeClaims/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  core-ui/src/components/Predefined/Details/PersistentVolumeClaims/PersistentVolumeClaims.details.js
  core-ui/src/components/Predefined/Details/PersistentVolumeClaims/RelatedPods.js
  core-ui/src/components/Predefined/Details/Pod/ContainersData.js
  core-ui/src/components/Predefined/Details/ResourcePods.js
  core-ui/src/components/Predefined/Details/StorageClasses/PersistentVolumeClaimsList.js
  core-ui/src/components/Predefined/Details/StorageClasses/PersistentVolumesList.js
  core-ui/src/components/Predefined/Details/StorageClasses/StorageClasses.details.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/PersistentVolumeClaims.list.js
  core-ui/src/components/Predefined/List/index.js
  core-ui/src/hooks/useMessageList.js
  core-ui/src/shared/components/PersistentVolumeClaimStatus.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  shared/components/StatusBadge/StatusBadge.scss
  tests/cypress.json
  tests/fixtures/test-persistent-volume-claim.yaml
  tests/plugins/index.js
  tests/support/loadPVC.js
  tests/tests/test-persistent-volume-claims.spec.js
  tests/tests/test-storage-classes.spec.js
Labels: size/XL, lgtm

#818 Fix bug related to binding Service Instance
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingForm.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#821 Add an option to create/edit applications, also on SKRs
  core-ui/src/components/Predefined/List/Application/Applications.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
  tests/tests/test-protected-resources.spec.js
Labels: size/M, lgtm

#819 Changed delete modal
  core-ui/src/components/Predefined/Details/StorageClasses/StorageClasses.details.js
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  shared/hooks/index.js
  shared/hooks/useDeleteResource.js
  tests/tests/in-cluster-eventing.spec.js
  tests/tests/reduced-permissions.spec.js
  tests/tests/test-cluster-role-bindings.spec.js
  tests/tests/test-custom-resource-definitions.spec.js
  tests/tests/test-namespace-overview.spec.js
  tests/tests/test-service-accounts.spec.js
Labels: size/L, lgtm

#813 Added persistent volumes details, view, edition, tests
  core-ui/src/components/Predefined/Create/PersistentVolumes/PersistentVolumes.create.js
  core-ui/src/components/Predefined/Create/PersistentVolumes/templates.js
  core-ui/src/components/Predefined/Create/index.js
  core-ui/src/components/Predefined/Details/PersistentVolume/PersistentVolumes.details.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/PersistentVolumes.list.js
  core-ui/src/components/Predefined/List/index.js
  core-ui/src/shared/helpers/universalLinks.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  shared/components/StatusBadge/StatusBadge.js
  tests/cypress.json
  tests/fixtures/test-persistent-volumes.yaml
  tests/support/loadPV.js
  tests/tests/test-persistent-volumes.spec.js
Labels: size/L, lgtm

#827 Added links to connected persistent volumes on list view
  core-ui/src/components/Predefined/Details/StorageClasses/PersistentVolumesList.js
  resources/web/deployment.yaml
Labels: enhancement, size/S, lgtm

#828 Repair create name in storage classes
  core-ui/src/components/Predefined/Create/StorageClasses/StorageClasses.create.js
  resources/web/deployment.yaml
Labels: bug, size/XS, lgtm

#816 Improve validation
  core-ui/src/components/Predefined/Create/Subscriptions/FiltersSection.js
  core-ui/src/components/Predefined/Create/Subscriptions/Subscriptions.create.js
  core-ui/src/components/Predefined/Details/Subscriptions/Subscriptions.details.js
  core-ui/src/shared/ResourceForm/components/FormField.js
  core-ui/src/shared/ResourceForm/components/Wrapper.js
  core-ui/src/shared/ResourceForm/fields/MultiInput.js
  core-ui/src/shared/ResourceForm/fields/TextArrayInput.js
  core-ui/src/shared/ResourceForm/inputs/Dropdown.js
  core-ui/src/shared/ResourceForm/inputs/Text.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/K8sNameInput/K8sNameInput.js
  shared/components/ModalWithForm/ModalWithForm.js
  shared/hooks/index.js
  shared/hooks/useValidation.js
Labels: size/L, lgtm

#824 Restart Workload feature
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Predefined/List/DaemonSets.list.js
  core-ui/src/components/Predefined/List/Deployments.list.js
  core-ui/src/components/Predefined/List/StatefulSets.list.js
  core-ui/src/shared/hooks/useRestartResource.js
  core-ui/src/shared/hooks/useShowNodeParamsError.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/GenericList/GenericList.scss
  shared/components/ListActions/ListActions.js
Labels: size/M, lgtm

#829 Fix Service Class links, add tooltips
  core-ui/src/components/Predefined/Details/PersistentVolume/PersistentVolumeStatus.js
  core-ui/src/components/Predefined/Details/PersistentVolume/PersistentVolumes.details.js
  core-ui/src/components/Predefined/Details/PersistentVolumeClaims/PersistentVolumeClaims.details.js
  core-ui/src/components/Predefined/List/PersistentVolumes.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: bug, size/L, lgtm

#826 Events
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodeMessages.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/components/Nodes/NodeDetails/NodeDetails.js
  core-ui/src/components/Nodes/NodeMessages.js
  core-ui/src/components/Predefined/Details/Events.details.js
  core-ui/src/components/Predefined/Details/HPA/HPA.details.js
  core-ui/src/components/Predefined/Details/Namespace/Namespace.details.js
  core-ui/src/components/Predefined/Details/PersistentVolume/PersistentVolumes.details.js
  core-ui/src/components/Predefined/Details/PersistentVolumeClaims/PersistentVolumeClaims.details.js
  core-ui/src/components/Predefined/Details/Pod/Pod.details.js
  core-ui/src/components/Predefined/Details/StorageClasses/StorageClasses.details.js
  core-ui/src/components/Predefined/Details/index.js
  core-ui/src/components/Predefined/List/Events.list.js
  core-ui/src/components/Predefined/List/PersistentVolumes.list.js
  core-ui/src/hooks/useMessageList.js
  core-ui/src/shared/components/EventsList.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/smoke-tests.spec.js
  tests/tests/test-HPA.spec.js
  tests/tests/test-cluster-overview.spec.js
  tests/tests/test-events.spec.js
  tests/tests/test-persistent-volume-claims.spec.js
  tests/tests/test-persistent-volumes.spec.js
Labels: size/XL, lgtm

#823 fix monaco bugs in namespace creation
  core-ui/src/components/Predefined/Create/Namespaces/Namespaces.create.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/fields/Editor.js
  core-ui/src/shared/useHasChanged.js
  resources/web/deployment.yaml
  tests/tests/test-custom-resource-definitions.spec.js
Labels: size/M, lgtm

#836 Changed icon and remove unnecesary import
  resources/web/deployment.yaml
  shared/components/ResourcesList/ResourcesList.js
  shared/contexts/YamlEditorContext/EditorActions.js
Labels: size/XS, lgtm

#825 Fix roles submit button disable state
  core-ui/src/components/Predefined/Create/Roles/GenericRoleCreate.js
  core-ui/src/components/Predefined/Create/Roles/RuleInput.js
  core-ui/src/components/Predefined/Create/Roles/useResourcesForApiGroups.js
  core-ui/src/shared/ResourceForm/fields/ComboboxArrayInput.js
  core-ui/src/shared/ResourceForm/inputs/ComboboxInput.js
  core-ui/src/shared/useComponentDidMount.js
  resources/web/deployment.yaml
  tests/tests/run-after.spec.js
  tests/tests/test-dns-providers.spec.js
  tests/tests/test-replica-sets.spec.js
  tests/tests/test-statefulsets.spec.js
Labels: size/M, lgtm

#844 Fix redirection after application deletion
  core-ui/src/components/Predefined/Details/Application/ApplicationServicesDetails/ApplicationServicesDetails.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/support/views/functions-view.js
Labels: bug, size/XS, lgtm

#846 Repair name singular
  core-ui/src/components/Predefined/Create/CustomResourceDefinitions/CustomResourceDefinitons.create.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#845 Show Kyma Version on Docker build
  Dockerfile.local
  tests/cypress-smoke.json
Labels: size/XS, lgtm

#850 Fix addons' name input
  core-ui/src/components/Lambdas/components/FormInput/FormInput.scss
  core-ui/src/components/Predefined/Details/PersistentVolume/PersistentVolumes.details.js
  core-ui/src/components/Predefined/Details/PersistentVolumeClaims/PersistentVolumeClaims.details.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: bug, size/M, lgtm

#873 Disable readonly mode in catalog
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/CreateServiceBindingModal.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Configuration/ServiceBindings/ServiceBindings.js
  resources/web/configmap.yaml
  resources/web/deployment.yaml
  service-catalog-ui/src/components/ServiceClassDetails/ServiceClassDetails.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingModal.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/CreateServiceBindingUsageForm/CreateServiceBindingUsageModal.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceBindings/ServiceInstanceBindings.js
  service-catalog-ui/src/components/ServiceInstanceDetails/ServiceInstanceHeader/ServiceInstanceHeader.js
  service-catalog-ui/src/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceTable.js
Labels: size/L, lgtm

#875 Add confirmation to the deletion of clusters and env variables
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/CreateVariable/CreateVariable.js
  core-ui/src/components/Lambdas/LambdaDetails/Tabs/Code/LambdaVariables/LambdaVariables.js
  core-ui/src/components/Predefined/List/Events.list.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  shared/components/ResourceDetails/ResourceDetails.js
  shared/components/ResourcesList/ResourcesList.js
  shared/hooks/useDeleteResource.js
  tests/tests/reduced-permissions.spec.js
Labels: bug, size/L, lgtm

#877 Change protected resources icon
  resources/web/deployment.yaml
  shared/hooks/useProtectedResources.js
Labels: size/XS, lgtm

#859 Handle deep linking with kubeconfig ID, figz #841
  core/src/luigi-config/cluster-management/cluster-management.js
  core/src/luigi-config/kubeconfig-id/index.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/navigation/previous-location.js
  resources/web/deployment.yaml
  tests/support/login-commands.js
  tests/tests/add-cluster-disabled.spec.js
  tests/tests/login-kubeconfigID.spec.js
  tests/tests/reduced-permissions.spec.js
Labels: size/L, lgtm

#880 Deprecate nodejs12
  core-ui/src/components/Lambdas/constants.js
  core-ui/src/components/Lambdas/helpers/runtime/test/runtime.test.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#872 Plural form of some of the options in Cron Job, Job, Gateway, Oath2 Client, and DNE Entry views
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/support/login-commands.js
  tests/tests/add-cluster-disabled.spec.js
  tests/tests/invalid-kubeconfig.spec.js
  tests/tests/multiple-context-kubeconfig.spec.js
  tests/tests/other-logins.spec.js
Labels: size/M, lgtm

#881 Fix small buttons on namespace details
  core-ui/src/components/Predefined/Details/Namespace/DeployNewWorkload.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#871 Show Helm release on Secret details
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/HelmReleases/ChartContent.js
  core-ui/src/components/HelmReleases/HelmReleaseData.js
  core-ui/src/components/HelmReleases/HelmReleaseStatus.js
  core-ui/src/components/HelmReleases/ReleaseDataPanel.js
  core-ui/src/components/HelmReleases/decodeHelmRelease.js
  core-ui/src/components/HelmReleases/tests/HelmReleaseData.test.js
  core-ui/src/components/HelmReleases/tests/ReleaseDataPanel.test.js
  core-ui/src/components/Predefined/Details/Secret/Secret.details.js
  core-ui/src/shared/components/ReadonlyEditorPanel.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#883 Introduce edit cluster option on the cluster list
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Clusters/views/EditCluster/AuthenticationDropdown.js
  core-ui/src/components/Clusters/views/EditCluster/EditCluster.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/edit-cluster.spec.js
Labels: size/L, lgtm

#889 Split function tests
  tests/cypress.json
  tests/support/views/functions-view.js
  tests/tests/create-an-api-rule.spec.js
  tests/tests/create-functions.spec.js
  tests/tests/in-cluster-eventing.spec.js
Labels: size/L, lgtm

#887 Skip remaining e2e tests when a test fails
  tests/plugins/index.js
  tests/support/commands.js
  tests/tests/add-cluster-disabled.spec.js
  tests/tests/certificates.spec.js
  tests/tests/cluster-configuration.spec.js
  tests/tests/create-a-deployment.spec.js
  tests/tests/create-a-role.spec.js
  tests/tests/create-an-api-rule.spec.js
  tests/tests/create-configuration-resources.spec.js
  tests/tests/download-a-kubeconfig.spec.js
  tests/tests/edit-cluster.spec.js
  tests/tests/in-cluster-eventing.spec.js
  tests/tests/invalid-kubeconfig.spec.js
  tests/tests/kyma-version.spec.js
  tests/tests/login-kubeconfigID.spec.js
  tests/tests/multiple-context-kubeconfig.spec.js
  tests/tests/other-logins.spec.js
  tests/tests/reduced-permissions.spec.js
  tests/tests/run-after.spec.js
  tests/tests/run-before.spec.js
  tests/tests/smoke-tests.spec.js
  tests/tests/test-HPA.spec.js
  tests/tests/test-application.spec.js
  tests/tests/test-cluster-overview.spec.js
  tests/tests/test-cluster-role-bindings.spec.js
  tests/tests/test-command-palette.spec.js
  tests/tests/test-cron-jobs.spec.js
  tests/tests/test-custom-resource-definitions.spec.js
  tests/tests/test-daemon-sets.spec.js
  tests/tests/test-dashboard-version.spec.js
  tests/tests/test-destination-rules.spec.js
  tests/tests/test-dns-entries.spec.js
  tests/tests/test-dns-providers.spec.js
  tests/tests/test-events.spec.js
  tests/tests/test-gateways.spec.js
  tests/tests/test-git-repositories.spec.js
  tests/tests/test-ingresses.spec.js
  tests/tests/test-issuers.spec.js
  tests/tests/test-jobs.spec.js
  tests/tests/test-namespace-overview.spec.js
  tests/tests/test-oauth2.spec.js
  tests/tests/test-persistent-volume-claims.spec.js
  tests/tests/test-persistent-volumes.spec.js
  tests/tests/test-protected-resources.spec.js
  tests/tests/test-replica-sets.spec.js
  tests/tests/test-secrets.spec.js
  tests/tests/test-service-accounts.spec.js
  tests/tests/test-statefulsets.spec.js
  tests/tests/test-storage-classes.spec.js
  tests/tests/test-virtual-services.spec.js
  tests/tests/test.settings.spec.js
Labels: size/L, lgtm

#891 Change default timeouts and removed manual timeouts in tests
  tests/cypress-smoke.json
  tests/cypress.json
  tests/tests/create-a-deployment.spec.js
  tests/tests/create-a-role.spec.js
  tests/tests/test-HPA.spec.js
  tests/tests/test-daemon-sets.spec.js
  tests/tests/test-dashboard-version.spec.js
  tests/tests/test-destination-rules.spec.js
  tests/tests/test-dns-providers.spec.js
  tests/tests/test-ingresses.spec.js
  tests/tests/test-jobs.spec.js
  tests/tests/test-namespace-overview.spec.js
  tests/tests/test-persistent-volume-claims.spec.js
  tests/tests/test-persistent-volumes.spec.js
  tests/tests/test-protected-resources.spec.js
  tests/tests/test-replica-sets.spec.js
  tests/tests/test-service-accounts.spec.js
  tests/tests/test.settings.spec.js
Labels: size/M, lgtm

#895 Fix css in timeframe-fn-logs
  core-ui/src/components/Predefined/Details/Pod/ContainersLogs.js
  core-ui/src/components/Predefined/Details/Pod/ContainersLogs.scss
  resources/web/deployment.yaml
Labels: size/S, lgtm

#878 allow importing multiple contexts
  core-ui/src/components/Clusters/components/AddClusterWizard.js
  core-ui/src/components/Clusters/components/AuthForm.js
  core-ui/src/components/Clusters/components/ContextChooser/ContextChooser.js
  core-ui/src/components/Clusters/shared.js
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Clusters/views/EditCluster/EditCluster.js
  core/src/i18n/en.yaml
  core/src/luigi-config/cluster-management/cluster-management.js
  core/src/luigi-config/communication.js
  core/src/luigi-config/kubeconfig-id/index.js
  core/src/luigi-config/navigation/navigation-data-init.js
  resources/web/deployment.yaml
  tests/support/loadKubeconfigFile.js
  tests/tests/download-a-kubeconfig.spec.js
  tests/tests/edit-cluster.spec.js
  tests/tests/multiple-context-kubeconfig.spec.js
  tests/tests/other-logins.spec.js
  tests/tests/reduced-permissions.spec.js
Labels: size/L, lgtm

#885 Helm Releases nav node
  core-ui/src/command-pallette/CommandPalletteUI/ResultsList/ResultsList.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/crdHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/helmReleaseHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/helpers.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/index.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/logsHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/nodesHandler.js
  core-ui/src/components/App/App.js
  core-ui/src/components/HelmReleases/ChartContent.js
  core-ui/src/components/HelmReleases/HelmReleaseData.js
  core-ui/src/components/HelmReleases/HelmReleaseDataPanel.scss
  core-ui/src/components/HelmReleases/HelmReleaseStatus.js
  core-ui/src/components/HelmReleases/HelmReleasesDetails.js
  core-ui/src/components/HelmReleases/HelmReleasesList.js
  core-ui/src/components/HelmReleases/OtherReleaseVersions.js
  core-ui/src/components/HelmReleases/ReleaseDataPanel.js
  core-ui/src/components/HelmReleases/findRecentRelease.js
  core-ui/src/components/HelmReleases/tests/HelmReleaseData.test.js
  core-ui/src/components/Predefined/Details/Secret/Secret.details.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/cypress.json
  tests/tests/smoke-tests.spec.js
  tests/tests/test-namespace-overview.spec.js
Labels: size/XL, lgtm
