Repository kyma-project/busola, pull requests merged in 2022-12, with the labels that each got.

#2082 Apirules never ending story
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/components/ResourceList.js
  core-ui/src/resources/Services/ApiRulesList.js
  core-ui/src/resources/Services/ServiceDetails.js
  core-ui/src/shared/components/SubscriptionsList.js
  examples/resources/gateway/apirules.yaml
  examples/resources/serverless/functions.yaml
  resources/web/deployment.yaml
  tests/tests/namespace/test-api-rules.spec.js
  tests/tests/namespace/test-in-cluster-eventing.spec.js
Labels: size/M, lgtm

#2089 Luigiless lists
  core-ui/src/resources/createResourceRoutes.js
  core-ui/src/resources/helpers.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
Labels: size/M

#2087 Luigiless cluster link
  core-ui/src/components/Clusters/views/ClusterOverview/clusterDetailsNode.ts
  core-ui/src/hooks/useUrl.ts
  core-ui/src/resources/createResourceRoutes.js
  core-ui/src/sidebar/NavItem.tsx
  core-ui/src/state/types.ts
Labels: size/M, lgtm

#2092 Luigiless details
  core-ui/src/header/Header.scss
  core-ui/src/resources/helpers.js
  core-ui/src/shared/components/ResourceGraph/ResourceGraph.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
Labels: size/S

#2069 fix async enums
  core-ui/src/components/Extensibility/components-form/StringRenderer.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#2093 Remove SSO
  backend/index.js
  backend/jwtCheck.js
  backend/package-lock.json
  backend/package.json
  backend/settings/defaultConfig.yaml
  core-ui/src/shared/hooks/BackendAPI/checkForTokenExpiration.ts
  core-ui/src/shared/hooks/BackendAPI/createHeaders.ts
  core-ui/src/shared/hooks/BackendAPI/useFetch.ts
  core-ui/src/state/clusterConfigSelector.ts
  core-ui/src/state/ssoDataAtom.ts
  core-ui/src/state/types.ts
  core-ui/src/state/utils/getFetchFn.ts
  docs/features.md
  package-lock.json
  package.json
  resources/web/configmap.yaml
Labels: size/L

#2097 Fix actions in general for list view
  core-ui/src/components/Extensibility/ExtensibilityList.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2098 Fix extensibility lists
  core-ui/src/components/App/App.js
  core-ui/src/components/App/ClusterRoutes.js
  core-ui/src/components/App/ExtensibilityRoutes.js
  core-ui/src/components/App/NamespaceRoutes.js
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/components/ResourceList.js
  core-ui/src/components/Extensibility/useGetCRbyPath.js
  core-ui/src/resources/helpers.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core-ui/src/state/navigation/extensibilityNodeAtom.ts
  core-ui/src/state/navigation/extensibilityNodesSelector.ts
  core-ui/src/state/navigation/sidebarNavigationNodesSelector.ts
Labels: size/L

#2099 HandleResetEndpoint
  core-ui/src/components/App/App.js
  core-ui/src/components/Clusters/shared.ts
Labels: size/S, lgtm

#2101 luigiless url navigation / handling
  core-ui/src/components/App/App.js
  core-ui/src/components/App/ClusterRoutes.js
  core-ui/src/components/App/NamespaceRoutes.js
  core-ui/src/components/Extensibility/useGetCRbyPath.js
  core-ui/src/header/Header.tsx
  core-ui/src/header/NamespaceDropdown/NamespaceDropdown.tsx
  core-ui/src/hooks/useUrl.js
  core-ui/src/hooks/useUrl.ts
  core-ui/src/resources/helpers.js
  core-ui/src/sidebar/NavItem.tsx
  core-ui/src/state/types.ts
Labels: size/L

#2103 Use recoil state instead of luigi context
  core-ui/src/components/App/resourceSchemas/useResourceSchemas.ts
  core-ui/src/components/Clusters/components/AddClusterWizard.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
  core-ui/src/components/Clusters/views/ClusterOverview/useGetVersions.js
Labels: size/M

#2104 remove useFeature
  core-ui/src/components/BusolaExtensions/BusolaExtensionDetails.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/ResourceCommitment.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/useMetricsQuery.js
  core-ui/src/components/Nodes/NodeDetails/NodeDetails.js
  core-ui/src/hooks/useFeature.ts
  core-ui/src/hooks/useVersionWarning.js
  core-ui/src/shared/components/StatsGraph/StatsPanel.js
  core-ui/src/shared/hooks/useFeature.js
  core-ui/src/shared/hooks/usePrometheus.js
Labels: size/M, lgtm

#2105 remove context from some places
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/command-pallette/CommandPalletteUI/CommandPaletteUI.js
  core-ui/src/components/App/App.js
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
  core-ui/src/components/Extensibility/components/EventList.js
  core-ui/src/components/Extensibility/components/ResourceList.js
  core-ui/src/components/HelmReleases/HelmReleasesDetails.js
  core-ui/src/components/HelmReleases/HelmReleasesList.js
  core-ui/src/components/NoPermissions/NoPermissions.js
  core-ui/src/hooks/tracking.ts
  core-ui/src/hooks/useHasPermissionsFor.js
  core-ui/src/hooks/useSentry.js
  core-ui/src/hooks/useVersionWarning.js
  core-ui/src/resources/ClusterRoles/ClusterRoleCreate.js
  core-ui/src/resources/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  core-ui/src/resources/CustomResourceDefinitions/CustomResources.details.js
  core-ui/src/resources/CustomResourceDefinitions/useNavigateToCustomResource.js
  core-ui/src/resources/DaemonSets/DaemonSetCreate.js
  core-ui/src/resources/DestinationRules/DestinationRuleCreate.js
  core-ui/src/resources/HorizontalPodAutoscalers/HPASubcomponent.js
  core-ui/src/resources/HorizontalPodAutoscalers/HorizontalPodAutoscalerCreate.js
  core-ui/src/resources/Ingresses/IngressCreate.js
  core-ui/src/resources/Ingresses/Rules.js
  core-ui/src/resources/LimitRanges/LimitRangeCreate.js
  core-ui/src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
  core-ui/src/resources/Namespaces/YamlUpload/useUploadResources.js
  core-ui/src/resources/NetworkPolicies/NetworkPolicyCreate.js
  core-ui/src/resources/Pods/PodCreate.js
  core-ui/src/resources/ResourceQuotas/ResourceQuotaCreate.js
  core-ui/src/resources/Roles/RoleCreate.js
  core-ui/src/resources/Roles/RuleInput.js
  core-ui/src/resources/Roles/useResourcesForApiGroups.js
  core-ui/src/resources/Secrets/SecretCreate.js
  core-ui/src/resources/Secrets/SecretForm.js
  core-ui/src/resources/ServiceAccounts/useDownloadSecretKubeconfig.tsx
  core-ui/src/resources/Services/ApiRulesList.js
  core-ui/src/resources/Services/ServiceCreate.js
  core-ui/src/resources/Services/ServiceDetails.js
  core-ui/src/resources/StatefulSets/StatefulSetCreate.js
  core-ui/src/resources/helpers.js
  core-ui/src/shared/ResourceForm/useCreateResource.js
  core-ui/src/shared/components/ControlledBy/ControlledBy.js
  core-ui/src/shared/components/LogsLink/LogsLink.js
  core-ui/src/shared/components/ResourceGraph/ResourceGraph.js
  core-ui/src/shared/components/ResourceGraph/useRelatedResources.js
  core-ui/src/shared/hooks/BackendAPI/useGet.js
  core-ui/src/shared/hooks/useIsInCurrentNamespace.js
  core-ui/src/shared/hooks/useIsInCurrentNamespace.ts
  core-ui/src/shared/hooks/useProtectedResources.js
  core-ui/src/shared/hooks/useSidecarInjection.js
  core-ui/src/state/navigation/clusterAndNsNodesSelector.ts
  core-ui/src/types/index.ts
  core-ui/src/types/kubeconfig.ts
Labels: size/L

#2100 Storage
  core-ui/src/components/Clusters/components/AddClusterWizard.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
  core-ui/src/state/clusterAtom.ts
  core-ui/src/state/clustersAtom.ts
  core-ui/src/state/utils/effects.ts
Labels: size/M, lgtm

#2045 remove destination rules from core-ui
  core-ui/src/resources/DestinationRules/ConnectionPoolHTTP.js
  core-ui/src/resources/DestinationRules/ConnectionPoolTCP.js
  core-ui/src/resources/DestinationRules/DestinationRuleCreate.js
  core-ui/src/resources/DestinationRules/DestinationRuleDetails.js
  core-ui/src/resources/DestinationRules/DestinationRuleList.js
  core-ui/src/resources/DestinationRules/DestinationRuleRefs.js
  core-ui/src/resources/DestinationRules/DestinationRuleRefs.scss
  core-ui/src/resources/DestinationRules/LoadBalancer.js
  core-ui/src/resources/DestinationRules/OutlierDetection.js
  core-ui/src/resources/DestinationRules/Subset.js
  core-ui/src/resources/DestinationRules/TlsSettings.js
  core-ui/src/resources/DestinationRules/TrafficPolicy.js
  core-ui/src/resources/DestinationRules/index.js
  core-ui/src/resources/DestinationRules/templates.js
  core-ui/src/resources/index.js
  core/src/i18n/en.yaml
  core/src/luigi-config/customResources.js
  core/src/luigi-config/customResources/destinationRules/.gitignore
  core/src/luigi-config/customResources/destinationRules/details/connectionPool.mjs
  core/src/luigi-config/customResources/destinationRules/details/index.mjs
  core/src/luigi-config/customResources/destinationRules/details/loadBalancer.mjs
  core/src/luigi-config/customResources/destinationRules/details/outlierDetection.mjs
  core/src/luigi-config/customResources/destinationRules/details/portLevelSettings.mjs
  core/src/luigi-config/customResources/destinationRules/details/subsets.mjs
  core/src/luigi-config/customResources/destinationRules/details/tls.mjs
  core/src/luigi-config/customResources/destinationRules/details/trafficPolicy.mjs
  core/src/luigi-config/customResources/destinationRules/details/tunnel.mjs
  core/src/luigi-config/customResources/destinationRules/form/index.mjs
  core/src/luigi-config/customResources/destinationRules/form/subsets.mjs
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/connectionPool.mjs
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/loadBalancer.mjs
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/outlierDetection.mjs
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/portLevelSettings.mjs
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/tls.mjs
  core/src/luigi-config/customResources/destinationRules/form/trafficPolicy/tunnel.mjs
  core/src/luigi-config/customResources/destinationRules/generator.mjs
  core/src/luigi-config/customResources/destinationRules/index.mjs
  core/src/luigi-config/customResources/destinationRules/translations.mjs
  core/src/luigi-config/customResources/index.js
  core/src/luigi-config/navigation/static-navigation-model.js
  examples/resources/istio/destination-rules.yaml
  resources/web/deployment.yaml
  tests/fixtures/test-custom-destination-rule.yaml
  tests/tests/namespace/test-destination-rules.spec.js
Labels: size/XXL, lgtm

#2107 Command palette luigiless
  core-ui/src/command-pallette/CommandPaletteProvider.js
  core-ui/src/command-pallette/CommandPaletteProvider.tsx
  core-ui/src/command-pallette/CommandPalletteUI/CommandPaletteUI.tsx
  core-ui/src/command-pallette/CommandPalletteUI/ResultsList/Result.tsx
  core-ui/src/command-pallette/CommandPalletteUI/ResultsList/ResultsList.tsx
  core-ui/src/command-pallette/CommandPalletteUI/components/components.tsx
  core-ui/src/command-pallette/CommandPalletteUI/handlers/helmReleaseHandler.ts
  core-ui/src/command-pallette/CommandPalletteUI/handlers/index.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/index.ts
  core-ui/src/command-pallette/CommandPalletteUI/handlers/nodesHandler.ts
  core-ui/src/command-pallette/CommandPalletteUI/handlers/nonResourceHandler.ts
  core-ui/src/command-pallette/CommandPalletteUI/types.ts
  core-ui/src/command-pallette/CommandPalletteUI/useResourceCache.js
  core-ui/src/command-pallette/CommandPalletteUI/useSearchResults.tsx
  core-ui/src/shared/components/Spinner/Spinner.tsx
Labels: do-not-merge/work-in-progress, size/XL, lgtm

#2110 Luigiless customUrl + CRDs
  core-ui/src/components/BusolaExtensions/BusolaExtensionList.js
  core-ui/src/components/CustomResources/CustomResourcesByGroup.js
  core-ui/src/hooks/useUrl.ts
  core-ui/src/resources/other/BusolaExtensions.routes.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
Labels: size/M

#2109 add apiGroupsState
  core-ui/src/hooks/useVersionWarning.ts
  core-ui/src/resources/ClusterRoles/ClusterRoleCreate.js
  core-ui/src/resources/DnsProviders/index.js
  core-ui/src/resources/OAuth2Clients/index.js
  core-ui/src/resources/Roles/RoleCreate.js
  core-ui/src/resources/Roles/RuleInput.js
  core-ui/src/resources/Roles/useResourcesForApiGroups.js
  core-ui/src/resources/Secrets/SecretCreate.js
  core-ui/src/resources/Secrets/helpers.js
  core-ui/src/resources/Secrets/index.js
  core-ui/src/shared/helpers/getResourceDefs.js
  core-ui/src/state/discoverability/apiGroupsSelector.ts
  core-ui/src/state/discoverability/groupVersionsSelector.ts
Labels: size/L, lgtm

#2112 Luigi/last contexts
  core-ui/public/config/defaultConfig.yaml
  core-ui/src/components/Extensibility/components/ResourceList.js
  core-ui/src/resources/Services/ApiRulesList.js
  core-ui/src/resources/helpers.js
  core-ui/src/shared/components/ResourceGraph/getResourceGraphConfig.js
  core-ui/src/shared/components/ResourceGraph/useRelatedResources.js
  core-ui/src/shared/helpers/getResourceDefs.js
Labels: size/M

#2113 Luigiless crds
  core-ui/src/components/CustomResources/CustomResources.js
  core-ui/src/resources/CustomResourceDefinitions/CRCreate.js
  core-ui/src/resources/CustomResourceDefinitions/useCustomResourceUrl.js
  core-ui/src/resources/CustomResourceDefinitions/useNavigateToCustomResource.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
Labels: size/L

#2095 Fix kk-id path, no permissions view, universal redirection
  core-ui/src/components/App/App.js
  core-ui/src/components/App/ClusterRoutes.js
  core-ui/src/components/App/useLoginWithKubeconfigID.ts
  core-ui/src/components/Clusters/shared.ts
  core-ui/src/components/NoPermissions/NoPermissions.tsx
  core-ui/src/index.js
  core-ui/src/sidebar/Sidebar.tsx
  core-ui/src/state/authDataAtom.ts
  core-ui/src/state/configurationAtom.ts
  core-ui/src/state/permissionSetsSelector.ts
  core-ui/src/state/useAfterInitHook.ts
Labels: size/L

#2023 Extensibility UI - ui-schema version
  core-ui/src/components/BusolaExtensions/BusolaExtensionDetails.js
  core-ui/src/components/BusolaExtensions/SectionEditor.js
  core-ui/src/components/Extensibility/components-form/Jsonata.js
  core-ui/src/components/Extensibility/components-form/MultiType.js
  core-ui/src/components/Extensibility/components-form/StringRenderer.js
  core-ui/src/components/Extensibility/components-form/index.js
  core/src/assets/customResources/schema-dataSources.yaml
  core/src/assets/customResources/schema-details.json
  core/src/assets/customResources/schema-details.yaml
  core/src/assets/customResources/schema-form.json
  core/src/assets/customResources/schema-form.yaml
  core/src/assets/customResources/schema-general.yaml
  core/src/assets/customResources/schema-list.json
  core/src/assets/customResources/schema-list.yaml
  core/src/assets/customResources/schema-navigation.json
  core/src/assets/customResources/schema-resource.json
  core/src/i18n/en.yaml
  core/src/luigi-config/customResources.js
  docs/extensibility/resources.md
  resources/web/deployment.yaml
Labels: size/XXL, lgtm

#2114 Small fix for resource lists
  core-ui/src/components/Extensibility/components/ResourceList.js
  examples/pizzas/configuration/pizzas-configmap.yaml
Labels: size/S

#2111 Cmd palette handlers
  core-ui/src/command-pallette/CommandPalletteUI/components/components.tsx
  core-ui/src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.ts
  core-ui/src/command-pallette/CommandPalletteUI/handlers/crHandler.ts
  core-ui/src/command-pallette/CommandPalletteUI/handlers/crListHandler.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/crListHandler.ts
  core-ui/src/command-pallette/CommandPalletteUI/handlers/crdHandler.ts
  core-ui/src/command-pallette/CommandPalletteUI/handlers/helmReleaseHandler.ts
  core-ui/src/command-pallette/CommandPalletteUI/handlers/helpers.js
  core-ui/src/command-pallette/CommandPalletteUI/handlers/helpers.ts
  core-ui/src/command-pallette/CommandPalletteUI/handlers/index.ts
  core-ui/src/command-pallette/CommandPalletteUI/handlers/logsHandler.ts
  core-ui/src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.ts
  core-ui/src/command-pallette/CommandPalletteUI/handlers/nodesHandler.ts
  core-ui/src/command-pallette/CommandPalletteUI/handlers/nonResourceHandler.ts
  core-ui/src/command-pallette/CommandPalletteUI/types.ts
  core-ui/src/shared/constants.ts
  core-ui/src/types/index.ts
  package-lock.json
  package.json
Labels: size/XXL

#2115 Tests
  tests/package-lock.json
  tests/support/commands.js
  tests/support/login-commands.js
  tests/tests/cluster/run-before.spec.js
  tests/tests/cluster/test-applications.spec.js
  tests/tests/cluster/test-cluster-overview.spec.js
  tests/tests/cluster/test-download-a-kubeconfig.spec.js
  tests/tests/cluster/test-edit-cluster.spec.js
  tests/tests/cluster/test-gardener-provider.spec.js
  tests/tests/cluster/test-kyma-version.spec.js
Labels: size/XXL, lgtm

#2117 clean up crds
  core-ui/src/components/CustomResources/CRDList.js
  core-ui/src/components/CustomResources/CustomResources.js
  core-ui/src/resources/CustomResourceDefinitions/CustomResourceDefinitionVersions.js
  core-ui/src/resources/CustomResourceDefinitions/RelatedCRDsList.js
  core-ui/src/resources/other/CustomResourceDefinitions.routes.js
Labels: size/L

#2118 adjust dashboard version and added dataTestId prop
  core-ui/src/shared/components/Link/Link.tsx
  core-ui/src/sidebar/Footer/Footer.tsx
  tests/tests/cluster/test-dashboard-version.spec.js
  tests/tests/cluster/test-other-login-options.spec.js
Labels: size/S

#2120 Luigiless remove navigateFn/fixedUrl
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/components/ResourceList.js
  core-ui/src/hooks/useUrl.ts
  core-ui/src/resources/CronJobs/CronJobJobs.js
  core-ui/src/resources/CustomResourceDefinitions/RelatedCRDsList.js
  core-ui/src/resources/Events/EventList.js
  core-ui/src/resources/PersistentVolumeClaims/PersistentVolumeClaimDetails.js
  core-ui/src/resources/ServiceAccounts/GenericSecrets.js
  core-ui/src/resources/ServiceInstances/ServiceBindingList.js
  core-ui/src/resources/Services/ApiRulesList.js
  core-ui/src/resources/StorageClasses/PersistentVolumeClaimsList.js
  core-ui/src/resources/StorageClasses/PersistentVolumesList.js
  core-ui/src/shared/components/RelatedPods.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core-ui/src/shared/components/SubscriptionsList.js
  core/src/assets/customResources/schema-dataSources.yaml
  core/src/assets/customResources/schema-details.yaml
  core/src/assets/customResources/schema-form.yaml
  core/src/assets/customResources/schema-general.yaml
  core/src/assets/customResources/schema-list.yaml
Labels: size/XXL

#2121 Handle Prometheus feature requests
  core-ui/src/components/App/App.tsx
  core-ui/src/components/App/useLoginWithKubeconfigID.ts
  core-ui/src/components/Clusters/components/AddClusterWizard.js
  core-ui/src/hooks/useFeature.ts
  core-ui/src/resources/Secrets/SecretCreate.js
  core-ui/src/state/configuration/configurationAtom.ts
  core-ui/src/state/configuration/featureChecks.ts
  core-ui/src/state/configuration/getFeatures.ts
  core-ui/src/state/configuration/prometheusFeature.ts
  core-ui/src/state/discoverability/apiGroupsSelector.ts
  core-ui/src/state/navigation/availableNodesSelector.ts
  core-ui/src/state/navigation/clusterAndNsNodesSelector.ts
  core-ui/src/state/navigation/externalNodesSelector.ts
  core-ui/src/state/navigation/sidebarNavigationNodesSelector.ts
  core-ui/src/state/types.ts
  core-ui/tsconfig.json
Labels: size/L

#2131 Luigiless extension editor
  core-ui/public/schemas/schema-dataSources.yaml
  core-ui/public/schemas/schema-details.yaml
  core-ui/public/schemas/schema-form.yaml
  core-ui/public/schemas/schema-general.yaml
  core-ui/public/schemas/schema-list.yaml
  core-ui/src/components/App/App.tsx
  core-ui/src/components/BusolaExtensions/BusolaExtensionDetails.js
  core-ui/src/components/Preferences/Preferences.tsx
  core-ui/src/hooks/useCustomMessageListener.js
  core-ui/src/index.js
  core-ui/src/resources/Ingresses/DefaultBackendPanel.js
  core-ui/src/resources/Ingresses/Rules.js
  core-ui/src/shared/components/GenericList/SearchInput.js
  core-ui/src/shared/components/Modal/Modal.js
  core-ui/src/shared/components/ModalWithForm/ModalWithForm.js
  core-ui/src/shared/components/PageHeader/PageHeader.js
  core-ui/src/shared/components/ResourceDetails/tests/ResourceDetails.test.js
  core-ui/src/shared/contexts/Microfrontend.js
  core-ui/src/shared/contexts/MicrofrontendContext.js
  core-ui/src/shared/contexts/YamlEditorContext/YamlEditorContext.js
  core-ui/src/state/extensibilitySchemasAtom.ts
Labels: size/XXL

#2124 fix Unit tests
  core-ui/src/components/Extensibility/components/Table.js
  core-ui/src/components/Extensibility/components/tests/ControlledBy.test.js
  core-ui/src/components/Extensibility/components/tests/ResourceLink.test.js
  core-ui/src/components/Extensibility/components/tests/Table.test.js
  core-ui/src/components/Extensibility/components/tests/Widget.copyable.test.js
  core-ui/src/components/Extensibility/components/tests/Widget.test.js
  core-ui/src/components/Extensibility/components/tests/helpers.tsx
  core-ui/src/components/Extensibility/tests/useGetCRDByPath.test.js
  core-ui/src/components/HelmReleases/tests/ReleaseDataPanel.test.js
  core-ui/src/shared/components/ControlledBy/test/ControlledBy.test.js
  core-ui/src/shared/components/PageHeader/test/PageHeader.test.js
  core-ui/src/shared/components/ResourceDetails/tests/ResourceDetails.test.js
  core-ui/src/shared/components/ResourceNotFound/test/ResourceNotFound.test.js
  core-ui/src/testing/enzymeUtils.tsx
  core-ui/src/testing/reactTestingUtils.tsx
Labels: kind/bug, size/XL, lgtm

#2134 Handle incorrect path
  core-ui/public/i18n/en.yaml
  core-ui/src/components/App/App.tsx
  core-ui/src/components/App/ClusterRoutes.js
  core-ui/src/components/App/IncorrectPath.js
  core-ui/src/components/App/NamespaceRoutes.js
  core-ui/src/hooks/useUrl.ts
Labels: size/M

#2132 fix $item in defaultValue
  core-ui/src/components/Extensibility/hooks/useVariables.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2137 Fix Sentry 12.12.2022
  core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#2091 create configmap for dns-providers
  examples/resources/configuration/dns-providers.yaml
Labels: size/L, lgtm

#2138 Fix busola in docker image
  Dockerfile.local
  backend/index.js
  core-ui/Makefile
  core-ui/config-overrides.js
  core-ui/package.json
Labels: size/S

#2143 Luigiless luigiclient
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/EntryNotFound/EntryNotFound.js
  core-ui/src/resources/ServiceBindings/ServiceBindingData.js
  core-ui/src/setupTests.js
  core-ui/src/shared/hooks/useShowNodeParamsError.js
Labels: size/L

#2147 update functions to include function templates on language change
  examples/resources/serverless/functions.yaml
Labels: size/M, lgtm

#2146 fix reset vars
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  resources/web/deployment.yaml
  tests/tests/namespace/run-prepare-functions.spec.js
Labels: size/S, lgtm

#2166 Fix widget resource for vars
  core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#2175 fix for missing extensions call
  core-ui/public/config/defaultConfig.yaml
  core-ui/src/state/navigation/extensionsAtom.ts
  docs/extensibility/README.md
  gulpfile.js
  resources/web/deployment.yaml
  tests/tests/cluster/test-cluster-configuration.spec.js
Labels: size/S, lgtm

#2177 fix extensions
  core-ui/src/state/navigation/extensionsAtom.ts
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2178 Fix double navigation
  core-ui/src/resources/OAuth2Clients/index.js
  core-ui/src/state/navigation/categories.ts
  resources/web/deployment.yaml
  tests/support/views/api-rules-view.js
  tests/tests/namespace/test-api-rules.spec.js
  tests/tests/namespace/test-oauth2.spec.js
Labels: size/S, lgtm

#2186 fix services loading
  core-ui/src/resources/Services/ApiRulesList.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#2184 fix: displaying version, leftNav styling, adjusting to smaller device, topNav styling
  core-ui/public/assets/version.yaml
  core-ui/src/components/App/App.tsx
  core-ui/src/shared/components/PageHeader/PageHeader.js
  core-ui/src/sidebar/Footer/useGetBusolaVersion.ts
  core-ui/src/sidebar/Sidebar.scss
  core-ui/src/sidebar/useSidebarCondensed.tsx
  resources/web/deployment.yaml
Labels: size/M, lgtm

#2176 fix dynamic values even more
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/contexts/Trigger.js
  core-ui/src/components/Extensibility/hooks/useVariables.js
  core-ui/src/components/Extensibility/plugins/TriggerHandler.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#2185 fix selected leftNav item and change ExternalLink in LeftNav
  core-ui/src/components/Extensibility/components/ExternalLink.js
  core-ui/src/shared/components/Link/Link.tsx
  core-ui/src/sidebar/NavItem.tsx
  resources/web/deployment.yaml
Labels: size/M, lgtm

#2188 Fix maximum call stack size exceeded in helm releases and secrets
  core-ui/src/components/HelmReleases/decodeHelmRelease.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#2189 UI fixes
  core-ui/public/i18n/en.yaml
  core-ui/src/components/App/IncorrectPath.js
  core-ui/src/components/App/IncorrectPath.scss
  core-ui/src/shared/components/K8sNameInput/K8sNameInput.js
  core-ui/src/shared/hooks/useDeleteResource.js
  core-ui/src/shared/hooks/useDeleteResource.scss
  docs/extensibility/form-section.md
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2194 Wait for extensions to load to display a redirection error
  core-ui/src/components/App/IncorrectPath.js
  core-ui/src/sidebar/NavItem.tsx
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#2201 Add nataliasitko to codeowners
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/XS, lgtm

#2199 fix: fetching extensibility Schemas
  core-ui/src/state/extensibilitySchemasAtom.ts
  core-ui/src/state/navigation/extensionsAtom.ts
  resources/web/deployment.yaml
Labels: size/M, lgtm

#2197 add closing namespace nav
  core-ui/src/header/Header.tsx
  core-ui/src/header/NamespaceDropdown/NamespaceDropdown.tsx
  resources/web/deployment.yaml
Labels: size/M, lgtm

#2196 fix: refreshing app when changing namespace
  CODEOWNERS
  core-ui/public/i18n/en.yaml
  core-ui/src/shared/components/ErrorBoundary/ErrorBoundary.js
  core-ui/src/sidebar/Sidebar.tsx
  core-ui/src/styles/index.scss
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#2207 fix cluster
  core-ui/src/header/Header.tsx
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#2192 Nginx & config fixes
  Dockerfile.local
  README.md
  core-ui/public/defaultConfig.yaml
  core-ui/src/state/configuration/configurationAtom.ts
  core-ui/src/state/navigation/extensionsAtom.ts
  lighthouse/lighthouse.spec.js
  nginx/nginx.conf
  resources/web/deployment.yaml
Labels: size/M, lgtm

#2214 fix trigger docs
  docs/extensibility/form-section.md
Labels: size/S, lgtm

#2215 Hide extensions of resources not existing on a cluster
  core-ui/src/state/navigation/extensionsAtom.ts
  core-ui/src/state/navigation/sidebarNavigationNodesSelector.ts
  core-ui/src/state/resourceList/mapBusolaResourceToNavNode.ts
  resources/web/deployment.yaml
  tests/support/exceptions.js
Labels: size/M, lgtm

#2217 Cleanup package json
  core-ui/package-lock.json
  core-ui/package.json
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/XXL, lgtm

#2213 fix: displaying select namespace without connected cluster
  core-ui/src/header/Header.tsx
  resources/web/deployment.yaml
Labels: size/M, lgtm

#2218 Fix Sentry
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/CommitmentGraph.js
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/resources/RoleBindings/RoleForm.js
  core-ui/src/shared/components/StatsGraph/StatsGraph.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#2222 remove externalNodes and fix uploading resource on Cluster lvl
  core-ui/public/defaultConfig.yaml
  core-ui/src/resources/Namespaces/YamlUpload/helpers.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2224 Busola hotfix: kubeconfig path & backend configuration
  Dockerfile.local
  backend/config/config.yaml
  backend/index.js
  core-ui/public/kubeconfig
  core/kubeconfig/.gitkeep
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2223 Fix refreshing on /clusters
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/state/authDataAtom.ts
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2200 handle simple/advanced flags in children
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/helpers/prepareSchemaRules.js
  examples/pizzas/configuration/pizzas-configmap.yaml
  examples/resources/configuration/dns-providers.yaml
  examples/resources/gateway/apirules.yaml
  examples/resources/istio/authorization-policies.yaml
  examples/resources/istio/gateways.yaml
  examples/resources/istio/service-entries.yaml
  examples/resources/istio/sidecars.yaml
  examples/resources/istio/virtual-services.yaml
  resources/web/deployment.yaml
  tests/tests/namespace/test-api-rules.spec.js
  tests/tests/namespace/test-dns-entries.spec.js
  tests/tests/namespace/test-stateful-sets.spec.js
Labels: size/L, lgtm

#2203 Gardener login
  core-ui/public/defaultConfig.yaml
  core-ui/public/i18n/en.yaml
  core-ui/src/components/App/App.tsx
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Gardener/GardenerLogin.tsx
  core-ui/src/components/Gardener/GardenerLoginFeature.tsx
  core-ui/src/components/Gardener/useGardenerLoginFunction.tsx
  core-ui/src/components/Gardener/useMakeGardenerLoginRoute.tsx
  core-ui/src/shared/components/Modal/Modal.js
  core-ui/src/sidebar/Sidebar.tsx
  core-ui/src/state/authDataAtom.ts
  core-ui/src/state/permissionSetsSelector.ts
  core-ui/src/state/types.ts
  core-ui/src/state/useAfterInitHook.ts
  docs/features.md
  resources/web/deployment.yaml
Labels: size/L, lgtm

#2225 remove kubeconfig from gardener in defaultConfig
  core-ui/public/defaultConfig.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#2221 fix: overwriting resources that has changed in the meantime
  core-ui/src/shared/ResourceForm/useCreateResource.js
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#2227 try to fix breaking UI with empty egenral
  core-ui/src/state/navigation/extensionsAtom.ts
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#2226 fix readableTimestamp for jsonata
  core-ui/public/defaultConfig.yaml
  core-ui/src/components/Extensibility/helpers/jsonataWrapper.js
  examples/resources/configuration/subscriptions.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2229 Remove requiresCA, fix ext details reload
  core-ui/src/components/Extensibility/components/ResourceList.js
  core-ui/src/components/Gardener/useGardenerLoginFunction.tsx
  core-ui/src/shared/hooks/BackendAPI/createHeaders.ts
  core-ui/src/shared/hooks/BackendAPI/useFetch.ts
  core-ui/src/state/authDataAtom.ts
  core-ui/src/state/clusterAtom.ts
  core-ui/src/state/clusterConfigSelector.ts
  core-ui/src/state/openapi/oidc.ts
  core-ui/src/state/utils/effects.ts
  core-ui/src/state/utils/getFetchFn.ts
  resources/web/deployment.yaml
Labels: size/L, lgtm

#2231 Fix getting schemas after cluster change
  core-ui/src/components/App/resourceSchemas/useResourceSchemas.ts
  core-ui/src/state/authDataAtom.ts
  core-ui/src/state/openapi/openapiLastFetchedAtom.ts
  resources/web/deployment.yaml
Labels: size/M, lgtm

#2236 properly handle the "required" value in resource ref
  core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRefRenderer.js
  core-ui/src/components/Extensibility/components-form/SimpleList.js
  core-ui/src/components/Extensibility/components-form/index.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2239 remove Daria and Piotr as CODEOWNERS, it was a pleasure to work with both of you
  CODEOWNERS
Labels: size/XS, lgtm
