Repository kyma-project/busola, pull requests merged in 2022-07, with the labels that each got.

#1515 store extensibility config per context
  core/src/luigi-config/customResources.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1507 Show more complex data
  backend/package-lock.json
  core-ui/src/components/Extensibility/components/Widget.js
  core-ui/src/components/Extensibility/helpers.js
  core/src/i18n/en.yaml
  docs/extensibility/resources.md
  examples/pizzas/pizzas-configmap.yaml
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1495 Extensibility - show connected resources
  backend/package-lock.json
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/command-pallette/CommandPaletteProvider.js
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/components/Columns.js
  core-ui/src/components/Extensibility/components/PendingWrapper.js
  core-ui/src/components/Extensibility/components/Plain.js
  core-ui/src/components/Extensibility/components/ResourceList.js
  core-ui/src/components/Extensibility/components/Widget.js
  core-ui/src/components/Extensibility/components/index.js
  core-ui/src/components/Extensibility/contexts/RelationsContext.js
  core-ui/src/components/Extensibility/helpers.js
  core-ui/src/shared/components/ControlledBy/ControlledBy.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core-ui/src/shared/components/Spinner/Spinner.js
  core-ui/src/shared/useObjectState.js
  docs/extensibility/display-widgets.md
  docs/extensibility/resources.md
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/XL, lgtm, extensibility

#1519 Fix monaco editor height
  core-ui/src/components/Clusters/components/AddClusterDialog.scss
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.scss
  core-ui/src/shared/components/MonacoEditorESM/Editor.scss
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1516 Resource widget
  core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
  core-ui/src/components/Extensibility/components-form/index.js
  docs/extensibility/form-widgets.md
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1529 Add widget that display joined array entries
  core-ui/src/components/Extensibility/components/JoinedArray.js
  core-ui/src/components/Extensibility/components/index.js
  core/src/i18n/en.yaml
  docs/extensibility/assets/display-widgets/JoinedArray.png
  docs/extensibility/display-widgets.md
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1533 EXT: custom lang for CodeViewer
  core-ui/src/components/Extensibility/components/CodeViewer.js
  core/src/i18n/en.yaml
  docs/extensibility/display-widgets.md
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1543 expandable table
  core-ui/src/components/Extensibility/components/Columns.js
  core-ui/src/components/Extensibility/components/Columns.scss
  core-ui/src/components/Extensibility/components/Table.js
  core-ui/src/components/Extensibility/components/Table.scss
  core-ui/src/shared/components/GenericList/GenericList.scss
  docs/extensibility/display-widgets.md
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1534 Fix monaco, use new config map views
  core-ui/src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
  core-ui/src/resources/ConfigMaps/ConfigMapCreate.js
  core-ui/src/resources/Namespaces/YamlUpload/YamlUpload.js
  core-ui/src/shared/ResourceForm/fields/Editor.js
  core-ui/src/shared/ResourceForm/fields/RichEditorDataField/RichEditorDataField.js
  core-ui/src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.js
  core-ui/src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.scss
  core-ui/src/shared/ResourceForm/fields/index.js
  core-ui/src/shared/components/Dropdown/Dropdown.scss
  core-ui/src/shared/components/MonacoEditorESM/Editor.js
  core-ui/src/shared/components/MonacoEditorESM/autocompletion/getSchemaLink.js
  core-ui/src/shared/components/MonacoEditorESM/autocompletion/monaco-autocomplete.worker.js
  core-ui/src/shared/components/MonacoEditorESM/autocompletion/useAutocompleteWorker.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useCreateEditor.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useDisplayWarnings.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useOnBlur.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useOnChange.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useOnFocus.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useOnMount.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useUpdateValueOnParentChange.js
  core-ui/src/styles/index.scss
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/namespace/test-config-maps.spec.js
  tests/tests/namespace/test-daemon-sets.spec.js
Labels: size/XL, lgtm

#1535 Fixed Graph tooltip and added a Legend
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/CommitmentGraph.js
  core-ui/src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/GraphLegend/GraphLegend.js
  core-ui/src/shared/components/GraphLegend/GraphLegend.js
  core-ui/src/shared/components/GraphLegend/GraphLegend.scss
  core-ui/src/shared/components/StatsGraph/StatsPanel.js
  core-ui/src/shared/components/StatsGraph/StatsPanel.scss
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: kind/bug, size/L, lgtm

#1564 Sentry
  core-ui/src/components/Extensibility/components-form/SimpleList.js
  core-ui/src/shared/components/BTPResourceStatus.js
  core/src/luigi-config/utils/configChanged.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1536 Add basic logging
  backend/index.js
  backend/tracking.js
  core-ui/src/components/App/App.js
  core-ui/src/hooks/useTracking.js
  docs/features.md
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1524 EXT: custom placeholders
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/components/Badge.js
  core-ui/src/components/Extensibility/components/ControlledBy.js
  core-ui/src/components/Extensibility/components/JoinedArray.js
  core-ui/src/components/Extensibility/components/Text.js
  core-ui/src/components/Extensibility/components/Widget.js
  core-ui/src/components/Extensibility/helpers.js
  core-ui/src/shared/components/LayoutPanelRow/LayoutPanelRow.js
  core-ui/src/shared/utils/helpers.js
  docs/extensibility/display-widgets.md
  docs/extensibility/resources.md
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1577 Fix for 0 as null in ext create modal
  core-ui/src/shared/ResourceForm/inputs/Number.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1567 The creation of resources still uses hardcoded values, but at least we have warnings
  README.md
  core-ui/src/components/ApiRules/components.js
  core-ui/src/hooks/useVersionWarning.js
  core-ui/src/resources/APIRules/GatewayDropdown.js
  core-ui/src/resources/DestinationRules/templates.js
  core-ui/src/resources/Gateways/templates.js
  core-ui/src/shared/components/ResourceDetails/ResourceDetails.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core/src/luigi-config/feature-discovery.js
  core/src/luigi-config/navigation/navigation-data-init.js
  core/src/luigi-config/navigation/queries.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/fixtures/test-custom-destination-rule.yaml
Labels: size/L, lgtm

#1571 Revert monaco change that break the edito
  core-ui/src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.js
  core-ui/src/shared/components/MonacoEditorESM/Editor.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useCreateEditor.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useOnBlur.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useOnChange.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useOnFocus.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useUpdateValueOnParentChange.js
  resources/web/deployment.yaml
Labels: kind/bug, size/L, lgtm

#1573 Add first session & cluster change tracking
  backend/common.js
  backend/index.js
  backend/settings/defaultConfig.json
  core-ui/src/components/App/App.js
  core-ui/src/hooks/tracking.js
  core-ui/src/hooks/useTracking.js
  core-ui/src/resources/Applications/ApplicationServices.js
  core-ui/src/shared/useComponentDidMount.js
  core/src/assets/defaultConfig.json
  core/src/luigi-config/communication.js
  core/src/luigi-config/tracking.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1580 Fix WS vulnerability, hide "Create UI" button if EXTENSIBILITY is disabled
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/resources/CustomResourceDefinitions/CustomResourceDefinitionDetails.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1581 Fix displaying widgets inside widgets
  core-ui/src/components/Extensibility/components/Widget.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1590 Fix tracking with SSO
  core-ui/src/components/Extensibility/components/Widget.js
  core/src/luigi-config/tracking.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1584 Extensibility: Details view: Hide key if the value is empty from panels
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/components/Widget.js
  core-ui/src/components/Extensibility/components/tests/Widget.test.js
  core-ui/src/setupTests.js
  core-ui/src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.js
  core-ui/src/shared/components/ResourceDetails/ResourceDetails.js
  core-ui/src/shared/components/ResourceDetails/tests/ResourceDetails.test.js
  core-ui/src/shared/typechecking/CustomPropTypes.js
  docs/extensibility/resources.md
  grep
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1579 Badge highlights
  core-ui/src/components/Extensibility/components/Badge.js
  core-ui/src/components/Extensibility/components/Widget.js
  docs/extensibility/display-widgets.md
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1586 Fix KeyValuePairRenderer
  core-ui/src/components/Extensibility/components-form/KeyValuePairRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRefRenderer.js
  core-ui/src/components/Extensibility/helpers.js
  core-ui/src/components/Extensibility/metadataSchema.js
  docs/extensibility/form-widgets.md
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1570 Extensibility: Extend Pizza examples
  core-ui/src/components/Extensibility/components-form/ResourceRefRenderer.js
  core-ui/src/components/Extensibility/components/CodeViewer.js
  core-ui/src/shared/components/MonacoEditorESM/autocompletion/getSchemaLink.js
  core-ui/src/shared/components/ResourceRef/ExternalResourceRef.js
  core-ui/src/shared/hooks/BackendAPI/useGet.js
  docs/extensibility/assets/display-widgets/ResourceList.png
  docs/extensibility/assets/display-widgets/ResourceRefs.png
  docs/extensibility/assets/form-widgets/Resource.png
  docs/extensibility/assets/form-widgets/ResourceRefs.png
  docs/extensibility/display-widgets.md
  docs/extensibility/form-widgets.md
  examples/pizzas/README.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizza-orders-crd.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  examples/pizzas/configuration/pizzas-crd.yaml
  examples/pizzas/pizzas-configmap.yaml
  examples/pizzas/samples.yaml
  resources/web/deployment.yaml
Labels: kind/feature, size/XL, lgtm

#1604 fix codeviewer yaml with empty string
  core-ui/src/components/Extensibility/components/CodeViewer.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1608 Fix btp versions missalign
  core-ui/src/resources/ServiceBindings/helpers.js
  core-ui/src/resources/ServiceInstances/ServiceBindingList.js
  core-ui/src/resources/ServiceInstances/helpers.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1592 Secret Creation is no longer missing DNS Providers
  core-ui/src/components/Extensibility/components/Widget.js
  core-ui/src/resources/GitRepositories/index.js
  core-ui/src/resources/Secrets/helpers.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core-ui/src/shared/helpers/getResourceDefs.js
  core-ui/src/shared/hooks/useWindowTitle.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1572 Extensibility: Details View: Table widget: Table column names
  backend/tracking.js
  core-ui/src/components/ApiRules/ApiRuleStatus/test/ApiRuleStatus.test.js
  core-ui/src/components/Extensibility/components/Table.js
  core-ui/src/components/Extensibility/components/tests/Table.test.js
  core-ui/src/components/HelmReleases/tests/HelmReleaseData.test.js
  core-ui/src/components/HelmReleases/tests/ReleaseDataPanel.test.js
  core-ui/src/resources/Applications/tests/useIsSKR.test.js
  core-ui/src/resources/CustomResourceDefinitions/ExtensibilityStarterModal/ColumnsInput.js
  core-ui/src/service-catalog-ui/setupTests.js
  core-ui/src/setupTests.js
  core-ui/src/shared/components/ErrorBoundary/test/ErrorBoundary.test.js
  core-ui/src/shared/components/LabelSelectorInput/test/LabelSelectorInput.test.js
  core-ui/src/shared/components/OAuth2ClientStatus/test/OAuth2ClientStatus.test.js
  core-ui/src/shared/components/Secret/test/SecretData.test.js
  core-ui/src/shared/components/Selector/tests/Selector.test.js
  core-ui/src/shared/components/StatusBadge/test/StatusBadge.test.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1563 Add ext tests
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/components/Badge.js
  core-ui/src/components/Extensibility/components/CodeViewer.js
  core-ui/src/components/Extensibility/components/Columns.js
  core-ui/src/components/Extensibility/components/JoinedArray.js
  core-ui/src/components/Extensibility/components/tests/Badge.test.js
  core-ui/src/components/Extensibility/components/tests/CodeViewer.test.js
  core-ui/src/components/Extensibility/components/tests/Columns.test.js
  core-ui/src/components/Extensibility/components/tests/ControlledBy.test.js
  core-ui/src/components/Extensibility/components/tests/JoinedArray.test.js
  core-ui/src/shared/utils/helpers.js
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1602 EXT: Fix Gaps between columns
  core-ui/src/components/Extensibility/components-form/KeyValuePairRenderer.js
  core-ui/src/components/Extensibility/components/Columns.js
  core-ui/src/components/Extensibility/components/Columns.scss
  core-ui/src/components/Extensibility/components/Panel.js
  core-ui/src/components/Extensibility/components/Table.js
  core-ui/src/resources/DnsProviders/DnsProviderDetails.js
  core-ui/src/resources/Issuers/IssuerDomains.js
  core-ui/src/service-catalog-ui/components/ServiceInstanceList/ServiceInstanceTable/ServiceInstanceTable.js
  core-ui/src/shared/components/GenericList/GenericList.js
  core-ui/src/styles/index.scss
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1613 Bump certs, fix some of Sentry issues
  backend/certs.pem
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/shared/ResourceForm/fields/ItemArray.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useOnChange.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1599 Extensibility versioning
  core-ui/src/components/Extensibility/migration.js
  core-ui/src/resources/ConfigMaps/ConfigMapDetails.js
  core-ui/src/resources/CustomResourceDefinitions/ExtensibilityStarterModal/helpers.js
  core/src/assets/defaultConfig.json
  core/src/i18n/en.yaml
  core/src/luigi-config/customResources.js
  docs/extensibility/resources.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1614 Disable tracking on Docker
  backend/common.js
  core/src/luigi-config/tracking.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1591 add feature defaultKubeconfig
  core/src/luigi-config/kubeconfig-id/loadKubeconfigById.js
  docs/features.md
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1622 Fix error on config map details when there are no labels
  core-ui/src/resources/ConfigMaps/ConfigMapDetails.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1615 Update CronJobs version
  core-ui/src/resources/Jobs/templates.js
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1619 Fix deleting resources from the CRD details view
  core-ui/src/components/CustomResources/CustomResources.js
  core-ui/src/resources/CustomResourceDefinitions/CRCreate.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1629 Fix formatting of parameters in the Extensibility documentation
  docs/extensibility/resources.md
Labels: documentation, size/S, lgtm, area/console

#1640 changed the copyright year
  NOTICE.md
Labels: size/XS, lgtm

#1631 Fix Missing property in Create form YAML
  core-ui/src/resources/APIRules/templates.js
  core-ui/src/resources/GitRepositories/helpers.js
  core-ui/src/resources/OAuth2Clients/helpers.js
  core-ui/src/resources/RoleBindings/GenericRoleBindingCreate.js
  core-ui/src/resources/RoleBindings/templates.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1638 Ext: Introduce Labels widget
  core-ui/src/components/Extensibility/components/Labels.js
  core-ui/src/components/Extensibility/components/index.js
  docs/extensibility/assets/display-widgets/Labels.png
  docs/extensibility/display-widgets.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  resources/web/deployment.yaml
Labels: kind/feature, size/M, lgtm

#1642 Allow Service Instances and Service Bindings to be edited
  core-ui/src/resources/ServiceBindings/ServiceBindingCreate.js
  core-ui/src/resources/ServiceBindings/ServiceBindingData.js
  core-ui/src/resources/ServiceBindings/ServiceBindingList.js
  core-ui/src/resources/ServiceBindings/ServiceInstanceLink.js
  core-ui/src/resources/ServiceInstances/ServiceInstanceCreate.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1644 Fix simple list names overwrites
  core-ui/src/components/Extensibility/components-form/SimpleList.js
  core-ui/src/components/Extensibility/components/Table.js
  examples/pizzas/configuration/pizzas-configmap.yaml
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#1612 Extensibility form reorder
  core-ui/src/components/Extensibility/ResourceSchema.js
  core-ui/src/components/Extensibility/SchemaRulesInjector.js
  core-ui/src/components/Extensibility/components-form/index.js
  docs/extensibility/resources.md
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1627 EXT: add description with links to resource list
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/helpers.js
  core/src/assets/defaultConfig.json
  docs/extensibility/resources.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm

#1633 align tooltips to new fiori standards
  core-ui/src/components/Clusters/views/EditCluster/EditCluster.js
  core-ui/src/components/Extensibility/ResourceSchema.js
  core-ui/src/components/Extensibility/metadataSchema.js
  core-ui/src/resources/APIRules/APIRuleCreate.js
  core-ui/src/resources/APIRules/Rules.js
  core-ui/src/resources/Applications/ApplicationCreate.js
  core-ui/src/resources/Certificates/CertificateCreate.js
  core-ui/src/resources/ConfigMaps/ConfigMapCreate.js
  core-ui/src/resources/CronJobs/CronJobCreate.js
  core-ui/src/resources/Deployments/DeploymentCreate.js
  core-ui/src/resources/DnsEntries/DnsEntryCreate.js
  core-ui/src/resources/DnsProviders/DnsProviderCreate.js
  core-ui/src/resources/Functions/FunctionCreate.js
  core-ui/src/resources/Gateways/GatewayCreate.js
  core-ui/src/resources/GitRepositories/GitRepositoryCreate.js
  core-ui/src/resources/Issuers/IssuerCreate.js
  core-ui/src/resources/Jobs/JobCreate.js
  core-ui/src/resources/Jobs/ScheduleSection.js
  core-ui/src/resources/Namespaces/NamespaceCreate.js
  core-ui/src/resources/OAuth2Clients/OAuth2ClientCreate.js
  core-ui/src/resources/ReplicaSets/ReplicaSetCreate.js
  core-ui/src/resources/RoleBindings/GenericRoleBindingCreate.js
  core-ui/src/resources/Roles/GenericRoleCreate.js
  core-ui/src/resources/Secrets/SecretCreate.js
  core-ui/src/resources/ServiceAccounts/ServiceAccountCreate.js
  core-ui/src/resources/ServiceBindings/ServiceBindingCreate.js
  core-ui/src/resources/ServiceInstances/ServiceInstanceCreate.js
  core-ui/src/resources/Subscriptions/FiltersSection.js
  core-ui/src/resources/Subscriptions/SubscriptionCreate.js
  core-ui/src/shared/ResourceForm/components/FormField.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/ResourceForm/fields/K8sNameField.js
  core-ui/src/shared/ResourceForm/fields/KeyValueField.js
  core-ui/src/shared/ResourceForm/fields/MultiInput.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/namespace/test-reduced-permissions.spec.js
  tests/tests/namespace/test-service-accounts.spec.js
Labels: size/XL, lgtm

#1652 Ext: Fix description and formulas
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
Labels: kind/bug, size/S, lgtm

#1657 Fix pizzas form example
  examples/pizzas/configuration/pizzas-configmap.yaml
Labels: size/S, lgtm

#1649 Fix namespace and resource name conflict for extensibility
  core-ui/src/components/Extensibility/tests/useGetCRDByPath.test.js
  core-ui/src/components/Extensibility/useGetCRbyPath.js
  resources/web/deployment.yaml
Labels: kind/bug, size/L, lgtm

#1641 ResourceLink component
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/components/Panel.js
  core-ui/src/components/Extensibility/components/ResourceLink.js
  core-ui/src/components/Extensibility/components/Table.js
  core-ui/src/components/Extensibility/components/Widget.js
  core-ui/src/components/Extensibility/components/index.js
  core-ui/src/components/Extensibility/components/tests/ResourceLink.test.js
  core-ui/src/components/Extensibility/helpers.js
  core/src/luigi-config/luigi-config.js
  docs/extensibility/assets/display-widgets/ResourceLink.png
  docs/extensibility/display-widgets.md
  docs/features.md
  examples/pizzas/configuration/pizzas-configmap.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1658 Fix resourceLink docs
  docs/extensibility/display-widgets.md
Labels: size/XS, lgtm

#1634 EXT take schema from OpenAPI
  core-ui/src/components/App/App.js
  core-ui/src/components/App/AppContext.js
  core-ui/src/components/App/resourceSchemas/resourceSchemaWorkerApi.js
  core-ui/src/components/App/resourceSchemas/resourceSchemas.worker.js
  core-ui/src/components/App/resourceSchemas/useResourceSchemas.js
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/hooks/useGetSchema.js
  core-ui/src/resources/CustomResourceDefinitions/ExtensibilityStarterModal/helpers.js
  core-ui/src/shared/components/MonacoEditorESM/autocompletion/useAutocompleteWorker.js
  core-ui/src/shared/hooks/BackendAPI/useFetch.js
  core/src/i18n/en.yaml
  docs/extensibility/resources.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#1643 Examples
  examples/README.md
  examples/apps/httpbin/README.md
  examples/apps/httpbin/all.yaml
  examples/apps/httpbin/apirule.yaml
  examples/apps/jobs/README.md
  examples/apps/jobs/cpu-load.yaml
  examples/apps/jobs/fibonacci-cronjob.yaml
  examples/apps/jobs/fibonacci.yaml
  examples/apps/jobs/memory-hog.yaml
  examples/apps/jobs/primes.yaml
  examples/apps/microservices-demo/README.md
  examples/apps/microservices-demo/all.yaml
  examples/apps/whoami/README.md
  examples/apps/whoami/all.yaml
  examples/apps/whoami/virtualservice.yaml
  examples/resources/README.md
  examples/resources/configuration/certificates.yaml
  examples/resources/configuration/gitrepositories.yaml
  examples/resources/configuration/services.yaml
  examples/resources/samples/certificate.yaml
  examples/resources/samples/gitrepository.yaml
  examples/resources/samples/service.yaml
Labels: size/XXL, lgtm

#1656 Ext/create button
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  docs/extensibility/resources.md
  examples/resources/README.md
  resources/web/deployment.yaml
Labels: kind/feature, size/S, lgtm

#1662 change Time to Age
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#1669 Tooltip for allowing modifying protected resources
  core-ui/src/resources/Namespaces/NamespaceDetails.js
  core-ui/src/shared/components/ListActions/ListActions.js
  core-ui/src/shared/components/ResourceDetails/ResourceDetails.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core-ui/src/shared/contexts/YamlEditorContext/EditorActions.js
  core-ui/src/shared/contexts/YamlEditorContext/YamlContent.js
  core-ui/src/shared/contexts/YamlEditorContext/YamlEditorContext.js
  core-ui/src/shared/hooks/useRestartResource.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
Labels: size/L, lgtm

#1676 fix link to OAth2 description
  core-ui/src/resources/OAuth2Clients/OAuth2ClientList.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm
