Repository kyma-project/busola, pull requests merged in 2022-11, with the labels that each got.

#1996 Fix sentry
  core-ui/src/components/Extensibility/components-form/GenericList.js
  core-ui/src/components/Extensibility/components/Columns.js
  core-ui/src/components/Extensibility/components/ResourceLink.js
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm

#1994 Move language and theme store to Recoil from Luigi
  core-ui/src/components/App/App.js
  core-ui/src/components/Extensibility/ExtensibilityErrBoundary.js
  core-ui/src/components/Preferences/LanguageSettings.js
  core-ui/src/components/Preferences/LanguageSettings.tsx
  core-ui/src/components/Preferences/NamespaceSettings.tsx
  core-ui/src/components/Preferences/Preferences.tsx
  core-ui/src/components/Preferences/ProtectedSettings.tsx
  core-ui/src/components/Preferences/ThemeChooser.tsx
  core-ui/src/components/Preferences/ThemePreview/ThemePreview.tsx
  core-ui/src/components/Preferences/test/NamespaceSettings.test.tsx
  core-ui/src/hooks/useCssVariables.js
  core-ui/src/index.js
  core-ui/src/shared/components/GraphLegend/GraphLegend.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useCreateEditor.js
  core-ui/src/shared/components/ReadonlyEditorPanel.js
  core-ui/src/shared/components/Tabs/Tab.js
  core-ui/src/shared/components/TileButton/TileButton.tsx
  core-ui/src/shared/contexts/Microfrontend.js
  core-ui/src/shared/contexts/ThemeContext.js
  core-ui/src/state/preferences/languageAtom.ts
  core-ui/src/state/preferences/themeAtom.ts
  core-ui/src/state/types.ts
  core-ui/src/state/utils/effects.ts
  core-ui/src/testing/reactTestingUtils.tsx
  core/src/luigi-config/communication.js
  core/src/luigi-config/luigi-config.js
  core/src/luigi-config/settings.js
  core/src/luigi-config/utils/theme.js
  resources/web/deployment.yaml
Labels: kind/feature, size/L, lgtm

#2004 Update codeowners
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/S, lgtm

#2008 fix: Preferences height and font size
  core-ui/src/components/Preferences/Preferences.scss
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1998 Add overwrite flag
  core-ui/src/components/Extensibility/plugins/VisibilityHandler.js
  docs/extensibility/form-section.md
  resources/web/deployment.yaml
Labels: size/S, lgtm

#1991 remove old implementation of sidecars
  core-ui/package-lock.json
  core-ui/package.json
  core-ui/src/components/Extensibility/hooks/useVariables.js
  core-ui/src/index.js
  core-ui/src/resources/Sidecars/IstioListeners.js
  core-ui/src/resources/Sidecars/IstioListeners.scss
  core-ui/src/resources/Sidecars/SidecarCreate.js
  core-ui/src/resources/Sidecars/SidecarDetails.js
  core-ui/src/resources/Sidecars/SidecarList.js
  core-ui/src/resources/Sidecars/index.js
  core-ui/src/resources/Sidecars/templates.js
  core-ui/src/resources/index.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/fixtures/test-sidecar.yaml
  tests/support/mockConfig.js
  tests/tests/namespace/test-sidecars.spec.js
Labels: size/XL, lgtm

#2001 Disable test colors on CI
  core/Makefile
  resources/web/deployment.yaml
  scripts/makefile-node-common.mk
Labels: size/XS, lgtm

#1979 update jsonata in forms
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/contexts/DataSources.js
  core-ui/src/components/Extensibility/contexts/DataSources.tsx
  core-ui/src/components/Extensibility/hooks/useJsonata.js
  core-ui/src/components/Extensibility/hooks/useJsonata.ts
  core-ui/src/components/Extensibility/hooks/useVariables.js
  core-ui/src/components/Extensibility/plugins/EnumHandler.js
  core-ui/src/components/Extensibility/plugins/VisibilityHandler.js
  core-ui/src/shared/hooks/BackendAPI/useFetch.ts
  core-ui/src/shared/useObjectState.js
  core-ui/src/shared/useObjectState.ts
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/XL, lgtm

#2018 add missing jsonata variables + fix index issue
  core-ui/src/components/Extensibility/hooks/useJsonata.ts
  core-ui/src/components/Extensibility/hooks/useVariables.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2009 remove old implementation of gateways
  core-ui/src/resources/Gateways/Forms/HostsForm.js
  core-ui/src/resources/Gateways/Forms/PortsForm.js
  core-ui/src/resources/Gateways/Forms/ServersForm.js
  core-ui/src/resources/Gateways/Forms/TlsForm.js
  core-ui/src/resources/Gateways/GatewayCreate.js
  core-ui/src/resources/Gateways/GatewayDetails.js
  core-ui/src/resources/Gateways/GatewayList.js
  core-ui/src/resources/Gateways/GatewayServers.js
  core-ui/src/resources/Gateways/helpers.js
  core-ui/src/resources/Gateways/index.js
  core-ui/src/resources/Gateways/templates.js
  core-ui/src/resources/index.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  examples/resources/istio/gateways.yaml
  resources/web/deployment.yaml
  tests/tests/namespace/test-gateways.spec.js
Labels: size/XXL, lgtm

#2020 Fix editor size
  core-ui/src/components/Extensibility/components-form/MonacoRenderer.js
  core-ui/src/shared/ResourceForm/fields/Editor.js
  resources/web/deployment.yaml
Labels: kind/bug, size/M, lgtm

#2010 remove old implementation of service entries
  core-ui/src/components/Extensibility/components/Panel.js
  core-ui/src/resources/ServiceEntries/Endpoints.js
  core-ui/src/resources/ServiceEntries/ServiceEntryCreate.js
  core-ui/src/resources/ServiceEntries/ServiceEntryDetails.js
  core-ui/src/resources/ServiceEntries/ServiceEntryList.js
  core-ui/src/resources/ServiceEntries/index.js
  core-ui/src/resources/ServiceEntries/templates.js
  core-ui/src/resources/index.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  resources/web/deployment.yaml
  tests/fixtures/test-service-entry.yaml
  tests/tests/namespace/test-service-entries.spec.js
Labels: size/L, lgtm

#2011 Readonly name
  core-ui/src/components/App/App.js
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/ResourceSchema.js
  core-ui/src/components/Extensibility/components-form/NameRenderer.js
  core-ui/src/components/Extensibility/helpers/prepareRules.js
  core-ui/src/shared/ResourceForm/components/ResourceForm.js
  core-ui/src/shared/components/ResourceDetails/ResourceDetails.js
  docs/extensibility/assets/form-widgets/Name.png
  docs/extensibility/assets/form-widgets/Name2.png
  docs/extensibility/form-section.md
  resources/web/deployment.yaml
Labels: size/M, lgtm

#2026 Sentry 202211
  core-ui/src/components/ApiRules/ApiRulesList.js
  core-ui/src/components/ApiRules/components.js
  core-ui/src/components/Extensibility/ExtensibilityDetails.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2029 fix: ext presets
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/helpers/index.js
  examples/resources/serverless/functions.yaml
  resources/web/deployment.yaml
Labels: kind/bug, size/S, lgtm, area/busola/extensibility

#2033 dynamic fields
  core-ui/src/components/Extensibility/ExtensibilityCreate.js
  core-ui/src/components/Extensibility/components-form/index.js
  core-ui/src/components/Extensibility/contexts/Trigger.js
  core-ui/src/components/Extensibility/hooks/useJsonata.ts
  core-ui/src/components/Extensibility/hooks/useTriggers.js
  core-ui/src/components/Extensibility/plugins/TriggerHandler.js
  docs/extensibility/form-section.md
  resources/web/deployment.yaml
Labels: size/L, lgtm

#2021 remove old implementation of authorization policies
  core-ui/src/components/Extensibility/components-form/GenericList.js
  core-ui/src/resources/AuthorizationPolicies/AuthorizationPolicyCreate.js
  core-ui/src/resources/AuthorizationPolicies/AuthorizationPolicyDetails.js
  core-ui/src/resources/AuthorizationPolicies/AuthorizationPolicyList.js
  core-ui/src/resources/AuthorizationPolicies/Rules.js
  core-ui/src/resources/AuthorizationPolicies/index.js
  core-ui/src/resources/AuthorizationPolicies/templates.js
  core-ui/src/resources/index.js
  core-ui/src/shared/ResourceForm/components/CollapsibleSection.js
  core-ui/src/shared/ResourceForm/fields/MultiInput.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  examples/resources/istio/authorization-policies.yaml
  examples/resources/istio/gateways.yaml
  resources/web/deployment.yaml
  tests/fixtures/test-authorization-policies.yaml
  tests/tests/namespace/test-authorization-policies.spec.js
  tests/tests/namespace/test-gateways.spec.js
  tests/tests/namespace/test-sidecars.spec.js
Labels: size/XL, lgtm

#2052 Fix resource version on edit
  core-ui/src/shared/ResourceForm/useCreateResource.js
  resources/web/deployment.yaml
Labels: kind/bug, size/XS, lgtm

#1918 API Rules
  core-ui/src/components/ApiRules/AccessStrategies/AccessStrategies.js
  core-ui/src/components/ApiRules/AccessStrategies/AccessStrategies.scss
  core-ui/src/components/ApiRules/ApiRuleStatus/ApiRuleStatus.js
  core-ui/src/components/ApiRules/ApiRuleStatus/test/ApiRuleStatus.test.js
  core-ui/src/components/ApiRules/ApiRulesList.js
  core-ui/src/components/ApiRules/CreateApiRule/CreateApiRule.js
  core-ui/src/components/ApiRules/CreateApiRule/test/mocks.js
  core-ui/src/components/ApiRules/accessStrategyTypes.js
  core-ui/src/components/ApiRules/components.js
  core-ui/src/components/ApiRules/constants.js
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/components/Extensibility/components/APIRules/APIRuleHost.js
  core-ui/src/components/Extensibility/components/index.js
  core-ui/src/hooks/useMessageList.js
  core-ui/src/resources/APIRules/APIRuleCreate.js
  core-ui/src/resources/APIRules/APIRuleDetails.js
  core-ui/src/resources/APIRules/APIRuleList.js
  core-ui/src/resources/APIRules/AccessStrategyForm.js
  core-ui/src/resources/APIRules/GatewayDropdown.js
  core-ui/src/resources/APIRules/HostAndSubdomain.js
  core-ui/src/resources/APIRules/JwtStrategyConfig.js
  core-ui/src/resources/APIRules/Rules.js
  core-ui/src/resources/APIRules/ServiceDropdown.js
  core-ui/src/resources/APIRules/Services.js
  core-ui/src/resources/APIRules/helpers.js
  core-ui/src/resources/APIRules/index.js
  core-ui/src/resources/APIRules/templates.js
  core-ui/src/resources/Services/ApiRulesList.js
  core-ui/src/resources/Services/ServiceDetails.js
  core-ui/src/resources/index.js
  core/src/i18n/en.yaml
  core/src/i18n/pl.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  examples/resources/gateway/apirules.yaml
  examples/resources/serverless/functions.yaml
  resources/web/deployment.yaml
  tests/support/mockConfig.js
  tests/support/views/api-rules-view.js
  tests/tests/namespace/run-prepare-functions.spec.js
  tests/tests/namespace/test-api-rules.spec.js
  tests/tests/namespace/test-authorization-policies.spec.js
  tests/tests/namespace/test-gateways.spec.js
  tests/tests/namespace/test-in-cluster-eventing.spec.js
  tests/tests/namespace/test-service-entries.spec.js
  tests/tests/namespace/test-sidecars.spec.js
Labels: size/XXL, lgtm

#2059 Cleanup build process: remove extensions
  Dockerfile.extensions.local
  Dockerfile.local
  Makefile
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2030 remove old implementation of virtual services
  core-ui/src/resources/VirtualServices/HttpRoutes.js
  core-ui/src/resources/VirtualServices/ServiceGateways.js
  core-ui/src/resources/VirtualServices/ServiceHosts.js
  core-ui/src/resources/VirtualServices/TcpRoutes.js
  core-ui/src/resources/VirtualServices/TlsRoutes.js
  core-ui/src/resources/VirtualServices/VirtualServiceCreate.js
  core-ui/src/resources/VirtualServices/VirtualServiceDetails.js
  core-ui/src/resources/VirtualServices/VirtualServiceDetails.scss
  core-ui/src/resources/VirtualServices/VirtualServiceList.js
  core-ui/src/resources/VirtualServices/common.js
  core-ui/src/resources/VirtualServices/index.js
  core-ui/src/resources/VirtualServices/templates.js
  core-ui/src/resources/index.js
  core/src/i18n/en.yaml
  core/src/luigi-config/navigation/static-navigation-model.js
  examples/resources/istio/virtual-services.yaml
  resources/web/deployment.yaml
  tests/tests/namespace/test-virtual-services.spec.js
Labels: size/XXL, lgtm

#2061 Remove groups state
  core-ui/src/components/App/useLuigiContextMigrator.js
  core-ui/src/components/Preferences/NamespaceSettings.tsx
  core-ui/src/components/Preferences/test/NamespaceSettings.test.tsx
  core-ui/src/state/groupsAtom.ts
  core-ui/src/testing/reactTestingUtils.tsx
  core/src/luigi-config/auth/auth.js
  core/src/luigi-config/navigation/navigation-data-init.js
  resources/web/deployment.yaml
Labels: size/M, lgtm

#2019 Move applications to extensibility
  core-ui/src/resources/Applications/ApplicationCreate.js
  core-ui/src/resources/Applications/ApplicationDetails.js
  core-ui/src/resources/Applications/ApplicationList.js
  core-ui/src/resources/Applications/ApplicationServices.js
  core-ui/src/resources/Applications/ApplicationServicesDetails/ApplicationServicesDetails.js
  core-ui/src/resources/Applications/ApplicationServicesDetails/ApplicationServicesDetails.scss
  core-ui/src/resources/Applications/ApplicationStatus.js
  core-ui/src/resources/Applications/ConnectApplicationModal.js
  core-ui/src/resources/Applications/index.js
  core-ui/src/resources/Applications/templates.js
  core-ui/src/resources/Applications/tests/useIsSKR.test.js
  core-ui/src/resources/Applications/useIsSKR.js
  core-ui/src/resources/Namespaces/YamlUpload/useUploadResources.js
  core-ui/src/resources/index.js
  core-ui/src/resources/other.js
  core-ui/src/resources/other/appServiceDetails.routes.js
  core-ui/src/state/types.ts
  core/src/i18n/en.yaml
  core/src/luigi-config/constants.js
  core/src/luigi-config/navigation/static-navigation-model.js
  docs/features.md
  examples/resources/applicationconnector/applications.yaml
  resources/web/deployment.yaml
  tests/tests/cluster/run-after.spec.js
  tests/tests/cluster/run-before.spec.js
  tests/tests/cluster/test-applications.spec.js
  tests/tests/cluster/test-command-palette.spec.js
  tests/tests/cluster/test-navigation-features.spec.js
  tests/tests/namespace/test-resource-upload.spec.js
Labels: size/XXL, lgtm

#2073 Add possibility to add, remoce and switch clusters
  core-ui/src/components/Clusters/shared.js
  core-ui/src/header/Header.tsx
  core-ui/src/shared/hooks/BackendAPI/createHeaders.ts
  core-ui/src/shared/hooks/BackendAPI/useFetch.ts
  core-ui/src/state/authDataAtom.ts
  core-ui/src/state/clusterAtom.ts
  core-ui/src/state/clustersAtom.ts
  core-ui/src/state/utils/getClustersInfo.js
  nginx/nginx.conf
Labels: size/L, lgtm

#2076 Comment failing tests since otters fix serverless
  tests/cypress.json
Labels: size/XS, lgtm

#2063 Apirules followup
  core-ui/src/resources/Services/ApiRulesList.js
  examples/resources/gateway/apirules.yaml
  resources/web/deployment.yaml
  tests/support/views/api-rules-view.js
  tests/tests/namespace/test-api-rules.spec.js
Labels: size/M, lgtm

#2070 Sentry fix 28.11.22
  core-ui/src/components/Extensibility/ExtensibilityList.js
  core-ui/src/shared/components/ResourceGraph/buildGraph/helpers.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#2081 fix: bring back api-rules/eventing tests
  tests/cypress.json
Labels: size/XS, lgtm

#2084 Get cluster and namespace from path
  core-ui/src/components/App/App.js
  core-ui/src/components/App/ClusterRoutes.js
  core-ui/src/components/App/ExtensibilityRoutes.js
  core-ui/src/components/App/NamespaceRoutes.js
  core-ui/src/components/App/useLuigiContextMigrator.js
  core-ui/src/header/Header.tsx
  core-ui/src/resources/createResourceRoutes.js
  core-ui/src/resources/index.js
  core-ui/src/resources/other.js
  core-ui/src/resources/other/CustomResourceDetails.routes.js
  core-ui/src/resources/other/CustomResourceListOfType.routes.js
  core-ui/src/resources/other/CustomResourcesByGroup.routes.js
  core-ui/src/resources/other/containerDetails.routes.js
  core-ui/src/resources/other/helmReleaseDetails.routes.js
  core-ui/src/resources/other/helmReleasesList.routes.js
  core-ui/src/shared/components/LogsLink/LogsLink.js
  core-ui/src/state/activeNamespaceIdAtom.ts
  core-ui/src/state/navigation/clusterAndNsNodesSelector.ts
  core-ui/src/state/navigation/sidebarNavigationNodesSelector.ts
  core-ui/src/state/permissionSetsSelector.ts
Labels: size/L

#2066 Allow force update
  core-ui/src/components/Preferences/Preferences.tsx
  core-ui/src/hooks/useEventListener.ts
  core-ui/src/setupTests.js
  core-ui/src/shared/ResourceForm/ForceUpdateModalContent.tsx
  core-ui/src/shared/ResourceForm/useCreateResource.js
  core-ui/src/shared/components/GenericList/actionHandlers/simpleDelete.js
  core-ui/src/shared/components/GenericList/actionHandlers/test/handleDelete.test.js
  core-ui/src/shared/components/MonacoEditorESM/hooks/useCreateDiffEditor.ts
  core-ui/src/shared/components/MonacoEditorESM/hooks/useCreateEditor.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core-ui/src/shared/contexts/ErrorModal/ErrorModal.scss
  core-ui/src/shared/contexts/ErrorModal/ErrorModal.tsx
  core-ui/src/shared/contexts/NotificationContext.js
  core-ui/src/shared/hooks/BackendAPI/useMutation.js
  core/src/i18n/en.yaml
  resources/web/deployment.yaml
  tests/tests/namespace/test-reduced-permissions.spec.js
Labels: size/XL, lgtm

#2083 Luigiless links - sidenav
  core-ui/src/hooks/useUrl.js
  core-ui/src/sidebar/NavItem.tsx
Labels: size/M

#2085 kubeconfig id
  core-ui/public/defaultConfig.yaml
  core-ui/src/components/App/useLoginWithKubeconfigID.ts
  core-ui/src/components/Clusters/shared.ts
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/components/Preferences/ProtectedSettings.tsx
  core-ui/src/hooks/useFeature.ts
  core-ui/src/shared/hooks/useGetHiddenNamespaces.ts
  core-ui/src/sidebar/Footer/useGetLegalLinks.ts
  core-ui/src/state/authDataAtom.ts
  core-ui/src/state/clusterAtom.ts
  core-ui/src/state/configFeatures/configFeaturesSelector.ts
  core-ui/src/state/navigation/clusterAndNsNodesSelector.ts
  core-ui/src/state/navigation/externalNodesSelector.ts
  core-ui/src/state/navigation/filters/shouldNodeBeVisible.ts
  core-ui/src/state/resourceList/resourceListSelector.ts
  core-ui/src/state/types.ts
  core-ui/src/state/utils/effects.ts
Labels: size/L
