Repository kyma-project/busola, pull requests merged in 2023-09, with the labels that each got.

#2568 Ui5 generic list
  resources/web/deployment.yaml
  src/components/Extensibility/components/Table.js
  src/components/Extensibility/components/Table.scss
  src/components/Extensibility/components/tests/Table.test.js
  src/setupTests.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/GenericList.scss
  src/shared/components/GenericList/components.js
  src/shared/components/GenericList/test/GenericList.test.js
  tests/integration/support/commands.js
  tests/integration/tests/cluster/test-download-a-kubeconfig.spec.js
  tests/integration/tests/cluster/test-edit-cluster.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/namespace/test-config-maps.spec.js
  tests/integration/tests/namespace/test-deployments.spec.js
  tests/integration/tests/namespace/test-events.spec.js
  tests/integration/tests/namespace/test-namespace-overview.spec.js
  tests/integration/tests/namespace/test-protected-resources.spec.js
  tests/integration/tests/namespace/test-resource-upload.spec.js
  tests/integration/tests/namespace/test-roles.spec.js
  tests/integration/tests/namespace/test-settings.spec.js
  tests/integration/tests/namespace/z-run-after.spec.js
Labels: size/L, lgtm

#2569 Ui5 headers
  resources/web/deployment.yaml
  src/shared/components/PageHeader/PageHeader.js
  src/shared/components/PageHeader/PageHeader.scss
  src/shared/components/PageHeader/test/PageHeader.test.js
  src/shared/components/ResourceNotFound/test/ResourceNotFound.test.js
  tests/integration/support/navigate-back-to.js
  tests/integration/tests/cluster/test-cluster-overview.spec.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/cluster/test-persistent-volumes.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/namespace/a-run-before.spec.js
  tests/integration/tests/namespace/test-custom-resources.spec.js
  tests/integration/tests/namespace/test-deployments.spec.js
  tests/integration/tests/namespace/test-persistent-volume-claims.spec.js
  tests/integration/tests/namespace/test-roles.spec.js
  tests/integration/tests/namespace/test-settings.spec.js
  tests/integration/tests/namespace/test-stateful-sets.spec.js
Labels: size/L, lgtm

#2572 fix displaying JoinedArray break
  resources/web/deployment.yaml
  src/components/Extensibility/components/JoinedArray.js
Labels: size/M, lgtm

#2573 Ui5 icons
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/Jsonata.js
  src/components/Extensibility/components-form/Modules/Modules.js
  src/components/Extensibility/components-form/SimpleList.js
  src/components/Extensibility/components/ExternalLink.js
  src/components/NoPermissions/NoPermissions.tsx
  src/components/Preferences/Preferences.tsx
  src/resources/Events/EventDetails.js
  src/resources/Events/EventList.js
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
  src/resources/Namespaces/ResourcesUsage.js
  src/resources/Namespaces/YamlUpload/YamlResourcesList.js
  src/resources/Roles/RuleTitle.js
  src/resources/Roles/Rules.js
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/components/Title.js
  src/shared/ResourceForm/fields/MultiInput.js
  src/shared/ResourceForm/inputs/Checkboxes.js
  src/shared/components/CertificateDate/CertificateDate.js
  src/shared/components/CircleProgress/CircleProgress.js
  src/shared/components/FileInput/FileInput.js
  src/shared/components/GenericList/Pagination/Pagination.js
  src/shared/components/KeyValueForm/KeyValueForm.js
  src/shared/components/Link/Link.tsx
  src/shared/components/ResourceGraph/SaveGraphControls.tsx
  src/shared/components/SchemaViewer/ObjectProperties.js
  src/shared/components/SideDrawer/SideDrawer.js
  src/shared/contexts/ErrorModal/ErrorModal.tsx
  src/shared/hooks/useProtectedResources.js
  src/state/navigation/categories.ts
  src/state/navigation/externalNodesSelector.ts
  src/state/types.ts
  src/styles/index.scss
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-services.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/namespace/test-custom-resources.spec.js
  tests/integration/tests/namespace/test-roles.spec.js
Labels: size/L, lgtm

#2571 Ui5 tabs
  resources/web/deployment.yaml
  src/components/Extensibility/components/Tabs.js
  src/components/Preferences/Preferences.tsx
  src/shared/components/Tabs/Tab.js
  src/shared/components/Tabs/Tab.scss
  src/shared/components/Tabs/Tabs.js
  src/shared/components/Tabs/Tabs.scss
  src/shared/components/Tabs/test/Tabs.test.js
  src/shared/components/VerticalTabs/VerticalTabs.scss
  tests/integration/tests/cluster/test-cluster-configuration.spec.js
  tests/integration/tests/namespace/test-resource-validation.spec.js
Labels: size/L, lgtm

#2579 no upload-yaml on noPermissions-view
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/header/Header.tsx
  tests/integration/tests/cluster/test-custom-resources.spec.js
Labels: size/S, lgtm

#2582 Ui5 switch
  resources/web/deployment.yaml
  src/components/Clusters/components/AuthForm.js
  src/components/Preferences/ConfirmationSettings.tsx
  src/components/Preferences/NamespaceSettings.tsx
  src/components/Preferences/ProtectedSettings.tsx
  src/components/Preferences/ResourceValidation/ResourceValidationSettings.tsx
  src/components/Preferences/test/NamespaceSettings.test.tsx
  src/resources/Namespaces/YamlUpload/YamlResourcesList.js
  src/resources/Pods/ContainersLogs.js
  src/resources/Pods/ContainersLogs.scss
  src/shared/ResourceForm/components/ResourceForm.scss
  src/shared/ResourceForm/inputs/Switch.js
  src/shared/components/StringInput/StringInput.js
  src/styles/index.scss
  tests/integration/tests/namespace/test-jobs.spec.js
  tests/integration/tests/namespace/test-protected-resources.spec.js
  tests/integration/tests/namespace/test-resource-validation.spec.js
  tests/integration/tests/namespace/test-service-accounts.spec.js
  tests/integration/tests/namespace/test-settings.spec.js
Labels: size/L, lgtm

#2575 Ui5 busyindicator
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/ResourceCommitment.scss
  src/components/Nodes/NodeResources/NodeResources.js
  src/components/Nodes/NodeResources/NodeResources.scss
  src/resources/Roles/RuleInput.js
  src/shared/components/LogsLink/LogsLink.js
  src/shared/components/ResourceGraph/ResourceGraph.scss
  src/shared/components/ResourceGraph/ResourceGraph.tsx
  src/shared/components/StatsGraph/StatsPanel.js
  src/shared/components/StatsGraph/StatsPanel.scss
  src/styles/index.scss
Labels: size/L, lgtm

#2580 Fix empty headerActions bug
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/shared/components/FileInput/FileInput.scss
  src/shared/components/GenericList/GenericList.js
Labels: size/S, lgtm

#2586 Whitesource fixes
  package-lock.json
Labels: size/XL, lgtm

#2591 Add new governance job
  .github/workflows/lint-markdown-links-daily.yml
  .github/workflows/lint-markdown-links-pr.yml
  .mlc.config.json
  milv.config.yaml
Labels: size/M, lgtm

#2592 Use semver 7.5.4 to 7.5.2
  package-lock.json
Labels: size/L, lgtm

#2594 Push mlc config through prettier
  .mlc.config.json
Labels: size/S, lgtm

#2590 Ui5 textarea
  .mlc.config.json
  resources/web/deployment.yaml
  src/resources/Secrets/DecodeSecretSwitch.js
  src/resources/Secrets/SecretCreate.scss
  src/resources/Secrets/SecretForm.js
  src/resources/Secrets/test/DecodeSecretSwitch.test.js
  src/resources/ServiceAccounts/SecretForm.js
  src/shared/ResourceForm/fields/DataField.js
  src/shared/ResourceForm/fields/DataField.scss
  src/shared/components/KeyValueForm/KeyValueForm.js
  src/shared/components/KeyValueForm/KeyValueForm.scss
  src/shared/components/KeyValueForm/helpers.js
  src/shared/components/KeyValueForm/test/KeyValueForm.test.js
  tests/integration/tests/namespace/test-secrets.spec.js
Labels: size/XL, lgtm

#2585 Ui5 checkbox
  resources/web/deployment.yaml
  src/components/BusolaExtensions/ColumnsInput.js
  src/components/BusolaExtensions/ExtensibilityStarterForm.scss
  src/components/Extensibility/components-form/Modules/Modules.js
  src/resources/Namespaces/NamespaceCreate.js
  src/shared/ResourceForm/inputs/Checkboxes.js
  src/shared/components/Checkbox/Checkbox.js
  src/shared/hooks/useDeleteResource.js
  src/styles/index.scss
  tests/integration/tests/cluster/test-cluster-validation.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/namespace/a-run-before.spec.js
Labels: size/L, lgtm

#2596 Remove "Open in Grafana" button in logs view
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/resources/Pods/ContainersLogs.js
  src/shared/components/LogsLink/LogsLink.js
  src/shared/components/LogsLink/LogsLink.scss
Labels: size/L, lgtm

#2589 Ui5 select
  resources/web/deployment.yaml
  src/components/Clusters/components/ContextChooser/ContextChooser.js
  src/components/Extensibility/components-form/KeyValuePairRenderer.js
  src/components/Extensibility/components-form/Modules/Modules.js
  src/components/Preferences/LanguageSettings.tsx
  src/components/Preferences/OtherSettings.tsx
  src/hooks/useMessageList.js
  src/resources/Namespaces/MemoryQuotas.js
  src/resources/Pods/ContainersLogs.js
  src/resources/RoleBindings/SubjectForm.js
  src/shared/ResourceForm/components/Presets.js
  src/shared/ResourceForm/components/Presets.scss
  src/shared/ResourceForm/fields/RuntimeResources.js
  src/shared/ResourceForm/fields/SelectArrayInput.js
  src/shared/ResourceForm/inputs/Dropdown.js
  src/shared/components/Deployment/Containers.scss
  src/shared/components/Dropdown/Dropdown.js
  src/shared/components/Dropdown/Dropdown.scss
  src/shared/components/MemoryInput.js
  src/shared/components/Select/Select.js
  src/shared/components/StatsGraph/StatsPanel.js
  src/shared/hooks/useCustomFormValidator.js
  src/styles/index.scss
  tests/integration/tests/cluster/test-cluster-configuration.spec.js
  tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
  tests/integration/tests/cluster/test-multiple-context-kubeconfig.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/namespace/a-run-before.spec.js
  tests/integration/tests/namespace/test-cron-jobs.spec.js
  tests/integration/tests/namespace/test-deployments.spec.js
  tests/integration/tests/namespace/test-jobs.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
Labels: size/L, lgtm
