Repository kyma-project/busola, pull requests merged in 2023-06, with the labels that each got.

#2489 fix vulnerability from checkmarx
  resources/web/deployment.yaml
  src/components/Extensibility/components/ExternalLink.js
Labels: size/XS, lgtm

#2490 bump monaco-yaml
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2487 Include extensibility resources in allNodes array
  resources/web/deployment.yaml
  src/resources/CustomResourceDefinitions/useCustomResourceUrl.js
  src/resources/Namespaces/YamlUpload/useUploadResources.js
  src/shared/components/ResourceGraph/DetailsCard/DetailsCard.tsx
  src/shared/components/ResourceGraph/useRelatedResources.ts
  src/shared/hooks/useIsInCurrentNamespace.ts
  src/state/navigation/allNodesSelector.ts
  src/state/resourceList/mapExtResourceToNavNode.ts
Labels: size/M, lgtm

#2492 bump yaml to version 2.2.2
  package-lock.json
Labels: size/L, lgtm

#2488 test-website
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/.kyma-project-io/build-preview.sh
  src/components/Extensibility/components-form/.kyma-project-io/values.yaml
Labels: size/L, lgtm

#2494 add build scripts
  .kyma-project-io/build-preview.sh
  .kyma-project-io/values.yaml
Labels: size/XS, lgtm

#2496 remove kyma-project-io dir
  .kyma-project-io/build-preview.sh
  .kyma-project-io/values.yaml
Labels: size/L, lgtm

#2502 add checking errors and not to display
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  src/shared/components/ResourcesList/ResourcesList.js
Labels: size/M, lgtm

#2505 fix parsing annotations data for CR
  resources/web/deployment.yaml
  src/components/CustomResources/CustomResources.js
Labels: size/S, lgtm
