Repository kyma-project/busola, pull requests merged in 2023-10, with the labels that each got.

#2597 fix types of badges
  docs/extensibility/display-section.md
  examples/injections/apirules.yaml
  examples/injections/functions.yaml
  examples/services/configuration.yaml
  public/schemas/schema-details.yaml
  public/schemas/schema-injections.yaml
  public/schemas/schema-list.yaml
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterStorageType.js
  src/components/Extensibility/components/Badge.js
  src/components/Extensibility/components/tests/Badge.test.js
  src/components/HelmReleases/HelmReleaseStatus.js
  src/components/HelmReleases/ReleaseDataPanel.js
  src/resources/CronJobs/CronJobConcurrencyPolicy.js
  src/resources/Jobs/JobCompletions.js
  src/resources/Jobs/JobConditions.js
  src/resources/Namespaces/NamespaceStatus.js
  src/resources/PersistentVolumes/PersistentVolumeStatus.js
  src/resources/Pods/ContainerStatus.js
  src/resources/Pods/PodRestarts.js
  src/resources/Pods/PodStatus.js
  src/shared/components/BTPResourceStatus.js
  src/shared/components/PersistentVolumeClaimStatus.js
  src/shared/components/ServiceAccountTokenStatus.js
  src/shared/components/StatusBadge/StatusBadge.js
  src/shared/components/SubscriptionConditionStatus.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/namespace/test-replica-sets.spec.js
Labels: size/L

#2601 Use chromium
  tests/integration/package.json
Labels: kind/bug, size/XS, lgtm, area/ci

#2600 UI5-combobox
  resources/web/deployment.yaml
  src/resources/RoleBindings/RoleForm.js
  src/resources/Secrets/SecretCreate.js
  src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.tsx
  src/shared/ResourceForm/fields/ComboboxArrayInput.js
  src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.js
  src/shared/ResourceForm/inputs/ComboboxInput.js
  src/shared/components/Dropdown/Dropdown.js
  src/shared/components/Dropdown/Dropdown.scss
  src/shared/components/K8sResourceSelect.js
  src/shared/components/ResourceRef/ExternalResourceRef.js
  src/styles/index.scss
  tests/integration/package.json
  tests/integration/support/helpers.js
  tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
Labels: size/L, lgtm

#2598 Update webcomponents to latest
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/components/Preferences/test/NamespaceSettings.test.tsx
  src/resources/Pods/PodRestarts.js
  src/resources/Pods/test/PodRestarts.test.js
  src/shared/components/StatusBadge/test/StatusBadge.test.js
  tests/integration/tests/namespace/test-jobs.spec.js
Labels: size/L

#2603 UI5 styling and bugfixes
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/useMetricsQuery.js
  src/components/Extensibility/components-form/SimpleList.js
  src/components/Extensibility/components-form/StringRenderer.js
  src/resources/Pods/PodRestarts.js
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/inputs/Dropdown.js
  src/shared/components/MonacoEditorESM/Editor.js
  src/shared/components/MonacoEditorESM/Editor.scss
  src/shared/components/TooltipBadge/TooltipBadge.scss
  src/shared/hooks/useDeleteResource.js
Labels: size/L, lgtm

#2609 add functionality for filtering general
  docs/extensibility/resources.md
  resources/web/deployment.yaml
  src/components/Extensibility/ExtensibilityList.js
Labels: size/S, lgtm

#2608 improve mobile view
  resources/web/deployment.yaml
  src/components/Preferences/Preferences.scss
  src/resources/Namespaces/NamespaceDetails.scss
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
  src/shared/components/StatsGraph/StatsGraph.scss
  src/shared/components/TileButton/TileButton.scss
  src/shared/components/VerticalTabs/VerticalTabs.scss
  src/sidebar/NavItem.tsx
Labels: size/M, lgtm

#2625 fix setting states
  resources/web/deployment.yaml
  src/hooks/usePermittedUrl.ts
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/components/ModalWithForm/ModalWithForm.js
Labels: size/M, lgtm

#2614 move infoLabel and menus
  resources/web/deployment.yaml
  src/components/CustomResources/CustomResourcesOfType.js
  src/components/Extensibility/components-form/Modules/Modules.js
  src/resources/RoleBindings/RoleForm.js
  src/resources/Secrets/SecretCreate.js
  src/shared/components/GenericList/SearchInput.js
  src/shared/components/ListActions/ListActions.js
  src/shared/components/SchemaViewer/JSONSchema.js
  src/shared/components/SchemaViewer/ObjectProperties.js
  tests/integration/support/commands.js
  tests/integration/support/inspect-list.js
  tests/integration/support/paste-to-monaco.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/cluster/test-navigation-features.spec.js
  tests/integration/tests/namespace/test-config-maps.spec.js
  tests/integration/tests/namespace/test-custom-resources.spec.js
  tests/integration/tests/namespace/test-deployments.spec.js
  tests/integration/tests/namespace/test-jobs.spec.js
  tests/integration/tests/namespace/test-reduced-permissions--configuration.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/integration/tests/namespace/test-resource-upload.spec.js
  tests/integration/tests/namespace/test-secrets.spec.js
  tests/integration/tests/namespace/test-service-accounts.spec.js
  tests/integration/tests/namespace/z-run-after.spec.js
Labels: size/L

#2620 UI5-Radiobutton
  resources/web/deployment.yaml
  src/components/Clusters/components/ChooseStorage.js
  src/components/Clusters/components/ChooseStorage.scss
  src/components/Extensibility/components/Table.js
  src/components/Preferences/ResourceValidation/ResourceValidationSettings.tsx
  src/shared/ResourceForm/inputs/Checkboxes.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/SortModalPanel.js
  src/shared/components/GenericList/test/GenericList.test.js
  tests/integration/support/login-commands.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/namespace/test-secrets.spec.js
Labels: size/L

#2629 Fix multi input
  resources/web/deployment.yaml
  src/resources/Secrets/SecretCreate.js
  src/resources/Secrets/SecretCreate.scss
  src/shared/ResourceForm/fields/DataField.js
  src/shared/ResourceForm/fields/DataField.scss
  src/shared/ResourceForm/fields/KeyValueField.js
  src/shared/ResourceForm/fields/MultiInput.js
  src/shared/ResourceForm/fields/MultiInput.scss
Labels: size/M

#2630 remove fundamental-react/styles and fix uuid for backend
  backend/common.js
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/shared/hooks/BackendAPI/useGet.js
  src/styles/index.scss
Labels: size/XL
