Repository kyma-project/busola, pull requests merged in 2023-04, with the labels that each got.

#2425 Sentry issue 3872900555
  resources/web/deployment.yaml
  src/shared/hooks/BackendAPI/config.js
Labels: size/S, lgtm

#2419 Fix bug on allNamespace-view: removing, creating & editing of resources
  resources/web/deployment.yaml
  src/shared/components/ResourcesList/ResourcesList.js
Labels: size/S, lgtm

#2421 fixed Redirection after Creation and Deletion of Extension
  resources/web/deployment.yaml
  src/components/BusolaExtensions/BusolaExtensionCreate.js
  src/shared/hooks/useDeleteResource.js
Labels: size/S, lgtm

#2430 remove qbalukom from codeowners
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/XS, lgtm

#2392 Extensibility wizard
  docs/extensibility/display-section.md
  docs/extensibility/resources.md
  docs/extensibility/wizard.md
  examples/README.md
  examples/injections/apirules.yaml
  examples/injections/functions.yaml
  examples/wizard/README.md
  examples/wizard/injection.yaml
  examples/wizard/serverless-wizard.yaml
  examples/wizard/wizard.yaml
  public/defaultConfig.yaml
  public/extensions/extensions.yaml
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/Clusters/components/AddClusterDialog.js
  src/components/Extensibility/ExtensibilityWizard.js
  src/components/Extensibility/ExtensibilityWizard.scss
  src/components/Extensibility/components-form/NameRenderer.js
  src/components/Extensibility/components-form/index.js
  src/components/Extensibility/components/Wizard.js
  src/components/Extensibility/components/index.js
  src/components/Extensibility/components/tests/Columns.test.js
  src/components/Extensibility/components/tests/JoinedArray.test.js
  src/components/Extensibility/components/tests/Table.test.js
  src/components/Extensibility/components/tests/Widget.test.js
  src/components/Extensibility/helpers/prepareSchemaRules.js
  src/components/Extensibility/plugins/ContextSwitcher.js
  src/components/Extensibility/plugins/VisibilityHandler.js
  src/components/Extensibility/useGetWizard.js
  src/hooks/useGetSchema.js
  src/shared/components/ErrorBoundary/ErrorBoundary.js
  src/shared/components/ErrorBoundary/ErrorBoundary.scss
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/state/navigation/extensionsAtom.ts
  src/state/types.ts
  src/styles/index.scss
  src/styles/wizard-dialog.scss
Labels: size/XXL, lgtm

#2434 Fixed description not being shown
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/SimpleList.js
  src/shared/ResourceForm/fields/MultiInput.js
Labels: size/S, lgtm

#2441 Add Gosia to CODEOWNERS
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/XS, lgtm

#2438 Bugfix: special characters reset Key-Value-Input
  resources/web/deployment.yaml
  src/shared/ResourceForm/fields/MultiInput.js
Labels: size/S, lgtm

#2439 Allow edit for wizard
  resources/web/deployment.yaml
  src/components/Extensibility/ExtensibilityWizard.js
  src/components/Extensibility/components/Wizard.js
  src/state/navigation/extensionsAtom.ts
Labels: size/M, lgtm

#2444 remove tests for removed resources
  tests/integration/cypress.json
Labels: size/XS, lgtm

#2452 change gcr to europe-docker
  Makefile
  README.md
  backend/Makefile
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2435 Customizable security validation
  config-overrides.js
  docs/features.md
  docs/resource-validation/README.md
  docs/resource-validation/assets/customize-policy-preferences.png
  examples/resource-validation/pod.yaml
  examples/resource-validation/rule-set.yaml
  package-lock.json
  package.json
  public/defaultConfig.yaml
  public/i18n/en.yaml
  resources/backend/deployment.yaml
  resources/resource-validation/rule-sets/datree/rules.yaml
  resources/resource-validation/rule-sets/default/policies.yaml
  resources/resource-validation/rule-sets/kubernetes-pod-security-standards/policies.yaml
  resources/resource-validation/rule-sets/kubernetes-pod-security-standards/rules.yaml
  resources/resource-validation/rulesetSchema.json
  resources/web/deployment.yaml
  scripts/update-resource-validation-imports.sh
  src/components/App/App.tsx
  src/components/Preferences/Preferences.scss
  src/components/Preferences/Preferences.tsx
  src/components/Preferences/ResourceValidation/ResourceValidationSettings.scss
  src/components/Preferences/ResourceValidation/ResourceValidationSettings.tsx
  src/components/Preferences/ResourcesValidationSettings.tsx
  src/resources/Namespaces/YamlUpload/FilteredResourcesDetails/FilteredResourcesDetails.js
  src/resources/Namespaces/YamlUpload/FilteredResourcesDetails/FilteredResourcesDetails.scss
  src/resources/Namespaces/YamlUpload/YamlResourcesList.js
  src/shared/hooks/useLoadingDebounce.ts
  src/shared/hooks/useValidateResourceBySchema/schema.js
  src/shared/hooks/useValidateResourceBySchema/useValidateResourceBySchema.js
  src/shared/hooks/useValidateResourceBySchema/useValidateResourceBySchema.ts
  src/state/preferences/validateResourcesAtom.ts
  src/state/types.ts
  src/state/utils/getConfigMaps.ts
  src/state/validationEnabledSchemasAtom.ts
  src/state/validationSchemasAtom.ts
  tests/integration/cypress.json
  tests/integration/support/mockConfig.js
  tests/integration/tests/namespace/test-resource-validation.spec.js
Labels: size/XXL, lgtm

#2442 add message panel widget
  docs/extensibility/assets/display-widgets/MessagePanel.png
  docs/extensibility/display-section.md
  public/extensions/wizards.yaml
  public/index.html
  resources/web/deployment.yaml
  src/components/Extensibility/components/MessagePage.js
  src/components/Extensibility/components/index.js
  src/state/navigation/extensionsAtom.ts
Labels: size/L, lgtm
