Repository kyma-project/busola, pull requests merged in 2023-07, with the labels that each got.

#2503 add messagestrip to cluster role create form
  package-lock.json
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/resources/Roles/RuleInput.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/integration/tests/namespace/test-roles.spec.js
Labels: size/S, lgtm

#2497 bump cypress
  docs/features.md
  package-lock.json
  resources/web/deployment.yaml
  src/components/App/IncorrectPath.js
  src/state/types.ts
  tests/integration/cypress-smoke.js
  tests/integration/cypress-smoke.json
  tests/integration/cypress.config.js
  tests/integration/cypress.json
  tests/integration/fixtures/test-customresourcedefinisions.yaml
  tests/integration/fixtures/test-daemon-sets.yaml
  tests/integration/fixtures/test-stateful-sets.yaml
  tests/integration/package-lock.json
  tests/integration/package.json
  tests/integration/scripts/busola-integration-k3s.sh
  tests/integration/support/exceptions.js
  tests/integration/support/login-commands.js
  tests/integration/tests/cluster/test-cluster-configuration.spec.js
  tests/integration/tests/cluster/test-command-palette.spec.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/cluster/test-kyma-version.spec.js
  tests/integration/tests/cluster/test-login-kubeconfigID.spec.js
  tests/integration/tests/cluster/test-multiple-context-kubeconfig.spec.js
  tests/integration/tests/cluster/test-other-login-options.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-services.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/namespace/a-run-before.spec.js
  tests/integration/tests/namespace/test-config-maps.spec.js
  tests/integration/tests/namespace/test-custom-resources.spec.js
  tests/integration/tests/namespace/test-daemon-sets.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/integration/tests/namespace/test-resource-validation.spec.js
  tests/integration/tests/namespace/test-stateful-sets.spec.js
  tests/integration/tests/namespace/z-run-after.spec.js
  tests/lighthouse/lighthouse.spec.js
Labels: size/XXL, lgtm, do-not-merge/missing-docs-review

#2516 Fix loading injections and wizards
  resources/web/deployment.yaml
  src/state/navigation/extensionsAtom.ts
Labels: size/XS, lgtm

#2518 fix value in string rendered
  resources/web/deployment.yaml
  src/components/App/IncorrectPath.js
  src/components/Extensibility/components-form/StringRenderer.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
Labels: size/S, lgtm

#2519 Fix resources lists on details views
  .github/pull-request-template.md
  milv.config.yaml
  resources/web/deployment.yaml
  src/components/Extensibility/contexts/DataSources.tsx
Labels: size/S, lgtm

#2521 fix for previous target port
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/StringRenderer.js
Labels: size/XS, lgtm

#2465 remove services
  public/extensions/extensions.yaml
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/resources/Services/ApiRulesList.js
  src/resources/Services/ServiceCreate.js
  src/resources/Services/ServiceDetails.js
  src/resources/Services/ServiceDetails.scss
  src/resources/Services/ServiceList.js
  src/resources/Services/SubscriptionsList.js
  src/resources/Services/index.ts
  src/resources/Services/templates.js
  src/resources/index.js
  tests/integration/fixtures/test-services.yaml
  tests/integration/tests/namespace/test-reduced-permissions--configuration.spec.js
  tests/integration/tests/namespace/test-services.spec.js
Labels: size/XL, lgtm

#2522 finall fix for parsing strings and number
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/StringRenderer.js
Labels: size/XS, lgtm

#2523 Busola lighthouse
  tests/lighthouse/lighthouse.spec.js
  tests/lighthouse/scripts/busola-lighthouse.sh
Labels: size/M, lgtm

#2526 fix fetching data sources
  resources/web/deployment.yaml
  src/components/Extensibility/contexts/DataSources.tsx
Labels: size/S, lgtm

#2527 fix info about node version
  README.md
Labels: size/XS, lgtm

#2529 add feedback icon and config
  docs/features.md
  public/defaultConfig.yaml
  resources/web/deployment.yaml
  src/header/Header.tsx
  src/state/types.ts
  tests/integration/tests/cluster/test-cluster-overview.spec.js
Labels: size/M, lgtm

#2530 Upgrade wizard with checkboxss
  package-lock.json
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/Modules/Modules.js
  src/components/Extensibility/components-form/Modules/Modules.scss
  src/components/Extensibility/components-form/index.js
  src/styles/index.scss
Labels: size/L, lgtm
