Repository kyma-project/busola, pull requests merged in 2023-02, with the labels that each got.

#2327 fix simple list styling
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/SimpleList.js
  src/components/Extensibility/components-form/SimpleList.scss
Labels: size/M, lgtm

#2329 Fix edit cluster
  resources/web/deployment.yaml
  src/components/Clusters/views/EditCluster/EditCluster.js
Labels: size/XS, lgtm

#2330 fix: add language to GenericList's template
  public/schemas/schema-form.yaml
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/MonacoRenderer.js
Labels: kind/bug, size/XS, lgtm

#2331 fix: handling undefined in ComboboxInput
  resources/web/deployment.yaml
  src/hooks/useGetSchema.js
  src/shared/ResourceForm/inputs/ComboboxInput.js
Labels: kind/bug, size/XS, lgtm

#2335 fix: badge highlights jsonata function usage
  resources/web/deployment.yaml
  src/components/Extensibility/components/Badge.js
Labels: kind/bug, size/S, lgtm

#2304 More triggers
  resources/web/deployment.yaml
  src/components/Extensibility/ExtensibilityCreate.js
  src/components/Extensibility/contexts/DataSources.tsx
  src/components/Extensibility/contexts/Trigger.js
  src/components/Extensibility/plugins/CustomFieldInjector.js
  src/shared/ResourceForm/components/ResourceForm.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
Labels: size/M, lgtm

#2336 fix: change oauth2clients label
  resources/web/deployment.yaml
  src/resources/OAuth2Clients/index.js
  tests/integration/tests/namespace/test-oauth2.spec.js
Labels: size/S, lgtm

#2332 Translations
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/MultiCheckbox.js
  src/components/Extensibility/components-form/StringRenderer.js
  src/components/Extensibility/components/Badge.js
  src/components/Extensibility/components/ExternalLink.js
  src/components/Extensibility/components/Text.js
  src/components/Extensibility/components/tests/Table.test.js
  src/components/Extensibility/components/tests/Widget.test.js
Labels: size/M, lgtm

#2345 fix redirect for non existing extension link
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/App/IncorrectPath.js
Labels: size/M, lgtm

#2348 fix: remove children icon in the category that already exists
  resources/web/deployment.yaml
  src/state/navigation/assignToCategories.ts
Labels: kind/bug, size/XS, lgtm

#2349 fix sentry
  resources/web/deployment.yaml
  src/components/BusolaExtensions/helpers.js
Labels: kind/bug, size/XS, lgtm

#2351 Features config order is wrong
  resources/web/deployment.yaml
  src/state/configuration/configurationAtom.ts
Labels: size/S, lgtm

#2356 Allow data entries that starts with a dot
  resources/web/deployment.yaml
  src/shared/ResourceForm/fields/DataField.js
Labels: size/XS, lgtm

#2352 fix: silent renew token
  resources/web/deployment.yaml
  src/shared/hooks/BackendAPI/useGet.js
  src/state/authDataAtom.ts
Labels: size/L, lgtm

#2354 Multi namespace
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/nonResourceHandler.ts
  src/components/App/NamespaceRoutes.tsx
  src/components/CustomResources/CustomResources.js
  src/header/Header.tsx
  src/header/NamespaceDropdown/NamespaceDropdown.tsx
  src/resources/Namespaces/AllNamespacesDetails.js
  src/resources/Namespaces/NamespaceDetails.js
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
  src/resources/Namespaces/ResourcesUsage.js
  src/resources/helpers.js
  src/shared/components/ResourcesList/ResourcesList.js
  tests/integration/tests/cluster/test-command-palette.spec.js
Labels: size/L, lgtm

#2357 update dynamicValue docs
  docs/extensibility/form-section.md
Labels: size/XS, lgtm

#2361 remove debug
  resources/web/deployment.yaml
  src/components/CustomResources/CustomResources.js
Labels: size/XS, lgtm

#2360 fix switch context on cluster overview
  resources/web/deployment.yaml
  src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.ts
Labels: size/M, lgtm

#2365 fix all permissions Role preset
  resources/web/deployment.yaml
  src/resources/Roles/helpers.js
Labels: size/XS, lgtm
