Repository kyma-project/busola, pull requests merged in 2023-12, with the labels that each got.

#2672 Fix excludes in sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: kind/bug, size/XS, lgtm, area/security, cla: yes

#2665 add comment and fix eslint problems
  backend/index.js
  resources/backend/deployment.yaml
  sec-scanners-config.yaml
Labels: size/S, lgtm, cla: yes

#2678 Update namespace chooser
  resources/web/deployment.yaml
  src/hooks/useAvailableNamespaces.ts
Labels: size/XS, lgtm, cla: yes

#2674 fix: upload Yaml and Kubeconfig YAML upload
  resources/web/deployment.yaml
  src/components/Clusters/components/AddClusterDialog.js
  src/components/Clusters/components/AddClusterWizard.js
  src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  src/components/Clusters/views/ClusterList.js
  src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
  src/components/CustomResources/CustomResourcesOfType.js
  src/components/CustomResources/GroupingListPage.js
  src/components/HelmReleases/HelmReleasesDetails.js
  src/components/HelmReleases/HelmReleasesList.js
  src/components/Nodes/NodeDetails/NodeDetails.js
  src/resources/Namespaces/YamlUpload/YamlUpload.js
  src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
  src/shared/components/FileInput/FileInput.js
  src/shared/components/GenericList/SearchInput.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/state/showAddClusterWizard.ts
Labels: size/L, lgtm, cla: yes

#2676 bump ui5 packages
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  src/components/Extensibility/components/tests/Table.test.js
  src/shared/components/GenericList/Pagination/test/Pagination.test.js
  src/shared/components/Secret/test/SecretData.test.js
  src/sidebar/Sidebar.scss
  src/sidebar/SidebarNavigation.tsx
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
Labels: size/L, lgtm, cla: yes

#2680 remove unused package and bump oidc-client-ts to bump crypto-js
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm, cla: yes

#2682 fix no-permissions button
  resources/web/deployment.yaml
  src/components/NoPermissions/NoPermissions.tsx
Labels: size/XS, lgtm, cla: yes

#2687 Add test GH Action job
  .github/workflows/cypress-tests.yml
Labels: size/M, lgtm, cla: yes

#2679 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#2681 List improvements
  resources/web/deployment.yaml
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/ReadableCreationTimestamp/ReadableCreationTimestamp.tsx
  src/shared/components/ResourcesList/ResourcesList.js
Labels: size/L, lgtm, cla: yes

#2692 remove busola-local image from blackduck
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#2691 Bump base Alpine image
  Dockerfile
  Dockerfile.local
  backend/Dockerfile
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm, cla: yes

#2684 remove observability
  Dockerfile.local
  docs/features.md
  public/defaultConfig.yaml
  public/i18n/en.yaml
  resources/web/configmap.yaml
  resources/web/deployment.yaml
  src/state/navigation/categories.ts
  src/state/navigation/externalNodesSelector.ts
  src/state/navigation/sidebarNavigationNodesSelector.ts
  src/state/types.ts
Labels: size/L, lgtm, cla: yes

#2696 Add missing information in resource quota
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/resources/ResourceQuotas/ResourceQuotaList.js
  src/resources/ResourceQuotas/templates.js
Labels: size/M, lgtm, cla: yes

#2694 fix extensibility badges
  docs/extensibility/display-section.md
  examples/injections/apirules.yaml
  examples/injections/functions.yaml
  examples/services/configuration.yaml
  public/schemas/schema-details.yaml
  public/schemas/schema-injections.yaml
  public/schemas/schema-list.yaml
  resources/web/deployment.yaml
  src/components/Extensibility/components/Badge.js
  src/components/Extensibility/components/tests/Badge.test.js
  src/resources/Namespaces/YamlUpload/YamlUpload.js
  src/shared/components/ResourceDetails/tests/ResourceDetails.test.js
  src/shared/components/ResourceDetails/tests/ResourceDetailsColumns.test.js
  src/shared/components/ResourceDetails/tests/ResourceDetailsVisibility.test.js
Labels: size/L, lgtm, cla: yes

#2695 Bump node and cypress
  Dockerfile
  Dockerfile.local
  README.md
  backend/Dockerfile
  backend/index.js
  backend/package-lock.json
  package-lock.json
  resources/backend/deployment.yaml
  tests/integration/package-lock.json
  tests/integration/package.json
  tests/integration/scripts/busola-integration-k3s.sh
Labels: size/XXL, lgtm, cla: yes

#2698 Bump base image for busola-web
  Dockerfile
  resources/web/deployment.yaml
Labels: size/XS, lgtm, cla: yes

#2686 remove prometheus
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.js
  src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterStats.js
  src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/CommitmentGraph.js
  src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/ResourceCommitment.js
  src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/ResourceCommitment.scss
  src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/queries.js
  src/components/Clusters/views/ClusterOverview/ClusterNodes/ResourceCommitment/useMetricsQuery.js
  src/components/Nodes/NodeDetails/NodeDetails.js
  src/components/Nodes/NodeDetails/NodeDetails.scss
  src/components/Nodes/nodeQueries.js
  src/resources/Deployments/DeploymentDetails.js
  src/resources/Namespaces/NamespaceDetails.js
  src/resources/PersistentVolumeClaims/PersistentVolumeClaimDetails.js
  src/resources/Pods/PodDetails.js
  src/resources/Pods/PodStatsGraph.js
  src/shared/components/CircleProgress/CircleProgress.js
  src/shared/components/GraphLegend/GraphLegend.js
  src/shared/components/GraphLegend/GraphLegend.scss
  src/shared/components/StatsGraph/StatsGraph.js
  src/shared/components/StatsGraph/StatsGraph.scss
  src/shared/components/StatsGraph/StatsPanel.js
  src/shared/components/StatsGraph/StatsPanel.scss
  src/shared/components/StatsGraph/index.js
  src/shared/components/UI5Panel/UI5Panel.js
  src/shared/hooks/usePrometheus.js
  src/state/configuration/configurationAtom.ts
  src/state/configuration/prometheusFeature.ts
  src/state/types.ts
  tests/integration/tests/cluster/test-navigation-features.spec.js
Labels: size/XXL, lgtm, cla: yes

#2702 change nginx version to alpine
  Dockerfile
Labels: size/XS, lgtm, cla: yes

#2704 Add snow feature
  package-lock.json
  package.json
  public/defaultConfig.yaml
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/components/App/Snow/Snow.js
  src/index.js
Labels: size/M, lgtm, cla: yes

#2701 add chriskari as a codeowner
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/XS, lgtm, cla: yes

#2705 Snow - Fix for light theme
  resources/web/deployment.yaml
  src/components/App/Snow/Snow.js
Labels: size/XS, lgtm, cla: yes

#2703 fix unit test errors
  resources/web/deployment.yaml
  src/components/Extensibility/components/tests/Badge.test.js
  src/components/Extensibility/components/tests/Table.test.js
  src/components/Extensibility/components/tests/Widget.copyable.test.js
  src/components/HelmReleases/tests/ReleaseDataPanel.test.js
  src/resources/Pods/test/PodRestarts.test.js
  src/shared/components/CopiableText/test/CopiableText.test.js
  src/shared/components/GenericList/Pagination/test/Pagination.test.js
  src/shared/components/GenericList/test/GenericList.test.js
  src/shared/components/ListActions/test/ListActions.test.js
  src/shared/components/ResourceDetails/tests/ResourceDetailsColumns.test.js
  src/shared/components/ResourceDetails/tests/ResourceDetailsVisibility.test.js
  src/shared/components/ResourceNotFound/test/ResourceNotFound.test.js
  src/shared/components/Selector/tests/Selector.test.js
  src/shared/components/StatusBadge/test/StatusBadge.test.js
Labels: size/XL, lgtm, cla: yes

#2707 code-clean-up ModalWithForm
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterList.js
  src/shared/ResourceForm/useCreateResource.js
  src/shared/components/ModalWithForm/ModalWithForm.js
  src/shared/components/ResourcesList/ResourcesList.js
Labels: size/M, lgtm, cla: yes
