Repository kyma-project/busola, pull requests merged in 2023-03, with the labels that each got.

#2303 Removed old codebase of ServiceInstances
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/resources/ServiceInstances/ServiceBindingList.js
  src/resources/ServiceInstances/ServiceInstanceCreate.js
  src/resources/ServiceInstances/ServiceInstanceData.js
  src/resources/ServiceInstances/ServiceInstanceDetails.js
  src/resources/ServiceInstances/ServiceInstanceList.js
  src/resources/ServiceInstances/helpers.js
  src/resources/ServiceInstances/index.js
  src/resources/index.js
Labels: size/L, lgtm

#2301 Removed old codebase of ServiceBindings
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/resources/ServiceBindings/SecretRefForm/SecretRefForm.js
  src/resources/ServiceBindings/SecretRefForm/SecretRefFrom.scss
  src/resources/ServiceBindings/ServiceBindingCreate.js
  src/resources/ServiceBindings/ServiceBindingData.js
  src/resources/ServiceBindings/ServiceBindingDetails.js
  src/resources/ServiceBindings/ServiceBindingList.js
  src/resources/ServiceBindings/ServiceInstanceLink.js
  src/resources/ServiceBindings/helpers.js
  src/resources/ServiceBindings/index.js
  src/resources/index.js
Labels: size/XL, lgtm

#2296 removed old codebase of certificates
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/Predefined/Details/Certificate/CertificateRefs.scss
  src/resources/Certificates/CertificateCreate.js
  src/resources/Certificates/CertificateCreate.scss
  src/resources/Certificates/CertificateDetails.js
  src/resources/Certificates/CertificateList.js
  src/resources/Certificates/CertificateRefs.js
  src/resources/Certificates/CertificateRefs.scss
  src/resources/Certificates/IssuerLink.js
  src/resources/Certificates/SecretLink.js
  src/resources/Certificates/index.js
  src/resources/Certificates/templates.js
  src/resources/index.js
  src/shared/components/CertificateDate/CertificateDate.js
  tests/integration/cypress.json
  tests/integration/tests/namespace/test-certificates.spec.js
  tests/integration/tests/namespace/test-custom-resources.spec.js
Labels: size/XL, lgtm

#2286 ExtOauth2 busola
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/Predefined/Details/OAuth2Clients/OAuthClientSpecPanel.scss
  src/resources/OAuth2Clients/OAuth2ClientCreate.js
  src/resources/OAuth2Clients/OAuth2ClientDetails.js
  src/resources/OAuth2Clients/OAuth2ClientList.js
  src/resources/OAuth2Clients/OAuthClientSpecPanel.js
  src/resources/OAuth2Clients/OAuthClientSpecPanel.scss
  src/resources/OAuth2Clients/helpers.js
  src/resources/OAuth2Clients/index.js
  src/resources/index.js
  src/shared/components/OAuth2ClientStatus/OAuth2ClientStatus.js
  src/shared/components/OAuth2ClientStatus/test/OAuth2ClientStatus.test.js
  tests/integration/cypress.json
  tests/integration/tests/namespace/test-oauth2.spec.js
Labels: size/XL, lgtm

#2373 fix daemonSets
  resources/web/deployment.yaml
  src/resources/DaemonSets/DaemonSetCreate.js
Labels: size/XS, lgtm

#2374 fix subscriptions
  resources/web/deployment.yaml
  src/resources/Subscriptions/SubscriptionDetails.js
Labels: size/XS, lgtm

#2375 Allow to see resource view without rights to namespace itself
  resources/web/deployment.yaml
  src/components/App/NamespaceRoutes.tsx
Labels: size/XS, lgtm

#2381 remove Lyczeq and add valentin
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/XS, lgtm

#2382 remove mmitoraj
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/XS, lgtm

#2380 update certs
  backend/certs.pem
  resources/backend/deployment.yaml
Labels: size/M, lgtm

#2379 Add TAG_DEFAULT_TAG build-arg to Dockerfiles
  Dockerfile
  Dockerfile.local
  Makefile
  resources/web/deployment.yaml
  src/sidebar/Footer/useGetBusolaVersion.ts
Labels: size/S, lgtm

#2364 Widgets
  docs/extensibility/display-section.md
  examples/injections/apirules.yaml
  examples/injections/functions.yaml
  public/defaultConfig.yaml
  public/schemas/schema-injections.yaml
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  src/components/Extensibility/ExtensibilityInjections.js
  src/components/Extensibility/useGetInjection.js
  src/resources/helpers.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceDetails/tests/ResourceDetails.test.js
  src/state/navigation/extensionsAtom.ts
  src/state/types.ts
Labels: size/XL, lgtm

#2393 fix dockerfiles
  Dockerfile
  Dockerfile.local
  Makefile
Labels: size/S, lgtm

#2377 Create shortcut for Yaml Upload
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/command-pallette/CommandPalletteUI/handlers/nonResourceHandler.ts
  src/command-pallette/CommandPalletteUI/types.ts
  src/command-pallette/CommandPalletteUI/useSearchResults.tsx
  src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
  src/components/CustomResources/CustomResourcesOfType.js
  src/components/CustomResources/GroupingListPage.js
  src/resources/Namespaces/NamespaceDetails.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceDetails/tests/ResourceDetails.test.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/state/showYamlUploadDialogAtom.ts
Labels: size/L, lgtm

#2387 Get proper resource url based on permissions
  docs/extensibility/jsonata.md
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/ResourceRefRenderer.js
  src/components/Extensibility/components-form/ResourceRenderer.js
  src/components/Extensibility/helpers/jsonataWrapper.ts
  src/hooks/usePermittedUrl.ts
  src/shared/components/ResourceRef/ExternalResourceRef.js
  src/state/permittedUrlsAtom.ts
Labels: size/L, lgtm

#2391 fix for sidecar injection
  resources/web/deployment.yaml
  src/resources/Deployments/DeploymentCreate.js
  src/resources/Namespaces/NamespaceCreate.js
  src/shared/hooks/useSidecarInjection.js
Labels: size/M, lgtm

#2411 fix regex for versions
  resources/web/deployment.yaml
  src/sidebar/Footer/useGetBusolaVersion.ts
Labels: size/S, lgtm

#2395 Remove subscriptions
  examples/resources/configuration/subscriptions.yaml
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/resources/Services/ServiceDetails.js
  src/resources/Services/SubscriptionsList.js
  src/resources/Subscriptions/EventFilters.scss
  src/resources/Subscriptions/FiltersSection.js
  src/resources/Subscriptions/SubscriptionConditions.js
  src/resources/Subscriptions/SubscriptionCreate.js
  src/resources/Subscriptions/SubscriptionDetails.js
  src/resources/Subscriptions/SubscriptionList.js
  src/resources/Subscriptions/helpers.js
  src/resources/Subscriptions/index.js
  src/resources/Subscriptions/templates.js
  src/resources/index.js
  src/shared/components/SubscriptionsList.js
Labels: size/XXL, lgtm

#2394 Fix comments in functions edit
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/MonacoRenderer.js
Labels: size/XS, lgtm

#2420 Sort-List-Dialog closes now after sorting
  resources/web/deployment.yaml
  src/shared/components/GenericList/SortModalPanel.js
Labels: size/XS, lgtm

#2422 Fix resource widget
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/ResourceRenderer.js
Labels: size/XS, lgtm
