Repository kyma-project/busola, pull requests merged in 2023-05, with the labels that each got.

#2440 Fix bug not required parent
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/CollapsibleRenderer.js
  src/components/Extensibility/components-form/ResourceRenderer.js
  src/shared/hooks/useCustomFormValidator.js
Labels: size/L, lgtm

#2455 change interval
  resources/web/deployment.yaml
  src/components/Extensibility/ExtensibilityInjections.js
Labels: size/XS, lgtm

#2453 Patch upgrade
  resources/web/deployment.yaml
  src/components/Extensibility/ExtensibilityCreate.js
  src/components/Extensibility/ExtensibilityWizard.js
  src/resources/ConfigMaps/ConfigMapCreate.js
  src/resources/CronJobs/CronJobCreate.js
  src/resources/Deployments/DeploymentCreate.js
  src/resources/Jobs/JobCreate.js
  src/resources/Namespaces/NamespaceCreate.js
  src/resources/Namespaces/YamlUpload/FilteredResourcesDetails/FilteredResourcesDetails.js
  src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
  src/resources/Namespaces/YamlUpload/useUploadResources.js
  src/resources/ReplicaSets/ReplicaSetCreate.js
  src/resources/RoleBindings/GenericRoleBindingCreate.js
  src/resources/Roles/GenericRoleCreate.js
  src/resources/Secrets/SecretCreate.js
  src/resources/ServiceAccounts/ServiceAccountCreate.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/tests/useCreateResource.test.js
  src/shared/ResourceForm/useCreateResource.js
  src/shared/components/ResourcesList/ResourcesList.js
  tests/integration/tests/namespace/test-deployments.spec.js
  tests/integration/tests/namespace/test-secrets.spec.js
Labels: size/L, lgtm

#2458 Fix upload Yaml
  resources/web/deployment.yaml
  src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
  src/resources/Namespaces/YamlUpload/useUploadResources.js
Labels: size/M, lgtm

#2459 Fix upload yaml v2
  resources/web/deployment.yaml
  src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
Labels: size/XS, lgtm

#2460 fix for add cluster validation
  resources/web/deployment.yaml
  src/shared/hooks/useCustomFormValidator.js
Labels: size/S, lgtm

#2445 provide hyperlinks in inputInfo field
  docs/extensibility/form-section.md
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/SimpleList.js
  src/components/Extensibility/helpers/index.js
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/fields/K8sNameField.js
  src/shared/ResourceForm/fields/MultiInput.js
Labels: size/M, lgtm

#2466 Wizard defaults
  resources/web/deployment.yaml
  src/components/Extensibility/ExtensibilityWizard.js
  src/shared/utils/helpers.js
Labels: size/M, lgtm

#2468 Show hidden namespaces by default
  resources/web/deployment.yaml
  src/state/preferences/showHiddenNamespacesAtom.ts
  tests/integration/tests/namespace/test-daemon-sets.spec.js
  tests/integration/tests/namespace/test-settings.spec.js
Labels: size/S, lgtm

#2469 allow overriding wizards
  resources/web/deployment.yaml
  src/state/navigation/extensionsAtom.ts
  src/state/types.ts
Labels: size/S, lgtm

#2471 removed navigation nodes for kiali and jaeger
  docs/features.md
  public/defaultConfig.yaml
  resources/web/configmap.yaml
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2475 Add possibility to have link in Alert
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/AlertRenderer.js
Labels: size/S, lgtm

#2478 Fix statics on extensibility views
  resources/web/deployment.yaml
  src/components/Extensibility/useGetInjection.js
Labels: size/XS, lgtm

#2480 Allow to have key and name
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/StringRenderer.js
Labels: size/M, lgtm

#2481 remove hpas
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/resources/HorizontalPodAutoscalers/HPABehavior.js
  src/resources/HorizontalPodAutoscalers/HPASubcomponent.js
  src/resources/HorizontalPodAutoscalers/HorizontalPodAutoscalerCreate.js
  src/resources/HorizontalPodAutoscalers/HorizontalPodAutoscalerDetails.js
  src/resources/HorizontalPodAutoscalers/HorizontalPodAutoscalerList.js
  src/resources/HorizontalPodAutoscalers/helpers.js
  src/resources/HorizontalPodAutoscalers/index.ts
  src/resources/HorizontalPodAutoscalers/templates.js
  src/resources/index.js
  tests/integration/cypress.json
  tests/integration/fixtures/test-HPA.yaml
  tests/integration/tests/namespace/test-HPA.spec.js
Labels: size/XL, lgtm

#2483 EXT: fix links for helm brackets
  resources/web/deployment.yaml
  src/components/Extensibility/helpers/index.js
Labels: size/XS, lgtm

#2484 Override kube-public with kyma-system
  resources/web/deployment.yaml
  src/state/navigation/extensionsAtom.ts
Labels: size/XS, lgtm
