Repository kyma-project/busola, pull requests merged in 2023-11, with the labels that each got.

#2628 Fix custom form-validation
  resources/web/deployment.yaml
  src/components/BusolaExtensions/SectionEditor.js
  src/components/Extensibility/ExtensibilityWizard.js
  src/components/Extensibility/ResourceSchema.js
  src/components/Extensibility/components-form/MultiCheckbox.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/hooks/useCustomFormValidator.js
  tests/integration/support/helpers.js
  tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
  tests/integration/tests/namespace/test-protected-resources.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/integration/tests/namespace/test-roles.spec.js
Labels: size/L

#2637 fix link checks
  .mlc.config.json
Labels: size/XS, lgtm

#2638 fix link checks
  .mlc.config.json
Labels: size/XS, lgtm

#2635 instant value-updates for comboboxes & inputs
  resources/web/deployment.yaml
  src/components/BusolaExtensions/BusolaExtensionCreate.js
  src/components/Extensibility/components-form/Jsonata.js
  src/resources/RoleBindings/RoleForm.js
  src/resources/Secrets/SecretCreate.js
  src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.tsx
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/fields/ComboboxArrayInput.js
  src/shared/ResourceForm/fields/K8sNameField.js
  src/shared/ResourceForm/inputs/ComboboxInput.js
  src/shared/ResourceForm/inputs/Text.js
  src/shared/components/GenericList/SearchInput.js
  src/shared/components/K8sNameInput/K8sNameInput.js
  src/shared/components/K8sResourceSelect.js
  src/shared/hooks/useCustomFormValidator.js
  tests/integration/support/commands.js
  tests/integration/support/paste-to-monaco.js
  tests/integration/tests/namespace/test-protected-resources.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
Labels: size/L, lgtm

#2639 Fix forms
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/Jsonata.js
  src/components/Extensibility/components-form/MonacoRenderer.js
  src/components/Extensibility/components-form/SimpleList.js
  src/components/Extensibility/components-form/StringRenderer.js
  src/resources/RoleBindings/RoleForm.js
  src/resources/RoleBindings/SubjectForm.js
  src/resources/Secrets/SecretCreate.js
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/components/ResourceForm.scss
  src/shared/ResourceForm/fields/K8sNameField.js
  src/shared/ResourceForm/fields/KeyValueField.js
  src/shared/ResourceForm/fields/KeyValueField.scss
  src/shared/ResourceForm/fields/MultiInput.js
  src/shared/ResourceForm/fields/RuntimeResources.js
  src/shared/ResourceForm/inputs/Checkboxes.js
  src/shared/ResourceForm/inputs/ComboboxInput.js
  src/shared/ResourceForm/inputs/Dropdown.js
  src/shared/ResourceForm/inputs/Number.js
  src/shared/ResourceForm/inputs/Switch.js
  src/shared/ResourceForm/inputs/Text.js
  src/shared/components/K8sResourceSelect.js
  src/shared/components/ResourceRef/ExternalResourceRef.js
  src/shared/hooks/useCustomFormValidator.js
  src/styles/index.scss
Labels: size/L

#2643 Fix ui5 sidenavigation2
  public/i18n/en.yaml
  public/index.html
  public/themes/dark.css
  public/themes/default.css
  public/themes/hcb.css
  public/themes/hcw.css
  public/themes/light_dark.css
  resources/web/deployment.yaml
  src/components/App/App.scss
  src/components/App/App.tsx
  src/components/App/ContentWrapper/ContentWrapper.scss
  src/components/App/ContentWrapper/ContentWrapper.tsx
  src/header/Header.scss
  src/header/Logo/Logo.tsx
  src/header/SidebarSwitcher/SidebarSwitcher.scss
  src/header/SidebarSwitcher/SidebarSwitcher.tsx
  src/resources/Namespaces/AllNamespacesDetails.js
  src/resources/Namespaces/NamespaceDetails.js
  src/shared/components/CircleProgress/CircleProgress.scss
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
  src/shared/components/GenericList/GenericList.js
  src/shared/components/SideDrawer/SideDrawer.scss
  src/sidebar/Footer/Footer.scss
  src/sidebar/Footer/Footer.tsx
  src/sidebar/Sidebar.scss
  src/sidebar/Sidebar.tsx
  src/sidebar/SidebarNavigation.tsx
  src/state/preferences/isSidebarCondensedAtom.ts
  src/styles/index.scss
  tests/integration/tests/cluster/test-dashboard-version.spec.js
Labels: size/XL, lgtm

#2644 Fix error boundary component
  resources/web/deployment.yaml
  src/header/Header.scss
  src/header/Header.tsx
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/components/ErrorBoundary/ErrorBoundary.js
  src/shared/components/ErrorBoundary/ErrorBoundary.scss
  src/styles/index.scss
  tests/integration/cypress.config.js
  tests/integration/support/commands.js
  tests/integration/tests/namespace/test-cron-jobs.spec.js
  tests/integration/tests/namespace/test-protected-resources.spec.js
  tests/integration/tests/namespace/test-roles.spec.js
Labels: size/L

#2646 adjust create-form
  resources/web/deployment.yaml
  src/components/BusolaExtensions/BusolaExtensionCreate.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/components/ResourceForm.scss
Labels: size/M, lgtm

#2645 Firefox safari
  resources/web/deployment.yaml
  src/styles/index.scss
Labels: size/XS

#2647 ux-compliance
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/GenericList.js
  src/components/Extensibility/components-form/Modules/Modules.js
  src/components/Extensibility/components-form/SimpleList.js
  src/components/Extensibility/components/ExternalLink.js
  src/resources/Events/EventDetails.js
  src/resources/Events/EventList.js
  src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
  src/shared/ResourceForm/fields/ItemArray.js
  src/shared/ResourceForm/fields/MultiInput.js
  src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.js
  src/shared/components/Deployment/Containers.js
  src/shared/components/Link/Link.tsx
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/hooks/useDeleteResource.js
  src/sidebar/Footer/Footer.tsx
  tests/integration/support/commands.js
  tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/cluster/test-persistent-volumes.spec.js
  tests/integration/tests/cluster/test-storage-classes.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-services.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/namespace/test-custom-resources.spec.js
  tests/integration/tests/namespace/test-namespace-overview.spec.js
  tests/integration/tests/namespace/test-persistent-volume-claims.spec.js
  tests/integration/tests/namespace/test-protected-resources.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/integration/tests/namespace/test-resource-upload.spec.js
  tests/integration/tests/namespace/test-roles.spec.js
  tests/integration/tests/namespace/z-run-after.spec.js
Labels: size/L, lgtm

#2648 Ui5 fix margins
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/SimpleList.js
  src/components/Extensibility/components/Columns.js
  src/components/Extensibility/components/Table.js
  src/components/Extensibility/components/Tabs.js
  src/components/Extensibility/components/Tabs.scss
  src/resources/Events/EventList.js
  src/resources/Namespaces/AllNamespacesDetails.js
  src/resources/Namespaces/NamespaceDetails.js
  src/resources/PersistentVolumeClaims/PersistentVolumeClaimDetails.js
  src/resources/PersistentVolumes/PersistentVolumeList.js
  src/resources/Pods/PodList.js
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/fields/MultiInput.js
  src/shared/ResourceForm/fields/RuntimeResources.js
  src/shared/ResourceForm/inputs/Checkboxes.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
  src/shared/components/GenericList/GenericList.js
  src/shared/components/PodTemplate/PodTemplate.js
  src/shared/components/PodTemplate/components.js
  src/shared/components/RelatedPods.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/shared/components/Selector/Selector.js
  src/styles/index.scss
Labels: size/M, lgtm

#2649 Edit-Cluster style & CSS refactor
  resources/web/deployment.yaml
  src/components/App/ContentWrapper/ContentWrapper.scss
  src/components/App/ContentWrapper/ContentWrapper.tsx
  src/components/BusolaExtensions/BusolaExtensionDetails.js
  src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.scss
  src/components/Clusters/views/ClusterList.js
  src/components/Clusters/views/ClusterOverview/ClusterOverview.scss
  src/components/Clusters/views/EditCluster/EditCluster.js
  src/components/Extensibility/components-form/KeyValuePairRenderer.scss
  src/components/Extensibility/components-form/SimpleList.js
  src/components/Extensibility/components-form/SimpleList.scss
  src/components/Extensibility/components/Badge.js
  src/components/Predefined/Details/Pod/ContainersData.scss
  src/components/Preferences/ResourceValidation/ResourceValidationSettings.scss
  src/header/SidebarSwitcher/SidebarSwitcher.scss
  src/header/SidebarSwitcher/SidebarSwitcher.tsx
  src/resources/Jobs/ContainersSection.js
  src/resources/Namespaces/MemoryQuotas.js
  src/resources/Namespaces/NamespaceCreate.scss
  src/resources/Namespaces/YamlUpload/FilteredResourcesDetails/FilteredResourcesDetails.js
  src/resources/Pods/ContainersLogs.scss
  src/resources/Roles/Rules.js
  src/resources/Secrets/SecretCreate.js
  src/resources/StorageClasses/StorageClassDetails.js
  src/shared/ResourceForm/components/CollapsibleSection.scss
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/components/ModeSelector.js
  src/shared/ResourceForm/components/ModeSelector.scss
  src/shared/ResourceForm/components/Presets.js
  src/shared/ResourceForm/components/Title.js
  src/shared/ResourceForm/fields/DataField.js
  src/shared/ResourceForm/fields/MultiInput.js
  src/shared/ResourceForm/fields/MultiInput.scss
  src/shared/ResourceForm/fields/RuntimeResources.js
  src/shared/ResourceForm/fields/RuntimeResources.scss
  src/shared/ResourceForm/fields/TextArrayInput.js
  src/shared/components/CertificateDate/CertificateDate.js
  src/shared/components/CertificateDate/CertificateDate.scss
  src/shared/components/Deployment/Containers.js
  src/shared/components/Deployment/Containers.scss
  src/shared/components/Dropdown/Dropdown.js
  src/shared/components/ErrorBoundary/ErrorBoundary.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/components.js
  src/shared/components/K8sResourceSelect.js
  src/shared/components/ListActions/ListActions.scss
  src/shared/components/MemoryInput.js
  src/shared/components/ProgressBar/ProgressBar.js
  src/shared/components/ProgressBar/ProgressBar.scss
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/shared/components/SchemaViewer/ObjectProperties.js
  src/shared/contexts/YamlEditorContext/EditorActions.js
  src/shared/contexts/YamlEditorContext/EditorActions.scss
  src/sidebar/Sidebar.scss
  src/sidebar/Sidebar.tsx
  tests/integration/support/commands.js
  tests/integration/tests/cluster/test-cluster-validation.spec.js
  tests/integration/tests/cluster/test-edit-cluster.spec.js
Labels: size/XL, lgtm

#2657 Adjust icons in navigation
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/index.js
  src/resources/ClusterEvents/index.js
  src/resources/Events/index.js
  src/resources/Namespaces/namespaceOverviewNode.ts
  src/sidebar/SidebarNavigation.tsx
  src/state/navigation/categories.ts
Labels: size/M, lgtm

#2651 Improve custom-form-validation
  resources/web/deployment.yaml
  src/components/App/App.scss
  src/components/Clusters/components/AddClusterWizard.js
  src/shared/ResourceForm/components/CollapsibleSection.js
  src/shared/ResourceForm/components/Title.js
  src/shared/ResourceForm/fields/RuntimeResources.js
  src/shared/components/ModalWithForm/ModalWithForm.js
  src/shared/components/ResourceRef/ExternalResourceRef.js
  src/shared/hooks/useCustomFormValidator.js
  src/shared/hooks/useCustomFormValidator/useCustomFormValidator.js
  src/shared/hooks/useCustomFormValidator/validateFormElement.js
  src/shared/hooks/useCustomFormValidator/validateWidgets.js
  src/styles/index.scss
Labels: size/L, lgtm, cla: yes

#2666 Exclude paths for sec scanners
  sec-scanners-config.yaml
Labels: kind/bug, size/XS, lgtm, area/security, cla: yes
