Repository kyma-project/busola, pull requests merged in 2023-08, with the labels that each got.

#2533 change combobocinput to dropdown
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/Modules/Modules.js
Labels: size/S, lgtm

#2535 fix for default expanded flag
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/CollapsibleRenderer.js
  src/components/Extensibility/components-form/GenericList.js
  src/components/Extensibility/components-form/KeyValuePairRenderer.js
  src/components/Extensibility/components-form/MonacoRenderer.js
  src/components/Extensibility/components-form/ResourceRefRenderer.js
  src/components/Extensibility/components-form/SimpleList.js
Labels: size/S, lgtm

#2534 fix no modules and one module
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/Modules/Modules.js
Labels: size/S, lgtm

#2537 move tests from `nkyma` to k3d
  resources/web/deployment.yaml
  src/components/App/IncorrectPath.js
  tests/integration/cypress.config.js
  tests/integration/scripts/busola-integration-k3s.sh
  tests/integration/support/login-commands.js
  tests/integration/tests/cluster/test-navigation-features.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-services.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/lighthouse/lighthouse.spec.js
  tests/lighthouse/scripts/busola-lighthouse.sh
Labels: size/L, lgtm

#2498 Use webcomponents in side navigation
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/index.js
  src/sidebar/CategoryItem.scss
  src/sidebar/CategoryItem.tsx
  src/sidebar/NavItem.scss
  src/sidebar/NavItem.tsx
  src/sidebar/Sidebar.scss
  src/sidebar/SidebarNavigation.tsx
  src/sidebar/useSidebarCondensed.tsx
  src/state/preferences/isSidebarCondensedAtom.ts
  tests/integration/fixtures/test-customresourcedefinisions-cluster.yaml
  tests/integration/fixtures/test-customresourcedefinisions-namespaced.yaml
  tests/integration/support/commands.js
  tests/integration/support/createNamespace.js
  tests/integration/support/login-commands.js
  tests/integration/support/navigate-to.js
  tests/integration/support/views/api-rules-view.js
  tests/integration/support/views/functions-view.js
  tests/integration/tests/cluster/test-cluster-configuration.spec.js
  tests/integration/tests/cluster/test-cluster-overview.spec.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-services.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/namespace/a-run-before.spec.js
  tests/integration/tests/namespace/test-config-maps.spec.js
  tests/integration/tests/namespace/test-custom-resources.spec.js
  tests/integration/tests/namespace/test-deployments.spec.js
  tests/integration/tests/namespace/test-events.spec.js
  tests/integration/tests/namespace/test-protected-resources.spec.js
  tests/integration/tests/namespace/test-reduced-permissions--configuration.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/integration/tests/namespace/test-replica-sets.spec.js
  tests/integration/tests/namespace/test-resource-upload.spec.js
  tests/integration/tests/namespace/test-roles.spec.js
  tests/integration/tests/namespace/test-settings.spec.js
  tests/integration/tests/namespace/z-run-after.spec.js
Labels: size/XXL, lgtm

#2531 Cluster Validation Scan
  docs/features.md
  docs/resource-validation/README.md
  package-lock.json
  package.json
  public/defaultConfig.yaml
  public/i18n/en.yaml
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  src/components/Clusters/views/ClusterOverview/ClusterValidation/ClusterValidation.tsx
  src/components/Clusters/views/ClusterOverview/ClusterValidation/ClusterValidationConfiguration.js
  src/components/Clusters/views/ClusterOverview/ClusterValidation/ResourceLoader.ts
  src/components/Clusters/views/ClusterOverview/ClusterValidation/ResourceValidation.ts
  src/components/Clusters/views/ClusterOverview/ClusterValidation/ResourceValidation.worker.ts
  src/components/Clusters/views/ClusterOverview/ClusterValidation/Scan.ts
  src/components/Clusters/views/ClusterOverview/ClusterValidation/ScanConfiguration.ts
  src/components/Clusters/views/ClusterOverview/ClusterValidation/ScanResult.ts
  src/components/Clusters/views/ClusterOverview/ClusterValidation/ScanResultTree.tsx
  src/hooks/useAvailableNamespaces.ts
  src/resources/Roles/RuleInput.js
  src/shared/ResourceForm/inputs/Checkboxes.js
  src/shared/hooks/useValidateResourceBySchema/useValidateResourceBySchema.ts
  src/state/permissionSetsSelector.ts
  src/state/resourcesAtom.ts
  src/state/types.ts
  src/state/validationEnabledSchemasAtom.ts
  src/types/index.ts
  tests/integration/cypress.config.js
  tests/integration/scripts/busola-integration-k3s.sh
  tests/integration/tests/cluster/test-cluster-validation.spec.js
Labels: size/XXL, lgtm

#2542 ui5 status badge
  config-overrides.js
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/components/HelmReleases/HelmReleaseStatus.js
  src/shared/components/RunningPodsStatus.js
  src/shared/components/SchemaViewer/JSONSchema.js
  src/shared/components/StatusBadge/StatusBadge.js
  src/shared/components/TooltipBadge/TooltipBadge.js
Labels: size/M, lgtm

#2557 bump
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/XS

#2544 Migrate messageBox to webcomponents
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/components/App/IncorrectPath.js
  src/components/App/IncorrectPath.scss
  src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
  src/setupTests.js
  src/shared/components/ResourceDetails/tests/ResourceDetails.test.js
  src/shared/hooks/useDeleteResource.js
  src/shared/hooks/useDeleteResource.scss
  tests/integration/support/commands.js
  tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/namespace/test-custom-resources.spec.js
  tests/integration/tests/namespace/test-jobs.spec.js
  tests/integration/tests/namespace/test-namespace-overview.spec.js
  tests/integration/tests/namespace/test-navigation.spec.js
  tests/integration/tests/namespace/test-protected-resources.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/integration/tests/namespace/test-resource-upload.spec.js
  tests/integration/tests/namespace/test-resource-validation.spec.js
  tests/integration/tests/namespace/test-settings.spec.js
  tests/integration/tests/namespace/z-run-after.spec.js
Labels: size/L, lgtm

#2545 Update links for the domain change
  resources/web/deployment.yaml
  src/resources/RoleBindings/GenericRoleBindingList.js
  src/resources/Roles/GenericRoleList.js
Labels: size/XS, lgtm

#2558 Ui5 message strips
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/components/BusolaExtensions/BusolaExtensionDetails.js
  src/components/BusolaExtensions/ColumnsInput.js
  src/components/Clusters/components/AddClusterWizard.js
  src/components/Clusters/components/AuthForm.js
  src/components/Clusters/components/ContextChooser/ContextChooser.js
  src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  src/components/Extensibility/components-form/AlertRenderer.js
  src/components/Extensibility/components-form/Modules/Modules.js
  src/components/Extensibility/components/Alert.js
  src/components/Gardener/GardenerLogin.tsx
  src/resources/Jobs/ContainersSection.js
  src/resources/Jobs/ContainersSection.scss
  src/resources/Jobs/JobCreate.js
  src/resources/Jobs/ScheduleSection.js
  src/resources/Namespaces/YamlUpload/FilteredResourcesDetails/FilteredResourcesDetails.js
  src/resources/Namespaces/YamlUpload/FilteredResourcesDetails/FilteredResourcesDetails.scss
  src/resources/RoleBindings/GenericRoleBindingCreate.js
  src/resources/Roles/InvalidRoleError.js
  src/resources/Roles/RuleInput.js
  src/resources/ServiceAccounts/ServiceAccountCreate.js
  src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.tsx
  src/shared/ResourceForm/ForceUpdateModalContent.tsx
  src/shared/ResourceForm/components/CollapsibleSection.scss
  src/shared/ResourceForm/fields/ItemArray.js
  src/shared/components/Deployment/Containers.js
  src/shared/components/LogsLink/LogsLink.js
  src/shared/components/MonacoEditorESM/Editor.js
  src/shared/components/ResourceRef/ExternalResourceRef.js
  src/shared/contexts/NotificationContext.tsx
  src/shared/hooks/useDeleteResource.js
  src/styles/index.scss
  tests/integration/tests/cluster/test-invalid-kubeconfig.spec.js
  tests/integration/tests/namespace/test-resource-validation.spec.js
Labels: size/L, lgtm

#2560 UI5-breadcrumbs
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/resources/RoleBindings/GenericRoleBindingList.js
  src/resources/Roles/GenericRoleList.js
  src/shared/components/PageHeader/PageHeader.js
  src/shared/components/PageHeader/test/PageHeader.test.js
  tests/integration/cypress.config.js
  tests/integration/support/index.js
  tests/integration/support/inspect-list.js
  tests/integration/support/navigate-back-to.js
  tests/integration/tests/cluster/test-cluster-configuration.spec.js
  tests/integration/tests/cluster/test-cluster-overview.spec.js
  tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
  tests/integration/tests/cluster/test-cluster-validation.spec.js
  tests/integration/tests/cluster/test-command-palette.spec.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/cluster/test-invalid-kubeconfig.spec.js
  tests/integration/tests/cluster/test-persistent-volumes.spec.js
  tests/integration/tests/cluster/test-storage-classes.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-services.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/namespace/a-run-before.spec.js
  tests/integration/tests/namespace/test-config-maps.spec.js
  tests/integration/tests/namespace/test-cron-jobs.spec.js
  tests/integration/tests/namespace/test-deployments.spec.js
  tests/integration/tests/namespace/test-events.spec.js
  tests/integration/tests/namespace/test-ingresses.spec.js
  tests/integration/tests/namespace/test-jobs.spec.js
  tests/integration/tests/namespace/test-namespace-overview.spec.js
  tests/integration/tests/namespace/test-navigation.spec.js
  tests/integration/tests/namespace/test-network-policies.spec.js
  tests/integration/tests/namespace/test-persistent-volume-claims.spec.js
  tests/integration/tests/namespace/test-protected-resources.spec.js
  tests/integration/tests/namespace/test-reduced-permissions--configuration.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/integration/tests/namespace/test-replica-sets.spec.js
  tests/integration/tests/namespace/test-resource-upload.spec.js
  tests/integration/tests/namespace/test-roles.spec.js
  tests/integration/tests/namespace/test-service-accounts.spec.js
  tests/integration/tests/namespace/test-settings.spec.js
  tests/integration/tests/namespace/z-run-after.spec.js
Labels: size/L, lgtm

#2555 shellbar ui5
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/clusterDetailsNode.ts
  src/header/Header.scss
  src/header/Header.tsx
  src/header/Logo/Logo.scss
  src/header/Logo/Logo.tsx
  src/header/NamespaceDropdown/NamespaceDropdown.test.tsx
  src/header/NamespaceDropdown/NamespaceDropdown.tsx
  src/header/SidebarSwitcher/SidebarSwitcher.tsx
  src/sidebar/SidebarNavigation.tsx
  src/state/navigation/addAdditionalNodes.ts
  tests/integration/support/commands.js
  tests/integration/support/helpers.js
  tests/integration/tests/cluster/test-cluster-configuration.spec.js
  tests/integration/tests/cluster/test-cluster-overview.spec.js
  tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
  tests/integration/tests/cluster/test-cluster-validation.spec.js
  tests/integration/tests/cluster/test-download-a-kubeconfig.spec.js
  tests/integration/tests/cluster/test-multiple-context-kubeconfig.spec.js
  tests/integration/tests/cluster/test-storage-classes.spec.js
  tests/integration/tests/namespace/test-cron-jobs.spec.js
  tests/integration/tests/namespace/test-persistent-volume-claims.spec.js
  tests/integration/tests/namespace/test-protected-resources.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/integration/tests/namespace/test-resource-upload.spec.js
  tests/integration/tests/namespace/test-resource-validation.spec.js
  tests/integration/tests/namespace/test-service-accounts.spec.js
  tests/integration/tests/namespace/test-settings.spec.js
Labels: size/XL, lgtm

#2562 Horizon theme
  package.json
  public/assets/logo-blue.svg
  public/i18n/en.yaml
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/components/App/useInitTheme.ts
  src/components/Preferences/ThemeChooser.tsx
  src/components/Preferences/ThemePreview/ThemePreview.scss
  src/components/Preferences/ThemePreview/ThemePreview.tsx
  src/header/Logo/Logo.tsx
  src/header/NamespaceDropdown/NamespaceDropdown.tsx
  src/index.js
  src/sidebar/Sidebar.scss
  src/state/preferences/isSidebarCondensedAtom.ts
  src/state/preferences/themeAtom.ts
  src/styles/index.scss
  tests/integration/tests/namespace/test-settings.spec.js
Labels: size/L, lgtm

#2565 Removed icon on notification message-strip
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/shared/contexts/NotificationContext.tsx
Labels: size/XS, lgtm

#2567 hide sidebar-switcher on cluster overview
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/header/Header.tsx
Labels: size/XS, lgtm

#2564 ui5-wizards
  resources/web/deployment.yaml
  src/components/Clusters/components/AddClusterWizard.js
  src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.scss
  src/components/Extensibility/ExtensibilityWizard.js
  src/shared/components/FileInput/FileInput.scss
  src/shared/components/WizardButtons/WizardButtons.js
  src/styles/wizard-dialog.scss
  tests/integration/support/login-commands.js
  tests/integration/tests/cluster/test-invalid-kubeconfig.spec.js
  tests/integration/tests/cluster/test-multiple-context-kubeconfig.spec.js
  tests/lighthouse/lighthouse.spec.js
Labels: size/L, lgtm
