Repository kyma-project/busola, pull requests merged in 2023-01, with the labels that each got.

#2242 add readOnly prop from schema and add to docs
  core-ui/public/schemas/schema-form.yaml
  core-ui/src/components/Extensibility/components-form/StringRenderer.js
  docs/extensibility/form-section.md
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2234 Invalid cluster message
  core-ui/public/i18n/en.yaml
  core-ui/src/components/App/resourceSchemas/useResourceSchemas.ts
  core-ui/src/components/Clusters/views/ClusterList.js
  core-ui/src/shared/contexts/NotificationContext.js
  core-ui/src/state/navigation/extensionsAtom.ts
  core-ui/src/state/openapi/openapiPathIdSelector.ts
  core-ui/src/state/openapi/openapiSelector.ts
  resources/web/deployment.yaml
Labels: size/L, lgtm

#2254 fix links
  core-ui/src/resources/DnsEntries/DnsEntryList.js
  core-ui/src/resources/DnsProviders/DnsProviderList.js
  core-ui/src/resources/OAuth2Clients/OAuth2ClientList.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#2243 remove tests and extensions moved to kyma-dashboard
  OWNERS_ALIASES
  docs/extensibility/README.md
  examples/resources/configuration/dns-providers.yaml
  examples/resources/gateway/apirules.yaml
  examples/resources/istio/authorization-policies.yaml
  examples/resources/istio/destination-rules.yaml
  examples/resources/istio/gateways.yaml
  examples/resources/istio/service-entries.yaml
  examples/resources/istio/sidecars.yaml
  examples/resources/istio/virtual-services.yaml
  examples/resources/serverless/functions.yaml
  extensions/extensions.json
  gulpfile.js
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  tests/fixtures/in-cluster-eventing-publisher-dependencies.json
  tests/fixtures/in-cluster-eventing-publisher.js
  tests/fixtures/in-cluster-eventing-receiver-dependencies.json
  tests/fixtures/in-cluster-eventing-receiver.js
  tests/fixtures/orders-function-dependencies.json
  tests/fixtures/test-virtual-service.yaml
  tests/tests/cluster/test-applications.spec.js
  tests/tests/namespace/run-prepare-functions.spec.js
  tests/tests/namespace/test-api-rules.spec.js
  tests/tests/namespace/test-authorization-policies.spec.js
  tests/tests/namespace/test-custom-resources.spec.js
  tests/tests/namespace/test-destination-rules.spec.js
  tests/tests/namespace/test-gateways.spec.js
  tests/tests/namespace/test-in-cluster-eventing.spec.js
  tests/tests/namespace/test-service-entries.spec.js
  tests/tests/namespace/test-sidecars.spec.js
  tests/tests/namespace/test-virtual-services.spec.js
Labels: size/XXL, lgtm

#2233 fix: non-existing Namespace displays details/list
  core-ui/src/components/App/NamespaceRoutes.tsx
  core-ui/src/header/Header.tsx
  core-ui/src/header/NamespaceDropdown/NamespaceDropdown.tsx
  core-ui/src/hooks/useAvailableNamespaces.ts
  core-ui/src/resources/Namespaces/NamespaceCreate.js
  core-ui/src/shared/components/ResourcesList/ResourcesList.js
  core-ui/src/shared/contexts/ErrorModal/ErrorModal.tsx
  core-ui/src/shared/contexts/NotificationContext.tsx
  core-ui/src/shared/hooks/BackendAPI/useGet.js
  core-ui/src/state/navigation/extensionsAtom.ts
  docs/features.md
  resources/web/deployment.yaml
  tests/integration/tests/cluster/test-navigation-features.spec.js
  tests/integration/tests/namespace/test-events.spec.js
Labels: kind/bug, size/L, lgtm

#2261 fix: sentry issues
  core-ui/src/components/Extensibility/components-form/ResourceRefRenderer.js
  core-ui/src/shared/components/Link/Link.tsx
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#2267 remove enabling ext manualy and tests related to applications
  examples/resources/applicationconnector/applications.yaml
  tests/integration/cypress.json
  tests/integration/fixtures/yaml-upload--valid.yaml
  tests/integration/support/mockConfig.js
  tests/integration/tests/cluster/run-after.spec.js
  tests/integration/tests/cluster/run-before.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-services.spec.js
  tests/integration/tests/namespace/test-resource-upload.spec.js
Labels: size/L, lgtm

#2251 Prettier tests
  core-ui/src/components/Extensibility/components-form/Jsonata.js
  core-ui/src/components/Extensibility/components-form/MultiType.js
  core-ui/src/components/Extensibility/components-form/NumberRenderer.js
  core-ui/src/components/Extensibility/components-form/ResourceRenderer.js
  core-ui/src/components/Extensibility/components-form/StringRenderer.js
  core-ui/src/components/Extensibility/components-form/SwitchRenderer.js
  examples/testing/configuration/test-resource-configmap.yaml
  examples/testing/configuration/test-resource-crd.yaml
  examples/testing/samples/test-resource-samples.yaml
  resources/web/deployment.yaml
  tests/integration/cypress.json
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
Labels: size/L, lgtm

#2268 Fix Alerts in GenericList
  core-ui/src/components/Extensibility/helpers/prepareSchemaRules.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2269 change json to yaml for generating extension
  core-ui/src/components/BusolaExtensions/helpers.js
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#2271 fix require name
  core-ui/src/shared/ResourceForm/fields/K8sNameField.js
  docs/extensibility/form-section.md
  resources/web/deployment.yaml
Labels: size/XS, lgtm

#2273 fix properties override
  core-ui/src/components/Extensibility/plugins/SchemaRulesInjector.js
  resources/web/deployment.yaml
Labels: size/S, lgtm

#2238 Dnsproviders as extension
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/resources/DnsProviders/DnsProviderCreate.js
  src/resources/DnsProviders/DnsProviderDetails.js
  src/resources/DnsProviders/DnsProviderList.js
  src/resources/DnsProviders/ProviderTypeDropdown.js
  src/resources/DnsProviders/index.js
  src/resources/DnsProviders/templates.js
  src/resources/index.js
  tests/integration/cypress.json
  tests/integration/tests/namespace/test-dns-providers.spec.js
Labels: size/XL, lgtm

#2211 added configuration for dnsEntries
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/resources/DnsEntries/DNSNameRef.js
  src/resources/DnsEntries/DnsEntryCreate.js
  src/resources/DnsEntries/DnsEntryDetails.js
  src/resources/DnsEntries/DnsEntryList.js
  src/resources/DnsEntries/TargetsRef.js
  src/resources/DnsEntries/TargetsRef.scss
  src/resources/DnsEntries/helpers.js
  src/resources/DnsEntries/index.js
  src/resources/index.js
  tests/integration/cypress.json
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/namespace/test-dns-entries.spec.js
Labels: size/XL, lgtm

#2245 Bump codeql
  .github/workflows/codeql-analysis.yml
Labels: size/M, lgtm

#2276 Bump minimatch and minimist
  backend/package-lock.json
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  tests/integration/package-lock.json
Labels: size/M, lgtm

#2277 fix auth update on cluster switch
  resources/web/deployment.yaml
  src/components/App/ClusterRoutes.js
  src/components/App/resourceSchemas/useResourceSchemas.ts
  src/components/Clusters/components/AddClusterWizard.js
  src/components/Clusters/views/EditCluster/EditCluster.js
Labels: size/M, lgtm

#2281 Sort items in side nav
  resources/web/deployment.yaml
  src/state/navigation/assignToCategories.ts
Labels: size/S, lgtm

#2284 add "decode" option to panel
  docs/extensibility/display-section.md
  public/schemas/schema-details.yaml
  resources/web/deployment.yaml
  src/components/Extensibility/components/Panel.js
Labels: size/M, lgtm

#2237 Issuers as extension
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/Clusters/views/EditCluster/AuthenticationDropdown.js
  src/resources/Issuers/IssuerCreate.js
  src/resources/Issuers/IssuerDetails.js
  src/resources/Issuers/IssuerDomains.js
  src/resources/Issuers/IssuerList.js
  src/resources/Issuers/IssuerTypeDropdown.js
  src/resources/Issuers/helpers.js
  src/resources/Issuers/index.js
  src/resources/Issuers/templates.js
  src/resources/index.js
  tests/integration/cypress.json
  tests/integration/tests/namespace/test-issuers.spec.js
Labels: size/XL, lgtm

#2235 Fetch namespace-specific extensions when entering a namespace
  package-lock.json
  resources/web/deployment.yaml
  src/hooks/useAvailableNamespaces.ts
  src/state/navigation/extensionsAtom.ts
  src/state/navigation/filters/permissions.ts
  src/state/navigation/sidebarNavigationNodesSelector.ts
  tests/integration/cypress.json
  tests/integration/support/commands.js
  tests/integration/tests/namespace/test-reduced-permissions--configuration.spec.js
Labels: size/L, lgtm

#2290 fix Combobox css
  resources/web/deployment.yaml
  src/shared/ResourceForm/inputs/ComboboxInput.js
  src/shared/ResourceForm/inputs/ComboboxInput.scss
Labels: size/S, lgtm

#2279 genericList required
  docs/extensibility/form-section.md
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/GenericList.js
  src/shared/ResourceForm/components/CollapsibleSection.js
  src/shared/ResourceForm/components/CollapsibleSection.scss
Labels: size/S, lgtm

#2287 fix: navigate to namespace with limited access
  resources/web/deployment.yaml
  src/components/App/IncorrectPath.js
  src/components/App/NamespaceRoutes.tsx
  src/resources/Namespaces/NamespaceCreate.js
  tests/integration/cypress.json
  tests/integration/tests/namespace/test-navigation.spec.js
Labels: size/M, lgtm, priority/critical

#2293 bump hpa to v2 and adjust non required fields
  examples/apps/whoami/all.yaml
  public/i18n/en.yaml
  resources/backend/hpa.yaml
  resources/web/deployment.yaml
  resources/web/hpa.yaml
  src/hooks/useVersionWarning.ts
  src/resources/HorizontalPodAutoscalers/HPABehavior.js
  src/resources/HorizontalPodAutoscalers/HPASubcomponent.js
  src/resources/HorizontalPodAutoscalers/HorizontalPodAutoscalerDetails.js
  src/resources/HorizontalPodAutoscalers/index.ts
  src/resources/HorizontalPodAutoscalers/templates.js
  tests/integration/fixtures/test-HPA.yaml
  tests/integration/tests/namespace/test-HPA.spec.js
  tests/integration/tests/namespace/test-navigation.spec.js
Labels: size/L, lgtm

#2297 fix: comparing extensions' properties
  resources/web/deployment.yaml
  src/state/navigation/extensionsAtom.ts
Labels: kind/bug, size/M, lgtm

#2270 feat: adjust ServiceAccounts to the Kubernetetes 1.24 version
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/hooks/useCreateKubeconfig.ts
  src/resources/ServiceAccounts/GenericSecrets.js
  src/resources/ServiceAccounts/ServiceAccountCreate.js
  src/resources/ServiceAccounts/ServiceAccountDetails.js
  src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.scss
  src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.tsx
  src/resources/ServiceAccounts/TokenRequestModal/useGenerateTokenRequest.ts
  src/resources/ServiceAccounts/useDownloadKubeconfigWithToken.ts
  src/resources/ServiceAccounts/useDownloadSecretKubeconfig.tsx
  src/shared/hooks/BackendAPI/usePost.ts
  tests/integration/tests/cluster/test-navigation-features.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/integration/tests/namespace/test-service-accounts.spec.js
Labels: kind/feature, size/XL, lgtm

#2289 Multi checkbox
  docs/extensibility/assets/form-widgets/MultiCheckbox.png
  docs/extensibility/form-section.md
  examples/testing/configuration/test-resource-configmap.yaml
  examples/testing/configuration/test-resource-crd.yaml
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/MultiCheckbox.js
  src/components/Extensibility/components-form/index.js
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/components/FormField.scss
  src/shared/ResourceForm/inputs/Checkboxes.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
Labels: size/L, lgtm

#2294 Update ExternalLink.js
  resources/web/deployment.yaml
  src/components/Extensibility/components/ExternalLink.js
Labels: size/XS, lgtm

#2308 feat: improve readable timestamp to show remaining time & fix: ResourceGraph
  resources/web/deployment.yaml
  src/resources/ServiceAccounts/index.ts
  src/shared/components/ReadableCreationTimestamp/ReadableCreationTimestamp.tsx
Labels: kind/feature, size/M, lgtm

#2309 fix: synchronize Resource and ResourceRef API
  docs/extensibility/form-section.md
  public/schemas/schema-form.yaml
  resources/web/deployment.yaml
  src/components/Extensibility/components-form/ResourceRefRenderer.js
  src/components/Extensibility/components-form/ResourceRenderer.js
Labels: size/S, lgtm

#2318 On local busola hide only kube-public
  docs/features.md
  public/defaultConfig.yaml
  resources/web/deployment.yaml
  tests/integration/tests/namespace/test-settings.spec.js
  tests/integration/tests/namespace/test-stateful-sets.spec.js
Labels: size/M, lgtm

#2315 fix: display HPAs on Replicaset details view
  resources/web/deployment.yaml
  src/resources/HorizontalPodAutoscalers/HPASubcomponent.js
Labels: size/L, lgtm

#2319 Tiny UI fix
  resources/web/deployment.yaml
  src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.js
  src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.scss
Labels: size/XS, lgtm

#2306 fix: namespace dropdown switch context
  resources/web/deployment.yaml
  src/header/Header.tsx
  src/header/NamespaceDropdown/NamespaceDropdown.test.tsx
  src/header/NamespaceDropdown/NamespaceDropdown.tsx
  src/hooks/useUrl.ts
  src/state/types.ts
Labels: size/L, lgtm

#2323 Preference switch for Resource validation
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/Preferences/Preferences.tsx
  src/components/Preferences/ResourcesValidationSettings.tsx
  src/resources/Namespaces/YamlUpload/FilteredResourcesDetails/FilteredResourcesDetails.js
  src/resources/Namespaces/YamlUpload/YamlResourcesList.js
  src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
  src/state/preferences/validateResourcesAtom.ts
Labels: size/M, lgtm
