Repository kyma-project/busola, pull requests merged in 2024-11, with the labels that each got.

#3440 fix: adjust render, css names and imports
  src/components/App/ContentWrapper/ContentWrapper.scss
  src/components/Clusters/views/ClusterOverview/ClusterValidation/ClusterValidation.tsx
  src/components/KymaModules/KymaModulesList.js
  src/components/KymaModules/ModulesCard.js
  src/header/Header.tsx
  src/index.tsx
  src/resources/Namespaces/YamlUpload/ResourceValidationResult.js
  src/resources/Namespaces/YamlUpload/YamlResourcesList.js
  src/resources/Namespaces/YamlUpload/YamlUpload.js
  src/shared/ResourceForm/components/CollapsibleSection.js
  src/shared/components/ExpandableListItem/ExpandableListItem.tsx
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/SortModalPanel.js
  src/shared/components/GenericList/components.js
  src/shared/components/Labels/Labels.js
  src/shared/components/PodTemplate/components.js
  src/shared/components/ResourceGraph/ResourceGraph.tsx
  src/shared/components/UI5Panel/UI5Panel.tsx
  src/sidebar/NavItem.tsx
  src/sidebar/Sidebar.scss
  src/styles/index.scss
Labels: size/L, lgtm, cla: yes

#3437 fix: allow usage of special characters in cluster context by encoding
  src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/crHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/crListHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/crdHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/helmReleaseHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/logsHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/nodesHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/nonResourceHandler.ts
  src/components/Clusters/shared.ts
  src/components/Clusters/views/ClusterList.js
  src/header/Header.tsx
  src/hooks/useUrl.ts
  src/resources/Namespaces/NamespaceList.js
  src/shared/hooks/useDeleteResource.js
  src/state/authDataAtom.ts
  src/state/useAfterInitHook.ts
Labels: size/L, lgtm, cla: yes

#3449 fix: Ui5 codemod adjustments
  src/components/BusolaExtensions/BusolaExtensionDetails.js
  src/components/BusolaExtensions/ColumnsInput.js
  src/components/Clusters/components/AddClusterDialog.js
  src/components/Clusters/components/AddClusterWizard.js
  src/components/Clusters/components/AuthForm.js
  src/components/Clusters/components/KubeconfigUpload/KubeconfigFileUpload.js
  src/components/Clusters/views/ClusterOverview/ClusterValidation/ClusterValidation.tsx
  src/components/Clusters/views/ClusterOverview/ClusterValidation/ClusterValidationConfiguration.js
  src/components/Extensibility/components-form/Modules/Modules.js
  src/components/Extensibility/components-form/MultiType.js
  src/components/Extensibility/components/ExternalLink.js
  src/components/Extensibility/components/ExternalLinkButton.js
  src/components/Extensibility/components/ResourceButton.js
  src/components/Extensibility/components/Wizard.js
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesCreate.js
  src/components/Preferences/Preferences.tsx
  src/components/Preferences/ResourceValidation/ResourceValidationSettings.tsx
  src/resources/Events/EventDetails.js
  src/resources/Events/EventList.js
  src/resources/Namespaces/YamlUpload/ResourceValidationResult.js
  src/resources/Namespaces/YamlUpload/YamlResourcesList.js
  src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
  src/resources/RoleBindings/GenericRoleBindingCreate.js
  src/resources/Roles/InvalidRoleError.js
  src/resources/Roles/RuleInput.js
  src/resources/ServiceAccounts/ServiceAccountCreate.js
  src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.tsx
  src/shared/ResourceForm/ForceUpdateModalContent.tsx
  src/shared/ResourceForm/components/ModeSelector.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/fields/DataField.js
  src/shared/ResourceForm/fields/ItemArray.js
  src/shared/components/CopiableText/CopiableText.js
  src/shared/components/Deployment/Containers.js
  src/shared/components/DescriptionHint/DescriptionHint.tsx
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/EmptyListComponent/EmptyListComponent.tsx
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/components.js
  src/shared/components/ListActions/ListActions.js
  src/shared/components/Modal/Modal.js
  src/shared/components/ModalWithForm/ModalWithForm.js
  src/shared/components/MonacoEditorESM/Editor.js
  src/shared/components/PopoverBadge/PopoverBadge.tsx
  src/shared/components/ResourceRef/ExternalResourceRef.js
  src/shared/components/SchemaViewer/JSONSchema.js
  src/shared/components/SchemaViewer/SchemaViewer.js
  src/shared/components/ServiceAccountTokenStatus.tsx
  src/shared/contexts/ErrorModal/ErrorModal.tsx
  src/shared/hooks/useProtectedResources.js
Labels: size/L, lgtm, cla: yes

#3453 docs: add issue template for epics
  .github/ISSUE_TEMPLATE/epic.md
Labels: size/M, lgtm, cla: yes

#3445 fix: adjust DynamicPageComponent
  src/shared/ResourceForm/components/ModeSelector.js
  src/shared/ResourceForm/components/ResourceForm.scss
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
  src/shared/components/GenericList/GenericList.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourcesList/ResourcesList.js
Labels: size/L, lgtm, cla: yes

#3460 fix: Fix search slash
  src/shared/components/GenericList/SearchInput.js
Labels: size/XS, lgtm, cla: yes

#3444 feat: enum parameter for Number Form Widget
  docs/extensibility/60-form-widgets.md
  public/schemas/schema-form.yaml
  src/components/Extensibility/components-form/NumberRenderer.js
  src/shared/ResourceForm/inputs/ComboboxInput.js
Labels: size/M, lgtm, cla: yes

#3462 fix: toast adjustments
  src/shared/contexts/NotificationContext.tsx
Labels: size/XS, lgtm, cla: yes

#3461 fix: wrong links
  docs/extensibility/50-list-and-details-widgets.md
Labels: size/XS, lgtm, cla: yes

#3463 fix: adjust tokens
  src/shared/components/Tokens.js
Labels: size/S, lgtm, cla: yes

#3466 feat: Add replicas to deployment form
  src/resources/Deployments/DeploymentCreate.js
Labels: size/S, lgtm, cla: yes

#3468 feat: FeatureCard without illustration
  docs/extensibility/50-list-and-details-widgets.md
  src/components/Extensibility/components/FeaturedCard/FeaturedCard.js
Labels: size/S, lgtm, cla: yes

#3464 fix: adjust badges
  src/components/Clusters/views/ClusterOverview/ClusterNodes.js
  src/components/Extensibility/components/Badge.js
  src/components/HelmReleases/HelmReleaseStatus.js
  src/components/KymaModules/KymaModulesList.js
  src/components/KymaModules/components/ModuleStatus.tsx
  src/resources/CustomResourceDefinitions/CurrentCRDVersion.js
  src/resources/Ingresses/IngressDetails.js
  src/resources/Jobs/JobCompletions.js
  src/resources/Jobs/JobConditions.js
  src/resources/Namespaces/NamespaceStatus.js
  src/resources/PersistentVolumes/PersistentVolumeStatus.js
  src/resources/Pods/ContainerStatus.js
  src/resources/Pods/PodRestarts.js
  src/resources/Pods/PodStatus.js
  src/shared/components/BTPResourceStatus.js
  src/shared/components/ExpandableListItem/ExpandableListItem.tsx
  src/shared/components/PersistentVolumeClaimStatus.js
  src/shared/components/PopoverBadge/PopoverBadge.tsx
  src/shared/components/RunningPodsStatus.js
  src/shared/components/StatusBadge/StatusBadge.js
  src/shared/components/SubscriptionConditionStatus.js
  src/shared/components/TooltipBadge/TooltipBadge.js
Labels: size/L, lgtm, cla: yes

#3470 feat: Move banner slot in the Resource components
  docs/extensibility/70-widget-injection.md
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourcesList/ResourcesList.js
Labels: size/M, lgtm, cla: yes

#3467 fix: adjust headers size
  src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  src/components/Clusters/views/ClusterOverview/ClusterStats.js
  src/components/Clusters/views/EditCluster/EditCluster.js
  src/components/Extensibility/components/FeaturedCard/FeaturedCard.js
  src/components/KymaModules/ModulesCard.js
  src/components/Nodes/NodeDetails/NodeDetails.js
  src/resources/CustomResourceDefinitions/CurrentCRDVersion.js
  src/resources/Namespaces/AllNamespacesDetails.js
  src/resources/Namespaces/YamlUpload/YamlResourcesList.js
  src/resources/ResourceQuotas/ResourceQuotaDetails.tsx
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceHealthCard/ResourceHealthCard.js
Labels: size/S, lgtm, cla: yes

#3469 fix: defaultProps
  src/components/Extensibility/ExtensibilityErrBoundary.js
  src/components/Extensibility/ExtensibilityList.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/ErrorBoundary/ErrorBoundary.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/Modal/Modal.js
  src/shared/components/ModalWithForm/ModalWithForm.js
  src/shared/components/ResourceCreate/ResourceCreate.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/shared/components/Tooltip/Tooltip.js
Labels: size/L, cla: yes

#3448 feat: add tooltips for other resource forms
  src/hooks/useGetSchema.js
  src/resources/ConfigMaps/ConfigMapCreate.js
  src/resources/CronJobs/CronJobCreate.js
  src/resources/Jobs/ContainersSection.js
  src/resources/Jobs/JobCreate.js
  src/resources/Jobs/ScheduleSection.js
  src/resources/Namespaces/NamespaceCreate.js
  src/resources/RoleBindings/GenericRoleBindingCreate.js
  src/resources/Roles/GenericRoleCreate.js
  src/resources/Roles/RuleInput.js
  src/resources/Secrets/SecretCreate.js
  src/resources/createResourceRoutes.js
  src/shared/ResourceForm/fields/ItemArray.js
  src/shared/ResourceForm/fields/RichEditorDataField/RichEditorDataField.js
  tests/integration/tests/namespace/test-cron-jobs.spec.js
Labels: size/L, lgtm, cla: yes

#3474 fix: spinner
  src/shared/components/Spinner/Spinner.tsx
Labels: size/XS, lgtm, cla: yes

#3477 chore: Allow run web-build against release featue branch
  .github/workflows/busola-web-build.yml
Labels: size/XS, lgtm, cla: yes

#3452 feat: Show resoruces per node
  public/i18n/en.yaml
  src/components/Nodes/MachineInfo/MachineInfo.js
  src/components/Nodes/NodeDetails/NodeDetails.js
  src/components/Nodes/NodeDetailsCard.js
  src/components/Nodes/NodeResources/NodeResources.js
  src/components/Nodes/nodeQueries.js
  src/components/Nodes/nodeQueries.test.js
  src/resources/Namespaces/ResourcesUsage.js
  src/shared/components/UI5RadialChart/UI5RadialChart.js
  src/shared/utils/helpers.js
Labels: size/L, lgtm, cla: yes

#3475 fix: theme is not working
  src/components/App/App.tsx
Labels: size/XS, lgtm, cla: yes

#3478 feat: Create release workflow skeleton
  .github/workflows/create-release.yml
Labels: size/L, lgtm, cla: yes

#3473 fix: adjust forms
  src/components/Extensibility/components-form/AlertRenderer.js
  src/components/Extensibility/components/Alert.js
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesAddModule.scss
  src/index.tsx
  src/shared/ResourceForm/components/Presets.js
  src/shared/ResourceForm/components/Presets.scss
  src/shared/ResourceForm/components/ResourceForm.scss
  src/shared/ResourceForm/inputs/Text.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/shared/components/UnsavedMessageBox/UnsavedMessageBox.tsx
  src/styles/reset.css
Labels: size/L, lgtm, cla: yes

#3488 feat: add rebase actions and add to test workflows
  .github/actions/rebase/action.yml
  .github/workflows/pull-integration-cluster-k3d.yml
  .github/workflows/pull-integration-namespace-k3d.yml
  .github/workflows/pull-kyma-integration-tests.yml
  .github/workflows/pull-lighthouse.yml
  .github/workflows/pull-smoke-test-prod.yml
  .github/workflows/pull-smoke-test-stage.yml
  .github/workflows/pull-unit-tests.yml
Labels: size/M, lgtm, cla: yes

#3487 fix: objectPageHeader styling and modules card
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
  src/shared/components/ResourceCreate/ResourceCreate.js
  src/shared/components/ResourceDetails/ResourceDetails.scss
Labels: size/XS, lgtm, cla: yes

#3484 fix: Truncated deep links
  src/components/Extensibility/components/ExternalLink.js
  src/resources/other/kymaModules.routes.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
  src/shared/components/ResourceDetails/ResourceDetails.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/namespace/test-service-accounts.spec.js
Labels: size/M, lgtm, cla: yes

#3491 fix: adjust V1 Tables
  package-lock.json
  package.json
  src/components/App/App.tsx
  src/components/App/ContentWrapper/ContentWrapper.scss
  src/components/App/UI5Imports.js
  src/header/Header.scss
  src/resources/Namespaces/YamlUpload/ResourceValidationResult.js
  src/shared/components/EmptyListComponent/EmptyListComponent.tsx
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/components.js
  src/sidebar/Sidebar.scss
  src/styles/index.scss
  src/styles/reset.css
Labels: size/L, lgtm, cla: yes

#3501 feat: Display modules status in the same way on all views
  kyma/extensions/kyma/kyma.yaml
  src/components/Extensibility/components/Badge.js
  src/components/Extensibility/helpers/jsonataWrapper.ts
Labels: size/S, lgtm, cla: yes
