Repository kyma-project/busola, pull requests merged in 2024-02, with the labels that each got.

#2760 Modules promotion banner
  docs/extensibility/assets/display-widgets/ExternalLinkButton.png
  docs/extensibility/assets/display-widgets/FeaturedCard.png
  docs/extensibility/assets/display-widgets/MessagePanel.png
  docs/extensibility/display-section.md
  resources/web/deployment.yaml
  src/components/Extensibility/components/ExternalLinkButton.js
  src/components/Extensibility/components/FeaturedCard/FeaturedCard.js
  src/components/Extensibility/components/FeaturedCard/FeaturedCard.scss
  src/components/Extensibility/components/FeaturedCard/assets/cardIllustration.svg
  src/components/Extensibility/components/FeaturedCard/assets/cardIllustrationHC.svg
  src/components/Extensibility/components/MessagePage.js
  src/components/Extensibility/components/Wizard.js
  src/components/Extensibility/components/index.js
Labels: size/L, lgtm, cla: yes

#2768 fix: create button on all namespaces list view
  resources/web/deployment.yaml
  src/resources/HorizontalPodAutoscalers/HPASubcomponent.js
  src/shared/components/EmptyListComponent/EmptyListComponent.tsx
  src/shared/components/ResourcesList/ResourcesList.js
  tests/integration/tests/cluster/test-cluster-validation.spec.js
Labels: size/S, lgtm, cla: yes

#2775 fix: displaying extensions view
  resources/web/deployment.yaml
  src/resources/other/BusolaExtensions.routes.js
Labels: size/XS, lgtm, priority/critical, cla: yes

#2774 feat: use latest image tag and remove need for bumps
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/XS, lgtm, priority/critical, cla: yes

#2764 Implement updated metadata view
  public/i18n/en.yaml
  src/resources/CronJobs/CronJobDescription.js
  src/resources/CronJobs/CronJobDetails.js
  src/resources/CronJobs/CronJobList.js
  src/resources/DaemonSets/DaemonSetDescription.js
  src/resources/DaemonSets/DaemonSetDetails.js
  src/resources/DaemonSets/DaemonSetList.js
  src/resources/Deployments/DeploymentDescription.js
  src/resources/Deployments/DeploymentDetails.js
  src/resources/Deployments/DeploymentList.js
  src/resources/Jobs/JobDescription.js
  src/resources/Jobs/JobDetails.js
  src/resources/Jobs/JobList.js
  src/shared/components/DescriptionHint/DescriptionHint.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/ReadableElapsedTimeFromNow/ReadableElapsedTimeFromNow.tsx
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceDetails/tests/ResourceDetailsColumns.test.js
  src/shared/components/ResourceDetails/tests/ResourceDetailsVisibility.test.js
  tests/integration/support/commands.js
  tests/integration/tests/namespace/test-deployments.spec.js
  tests/integration/tests/namespace/test-persistent-volume-claims.spec.js
  tests/integration/tests/namespace/test-replica-sets.spec.js
Labels: size/L, lgtm, cla: yes

#2756 feat: adjust add cluster wizard to new design
  public/i18n/en.yaml
  src/components/Clusters/components/AddClusterDialog.js
  src/components/Clusters/components/AddClusterWizard.js
  src/components/Clusters/components/AddClusterWizard.scss
  src/components/Clusters/components/AuthForm.js
  src/components/Clusters/components/ChooseStorage.js
  src/components/Clusters/components/ClusterPreview.js
  src/components/Clusters/components/ClusterPreview.scss
  src/components/Clusters/components/ContextChooser/ContextChooser.js
  src/components/Clusters/components/KubeconfigUpload/KubeconfigFileUpload.js
  src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.scss
  src/components/Clusters/components/oidc-params.ts
  src/components/Clusters/shared.ts
  src/components/Clusters/views/EditCluster/EditCluster.js
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/components/Label.js
  src/shared/ResourceForm/components/ModeSelector.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/components/ResourceForm.scss
  src/shared/ResourceForm/fields/Editor.js
  src/shared/components/FileInput/FileInput.js
  src/shared/components/FileInput/FileInput.scss
  src/shared/components/MonacoEditorESM/Editor.js
  src/shared/components/MonacoEditorESM/Editor.scss
  src/shared/components/WizardButtons/WizardButtons.js
  src/shared/contexts/YamlEditorContext/EditorActions.js
  src/shared/contexts/YamlEditorContext/EditorActions.scss
  tests/integration/support/login-commands.js
  tests/integration/tests/cluster/test-invalid-kubeconfig.spec.js
  tests/integration/tests/cluster/test-multiple-context-kubeconfig.spec.js
  tests/lighthouse/lighthouse.spec.js
Labels: size/XXL, lgtm, cla: yes

#2779 feat: set metadata styling when resource is fullScreen
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceDetails/ResourceDetails.scss
Labels: size/S, lgtm, cla: yes

#2788 feat: add eslint-check and remove unused file
  package.json
  src/testing/index.js
Labels: size/XS, lgtm, cla: yes

#2761 feat: implementation of Redesigned Status Card
  public/i18n/en.yaml
  src/components/Clusters/views/ClusterOverview/ClusterDetails.js
  src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  src/components/Extensibility/components/FeaturedCard/FeaturedCard.js
  src/resources/Deployments/DeploymentDetails.js
  src/shared/components/ExpandableListItem/ExpandableListItem.scss
  src/shared/components/ExpandableListItem/ExpandableListItem.tsx
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceDetails/ResourceDetails.scss
  src/shared/components/ResourceDetails/ResourceDetailsCard.js
  src/shared/components/ResourceStatusCard/ResourceStatusCard.js
  src/shared/components/ResourceStatusCard/ResourceStatusCard.scss
  src/shared/components/StatusBadge/StatusBadge.js
  src/shared/components/TooltipBadge/TooltipBadge.js
  tests/integration/tests/namespace/test-deployments.spec.js
Labels: size/L, lgtm, cla: yes

#2796 fix resourceButton
  src/components/Extensibility/components/ResourceButton.js
Labels: size/S, lgtm, cla: yes

#2797 fix: Monaco editor is white in dark theme
  src/shared/components/MonacoEditorESM/hooks/useCreateEditor.js
Labels: size/XS, lgtm, cla: yes
