Repository kyma-project/busola, pull requests merged in 2024-07, with the labels that each got.

#3018 feat: Adjust deployments
  public/i18n/en.yaml
  src/resources/Deployments/DeploymentDetails.js
Labels: size/M, lgtm, cla: yes

#3026 feat: allow to change channel for the module
  public/i18n/en.yaml
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesAddModule.scss
  src/components/KymaModules/KymaModulesList.js
  src/shared/components/PopoverBadge/PopoverBadge.scss
Labels: size/L, lgtm, cla: yes

#3032 fix: editing kyma resource
  src/components/KymaModules/KymaModulesCreate.js
Labels: size/XS, lgtm, cla: yes

#3023 test: added tests of radialgraph
  examples/injections/countingcard.yaml
  src/shared/components/UI5RadialChart/test/UI5RadialChart.test.js
  tests/integration/tests/cluster/test-cluster-overview.spec.js
Labels: size/M, lgtm, cla: yes

#3025 feat: move info from card to status in replicasets and statefulsets
  public/i18n/en.yaml
  src/resources/ReplicaSets/ReplicaSetDetails.js
  src/resources/StatefulSets/StatefulSetDetails.js
Labels: size/L, lgtm, cla: yes

#3034 fix: Disable delete if module is not in spec, assign findStatus to a variable
  src/components/KymaModules/KymaModulesList.js
Labels: size/M, lgtm, cla: yes

#3037 fix: Not able to add modules when there are none initially
  src/components/KymaModules/KymaModulesAddModule.js
Labels: size/XS, lgtm, cla: yes

#3045 fix: incorrect permissions for restricted users
  src/components/Clusters/views/ClusterOverview/ClusterValidation/Scan.ts
  src/components/Extensibility/helpers/jsonataWrapper.ts
  src/state/navigation/extensionsAtom.ts
  src/state/navigation/filters/permissions.ts
  src/state/permissionSetsSelector.ts
  src/state/utils/getConfigMaps.ts
  tests/integration/tests/namespace/test-reduced-permissions--configuration.spec.js
Labels: size/L, lgtm, cla: yes

#3046 docs: Documented SSL connectivity issues in the README
  README.md
Labels: size/M, lgtm, cla: yes

#3050 docs: fix readme
  README.md
Labels: size/XS, lgtm, cla: yes

#3047 fix: Modules disable link
  src/components/KymaModules/KymaModulesList.js
  src/resources/other/kymaModules.routes.js
  src/shared/components/GenericList/GenericList.js
Labels: size/M, lgtm, cla: yes

#3051 fix: remove empty space for empty health section
  src/components/Extensibility/ExtensibilityDetails.js
  src/components/Extensibility/ExtensibilityInjections.js
  src/shared/ResourceForm/fields/MultiInput.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/UnsavedMessageBox/UnsavedMessageBox.tsx
Labels: size/S, lgtm, cla: yes

#3020 test: e2e extensibility
  examples/extensions/configuration/potatoes-crd.yaml
  examples/extensions/configuration/potatoes-updates-details-view.yaml
  examples/extensions/samples/potato.yaml
  src/components/BusolaExtensions/BusolaExtensionCreate.js
  src/components/BusolaExtensions/ColumnsInput.js
  src/shared/ResourceForm/components/CollapsibleSection.js
  tests/integration/cypress.config.js
  tests/integration/support/navigate-to.js
  tests/integration/tests/extensibility/ext-test-extensibility.spec.js
  tests/integration/tests/namespace/test-ingresses.spec.js
  tests/integration/tests/namespace/test-jobs.spec.js
Labels: size/L, lgtm, cla: yes

#3048 fix: discard changes and unnecessary scroll in Modules form
  src/components/KymaModules/KymaModulesCreate.js
  src/components/KymaModules/KymaModulesCreate.scss
  src/components/KymaModules/KymaModulesList.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/ResourceDetails/ResourceDetails.js
Labels: size/M, lgtm, cla: yes

#3057 fix: modules view when modules are not presented in Kyma CR
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesList.js
Labels: size/XS, lgtm, cla: yes

#3060 chore: adjust PR template to match microdelivery specification
  .github/issue-template.md
  .github/pull-request-template.md
Labels: size/S, lgtm, cla: yes

#3056 Fix footer position
  src/shared/components/ResourceCreate/ResourceCreate.js
  tests/integration/support/create-edit-support.js
Labels: size/M, lgtm, cla: yes

#3052 feat: Add separate GHAction for lint check
  .github/workflows/busola-local-build.yml
  .github/workflows/lint-check-pr.yml
  src/shared/components/__mocks__/popper.js.js
Labels: size/S, lgtm, cla: yes

#3061 feat: take module state from module instead of kyma CR
  src/components/KymaModules/KymaModulesList.js
  src/components/KymaModules/components/ModuleStatus.tsx
  src/components/KymaModules/support.ts
  src/shared/components/PopoverBadge/PopoverBadge.tsx
Labels: size/L, lgtm, cla: yes

#3069 chore: bump alpine image
  Dockerfile
  Dockerfile.local
  backend/Dockerfile
Labels: size/XS, lgtm, cla: yes

#3066 feat: Improve pods statistics
  public/i18n/en.yaml
  src/components/Clusters/views/ClusterOverview/ClusterStats.js
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloadsHelpers.js
Labels: size/M, lgtm, cla: yes

#3058 fix: Fix tests after changing gardener flow
  tests/integration/cypress.config.js
  tests/integration/tests/cluster/test-cluster-configuration.spec.js
  tests/integration/tests/cluster/test-edit-cluster.spec.js
  tests/integration/tests/cluster/test-login-kubeconfigID.spec.js
  tests/integration/tests/cluster/test-other-login-options.spec.js
Labels: size/L, lgtm, cla: yes

#3053 fix(oidc): client secret may contain equal signs
  src/components/Clusters/components/oidc-params.ts
  src/components/Clusters/components/test/oidc-params.test.js
Labels: size/M, lgtm, cla: yes

#3065 feat: adjust module cards
  public/i18n/en.yaml
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesAddModule.scss
  src/components/KymaModules/ModulesCard.js
Labels: size/L, lgtm, cla: yes

#3072 feat: separate workflow for unit tests
  .github/workflows/pull-unit-tests.yml
  Dockerfile
  Dockerfile.local
Labels: size/M, lgtm, cla: yes

#3073 chore: remove node-sass library and add sass
  package-lock.json
  package.json
  src/shared/contexts/ErrorModal/ErrorModal.scss
Labels: size/XXL, lgtm, cla: yes

#3083 fix: checking is form is open
  src/shared/ResourceForm/components/ResourceForm.js
Labels: size/XS, lgtm, cla: yes

#3088 docs: fix links
  docs/extensibility/README.md
  docs/extensibility/jsonata.md
  docs/extensibility/resources.md
  docs/extensibility/wizard.md
Labels: size/S, lgtm, cla: yes

#3087 chore: remove unused packages from dockerfiles
  Dockerfile
  Dockerfile.local
  backend/Dockerfile
Labels: size/XS, lgtm, cla: yes

#3090 feat: add badge for overriden channel
  public/i18n/en.yaml
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesList.js
Labels: size/M, lgtm, cla: yes

#3085 fix: cursor pointer on GenericList
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/GenericList.scss
Labels: size/XS, lgtm, cla: yes

#3091 chore: add data-testid for advanced panel for module
  src/components/KymaModules/ModulesCard.js
Labels: size/XS, lgtm, cla: yes

#3071 fix: Show tooltip on defined widget
  docs/extensibility/60-form-widgets.md
  src/components/Clusters/views/ClusterStorageType.js
  src/components/Extensibility/components-form/FormGroup.js
  src/components/Extensibility/components-form/GenericList.js
  src/components/KymaModules/KymaModulesList.js
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/components/Title.js
  src/shared/components/DescriptionHint/DescriptionHint.tsx
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/GenericList/Pagination/Pagination.js
  src/shared/components/ResourceDetails/ResourceDetails.js
Labels: size/M, lgtm, cla: yes

#3092 fix: empty module list
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesList.js
Labels: size/XS, lgtm, cla: yes

#3093 feat: Show description tooltip on editor component
  src/components/Extensibility/components-form/MonacoRenderer.js
Labels: size/XS, lgtm, cla: yes

#3095 chore: Bump alpine and nginx images
  Dockerfile
  Dockerfile.local
  backend/Dockerfile
Labels: size/S, lgtm, cla: yes

#3075 feat: External navigation nodes as part of extensibility
  docs/extensibility/resources.md
  docs/features.md
  src/components/Extensibility/ExtensibilityInjections.js
  src/components/Extensibility/contexts/DataSources.tsx
  src/components/Extensibility/hooks/useJsonata.ts
  src/sidebar/CategoryItem.tsx
  src/sidebar/NavItem.tsx
  src/state/navigation/extensibilityNodesExtSelector.ts
  src/state/navigation/externalNodesSelector.ts
  src/state/navigation/sidebarNavigationNodesSelector.ts
  src/state/types.ts
Labels: size/L, lgtm, cla: yes

#3096 chore: Update certs
  backend/certs.pem
Labels: size/XL, lgtm, cla: yes

#3099 feat: Add statusBadge for extensibility
  docs/extensibility/30-details-summary.md
  docs/extensibility/50-list-and-details-widgets.md
  src/components/Extensibility/ExtensibilityDetails.js
  src/components/Extensibility/components/Badge.js
Labels: size/M, lgtm, cla: yes

#3098 feat: Edit module
  public/i18n/en.yaml
  src/components/KymaModules/KymaModulesCreate.js
  src/components/KymaModules/KymaModulesCreate.scss
  src/components/KymaModules/ModulesCard.js
  src/shared/ResourceForm/components/CollapsibleSection.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/useCreateResource.js
Labels: size/L, lgtm, cla: yes

#3094 feat: Add view allows only adding the modules
  public/i18n/en.yaml
  src/components/KymaModules/KymaModulesAddModule.js
Labels: size/S, lgtm, cla: yes
