Repository kyma-project/busola, pull requests merged in 2024-08, with the labels that each got.

#3097 feat: improve detecting links in tooltip and other texts
  src/components/Extensibility/components-form/GenericList.js
  src/components/Extensibility/helpers/index.js
  src/shared/components/DescriptionHint/DescriptionHint.tsx
  src/shared/helpers/linkExtractor.js.test.js
  src/shared/helpers/linkExtractor.tsx
Labels: size/L, lgtm, cla: yes

#3103 feat: delete modules from details
  public/i18n/en.yaml
  src/components/Extensibility/ExtensibilityDetails.js
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesList.js
  src/resources/CustomResourceDefinitions/CustomResources.details.js
  src/resources/other/kymaModules.routes.js
  src/shared/components/ResourceDetails/ResourceDetails.js
Labels: size/L, lgtm, cla: yes

#3114 fix: nodes details
  src/components/Nodes/NodeDetailsCard.js
Labels: size/XS, lgtm, cla: yes

#3108 fix: bug fixes
  src/components/BusolaExtensions/BusolaExtensionDetails.js
  src/resources/Roles/RuleInput.js
  src/shared/ResourceForm/fields/KeyValueField.js
  src/shared/components/CopiableText/CopiableText.js
  src/shared/components/GenericList/SortModalPanel.js
  src/shared/components/ListActions/ListActions.js
  src/shared/components/ListActions/ListActions.scss
  src/shared/components/Modal/Modal.js
  src/shared/components/ModalWithForm/ModalWithForm.js
  src/shared/components/ResourceCreate/ResourceCreate.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceGraph/SaveGraphControls.tsx
  src/shared/hooks/useDeleteResource.js
Labels: size/L, lgtm, cla: yes

#3115 feat: add external nodes for statics
  docs/extensibility/statics.md
  src/state/navigation/extensibilityNodesExtSelector.ts
  src/state/navigation/extensionsAtom.ts
Labels: size/M, lgtm, cla: yes

#3111 fix: UI5 toast component
  src/shared/contexts/NotificationContext.tsx
  src/styles/index.scss
  tests/integration/support/commands.js
Labels: size/M, lgtm, cla: yes

#3120 fix: links in tables
  src/components/Clusters/views/ClusterOverview/ClusterNodes.js
  src/shared/components/Link/Link.tsx
  tests/integration/tests/cluster/test-cluster-overview.spec.js
Labels: size/M, lgtm, cla: yes

#3104 feat: add schema for wizards
  public/schemas/schema-general.yaml
  public/schemas/schema-wizard.yaml
Labels: size/M, lgtm, cla: yes

#3121 fix: refresh on module details and module details not working properly
  src/components/Extensibility/ExtensibilityDetails.js
  src/resources/CustomResourceDefinitions/CustomResources.details.js
  src/resources/other/kymaModules.routes.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceNotFound/ResourceNotFound.js
  src/shared/helpers/linkExtractor.tsx
  src/shared/hooks/BackendAPI/useGet.js
Labels: size/M, lgtm, cla: yes

#3118 feat: uxc tables improvements
  src/components/Clusters/views/ClusterList.js
  src/components/Extensibility/helpers/index.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/GenericList.scss
  src/shared/components/GenericList/Pagination/Pagination.scss
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/shared/helpers/linkExtractor.tsx
  src/shared/hooks/useProtectedResources.js
  src/styles/index.scss
  tests/integration/support/commands.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
Labels: size/L, lgtm, cla: yes

#3128 fix: error positioning of table items
  src/shared/components/GenericList/components.js
Labels: size/XS, lgtm, cla: yes

#3117 feat: disableOnEdit Text widget
  docs/extensibility/60-form-widgets.md
  public/schemas/schema-form.yaml
  src/components/Extensibility/components-form/StringRenderer.js
Labels: size/XS, lgtm, cla: yes

#3130 fix: ControlledBy link for all namespaces
  src/resources/ConfigMaps/ConfigMapDetails.js
  src/resources/DaemonSets/DaemonSetDetails.js
  src/resources/Deployments/DeploymentDetails.js
  src/resources/Jobs/JobDetails.js
  src/resources/Jobs/JobList.js
  src/resources/Pods/PodDetails.js
  src/resources/ReplicaSets/ReplicaSetDetails.js
  src/resources/Secrets/SecretDetails.js
  src/resources/StatefulSets/StatefulSetDetails.js
  src/shared/components/ControlledBy/ControlledBy.js
Labels: size/M, lgtm, cla: yes

#3202 feat: Pass fallback namespace to datasources
  src/components/Extensibility/contexts/DataSources.tsx
Labels: size/XS, lgtm, cla: yes

#3207 feat: enhance network policies
  public/i18n/en.yaml
  src/resources/NetworkPolicies/LabelSelector.js
  src/resources/NetworkPolicies/NetworkPolicyDetails.js
  src/shared/components/LayoutPanelRow/LayoutPanelRow.js
  src/shared/components/Selector/Selector.js
Labels: size/M, lgtm, cla: yes

#3287 docs: add example for External Nodes in static extensions
  docs/extensibility/statics.md
  examples/statics/statics-external-nodes.yaml
Labels: size/M, lgtm, cla: yes

#3205 feat: enhance Ingress details view
  public/i18n/en.yaml
  src/resources/Ingresses/IngressCreate.js
  src/resources/Ingresses/IngressDetails.js
  src/resources/Ingresses/IngressSpecification.js
  src/resources/Ingresses/IngressStatus.js
  src/resources/Ingresses/IngressStatus.scss
  src/shared/components/ConditionList/ConditionList.tsx
  src/shared/components/ExpandableListItem/ExpandableListItem.tsx
  tests/integration/fixtures/test-ingress.yaml
  tests/integration/tests/namespace/test-ingresses.spec.js
Labels: size/L, lgtm, cla: yes

#3107 feat: Tooltip content based on crd schema for static views
  src/resources/Jobs/JobCreate.js
  src/resources/createResourceRoutes.js
  src/setupTests.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/components/Deployment/Containers.js
  src/shared/components/Deployment/ContainersViews.js
  src/shared/helpers/schema.ts
  src/shared/helpers/tests/fixtures/deployment-schema.json
  src/shared/helpers/tests/schema.test.ts
Labels: size/L, lgtm, cla: yes

#3293 feat: Enhance Storage Classes
  public/i18n/en.yaml
  src/resources/StorageClasses/PersistentVolumeClaimsList.js
  src/resources/StorageClasses/PersistentVolumesList.js
  src/resources/StorageClasses/StorageClassDetails.js
Labels: size/M, lgtm, cla: yes

#3211 feat: added Switch widget and documentation.
  docs/extensibility/60-form-widgets.md
  docs/extensibility/assets/form-widgets/Switch.png
  docs/extensibility/assets/form-widgets/Switch2.png
  public/schemas/schema-form.yaml
  src/components/Extensibility/components-form/SwitchRenderer.js
  src/components/Extensibility/components-form/index.js
Labels: size/M, lgtm, cla: yes

#3286 feat: enhancement of Persisten Volumes
  public/i18n/en.yaml
  src/resources/NetworkPolicies/NetworkPolicyDetails.js
  src/resources/PersistentVolumes/PersistentVolumeDetails.js
  src/resources/PersistentVolumes/components/VolumeCSI.tsx
  src/resources/PersistentVolumes/components/VolumeFC.tsx
  src/resources/PersistentVolumes/components/VolumeHostPath.tsx
  src/resources/PersistentVolumes/components/VolumeISCSI.tsx
  src/resources/PersistentVolumes/components/VolumeLocal.tsx
  src/resources/PersistentVolumes/components/VolumeNFS.tsx
  src/shared/components/LayoutPanelRow/LayoutPanelRow.tsx
  src/shared/components/ResourceDetails/ResourceDetails.js
  tests/integration/fixtures/test-persistent-volume-CSI.yaml
  tests/integration/fixtures/test-persistent-volume-NFS.yaml
  tests/integration/tests/cluster/test-persistent-volumes.spec.js
Labels: size/XL, lgtm, cla: yes

#3209 fix: cluster-wizard UI & oidc-scopes
  src/components/Clusters/components/AddClusterDialog.js
  src/components/Clusters/components/AddClusterWizard.js
  src/components/Clusters/components/AddClusterWizard.scss
  src/components/Clusters/components/AuthForm.js
  src/components/Clusters/components/ChooseStorage.js
  src/components/Clusters/components/ClusterPreview.js
  src/components/Clusters/components/ClusterPreview.scss
  src/components/Clusters/components/KubeconfigUpload/KubeconfigFileUpload.js
  src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.js
  src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.scss
  src/components/Clusters/components/oidc-params.ts
  src/components/Clusters/components/test/oidc-params.test.js
  src/components/Clusters/shared.ts
  src/components/Clusters/views/EditCluster/AuthenticationDropdown.js
  src/components/Clusters/views/EditCluster/EditCluster.js
  src/resources/RoleBindings/RoleForm.js
  src/resources/RoleBindings/SubjectForm.js
  src/shared/ResourceForm/components/FormField.js
  src/shared/components/Dropdown/Dropdown.js
  src/state/authDataAtom.ts
Labels: size/XL, lgtm, cla: yes

#3301 feat: Enhance Service Accounts
  src/resources/ServiceAccounts/ServiceAccountDetails.js
  src/shared/components/ServiceAccountTokenStatus.js
  src/shared/components/ServiceAccountTokenStatus.tsx
Labels: size/L, lgtm, cla: yes

#3305 feat: add latest tag to builds
  .github/workflows/busola-backend-build.yml
  .github/workflows/busola-local-build.yml
  .github/workflows/busola-web-build.yml
Labels: size/XS, lgtm, cla: yes

#3292 feat: support `--oidc-use-access-token` flag
  src/components/Clusters/components/oidc-params.ts
  src/components/Clusters/components/test/oidc-params.test.js
  src/components/Clusters/shared.ts
  src/components/Gardener/GardenerLogin.tsx
  src/state/authDataAtom.ts
Labels: size/M, lgtm, cla: yes

#3303 feat: added Number widget and documentation
  docs/extensibility/60-form-widgets.md
  docs/extensibility/assets/form-widgets/Number.png
  docs/extensibility/assets/form-widgets/Number2.png
  public/schemas/schema-form.yaml
  src/components/Extensibility/components-form/NumberRenderer.js
  src/components/Extensibility/components-form/index.js
Labels: size/M, lgtm, cla: yes

#3309 fix: fix redirect to resource in Resource Graph
  src/shared/components/ResourceGraph/DetailsCard/DetailsCard.tsx
Labels: size/S, lgtm, cla: yes

#3300 feat: Enhance Config Maps
  src/resources/ConfigMaps/ConfigMapDetails.js
  src/resources/ConfigMaps/index.tsx
  src/resources/Pods/index.tsx
  src/shared/components/MonacoEditorESM/Editor.js
  src/shared/components/ReadonlyEditorPanel.js
Labels: size/M, lgtm, cla: yes

#3310 chore: add git dir to dockerignore
  .dockerignore
Labels: size/XS, lgtm, cla: yes

#3304 feat: Enhance Secrets
  public/i18n/en.yaml
  src/components/Clusters/components/AddClusterWizard.js
  src/components/Clusters/components/ClusterPreview.js
  src/components/Clusters/views/ClusterOverview/ClusterValidation/ClusterValidationConfiguration.js
  src/resources/Secrets/SecretDetails.js
  src/resources/Secrets/index.tsx
  src/resources/ServiceAccounts/ServiceAccountDetails.js
Labels: size/M, lgtm, cla: yes

#3313 fix: default_tag in docker build
  Dockerfile
  Dockerfile.local
Labels: size/XS, lgtm, cla: yes

#3314 fix: More chown and version pinning
  Dockerfile
Labels: size/XS, lgtm, cla: yes
