Repository kyma-project/busola, pull requests merged in 2024-06, with the labels that each got.

#2950 refactor: optimization of GetCrByPath and getResourceGraph
  src/components/Extensibility/useGetCRbyPath.js
  src/resources/helpers.js
  src/shared/components/ResourceGraph/getResourceGraphConfig.js
  src/shared/components/ResourceGraph/useGetResourceGraphConfig.js
Labels: size/L, lgtm, cla: yes

#2954 fix: custom urlPath for extensibility
  src/components/App/ExtensibilityRoutes.js
  src/components/Extensibility/helpers/getExtensibilityPath.ts
  src/resources/Namespaces/NamespaceCreate.js
  src/resources/ServiceAccounts/ServiceAccountCreate.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/useCreateResource.js
Labels: size/S, lgtm, cla: yes

#2945 fix: events are empty when you open details from all namespaces list
  src/command-pallette/CommandPalletteUI/handlers/crHandler.ts
  src/components/Extensibility/components/EventList.js
  src/hooks/useMessageList.js
  src/state/navigation/extensionsAtom.ts
Labels: size/M, lgtm, cla: yes

#2956 fix: custom urlPath for extensibility
  src/components/App/ExtensibilityRoutes.js
  src/sidebar/NavItem.tsx
Labels: size/M, lgtm, cla: yes

#2919 docs: extensibility docs restructuring
  docs/extensibility/20-list-columns.md
  docs/extensibility/30-details-summary.md
  docs/extensibility/40-form-fields.md
  docs/extensibility/50-list-and-details-widgets.md
  docs/extensibility/60-form-widgets.md
  docs/extensibility/70-widget-injection.md
  docs/extensibility/display-section.md
  docs/extensibility/form-section.md
Labels: size/XXL, lgtm, cla: yes

#2953 feat: Add condition list to extensibility and add status section
  docs/extensibility/20-list-columns.md
  docs/extensibility/30-details-summary.md
  docs/extensibility/40-form-fields.md
  docs/extensibility/50-list-and-details-widgets.md
  docs/extensibility/60-form-widgets.md
  docs/extensibility/70-widget-injection.md
  docs/extensibility/assets/display-widgets/ConditionList.png
  src/components/Extensibility/ExtensibilityDetails.js
  src/components/Extensibility/components/ConditionList.js
  src/components/Extensibility/components/index.js
  src/shared/components/ConditionList/ConditionList.tsx
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceStatusCard/ResourceStatusCard.js
  src/shared/components/ResourceStatusCard/ResourceStatusCard.scss
Labels: size/XL, lgtm, cla: yes

#2961 fix: bump apline image
  Dockerfile
  Dockerfile.local
  backend/Dockerfile
Labels: size/XS, lgtm, cla: yes

#2941 feat: enhancements of statistical cards in clusteroverview
  docs/extensibility/50-list-and-details-widgets.md
  docs/extensibility/70-widget-injection.md
  public/i18n/en.yaml
  src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  src/components/Clusters/views/ClusterOverview/ClusterStats.js
  src/components/Clusters/views/ClusterOverview/ClusterStats.scss
  src/components/Extensibility/components/index.js
  src/components/Nodes/NodeResources/NodeResources.js
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloadsHelpers.js
  src/resources/Namespaces/ResourcesUsage.js
  src/shared/components/CountingCard/CountingCard.tsx
  src/shared/components/UI5RadialChart/UI5RadialChart.js
  src/shared/utils/helpers.js
  src/state/navigation/extensionsAtom.ts
Labels: size/XL, lgtm, cla: yes

#2957 fix: discard changes is not working properly in some cases
  public/i18n/en.yaml
  src/components/BusolaExtensions/BusolaExtensionEdit.js
  src/components/BusolaExtensions/SectionEditor.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/fields/Editor.js
  src/shared/ResourceForm/useCreateResource.js
  src/shared/components/ModalWithForm/ModalWithForm.js
  src/shared/components/ModalWithForm/test/ModalWithForm.test.js
  src/shared/components/ResourceCreate/ResourceCreate.js
  src/shared/hooks/useDeleteResource.js
Labels: size/M, lgtm, cla: yes

#2964 Adjust codeowners
  CODEOWNERS
  OWNERS
  OWNERS_ALIASES
Labels: size/M, lgtm, cla: yes

#2970 fix: handle pure integers values in CR form fields of type string
  src/components/Extensibility/components-form/StringRenderer.js
Labels: size/S, lgtm, cla: yes

#2971 feat: add workflow for building busola-local
  .github/workflows/busola-local-build.yml
Labels: size/S, lgtm, cla: yes

#2972 feat: adjust docker tag for busola local build
  .github/workflows/busola-local-build.yml
  Dockerfile.local
  Makefile
Labels: size/S, lgtm, cla: yes

#2974 fix: rename of busola-local workflow job
  .github/workflows/busola-local-build.yml
Labels: size/XS, lgtm, cla: yes

#2965 feat: adjust Jobs
  public/i18n/en.yaml
  src/resources/Jobs/JobDetails.js
  src/shared/components/ConditionList/ConditionList.tsx
  src/shared/components/ExpandableListItem/ExpandableListItem.tsx
  src/shared/components/ResourceDetails/ResourceDetails.js
Labels: size/L, lgtm, cla: yes

#2955 feat: UX adjustments - Modules
  docs/extensibility/70-widget-injection.md
  examples/injections/apirules.yaml
  examples/injections/functions.yaml
  public/i18n/en.yaml
  src/components/Extensibility/ExtensibilityDetails.js
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesList.js
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloadsHelpers.js
  src/resources/other/kymaModules.routes.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/useCreateResource.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
  src/shared/components/ExternalLink/ExternalLink.tsx
  src/shared/components/GenericList/GenericList.js
  src/shared/components/ResourceCreate/ResourceCreate.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/StatusBadge/StatusBadge.js
  src/shared/components/StatusBadge/StatusBadge.scss
  src/shared/components/StatusBadge/test/StatusBadge.test.js
  src/shared/components/UI5Panel/UI5Panel.js
  src/styles/index.scss
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
Labels: size/XL, lgtm, cla: yes

#2978 fix: modeSelector for form
  src/shared/ResourceForm/components/ResourceForm.js
Labels: size/S, lgtm, cla: yes

#2976 feat: add paths for local build
  .github/workflows/busola-local-build.yml
Labels: size/S, lgtm, cla: yes

#2977 feat: Add USER to dockerfiles
  Dockerfile.local
  backend/Dockerfile
Labels: size/S, lgtm, cla: yes

#2980 fix: responsiveness of labels
  src/shared/components/Labels/Labels.scss
Labels: size/XS, lgtm, cla: yes

#2979 feat: Redesign of sort dialog
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/SortModalPanel.js
  src/shared/components/GenericList/SortModalPanel.scss
  src/shared/components/Modal/Modal.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
Labels: size/L, lgtm, cla: yes

#2985 feat: modules baner on cluster details
  docs/extensibility/50-list-and-details-widgets.md
  public/i18n/en.yaml
  src/components/Clusters/views/ClusterOverview/ClusterDetails.js
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesQuery.js
  src/shared/components/CountingCard/CountingCard.tsx
Labels: size/L, lgtm, cla: yes

#2981 feat: gha cypress namespace tests
  .github/workflows/busola-local-build.yml
  .github/workflows/pull-integration-namespace-k3d.yml
  tests/integration/tests/namespace/z-run-after.spec.js
Labels: size/M, lgtm, cla: yes

#2983 fix: Display correct value for resource quota when spec is not in `requests`
  src/resources/Namespaces/ResourcesUsage.js
  src/resources/ResourceQuotas/ResourceQuotaList.js
Labels: size/S, lgtm, cla: yes

#2982 fix: improve error handling on details view
  src/components/Extensibility/components/ResourceList.js
  src/components/Extensibility/components/Widget.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/shared/hooks/BackendAPI/config.js
  src/shared/utils/helpers.js
Labels: size/S, lgtm, cla: yes

#2973 feat: new pagination
  public/i18n/en.yaml
  src/components/Preferences/OtherSettings.tsx
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/Pagination/Pagination.js
  src/shared/components/GenericList/Pagination/Pagination.scss
  src/shared/components/GenericList/Pagination/test/Pagination.test.js
  src/state/preferences/pageSizeAtom.ts
Labels: size/L, lgtm, cla: yes

#2993 fix: correctly count healty pods
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloadsHelpers.js
Labels: size/XS, lgtm, cla: yes

#2994 fix: Remove Monitoring and Health title from details except for Namespace details
  src/resources/Namespaces/NamespaceDetails.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceHealthCard/ResourceHealthCard.js
Labels: size/M, lgtm, cla: yes

#2987 feat: Adjust Statefull Sets
  public/i18n/en.yaml
  src/resources/ReplicaSets/ReplicaSetDetails.js
  src/resources/StatefulSets/StatefulSetDetails.js
Labels: size/L, lgtm, cla: yes

#2997 fix: Fix ediiting the extension
  src/components/BusolaExtensions/BusolaExtensionEdit.js
Labels: size/XS, lgtm, cla: yes

#2996 feat: OSS Rules
  .gitignore
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: size/L, lgtm, cla: yes

#2966 feat: Add Radial Chart to extensibility
  docs/extensibility/50-list-and-details-widgets.md
  docs/extensibility/assets/display-widgets/RadialChart.png
  src/components/Extensibility/components/RadialChart.js
  src/components/Extensibility/components/index.js
  src/components/Extensibility/hooks/useJsonata.ts
  src/shared/components/UI5RadialChart/UI5RadialChart.js
Labels: size/M, lgtm, cla: yes

#3012 feat: adjust daemonsets
  public/i18n/en.yaml
  src/resources/DaemonSets/DaemonSetDetails.js
Labels: size/M, lgtm, cla: yes

#3013 fix: fix Extensions discard
  src/components/BusolaExtensions/BusolaExtensionCreate.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/components/Single.js
Labels: size/M, lgtm, cla: yes
