Repository kyma-project/busola, pull requests merged in 2024-10, with the labels that each got.

#3369 fix: use allowed version of markdown lint check
  .github/workflows/lint-markdown-links-daily.yml
  .github/workflows/lint-markdown-links-pr.yml
Labels: size/XS, lgtm, cla: yes

#3370 fix: accessiblity - Info button in resources headers
  src/components/KymaModules/KymaModulesList.js
  src/shared/components/DescriptionHint/DescriptionHint.tsx
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/ResourceDetails/ResourceDetails.js
Labels: size/S, lgtm, cla: yes

#3334 chore: change CRA to Vite
  babel.config.json
  config-overrides.js
  config-overrides/index.js
  config-overrides/package.json
  index.html
  jest.config.js
  package-lock.json
  package.json
  public/assets/favicon-16x16.png
  public/assets/favicon-32x32.png
  public/index.html
  src/components/App/resourceSchemas/resourceSchemas.worker.js
  src/components/BusolaExtensions/BusolaExtensionEdit.js
  src/components/Clusters/components/AuthForm.js
  src/components/Clusters/views/EditCluster/EditCluster.js
  src/components/CustomResources/CustomResources.js
  src/components/Extensibility/ExtensibilityCreate.js
  src/components/Extensibility/ExtensibilityWizard.js
  src/components/Extensibility/components-form/NameRenderer.js
  src/components/Extensibility/contexts/DataSources.tsx
  src/components/Extensibility/contexts/VarStore.js
  src/components/Extensibility/hooks/useVariables.js
  src/components/Extensibility/migration.js
  src/components/Extensibility/plugins/CustomFieldInjector.js
  src/index.tsx
  src/resources/CronJobs/CronJobCreate.js
  src/resources/CustomResourceDefinitions/templates.js
  src/resources/Deployments/DeploymentCreate.js
  src/resources/Jobs/JobCreate.js
  src/resources/Namespaces/MemoryQuotas.js
  src/resources/Namespaces/NamespaceCreate.js
  src/resources/ReplicaSets/ReplicaSetCreate.js
  src/resources/ResourceQuotas/ResourceQuotaDetails.scss
  src/resources/RoleBindings/GenericRoleBindingCreate.js
  src/resources/Roles/RuleInput.js
  src/resources/ServiceAccounts/ServiceAccountCreate.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/components/Wrapper.js
  src/shared/ResourceForm/fields/RuntimeResources.js
  src/shared/components/Deployment/Containers.js
  src/shared/components/Deployment/ContainersViews.js
  src/shared/components/MonacoEditorESM/autocompletion/useAutocompleteWorker.js
  src/shared/components/MonacoEditorESM/autocompletion/yaml.worker.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/shared/contexts/NotificationContext.tsx
  src/shared/hooks/useProtectedResources.js
  src/shared/hooks/useRestartResource.js
  src/shared/hooks/useSidecarInjection.js
  src/state/preferences/themeAtom.ts
  src/state/utils/getBackendInfo.ts
  src/styles/index.scss
  tests/integration/cypress.config.js
  tests/integration/package-lock.json
  tests/integration/package.json
  tests/integration/tests/namespace/test-settings.spec.js
  tsconfig.json
  vite.config.mts
Labels: size/XXL, lgtm, cla: yes

#3389 chore: adjust sec-scanners-config
  sec-scanners-config.yaml
Labels: size/XS, lgtm, hacktoberfest-accepted, hacktoberfest, cla: yes

#3377 feat: add accessibility automation configuration
  .github/workflows/accessibility-tests.yml
  .gitignore
  tests/integration/continuum/continuum.conf.js
  tests/integration/continuum/cypress.js
  tests/integration/cypress.config.js
  tests/integration/lib/continuum-continuum-javascript-professional-5.1.2.tgz
  tests/integration/package-lock.json
  tests/integration/package.json
  tests/integration/support/index.js
  tests/integration/tests/accessibility/test-cluster-overview.spec.js
Labels: size/XXL, lgtm, hacktoberfest-accepted, hacktoberfest, cla: yes

#3378 fix: activate form mode buttons using keyboard
  src/shared/ResourceForm/components/ModeSelector.js
Labels: size/S, lgtm, hacktoberfest, cla: yes

#3396 tests: trigger acc test
  .github/workflows/accessibility-tests.yml
Labels: size/XS, lgtm, hacktoberfest-accepted, hacktoberfest, cla: yes

#3398 chore: add ref for checkout in ACC GHA
  .github/workflows/accessibility-tests.yml
Labels: size/XS, lgtm, cla: yes

#3373 fix: infinite loop on hidden namespace
  src/hooks/useAvailableNamespaces.ts
  src/shared/hooks/useGetHiddenNamespaces.ts
Labels: size/S, lgtm, cla: yes

#3397 fix: configurarion of accessibility automated testing
  .github/workflows/accessibility-tests.yml
  tests/integration/continuum/cypress.js
  tests/integration/cypress.config.js
  tests/integration/lib/continuum-continuum-javascript-professional-5.1.2.tgz
  tests/integration/lib/continuum-continuum-javascript-professional-6.1.0.tgz
  tests/integration/package-lock.json
  tests/integration/package.json
  tests/integration/plugins/index.js
  tests/integration/tests/accessibility/test-acc-cluster.spec.js
  tests/integration/tests/accessibility/test-acc-namespace-overview.spec.js
Labels: size/M, lgtm, cla: yes

#3388 chore: Merge kyma tests into integration
  .github/scripts/setup-kyma.sh
  .github/workflows/pull-kyma-integration-tests.yml
  .github/workflows/pull-smoke-test-prod.yml
  .github/workflows/pull-smoke-test-stage.yml
  examples/service-binding-mock-crd.yaml
  examples/service-instance-mock-crd.yaml
  tests/integration/cypress-smoke.js
  tests/integration/cypress.config.js
  tests/integration/fixtures/in-cluster-eventing-publisher-dependencies.json
  tests/integration/fixtures/in-cluster-eventing-publisher.js
  tests/integration/fixtures/in-cluster-eventing-receiver-dependencies.json
  tests/integration/fixtures/in-cluster-eventing-receiver.js
  tests/integration/fixtures/modules/api-gateway-regular.yaml
  tests/integration/fixtures/modules/eventing-fast.yaml
  tests/integration/fixtures/modules/eventing-regular.yaml
  tests/integration/fixtures/orders-function-dependencies.json
  tests/integration/package.json
  tests/integration/support/check-extension.js
  tests/integration/support/create-edit-support.js
  tests/integration/support/exceptions.js
  tests/integration/support/helpers.js
  tests/integration/support/index.js
  tests/integration/support/navigate-back-to.js
  tests/integration/tests/kyma-cluster/test-check-extensions.spec.js
  tests/integration/tests/kyma-cluster/test-kyma-modules.spec.js
  tests/integration/tests/kyma-cluster/test-kyma-version.spec.js
  tests/integration/tests/kyma-namespace/a-run-before.spec.js
  tests/integration/tests/kyma-namespace/test-certificates.spec.js
  tests/integration/tests/kyma-namespace/test-check-extensions.spec.js
  tests/integration/tests/kyma-namespace/test-dns-entries.spec.js
  tests/integration/tests/kyma-namespace/test-dns-providers.spec.js
  tests/integration/tests/kyma-namespace/test-hpa.spec.js
  tests/integration/tests/kyma-namespace/test-issuers.spec.js
  tests/integration/tests/kyma-namespace/test-oauth2.spec.js
  tests/integration/tests/kyma-namespace/test-services.spec.js
  tests/integration/tests/kyma-namespace/test-smoke-service-management.spec.js
  tests/integration/tests/kyma-namespace/z-run-after.spec.js
  tests/kyma/config.js
  tests/kyma/cypress-smoke.js
  tests/kyma/package-lock.json
  tests/kyma/package.json
  tests/kyma/plugins/index.js
  tests/kyma/support/commands.js
  tests/kyma/support/create-edit-support.js
  tests/kyma/support/exceptions.js
  tests/kyma/support/helpers.js
  tests/kyma/support/index.js
  tests/kyma/support/inspect-list.js
  tests/kyma/support/inspectTab.js
  tests/kyma/support/loadFile.js
  tests/kyma/support/login-commands.js
  tests/kyma/support/mockConfig.js
  tests/kyma/support/navigate-to.js
  tests/kyma/support/paste-to-monaco.js
  tests/kyma/tests/cluster/test-applications.spec.js
  tests/kyma/tests/cluster/test-modules-wizard.spec.js
  tests/kyma/tests/namespace/test-kyma.spec.js
  tests/kyma/tests/namespace/test-module-templates.spec.js
Labels: size/XXL, lgtm, cla: yes

#3395 fix: tighten backend's request validation
  backend/package-lock.json
  backend/package.json
  backend/request-filters.js
  backend/request-filters.test.js
Labels: size/XXL, lgtm, cla: yes

#3408 chore: install kyma on k3d for accessbility tests
  .github/workflows/accessibility-tests.yml
Labels: size/S, lgtm, cla: yes

#3402 docs: Update docs about busola-kyma image
  README.md
Labels: size/S, lgtm, cla: yes

#3407 docs: Update docs merge tests
  tests/integration/README.md
  tests/kyma/README.md
Labels: size/M, lgtm, cla: yes

#3404 chore: Unify dockerfiles
  .github/scripts/setup-busola.sh
  .github/workflows/busola-build.yml
  .github/workflows/busola-kyma-build.yml
  .github/workflows/busola-web-build.yml
  Dockerfile
  Dockerfile.local
  Dockerfile.local.kyma
  Dockerfile.web
  resources/base/web/deployment.yaml
  tests/integration/package.json
Labels: size/L, lgtm, cla: yes

#3410 fix: Use correct image in tests package.json
  tests/integration/package.json
Labels: size/XS, lgtm, cla: yes

#3413 docs: accessibility tests
  tests/integration/README.md
Labels: size/S, lgtm, cla: yes

#3418 chore: hardcode older version of chrome for cypress
  .github/workflows/pull-integration-cluster-k3d.yml
  .github/workflows/pull-integration-namespace-k3d.yml
  tests/integration/package.json
  tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
  tests/integration/tests/cluster/test-edit-cluster.spec.js
Labels: size/S, lgtm, cla: yes

#3393 chore: migrate unit tests to Vitest
  babel.config.json
  config-overrides/index.js
  config-overrides/package.json
  jest.config.js
  package-lock.json
  package.json
  src/components/Extensibility/components/tests/Badge.test.js
  src/components/Extensibility/components/tests/CodeViewer.test.js
  src/components/Extensibility/components/tests/Columns.test.js
  src/components/Extensibility/components/tests/ControlledBy.test.js
  src/components/Extensibility/components/tests/JoinedArray.test.js
  src/components/Extensibility/components/tests/ResourceLink.test.js
  src/components/Extensibility/components/tests/Table.test.js
  src/components/Extensibility/components/tests/Widget.copyable.test.js
  src/components/Extensibility/components/tests/Widget.test.js
  src/components/Extensibility/tests/useGetCRDByPath.test.js
  src/components/HelmReleases/tests/HelmReleaseData.test.js
  src/resources/Namespaces/test/__snapshots__/Namespaces.helpers.test.js.snap
  src/resources/Pods/test/PodRestarts.test.js
  src/setupTests.js
  src/shared/ResourceForm/fields/RichEditorDataField/RichEditorDataField.js
  src/shared/ResourceForm/tests/useCreateResource.test.js
  src/shared/components/ControlledBy/test/ControlledBy.test.js
  src/shared/components/CopiableText/test/CopiableText.test.js
  src/shared/components/ErrorBoundary/test/ErrorBoundary.test.js
  src/shared/components/GenericList/Pagination/test/Pagination.test.js
  src/shared/components/ListActions/test/ListActions.test.js
  src/shared/components/ResourceDetails/tests/ResourceDetailsColumns.test.js
  src/shared/components/ResourceDetails/tests/ResourceDetailsVisibility.test.js
  src/shared/components/Selector/Selector.js
  src/shared/components/Selector/tests/Selector.test.js
  src/shared/components/StatusBadge/test/StatusBadge.test.js
  src/shared/components/StatusBadge/test/__snapshots__/StatusBadge.test.js.snap
  src/shared/components/UI5RadialChart/test/UI5RadialChart.test.js
  src/shared/components/__mocks__/popper.js.js
  src/shared/helpers/tests/__snapshots__/safeBase64.test.js.snap
  src/shared/hooks/BackendAPI/tests/useGet.test.js
  src/shared/typechecking/test/CustomPropTypes.test.js
  src/shared/utils/test/handleSubscriptionArrayEvent.test.js
  vite.config.mts
  vitest.config.js
Labels: size/XXL, lgtm, cla: yes

#3412 fix: accessibility - add tooltips and fix collapsibleSection focus
  public/i18n/en.yaml
  src/header/Header.tsx
  src/header/SidebarSwitcher/SidebarSwitcher.tsx
  src/shared/ResourceForm/components/CollapsibleSection.js
  src/shared/components/DescriptionHint/DescriptionHint.tsx
Labels: size/S, lgtm, cla: yes

#3417 fix: fix redirect after double slashes
  src/state/useAfterInitHook.ts
Labels: size/XS, lgtm, cla: yes

#3421 chore: fix acc workflow
  .github/workflows/accessibility-tests.yml
Labels: size/S, lgtm, cla: yes

#3419 fix: labels for expand/collapse buttons in Panel
  src/shared/ResourceForm/components/CollapsibleSection.js
  tests/integration/tests/accessibility/test-acc-cron-jobs.spec.js
  tests/integration/tests/extensibility/ext-test-extensibility.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/kyma-namespace/a-run-before.spec.js
  tests/integration/tests/kyma-namespace/test-certificates.spec.js
  tests/integration/tests/kyma-namespace/test-dns-providers.spec.js
  tests/integration/tests/kyma-namespace/test-services.spec.js
  tests/integration/tests/namespace/a-run-before.spec.js
  tests/integration/tests/namespace/test-config-maps.spec.js
  tests/integration/tests/namespace/test-cron-jobs.spec.js
  tests/integration/tests/namespace/test-deployments.spec.js
  tests/integration/tests/namespace/test-jobs.spec.js
Labels: size/M, lgtm, cla: yes

#3424 fix: accessibility of kyma logo
  src/header/Header.tsx
Labels: size/S, lgtm, cla: yes

#3425 fix: backend requests in safari
  src/resources/helpers.js
  src/shared/components/GenericList/GenericList.js
Labels: size/XS, lgtm, cla: yes

#3414 fix: allow more characters in url
  backend/request-filters.js
  backend/request-filters.test.js
  tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
Labels: size/S, lgtm, cla: yes

#3429 test: adjust unit tests to previous debugging changes
  backend/request-filters.test.js
Labels: size/XS, lgtm, cla: yes

#3430 fix: adjust invalidHeaderFilter to handle empty headers correctly
  backend/request-filters.js
  backend/request-filters.test.js
Labels: size/XS, lgtm, cla: yes

#3426 fix: make CSP stricter
  nginx/nginx.conf
Labels: size/XS, lgtm, cla: yes

#3423 feat: add second badge for modules status
  public/i18n/en.yaml
  src/components/KymaModules/KymaModulesList.js
  src/components/KymaModules/components/ModuleStatus.tsx
Labels: size/M, lgtm, cla: yes

#3431 fix: remove invalid header filter
  backend/common.js
  backend/request-filters.js
  backend/request-filters.test.js
Labels: size/M, lgtm, cla: yes

#3432 fix: Fix build web trigger
  .github/workflows/busola-build.yml
  .github/workflows/busola-web-build.yml
Labels: size/XS, lgtm, cla: yes

#3403 fix: accessibility of search input
  src/shared/components/GenericList/SearchInput.js
  src/shared/components/GenericList/SearchInput.scss
  src/shared/components/UI5Panel/UI5Panel.scss
  src/shared/components/UI5Panel/UI5Panel.tsx
  tests/integration/support/commands.js
  tests/integration/support/inspect-list.js
  tests/integration/tests/accessibility/test-acc-cron-jobs.spec.js
  tests/integration/tests/accessibility/test-acc-custom-resoureces.spec.js
  tests/integration/tests/accessibility/test-acc-extensions.spec.js
  tests/integration/tests/accessibility/test-acc-pizzas.spec.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/cluster/test-navigation-features.spec.js
  tests/integration/tests/extensibility/ext-test-extensibility.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-services.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/kyma-cluster/test-kyma-modules.spec.js
  tests/integration/tests/kyma-namespace/test-oauth2.spec.js
  tests/integration/tests/namespace/test-custom-resources.spec.js
  tests/integration/tests/namespace/test-reduced-permissions--configuration.spec.js
Labels: size/L, lgtm, cla: yes

#3427 feat: add checkbox to display managed modules
  .github/workflows/pull-kyma-integration-tests.yml
  public/i18n/en.yaml
  src/components/KymaModules/ChannelWarning.tsx
  src/components/KymaModules/KymaModulesCreate.js
  src/components/KymaModules/KymaModulesCreate.scss
  src/components/KymaModules/ManagedWarnings.tsx
  src/components/KymaModules/UnmanagedModuleInfo.tsx
Labels: size/L, lgtm, cla: yes

#3434 fix: proper error handling for polling hook
  src/shared/hooks/BackendAPI/useGet.js
Labels: size/S, lgtm, cla: yes

#3439 chore: UI5 bump packages
  package-lock.json
  package.json
  src/components/Extensibility/components/CodeViewer.js
  src/components/Extensibility/components/Columns.js
  src/components/Extensibility/components/tests/Badge.test.js
  src/components/Extensibility/components/tests/CodeViewer.test.js
  src/components/Extensibility/components/tests/Columns.test.js
  src/components/Extensibility/components/tests/ControlledBy.test.js
  src/components/Extensibility/components/tests/Table.test.js
  src/components/KymaModules/ModulesCard.js
  src/setupTests.js
  src/testing/enzymeUtils.tsx
Labels: size/XXL, lgtm, cla: yes
