Repository kyma-project/busola, pull requests merged in 2024-05, with the labels that each got.

#2898 fix: redirect after deleting on extension list
  src/shared/hooks/useDeleteResource.js
Labels: size/XS, lgtm, cla: yes

#2899 fix: remove redirect in Custom Resources when resource has extension defined
  src/components/CustomResources/CustomResources.js
  src/resources/CustomResourceDefinitions/CRCreate.js
  src/resources/CustomResourceDefinitions/useCustomResourceUrl.js
Labels: size/M, lgtm, cla: yes

#2900 fix: mend vulns, move sap logo to local SVG
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
  public/assets/logo-black.svg
  public/assets/logo-blue.svg
  public/assets/logo.svg
  public/assets/sap-logo.svg
  public/defaultConfig.yaml
  src/components/Clusters/views/ClusterOverview/ClusterDetails.js
  src/components/Extensibility/helpers/jsonataWrapper.ts
  src/header/Logo/Logo.tsx
Labels: size/L, lgtm, cla: yes

#2905 fix: tooltip bug that causes extension list to load with error
  public/i18n/en.yaml
  src/shared/components/ResourcesList/ResourcesList.js
Labels: size/XS, lgtm, cla: yes

#2903 feat: brought back slash-shortcut
  src/components/Clusters/views/ClusterOverview/ClusterNodes.js
  src/components/CustomResources/CustomResources.js
  src/components/CustomResources/GroupingListPage.js
  src/components/Extensibility/components/Table.js
  src/components/HelmReleases/HelmReleasesList.js
  src/resources/createResourceRoutes.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/SearchInput.js
  src/sidebar/Sidebar.scss
  tests/integration/tests/cluster/test-custom-resources.spec.js
Labels: size/M, lgtm, cla: yes

#2907 Update Extensibility README
  docs/extensibility/README.md
Labels: size/M, lgtm, cla: yes

#2906 feat: cards view for adding modules
  docs/extensibility/README.md
  public/i18n/en.yaml
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesAddModule.scss
  src/components/KymaModules/KymaModulesList.js
  src/shared/components/ExternalLink/ExternalLink.tsx
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/components.js
Labels: size/L, lgtm, cla: yes

#2917 Fix unit tests
  package-lock.json
  package.json
  src/components/App/IncorrectPath.js
  src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  src/components/Extensibility/components/Badge.js
  src/components/Extensibility/components/Table.js
  src/components/Extensibility/components/tests/Badge.test.js
  src/components/Extensibility/components/tests/Table.test.js
  src/components/KymaModules/KymaModulesList.js
  src/components/Preferences/EditViewSettings.tsx
  src/header/NamespaceDropdown/NamespaceDropdown.tsx
  src/resources/CronJobs/CronJobDetails.js
  src/resources/CustomResourceDefinitions/CurrentCRDVersion.js
  src/resources/CustomResourceDefinitions/CustomResourceDefinitionDetails.js
  src/resources/CustomResourceDefinitions/CustomResources.details.js
  src/resources/CustomResourceDefinitions/RelatedCRDsList.js
  src/resources/DaemonSets/DaemonSetDetails.js
  src/resources/Events/EventDetails.js
  src/resources/HorizontalPodAutoscalers/HPASubcomponent.js
  src/resources/Ingresses/IngressDetails.js
  src/resources/Jobs/JobDetails.js
  src/resources/NetworkPolicies/NetworkPolicyDetails.js
  src/resources/PersistentVolumeClaims/PersistentVolumeClaimDetails.js
  src/resources/Pods/ContainersData.js
  src/resources/Pods/PodDetails.js
  src/resources/ReplicaSets/ReplicaSetDetails.js
  src/resources/ServiceAccounts/ServiceAccountDetails.js
  src/resources/StatefulSets/StatefulSetDetails.js
  src/setupTests.js
  src/shared/ResourceForm/inputs/ComboboxInput.js
  src/shared/components/CountingCard/CountingCard.tsx
  src/shared/components/GenericList/SearchInput.js
  src/shared/components/GenericList/test/GenericList.test.js
  src/shared/components/GenericList/test/GenericList2.test.js
  src/shared/components/PodTemplate/components.js
  src/shared/components/ResourceDetails/tests/ResourceDetailsColumns.test.js
  src/shared/components/ResourceDetails/tests/ResourceDetailsVisibility.test.js
  src/shared/components/ResourceStatusCard/ResourceStatusCard.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/shared/components/StatusBadge/StatusBadge.js
  src/shared/hooks/BackendAPI/tests/useGet.test.js
  src/sidebar/SidebarNavigation.tsx
Labels: size/XXL, lgtm, cla: yes

#2918 fix: no modules in status
  src/components/KymaModules/KymaModulesList.js
Labels: size/S, lgtm, cla: yes

#2908 Update the Pizzas example
  examples/pizzas/README.md
Labels: size/M, lgtm, cla: yes

#2920 fix: injections order & delete in edit-mode
  src/components/Extensibility/useGetInjection.js
  src/shared/components/ResourceDetails/ResourceDetails.js
Labels: size/S, lgtm, cla: yes

#2922 fix: warning in Add Kyma Module YAML form
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesList.js
Labels: size/S, lgtm, cla: yes

#2924 Hide create button on service account details view
  src/resources/ServiceAccounts/GenericSecrets.js
Labels: size/XS, lgtm, cla: yes

#2928 fix: add initial resource to cluster validation
  src/components/Clusters/views/ClusterOverview/ClusterValidation/ClusterValidationConfiguration.js
Labels: size/XS, lgtm, cla: yes

#2926 fix: displaying incorrect Shoot after invalid link
  src/components/App/ClusterRoutes.js
Labels: size/XS, lgtm, cla: yes

#2929 Fix API server address text cut off
  src/components/Clusters/views/ClusterOverview/ClusterDetails.js
Labels: size/XS, lgtm, cla: yes

#2935 fix: useState instead of if to improve performance for every create file
  src/command-pallette/CommandPaletteProvider.tsx
  src/components/Extensibility/ExtensibilityCreate.js
  src/resources/ConfigMaps/ConfigMapCreate.js
  src/resources/CronJobs/CronJobCreate.js
  src/resources/CustomResourceDefinitions/CRCreate.js
  src/resources/CustomResourceDefinitions/CustomResourceDefinitionCreate.js
  src/resources/DaemonSets/DaemonSetCreate.js
  src/resources/Deployments/DeploymentCreate.js
  src/resources/Ingresses/IngressCreate.js
  src/resources/Jobs/JobCreate.js
  src/resources/LimitRanges/LimitRangeCreate.js
  src/resources/Namespaces/NamespaceCreate.js
  src/resources/NetworkPolicies/NetworkPolicyCreate.js
  src/resources/PersistentVolumeClaims/PersistentVolumeClaimCreate.js
  src/resources/PersistentVolumes/PersistentVolumeCreate.js
  src/resources/Pods/PodCreate.js
  src/resources/ReplicaSets/ReplicaSetCreate.js
  src/resources/ResourceQuotas/ResourceQuotaCreate.js
  src/resources/RoleBindings/GenericRoleBindingCreate.js
  src/resources/Roles/GenericRoleCreate.js
  src/resources/Secrets/SecretCreate.js
  src/resources/ServiceAccounts/ServiceAccountCreate.js
  src/resources/StatefulSets/StatefulSetCreate.js
  src/resources/StorageClasses/StorageClassCreate.js
Labels: size/L, lgtm, priority/critical, cla: yes

#2942 fix: taking data to useEffect for discard changes
  src/shared/ResourceForm/components/ResourceForm.js
Labels: size/S, lgtm, cla: yes

#2931 feat: adjust pods
  public/i18n/en.yaml
  src/resources/Deployments/DeploymentDetails.js
  src/resources/Pods/ContainersData.js
  src/resources/Pods/PodDetails.js
  src/resources/helpers.js
  src/shared/components/ReadableElapsedTimeFromNow/ReadableElapsedTimeFromNow.tsx
Labels: size/L, lgtm, cla: yes

#2921 feat: adjust status and metadata in replica set detail view
  public/i18n/en.yaml
  src/resources/ReplicaSets/ReplicaSetDetails.js
  src/resources/ReplicaSets/ReplicaSetStatus.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceDetails/ResourceDetails.scss
  src/shared/components/ResourceDetails/ResourceDetailsCard.js
  src/shared/components/ResourceStatusCard/ResourceStatusCard.js
  src/shared/components/ResourceStatusCard/ResourceStatusCard.scss
Labels: size/L, lgtm, cla: yes

#2933 fix: Link to dashboard leads to another cluster
  src/components/App/resourceSchemas/useResourceSchemas.ts
  src/components/App/useLoginWithKubeconfigID.ts
  src/components/Clusters/shared.ts
  tests/integration/support/exceptions.js
Labels: size/S, lgtm, cla: yes

#2948 feat: disable create in details resource lists
  src/components/Extensibility/components/ResourceList.js
Labels: size/XS, lgtm, cla: yes

#2949 fix: refactor discard changes
  src/command-pallette/CommandPaletteProvider.tsx
  src/command-pallette/CommandPalletteUI/ResultsList/ResultsList.tsx
  src/components/Clusters/components/AddClusterWizard.js
  src/components/KymaModules/KymaModulesList.js
  src/header/Header.tsx
  src/header/NamespaceChooser/NamespaceChooser.tsx
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/useCreateResource.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/ResourceCreate/ResourceCreate.js
  src/shared/components/UnsavedMessageBox/UnsavedMessageBox.tsx
  src/shared/components/UnsavedMessageBox/helpers.ts
  src/sidebar/NavItem.tsx
  src/sidebar/SidebarNavigation.tsx
  src/state/formOpenAtom.ts
  src/state/resourceEditedAtom.ts
Labels: size/L, lgtm, cla: yes
