Repository kyma-project/busola, pull requests merged in 2024-12, with the labels that each got.

#3495 fix: Fix deployment status properly
  src/resources/Deployments/DeploymentDetails.js
  src/resources/Deployments/DeploymentStatus.js
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloadsHelpers.js
  src/shared/components/ConditionList/ConditionList.tsx
  src/shared/components/ExpandableListItem/ExpandableListItem.tsx
Labels: size/M, lgtm, cla: yes

#3507 fix: fix all namespaces
  src/resources/Namespaces/AllNamespacesDetails.js
Labels: size/XS, lgtm, cla: yes

#3500 feat(Modules): modules version adjustments to moduleCatalog changes
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesCreate.js
  src/components/KymaModules/KymaModulesList.js
  src/components/KymaModules/ModulesCard.js
Labels: size/L, lgtm, cla: yes

#3516 fix(nodes): fix metrics for nodes
  src/components/Nodes/NodeResources/NodeResources.js
  src/components/Nodes/nodeQueries.js
  src/resources/Namespaces/ResourcesUsage.js
Labels: size/M, lgtm, cla: yes

#3518 fix: UI5 logo accessibility
  src/header/Header.tsx
Labels: size/S, lgtm, cla: yes

#3524 adjust reset.css
  src/header/Header.tsx
  src/styles/index.scss
  src/styles/reset.css
Labels: size/M, lgtm, cla: yes

#3509 fix: Fix fonts in safari
  index.html
Labels: size/XS, lgtm, cla: yes

#3525 docs: adjust testing strategy to github actions and add new workflows
  docs/contributor/testing-strategy.md
Labels: size/M, lgtm, cla: yes

#3527 chore: override cookie and path-to-regexp packages in express
  .github/workflows/pull-integration-cluster-k3d.yml
  .github/workflows/pull-integration-namespace-k3d.yml
  .github/workflows/pull-kyma-integration-tests.yml
  backend/package-lock.json
  backend/package.json
Labels: size/M, lgtm, cla: yes

#3528 chore: add package-locks to exclude for checkmarx
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#3530 chore(deps): bump express version
  backend/package-lock.json
  backend/package.json
Labels: size/M, lgtm, cla: yes

#3531 fix: Loading custom script from blob
  index.html
  src/components/Extensibility/ExtensibilityList.js
Labels: size/S, lgtm, cla: yes

#3526 tests: fix cron job acc test
  .github/workflows/accessibility-tests.yml
  tests/integration/tests/accessibility/test-acc-cron-jobs.spec.js
Labels: size/S, lgtm, cla: yes

#3498 fix: Busola is flickering when ObjectPage is opened
  src/components/App/App.tsx
  src/components/Extensibility/components-form/GenericList.js
  src/components/Extensibility/components/FeaturedCard/FeaturedCard.scss
  src/components/HelmReleases/HelmReleasesList.js
  src/components/KymaModules/KymaModulesList.js
  src/header/NamespaceDropdown/NamespaceDropdown.tsx
  src/hooks/useAvailableNamespaces.ts
  src/resources/createResourceRoutes.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
  src/shared/components/GenericList/GenericList.js
  src/shared/components/UI5Panel/UI5Panel.tsx
  src/state/authDataAtom.ts
  src/state/namespacesAtom.ts
Labels: size/L, lgtm, cla: yes

#3537 Fix proxy endpoint
  backend/index.js
Labels: size/XS, lgtm, cla: yes

#3539 fix: selected prop is not working in the tables
  src/shared/components/GenericList/components.js
Labels: size/XS, lgtm, cla: yes

#3543 fix: selected prop is not working in the tables
  src/shared/components/GenericList/components.js
Labels: size/XS

#3485 feat: Create release process
  .github/scripts/create_changelog.sh
  .github/scripts/create_draft_release.sh
  .github/scripts/publish_release.sh
  .github/scripts/upload_assets.sh
  .github/workflows/busola-backend-build.yml
  .github/workflows/busola-build.yml
  .github/workflows/busola-web-build.yml
  .github/workflows/create-release.yml
  Dockerfile
  Dockerfile.web
  resources/apply-resources.sh
  resources/base/backend/deployment.yaml
  resources/base/kustomization.yaml
  resources/base/web/deployment.yaml
  resources/ingress/ingress.tpl.yaml
  resources/ingress/ingressClass.yaml
Labels: size/L, lgtm, cla: yes

#3546 fix: Chrome tooltip overlays dropdown options
  src/components/Extensibility/components/Widget.js
  src/shared/components/Dropdown/Dropdown.js
Labels: size/S, lgtm, cla: yes

#3535 feat: Snow Falling Animation
  kyma/environments/dev/config.yaml
  kyma/environments/prod/config.yaml
  kyma/environments/stage/config.yaml
  public/defaultConfig.yaml
  public/i18n/en.yaml
  src/header/Header.scss
  src/header/Header.tsx
Labels: size/L, lgtm, cla: yes

#3553 fix: adjust Cypress tests
  .github/workflows/pull-integration-cluster-k3d.yml
  .github/workflows/pull-integration-namespace-k3d.yml
  .github/workflows/pull-kyma-integration-tests.yml
  .github/workflows/pull-lighthouse.yml
  .github/workflows/pull-smoke-test-prod.yml
  .github/workflows/pull-smoke-test-stage.yml
  src/command-pallette/CommandPaletteProvider.tsx
  src/header/NamespaceChooser/NamespaceChooser.tsx
  src/hooks/useAvailableNamespaces.ts
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/Labels/Labels.js
  src/shared/hooks/BackendAPI/useGet.js
  src/state/useAfterInitHook.ts
  tests/integration/support/commands.js
  tests/integration/support/inspect-list.js
  tests/integration/tests/accessibility/test-acc-custom-resoureces.spec.js
  tests/integration/tests/accessibility/test-acc-performance.spec.js
  tests/integration/tests/cluster/test-cluster-configuration.spec.js
  tests/integration/tests/cluster/test-cluster-overview.spec.js
  tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
  tests/integration/tests/cluster/test-command-palette.spec.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/cluster/test-dashboard-version.spec.js
  tests/integration/tests/cluster/test-multiple-context-kubeconfig.spec.js
  tests/integration/tests/cluster/test-navigation-features.spec.js
  tests/integration/tests/cluster/test-persistent-volumes.spec.js
  tests/integration/tests/cluster/test-storage-classes.spec.js
  tests/integration/tests/extensibility/ext-test-extensibility.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/kyma-cluster/test-kyma-modules.spec.js
  tests/integration/tests/kyma-namespace/a-run-before.spec.js
  tests/integration/tests/kyma-namespace/test-issuers.spec.js
  tests/integration/tests/namespace/a-run-before.spec.js
  tests/integration/tests/namespace/test-cron-jobs.spec.js
  tests/integration/tests/namespace/test-jobs.spec.js
  tests/integration/tests/namespace/test-namespace-overview.spec.js
  tests/integration/tests/namespace/test-protected-resources.spec.js
  tests/integration/tests/namespace/test-reduced-permissions--configuration.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/integration/tests/namespace/test-resource-validation.spec.js
  tests/integration/tests/namespace/test-service-accounts.spec.js
  tests/integration/tests/namespace/test-settings.spec.js
  tests/integration/tests/namespace/z-run-after.spec.js
Labels: size/L, lgtm, cla: yes

#3554 chore: add unsafe eval for accessibility tests
  index.html
Labels: size/XS, lgtm, cla: yes

#3555 fix: small leftover bugs
  src/components/Extensibility/components/FeaturedCard/FeaturedCard.scss
  src/components/Preferences/Preferences.scss
  src/resources/createResourceRoutes.js
  src/shared/components/ExpandableListItem/ExpandableListItem.tsx
  src/shared/components/GenericList/SortModalPanel.js
  src/shared/components/PodTemplate/components.js
  src/shared/components/ProgressIndicatorWithPercentage/ProgressIndicatorWithPercentage.js
  src/sidebar/Sidebar.scss
  tests/integration/tests/accessibility/test-acc-cron-jobs.spec.js
  tests/integration/tests/accessibility/test-acc-extensions.spec.js
  tests/integration/tests/accessibility/test-acc-pizzas.spec.js
Labels: size/M, lgtm, cla: yes

#3556 feat: Modules docs url
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesCreate.js
  src/components/KymaModules/KymaModulesList.js
  src/components/KymaModules/ModulesCard.js
Labels: size/M, lgtm, cla: yes

#3557 fix: Adjust hpa status in yaml
  kyma/extensions/discovery-and-network/horizontal-pod-autoscalers.yaml
Labels: size/S, lgtm, cla: yes

#3550 feat(Modules): Add icon from ModuleTemplates
  .github/workflows/pull-integration-cluster-k3d.yml
  .github/workflows/pull-integration-namespace-k3d.yml
  .github/workflows/pull-kyma-integration-tests.yml
  .github/workflows/pull-lighthouse.yml
  .github/workflows/pull-smoke-test-prod.yml
  .github/workflows/pull-smoke-test-stage.yml
  .github/workflows/pull-unit-tests.yml
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesAddModule.scss
  src/components/KymaModules/ModulesCard.js
Labels: size/M, lgtm, cla: yes

#3562 fix: CPU and memory usage is not refreshing
  src/components/Nodes/NodeResources/NodeResources.js
  src/components/Nodes/nodeQueries.js
  src/shared/hooks/BackendAPI/useGet.js
Labels: size/M, lgtm, cla: yes

#3564 fix: Popover rendering problem
  src/shared/components/MonacoEditorESM/Editor.scss
Labels: size/XS, lgtm, cla: yes
