Repository kyma-project/busola, pull requests merged in 2024-03, with the labels that each got.

#2798 fix: stabilise cypress tests
  tests/integration/support/commands.js
  tests/integration/support/login-commands.js
  tests/integration/support/paste-to-monaco.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/cluster/test-dashboard-version.spec.js
  tests/integration/tests/namespace/z-run-after.spec.js
Labels: size/M, lgtm, cla: yes

#2805 fix: react-router links
  src/components/BusolaExtensions/BusolaExtensionDetails.js
  src/components/BusolaExtensions/BusolaExtensionList.js
  src/components/Clusters/views/ClusterList.js
  src/components/Clusters/views/ClusterOverview/ClusterNodes.js
  src/components/CustomResources/CustomResourcesByGroup.js
  src/components/CustomResources/CustomResourcesOfType.js
  src/components/Extensibility/components-form/Modules/Modules.js
  src/components/Extensibility/components/APIRules/APIRuleHost.js
  src/components/Extensibility/components/ResourceLink.js
  src/components/Extensibility/components/ResourceRefs.js
  src/components/Extensibility/helpers/index.js
  src/components/HelmReleases/HelmReleasesDetails.js
  src/components/HelmReleases/HelmReleasesList.js
  src/components/HelmReleases/OtherReleaseVersions.js
  src/components/HelmReleases/ReleaseDataPanel.js
  src/hooks/useMessageList.js
  src/resources/CronJobs/CronJobDetails.js
  src/resources/Events/EventDetails.js
  src/resources/Ingresses/DefaultBackendPanel.js
  src/resources/Ingresses/Rules.js
  src/resources/PersistentVolumeClaims/PersistentVolumeClaimDetails.js
  src/resources/PersistentVolumes/PersistentVolumeDetails.js
  src/resources/PersistentVolumes/PersistentVolumeList.js
  src/resources/Pods/PodDetails.js
  src/resources/Pods/PodList.js
  src/resources/RoleBindings/GenericRoleBindingList.js
  src/resources/RoleBindings/RoleRef.js
  src/resources/RoleBindings/SubjectLink.js
  src/shared/components/ControlledBy/ControlledBy.js
  src/shared/components/ControlledBy/test/ControlledBy.test.js
  src/shared/components/CountingCard/CountingCard.tsx
  src/shared/components/Description/Description.js
  src/shared/components/EmptyListComponent/EmptyListComponent.tsx
  src/shared/components/ExternalLink/CopiableLink.js
  src/shared/components/ExternalLink/ExternalLink.tsx
  src/shared/components/Link/Link.tsx
  src/shared/components/PodTemplate/components.js
  tests/integration/support/commands.js
  tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
  tests/integration/tests/namespace/test-jobs.spec.js
Labels: size/L, lgtm, cla: yes

#2806 feat: protected resources and yaml tab
  public/i18n/en.yaml
  src/components/BusolaExtensions/BusolaExtensionEdit.js
  src/components/Extensibility/ExtensibilityCreate.js
  src/components/HelmReleases/HelmReleasesDetails.js
  src/components/HelmReleases/HelmReleasesList.js
  src/components/HelmReleases/HelmReleasesYaml.js
  src/components/HelmReleases/index.tsx
  src/resources/ClusterRoleBindings/ClusterRoleBindingCreate.js
  src/resources/ClusterRoles/ClusterRoleCreate.js
  src/resources/ConfigMaps/ConfigMapCreate.js
  src/resources/CronJobs/CronJobCreate.js
  src/resources/CustomResourceDefinitions/CRCreate.js
  src/resources/CustomResourceDefinitions/CustomResourceDefinitionCreate.js
  src/resources/DaemonSets/DaemonSetCreate.js
  src/resources/Deployments/DeploymentCreate.js
  src/resources/Events/EventDetails.js
  src/resources/Events/EventYaml.js
  src/resources/Events/index.tsx
  src/resources/Ingresses/IngressCreate.js
  src/resources/Jobs/JobCreate.js
  src/resources/LimitRanges/LimitRangeCreate.js
  src/resources/Namespaces/NamespaceCreate.js
  src/resources/NetworkPolicies/NetworkPolicyCreate.js
  src/resources/PersistentVolumeClaims/PersistentVolumeClaimCreate.js
  src/resources/PersistentVolumes/PersistentVolumeCreate.js
  src/resources/Pods/PodCreate.js
  src/resources/ReplicaSets/ReplicaSetCreate.js
  src/resources/ResourceQuotas/ResourceQuotaCreate.js
  src/resources/RoleBindings/RoleBindingCreate.js
  src/resources/Roles/RoleCreate.js
  src/resources/Secrets/SecretCreate.js
  src/resources/ServiceAccounts/ServiceAccountCreate.js
  src/resources/StatefulSets/StatefulSetCreate.js
  src/resources/StorageClasses/StorageClassCreate.js
  src/resources/helpers.js
  src/resources/other/helmReleases.routes.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/ResourceCreate/ResourceCreate.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/hooks/useProtectedResources.js
Labels: size/L, lgtm, cla: yes

#2803 fix: view is jumping with column layout on some views
  src/components/App/ExtensibilityRoutes.js
  src/components/CustomResources/CustomResources.js
  src/components/CustomResources/CustomResourcesOfType.js
  src/resources/CustomResourceDefinitions/CustomResources.details.js
  src/resources/CustomResourceDefinitions/useCustomResourceUrl.js
  src/resources/createResourceRoutes.js
  src/resources/other/CustomResourceDetails.routes.js
  src/resources/other/CustomResourceListOfType.routes.js
  src/resources/other/CustomResourcesByGroup.routes.js
  src/shared/components/GenericList/GenericList.js
  tests/integration/support/commands.js
  tests/integration/support/paste-to-monaco.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/extensibility/ext-test-services.spec.js
Labels: size/XL, lgtm, cla: yes

#2812 feat: set edit view type based on preferences
  public/i18n/en.yaml
  src/components/Clusters/views/EditCluster/EditCluster.js
  src/components/Preferences/EditViewSettings.tsx
  src/components/Preferences/Preferences.tsx
  src/shared/ResourceForm/components/ModeSelector.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/state/preferences/editViewModeAtom.ts
Labels: size/L, lgtm, cla: yes

#2813 feat: Adjust edit/create layout
  src/components/App/ExtensibilityRoutes.js
  src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.scss
  src/resources/createResourceRoutes.js
  src/resources/other/BusolaExtensions.routes.js
  src/resources/other/CustomResourcesByGroup.routes.js
  src/resources/other/helmReleases.routes.js
  src/shared/ResourceForm/components/Presets.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/components/ResourceForm.scss
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
  src/shared/components/ResourceCreate/ResourceCreate.js
  src/shared/components/ResourceCreate/ResourceCreate.scss
  src/shared/hooks/useProtectedResources.js
  src/styles/index.scss
Labels: size/L, lgtm, cla: yes

#2814 fix: positioning of tabs-widget
  src/components/Extensibility/ExtensibilityDetails.js
  src/components/Extensibility/components/Tabs.js
  src/components/Extensibility/components/Widget.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceDetails/ResourceDetails.scss
  src/shared/components/ResourceDetails/ResourceDetailsCard.js
Labels: size/M, lgtm, cla: yes

#2820 fix: cloning resources is not working
  src/resources/createResourceRoutes.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/ResourcesList/ResourcesList.js
Labels: size/M, lgtm, cla: yes

#2819 feat: Adjust forms to new designs
  public/i18n/en.yaml
  src/components/App/ExtensibilityRoutes.js
  src/components/Extensibility/components-form/Jsonata.js
  src/components/Extensibility/components-form/MonacoRenderer.js
  src/components/Extensibility/components-form/SimpleList.js
  src/components/Extensibility/components-form/StringRenderer.js
  src/resources/Jobs/ScheduleSection.js
  src/resources/Namespaces/Presets.js
  src/resources/RoleBindings/RoleForm.js
  src/resources/RoleBindings/SubjectForm.js
  src/resources/Roles/RuleInput.js
  src/resources/Secrets/SecretCreate.js
  src/resources/helpers.js
  src/shared/ResourceForm/components/CollapsibleSection.js
  src/shared/ResourceForm/components/CollapsibleSection.scss
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/components/FormField.scss
  src/shared/ResourceForm/components/Label.js
  src/shared/ResourceForm/components/Label.scss
  src/shared/ResourceForm/components/Presets.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/components/ResourceForm.scss
  src/shared/ResourceForm/components/Title.js
  src/shared/ResourceForm/fields/DataField.js
  src/shared/ResourceForm/fields/K8sNameField.js
  src/shared/ResourceForm/fields/K8sNameField.scss
  src/shared/ResourceForm/fields/KeyValueField.js
  src/shared/ResourceForm/fields/MultiInput.js
  src/shared/ResourceForm/fields/RuntimeResources.js
  src/shared/ResourceForm/fields/RuntimeResources.scss
  src/shared/ResourceForm/inputs/Checkboxes.js
  src/shared/ResourceForm/inputs/ComboboxInput.js
  src/shared/ResourceForm/inputs/Dropdown.js
  src/shared/ResourceForm/inputs/Number.js
  src/shared/ResourceForm/inputs/Switch.js
  src/shared/ResourceForm/inputs/Text.js
  src/shared/components/Dropdown/Dropdown.js
  src/shared/components/K8sResourceSelect.js
  src/shared/components/ResourceRef/ExternalResourceRef.js
  src/shared/utils/helpers.js
  src/shared/utils/randomNamesGenerator/randomNamesGenerator.js
  src/shared/utils/randomNamesGenerator/words.js
  src/styles/index.scss
Labels: size/XXL, lgtm, cla: yes

#2822 fix: Translations on create form
  src/components/Extensibility/ExtensibilityCreate.js
Labels: size/M, lgtm, cla: yes

#2825 fix: Fix bug with alignment
  src/resources/Roles/RuleInput.js
  src/shared/ResourceForm/fields/KeyValueField.js
  src/shared/ResourceForm/fields/MultiInput.js
Labels: size/M, lgtm, cla: yes

#2826 fix: set correct image for busola web
  resources/web/deployment.yaml
Labels: size/XS, lgtm, cla: yes

#2821 fix: path in custom resources
  src/components/CustomResources/CustomResources.js
  src/resources/CustomResourceDefinitions/useCustomResourceUrl.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/ResourcesList/ResourcesList.js
Labels: size/M, lgtm, cla: yes

#2828 Merge main into in-page-edit
  resources/web/deployment.yaml
  src/components/App/ExtensibilityRoutes.js
  src/components/Clusters/views/ClusterOverview/ClusterNodes.js
  src/components/CustomResources/CustomResources.js
  src/components/CustomResources/GroupingListPage.js
  src/components/Extensibility/components/Table.js
  src/components/HelmReleases/HelmReleasesList.js
  src/resources/Pods/ContainersLogs.js
  src/resources/Pods/ContainersLogs.scss
  src/resources/createResourceRoutes.js
  src/resources/other/CustomResourcesByGroup.routes.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/GenericList.scss
  src/shared/components/GenericList/SearchInput.js
  src/shared/components/GenericList/constants.js
  tests/integration/support/commands.js
  tests/integration/support/inspect-list.js
  tests/integration/tests/cluster/test-command-palette.spec.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/cluster/test-navigation-features.spec.js
  tests/integration/tests/namespace/test-custom-resources.spec.js
  tests/integration/tests/namespace/test-jobs.spec.js
  tests/integration/tests/namespace/test-reduced-permissions--configuration.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/integration/tests/namespace/test-resource-upload.spec.js
  tests/integration/tests/namespace/z-run-after.spec.js
Labels: size/L, lgtm, cla: yes

#2827 fix: helm releases list is not working properly
  src/components/HelmReleases/HelmReleasesDetails.js
  src/components/HelmReleases/HelmReleasesList.js
  src/shared/ResourceForm/fields/MultiInput.scss
  src/shared/components/GenericList/GenericList.js
Labels: size/M, lgtm, cla: yes

#2823 fix: tabs alignment and namespace tests
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/components/UI5Panel/UI5Panel.js
  src/shared/components/UI5Panel/UI5Panel.scss
  tests/integration/support/commands.js
  tests/integration/support/create-edit-support.js
  tests/integration/support/createNamespace.js
  tests/integration/support/index.js
  tests/integration/support/inspectTab.js
  tests/integration/support/navigate-back-to.js
  tests/integration/support/paste-to-monaco.js
  tests/integration/tests/namespace/a-run-before.spec.js
  tests/integration/tests/namespace/test-config-maps.spec.js
  tests/integration/tests/namespace/test-cron-jobs.spec.js
  tests/integration/tests/namespace/test-daemon-sets.spec.js
  tests/integration/tests/namespace/test-deployments.spec.js
  tests/integration/tests/namespace/test-ingresses.spec.js
  tests/integration/tests/namespace/test-jobs.spec.js
  tests/integration/tests/namespace/test-namespace-overview.spec.js
  tests/integration/tests/namespace/test-network-policies.spec.js
  tests/integration/tests/namespace/test-persistent-volume-claims.spec.js
  tests/integration/tests/namespace/test-protected-resources.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/integration/tests/namespace/test-replica-sets.spec.js
  tests/integration/tests/namespace/test-roles.spec.js
  tests/integration/tests/namespace/test-secrets.spec.js
  tests/integration/tests/namespace/test-service-accounts.spec.js
  tests/integration/tests/namespace/test-settings.spec.js
  tests/integration/tests/namespace/test-stateful-sets.spec.js
Labels: size/XL, lgtm, cla: yes

#2829 fix: replace collapsible sections & remove simple, advanced
  docs/extensibility/README.md
  docs/extensibility/form-section.md
  examples/pizzas/configuration/pizza-orders-configmap.yaml
  examples/pizzas/configuration/pizzas-configmap.yaml
  examples/testing/configuration/test-resource-configmap.yaml
  examples/wizard/serverless-wizard.yaml
  public/i18n/en.yaml
  public/schemas/schema-form.yaml
  src/components/BusolaExtensions/helpers.js
  src/components/Clusters/views/ClusterOverview/ClusterValidation/ClusterValidationConfiguration.js
  src/components/Clusters/views/EditCluster/EditCluster.js
  src/components/Extensibility/ExtensibilityCreate.js
  src/components/Extensibility/components-form/CollapsibleRenderer.scss
  src/components/Extensibility/components-form/FormGroup.js
  src/components/Extensibility/components-form/FormGroup.scss
  src/components/Extensibility/components-form/index.js
  src/components/Extensibility/helpers/prepareRules.js
  src/components/Extensibility/plugins/SchemaRulesInjector.js
  src/components/HelmReleases/HelmReleaseData.js
  src/components/HelmReleases/HelmReleasesDetails.js
  src/components/HelmReleases/ReleaseDataPanel.js
  src/components/HelmReleases/tests/HelmReleaseData.test.js
  src/resources/CronJobs/CronJobCreate.js
  src/resources/Deployments/DeploymentCreate.js
  src/resources/Jobs/Containers.js
  src/resources/Jobs/ContainersSection.js
  src/resources/Jobs/JobCreate.js
  src/resources/Jobs/SpecSection.js
  src/resources/Namespaces/NamespaceCreate.js
  src/resources/ReplicaSets/ReplicaSetCreate.js
  src/resources/RoleBindings/GenericRoleBindingCreate.js
  src/resources/RoleBindings/SubjectForm.js
  src/resources/Roles/GenericRoleCreate.js
  src/resources/Roles/RuleInput.js
  src/resources/ServiceAccounts/ServiceAccountCreate.js
  src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.tsx
  src/shared/ResourceForm/components/CollapsibleSection.js
  src/shared/ResourceForm/components/CollapsibleSection.scss
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/components/ResourceForm.scss
  src/shared/ResourceForm/components/Title.js
  src/shared/ResourceForm/components/Wrapper.js
  src/shared/ResourceForm/fields/ComboboxArrayInput.js
  src/shared/ResourceForm/fields/ItemArray.js
  src/shared/ResourceForm/fields/K8sNameField.js
  src/shared/ResourceForm/fields/KeyValueField.js
  src/shared/ResourceForm/fields/MultiInput.js
  src/shared/ResourceForm/fields/RuntimeResources.js
  src/shared/ResourceForm/fields/SelectArrayInput.js
  src/shared/components/Deployment/Containers.js
  src/shared/components/Deployment/ContainersViews.js
  src/shared/components/ResourceRef/ExternalResourceRef.js
  src/shared/hooks/useCustomFormValidator/useCustomFormValidator.js
  src/shared/hooks/useCustomFormValidator/validateFormElement.js
Labels: size/XL, lgtm, cla: yes

#2833 fix: navigate to logs of pod
  src/resources/Pods/ContainersData.js
Labels: size/S, lgtm, cla: yes

#2824 feat: Replace `a` with `ui5link`
  src/components/Extensibility/components-form/Modules/Modules.js
  src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.tsx
  src/shared/components/CopiableText/CopiableText.js
  src/shared/components/DescriptionHint/DescriptionHint.js
  src/shared/components/EmptyListComponent/EmptyListComponent.scss
  src/shared/components/EmptyListComponent/EmptyListComponent.tsx
  src/shared/components/ExternalLink/CopiableLink.tsx
  src/shared/components/ExternalLink/ExternalLink.tsx
  src/styles/index.scss
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
Labels: size/M, lgtm, cla: yes

#2835 feat: basic UI panel for ai assistant
  public/i18n/en.yaml
  src/components/AIassistant/components/AIassistant.js
  src/components/AIassistant/components/AIassistant.scss
  src/components/AIassistant/components/Chat.js
  src/components/AIassistant/components/Chat.scss
  src/components/AIassistant/components/IntroBox.js
  src/components/AIassistant/components/IntroBox.scss
  src/components/AIassistant/components/PageInsights.js
  src/components/AIassistant/components/PageInsights.scss
  src/components/AIassistant/state/showAIassistantAtom.ts
  src/components/App/App.scss
  src/components/App/App.tsx
  src/header/Header.tsx
Labels: size/L, cla: yes

#2831 feat: Adjust cluster tests
  src/components/App/ExtensibilityRoutes.js
  tests/integration/support/create-edit-support.js
  tests/integration/support/createNamespace.js
  tests/integration/support/exceptions.js
  tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
  tests/integration/tests/cluster/test-cluster-validation.spec.js
  tests/integration/tests/cluster/test-command-palette.spec.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/cluster/test-persistent-volumes.spec.js
  tests/integration/tests/cluster/test-storage-classes.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-services.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
Labels: size/L, lgtm, cla: yes

#2846 Merge main into in-page-edit
  src/components/Extensibility/components-form/Modules/Modules.js
  src/resources/Pods/ContainersData.js
  src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.tsx
  src/shared/components/CopiableText/CopiableText.js
  src/shared/components/DescriptionHint/DescriptionHint.js
  src/shared/components/EmptyListComponent/EmptyListComponent.scss
  src/shared/components/EmptyListComponent/EmptyListComponent.tsx
  src/shared/components/ExternalLink/CopiableLink.tsx
  src/shared/components/ExternalLink/ExternalLink.tsx
  src/styles/index.scss
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
Labels: size/L, lgtm, cla: yes

#2832 fix: in-page edit UX adjustments
  src/resources/other/helmReleases.routes.js
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/components/Title.js
  src/shared/components/DescriptionHint/DescriptionHint.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
  src/shared/components/ResourceCreate/ResourceCreate.scss
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/contexts/YamlEditorContext/EditorActions.js
  src/shared/contexts/YamlEditorContext/EditorActions.scss
Labels: size/L, lgtm, cla: yes

#2848 fix: Upload YAML is broken on some views
  src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  src/components/CustomResources/CustomResourcesOfType.js
  src/components/CustomResources/GroupingListPage.js
  src/components/HelmReleases/HelmReleasesDetails.js
  src/components/HelmReleases/HelmReleasesList.js
  src/components/Nodes/NodeDetails/NodeDetails.js
  tests/integration/tests/namespace/test-resource-upload.spec.js
Labels: size/S, lgtm, cla: yes

#2851 fix: Fix tests and simple/advanced changes
  src/resources/CronJobs/CronJobCreate.js
  src/resources/Deployments/DeploymentCreate.js
  src/resources/Jobs/ContainersSection.js
  src/resources/Jobs/JobCreate.js
  src/resources/ReplicaSets/ReplicaSetCreate.js
  src/resources/RoleBindings/GenericRoleBindingCreate.js
  src/resources/RoleBindings/SubjectForm.js
  src/shared/components/Deployment/ContainersViews.js
  tests/integration/support/commands.js
  tests/integration/support/inspect-list.js
  tests/integration/tests/cluster/test-cluster-validation.spec.js
  tests/integration/tests/namespace/test-jobs.spec.js
  tests/integration/tests/namespace/test-reduced-permissions.spec.js
  tests/integration/tests/namespace/test-service-accounts.spec.js
Labels: size/L, lgtm, cla: yes

#2859 fix: fix injections bug
  src/components/Extensibility/useGetInjection.js
Labels: size/XS, lgtm, cla: yes

#2852 feat: kyma companion prototype
  public/i18n/en.yaml
  src/components/AIassistant/components/AIassistant.js
  src/components/AIassistant/components/AIassistant.scss
  src/components/AIassistant/components/Chat.js
  src/components/AIassistant/components/Chat.scss
  src/components/AIassistant/components/Chat/Chat.js
  src/components/AIassistant/components/Chat/Chat.scss
  src/components/AIassistant/components/Chat/messages/Bubbles.js
  src/components/AIassistant/components/Chat/messages/Bubbles.scss
  src/components/AIassistant/components/Chat/messages/ErrorMessage.js
  src/components/AIassistant/components/Chat/messages/MessageWithList.js
  src/components/AIassistant/components/Chat/messages/MessageWithList.scss
  src/components/AIassistant/components/Chat/messages/PlainMessage.js
  src/components/AIassistant/components/Chat/messages/PlainMessage.scss
  src/components/AIassistant/components/IntroBox.scss
  src/components/AIassistant/components/PageInsights.js
  src/components/AIassistant/components/PageInsights.scss
  src/components/AIassistant/components/PageInsights/InsightPanel.js
  src/components/AIassistant/components/PageInsights/InsightPanel.scss
  src/components/AIassistant/components/PageInsights/PageInsights.js
  src/components/AIassistant/components/PageInsights/PageInsights.scss
  src/components/AIassistant/utils/getChatResponse.js
  src/components/AIassistant/utils/getPromptSuggestions.js
  src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  src/components/Clusters/views/ClusterOverview/ClusterOverview.scss
  src/components/HelmReleases/HelmReleasesDetails.js
  src/header/Header.tsx
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceDetails/ResourceDetailsCard.js
  src/styles/index.scss
Labels: size/XL, lgtm, cla: yes

#2850 feat: Adjust upload yaml to new desing standards.
  public/i18n/en.yaml
  src/resources/Namespaces/YamlUpload/FilteredResourcesDetails/FilteredResourcesDetails.js
  src/resources/Namespaces/YamlUpload/YamlResourcesList.js
  src/resources/Namespaces/YamlUpload/YamlResourcesList.scss
  src/resources/Namespaces/YamlUpload/YamlUpload.js
  src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
  src/resources/Namespaces/YamlUpload/YamlUploadDialog.scss
  src/styles/wizard-dialog.scss
  tests/integration/tests/namespace/test-resource-upload.spec.js
  tests/integration/tests/namespace/test-resource-validation.spec.js
Labels: size/L, lgtm, cla: yes

#2853 fix: UX adjustments - general
  public/index.html
  src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  src/components/Extensibility/components/Badge.js
  src/components/Extensibility/components/tests/Badge.test.js
  src/header/Header.scss
  src/header/Header.tsx
  src/header/NamespaceDropdown/NamespaceDropdown.tsx
  src/resources/Jobs/JobCompletions.js
  src/resources/Pods/PodRestarts.js
  src/shared/ResourceForm/inputs/Switch.js
  src/shared/ResourceForm/inputs/Text.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
  src/shared/components/ExternalLink/ExternalLink.tsx
  src/shared/components/PopoverBadge/PopoverBadge.scss
  src/shared/components/PopoverBadge/PopoverBadge.tsx
  src/shared/components/ProgressIndicatorWithPercentage/ProgressIndicatorWithPercentage.js
  src/shared/components/ResourceStatusCard/ResourceStatusCard.scss
  src/shared/components/RunningPodsStatus.js
  src/shared/components/StatusBadge/StatusBadge.js
  src/shared/components/StatusBadge/StatusBadge.scss
  src/shared/contexts/YamlEditorContext/EditorActions.js
  src/shared/contexts/YamlEditorContext/EditorActions.scss
  src/sidebar/SidebarNavigation.tsx
  src/styles/index.scss
  tests/integration/tests/cluster/test-command-palette.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-services.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/namespace/test-resource-upload.spec.js
  tests/integration/tests/namespace/test-resource-validation.spec.js
Labels: size/L, lgtm, cla: yes

#2864 fix: edit Nodejs function dependencies in JSON format
  src/components/Extensibility/components-form/MonacoRenderer.js
Labels: size/S, lgtm, cla: yes

#2865 fix: paddings in Sidenav
  src/sidebar/Sidebar.scss
  src/sidebar/SidebarNavigation.tsx
Labels: size/M, lgtm, cla: yes
