Repository kyma-project/busola, pull requests merged in 2024-09, with the labels that each got.

#3312 feat: Dynamic config
  .gitignore
  .prettierignore
  Dockerfile
  src/shared/utils/env.ts
  src/shared/utils/path.test.ts
  src/shared/utils/path.ts
  src/state/configuration/configurationAtom.ts
  src/state/navigation/extensionsAtom.ts
  start_nginx.sh
Labels: size/M, lgtm, cla: yes

#3322 docs: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS, lgtm, cla: yes

#3325 docs: Add mandatory sections to README.md
  README.md
Labels: size/S, lgtm, cla: yes

#3320 feat: create view for Limit Ranges
  public/i18n/en.yaml
  src/resources/LimitRanges/LimitRangeCreate.js
  src/resources/LimitRanges/LimitRangeDetails.tsx
  src/resources/LimitRanges/LimitRangeList.js
  src/resources/LimitRanges/LimitRangeList.tsx
  src/resources/LimitRanges/LimitRangeSpecification.scss
  src/resources/LimitRanges/LimitRangeSpecification.tsx
  src/resources/LimitRanges/LimitRangesList.js
  src/resources/LimitRanges/index.tsx
  src/resources/Namespaces/NamespaceDetails.js
  src/resources/index.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/components.js
  tests/integration/cypress.config.js
  tests/integration/tests/namespace/test-limit-ranges.spec.js
  tests/integration/tests/namespace/test-namespace-overview.spec.js
Labels: size/XL, lgtm, cla: yes

#3328 chore: Update codeowners
  CODEOWNERS
Labels: size/XS, lgtm, cla: yes

#3324 feat: Add long columns in status card
  docs/extensibility/30-details-summary.md
  docs/extensibility/50-list-and-details-widgets.md
  src/components/Extensibility/ExtensibilityDetails.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceStatusCard/ResourceStatusCard.js
Labels: size/M, lgtm, cla: yes

#3321 feat: Add Kyma config from kyma-dashboard
  .dockerignore
  .github/workflows/busola-kyma-build.yml
  .gitignore
  .prettierignore
  Dockerfile.kyma
  Dockerfile.local.kyma
  kyma/.gitignore
  kyma/Makefile
  kyma/environments/dev/config.yaml
  kyma/environments/dev/extensions.json
  kyma/environments/dev/statics.json
  kyma/environments/dev/wizards.json
  kyma/environments/prod/config.yaml
  kyma/environments/prod/extensions.json
  kyma/environments/prod/statics.json
  kyma/environments/prod/wizards.json
  kyma/environments/stage/config.yaml
  kyma/environments/stage/extensions.json
  kyma/environments/stage/statics.json
  kyma/environments/stage/wizards.json
  kyma/extensions/applicationconnector/applications.yaml
  kyma/extensions/configuration/certificates.yaml
  kyma/extensions/configuration/dns-entries.yaml
  kyma/extensions/configuration/dns-providers.yaml
  kyma/extensions/configuration/issuers.yaml
  kyma/extensions/configuration/oauth2.yaml
  kyma/extensions/discovery-and-network/horizontal-pod-autoscalers.yaml
  kyma/extensions/discovery-and-network/services.yaml
  kyma/extensions/kyma/kyma.yaml
  kyma/extensions/service-management/servicebindings.yaml
  kyma/extensions/service-management/serviceinstances.yaml
  kyma/extensions/statics/kibana-links.yaml
  kyma/extensions/wizards/module-wizard.yaml
  kyma/gulpfile.js
  kyma/package-lock.json
  kyma/package.json
  src/shared/utils/env.ts
  start_node.sh
Labels: size/XXL, lgtm, cla: yes

#3319 feat: Enhance PVC
  public/i18n/en.yaml
  src/resources/PersistentVolumeClaims/PersistentVolumeClaim.scss
  src/resources/PersistentVolumeClaims/PersistentVolumeClaimCreate.js
  src/resources/PersistentVolumeClaims/PersistentVolumeClaimDetails.js
  src/shared/components/LayoutPanelRow/LayoutPanelRow.scss
Labels: size/L, lgtm, cla: yes

#3318 fix: clean up unused translations
  public/i18n/en.yaml
  src/components/BusolaExtensions/BusolaExtensionDetails.js
  src/components/Clusters/components/AddClusterWizard.js
  src/resources/Jobs/ScheduleSection.js
Labels: size/L, lgtm, cla: yes

#3332 feat: Unify nodejs version for building
  .github/workflows/busola-kyma-build.yml
  Dockerfile
  Dockerfile.kyma
  Dockerfile.local
  Dockerfile.local.kyma
Labels: size/S, lgtm, cla: yes

#3331 fix: editing resources
  src/resources/CustomResourceDefinitions/CustomResourceDefinitionCreate.js
  src/resources/DaemonSets/DaemonSetCreate.js
  src/resources/PersistentVolumes/PersistentVolumeCreate.js
  src/resources/Pods/PodCreate.js
  src/resources/StatefulSets/StatefulSetCreate.js
  src/resources/StorageClasses/StorageClassCreate.js
Labels: size/S, lgtm, cla: yes

#3335 chore: Remove script dir
  scripts/build-docker-image.sh
  scripts/checkClusterAvailability.sh
  scripts/pre-build-docker-image.sh
  scripts/pre-start-warning.sh
  scripts/update-resource-validation-imports.sh
Labels: size/L, lgtm, cla: yes

#3337 fix: adjust SCSSes
  src/resources/LimitRanges/LimitRangeSpecification.scss
  src/resources/Pods/ContainersLogs.scss
  src/shared/ResourceForm/fields/RichEditorDataField/RichEditorSection.scss
Labels: size/S, lgtm, cla: yes

#3339 fix: bug onRowClick with duplicate names
  src/shared/components/GenericList/GenericList.js
  src/shared/components/ResourcesList/ResourcesList.js
Labels: size/S, lgtm, cla: yes

#3336 feat: create Resource Quotas views
  public/i18n/en.yaml
  src/resources/LimitRanges/LimitRangeSpecification.tsx
  src/resources/Namespaces/NamespaceDetails.js
  src/resources/ResourceQuotas/ResourceQuotaCreate.js
  src/resources/ResourceQuotas/ResourceQuotaDetails.scss
  src/resources/ResourceQuotas/ResourceQuotaDetails.tsx
  src/resources/ResourceQuotas/ResourceQuotaLimits.tsx
  src/resources/ResourceQuotas/ResourceQuotaList.tsx
  src/resources/ResourceQuotas/ResourceQuotasList.tsx
  src/resources/ResourceQuotas/index.tsx
  src/resources/index.js
  src/shared/components/UI5Panel/UI5Panel.tsx
  tests/integration/cypress.config.js
  tests/integration/fixtures/test-resource-quotas.yaml
  tests/integration/tests/namespace/test-namespace-overview.spec.js
  tests/integration/tests/namespace/test-resource-quotas.spec.js
Labels: size/L, lgtm, cla: yes

#3341 feat: enhance Helm Releases
  public/i18n/en.yaml
  src/components/HelmReleases/ChartContent.js
  src/components/HelmReleases/HelmReleaseData.js
  src/components/HelmReleases/HelmReleasesDetails.js
  src/components/HelmReleases/HelmReleasesList.js
  src/components/HelmReleases/ReleaseDataPanel.js
  src/resources/Secrets/SecretDetails.js
  src/shared/components/ReadonlyEditorPanel.js
Labels: size/L, lgtm, cla: yes

#3338 feat: enhance events
  public/i18n/en.yaml
  src/resources/Events/EventDetails.js
  src/shared/components/ResourceDetails/ResourceDetails.js
Labels: size/L, lgtm, cla: yes

#3340 feat: Add visibility to status
  src/components/Extensibility/ExtensibilityDetails.js
Labels: size/S, lgtm, cla: yes

#3343 chore: remove unused commands and smoke test config
  tests/integration/cypress-smoke.js
  tests/integration/package.json
Labels: size/M, lgtm, cla: yes

#3342 feat: enhance namespace overview
  src/resources/Namespaces/AllNamespacesDetails.js
  src/resources/Namespaces/NamespaceDetails.js
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
  src/resources/ResourceQuotas/ResourceQuotasList.tsx
Labels: size/L, lgtm, cla: yes

#3344 feat: Add overlays with environments configuration
  config-overrides.js
  resources/apply-resources-istio.sh
  resources/apply-resources.sh
  resources/base/backend/deployment.yaml
  resources/base/backend/hpa.yaml
  resources/base/backend/kustomization.yaml
  resources/base/backend/service.yaml
  resources/base/extensions-patch/builtin-resource-extensions.configmap.yaml
  resources/base/extensions-patch/kustomization.yaml
  resources/base/extensions-patch/web-deployment.patch.yaml
  resources/base/ingress.tpl.yaml
  resources/base/ingressClass.yaml
  resources/base/kustomization.yaml
  resources/base/resource-validation/rule-sets/datree/rules.yaml
  resources/base/resource-validation/rule-sets/default/policies.yaml
  resources/base/resource-validation/rule-sets/kubernetes-pod-security-standards/policies.yaml
  resources/base/resource-validation/rule-sets/kubernetes-pod-security-standards/rules.yaml
  resources/base/resource-validation/rulesetSchema.json
  resources/base/web/configmap.yaml
  resources/base/web/deployment.yaml
  resources/base/web/hpa.yaml
  resources/base/web/kustomization.yaml
  resources/base/web/service.yaml
  resources/environments/dev/environment.env
  resources/environments/dev/kustomization.yaml
  resources/environments/prod/environment.env
  resources/environments/prod/kustomization.yaml
  resources/environments/stage/environment.env
  resources/environments/stage/kustomization.yaml
  resources/istio/kustomization.yaml
  resources/istio/virtualservice-busola.tpl.yaml
Labels: size/M, lgtm, cla: yes

#3349 fix: fix console errors in Extensions
  src/components/BusolaExtensions/BusolaExtensionDetails.js
  src/components/BusolaExtensions/BusolaExtensionEdit.js
  src/shared/ResourceForm/fields/KeyValueField.js
  src/shared/components/MonacoEditorESM/Editor.js
  src/sidebar/CategoryItem.tsx
Labels: size/L, lgtm, cla: yes

#3316 feat: disableOnEdit KeyValuePair
  docs/extensibility/60-form-widgets.md
  public/schemas/schema-form.yaml
  src/components/Extensibility/components-form/KeyValuePairRenderer.js
  src/shared/ResourceForm/fields/KeyValueField.js
  src/shared/ResourceForm/fields/MultiInput.js
Labels: size/M, lgtm, cla: yes

#3352 feat: sync kyma dashboard with PR https://github.com/kyma-project/kyma-dashboard/pull/376
  kyma/extensions/discovery-and-network/services.yaml
Labels: size/L, lgtm, cla: yes

#3348 fix: escape kebab case in jsonata expression
  src/components/Extensibility/helpers/jsonataWrapper.ts
  src/components/Extensibility/helpers/tests/escapeKebabCase.test.js
Labels: size/L, lgtm, cla: yes

#3347 feat: Update docs about recent changes related to kyma-dashboard
  README.md
  kyma/README.md
  tests/kyma/README.md
  tests/kyma/package.json
Labels: size/L, lgtm, cla: yes

#3354 fix: defaultOpen for job containers
  src/resources/Jobs/ContainersSection.js
  tests/integration/tests/namespace/test-jobs.spec.js
Labels: size/XS, lgtm, cla: yes

#3353 fix: edit resource from upload yaml
  src/components/Extensibility/ExtensibilityWizard.js
  src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
  src/resources/Namespaces/YamlUpload/useUploadResources.js
Labels: size/M, lgtm, cla: yes

#3360 fix: Remove capitalization of data in rows
  src/resources/PersistentVolumeClaims/PersistentVolumeClaimDetails.js
  src/shared/components/LayoutPanelRow/LayoutPanelRow.scss
  src/shared/components/LayoutPanelRow/LayoutPanelRow.tsx
Labels: size/S, lgtm, cla: yes

#3363 chore: bump deps in backend image
  backend/Dockerfile
  backend/package-lock.json
  backend/package.json
Labels: size/L, lgtm, cla: yes

#3361 fix: section editor performance
  package-lock.json
  package.json
  public/i18n/en.yaml
  src/components/BusolaExtensions/BusolaExtensionDetails.js
  src/components/Clusters/views/ClusterOverview/ClusterDetails.js
  src/components/Clusters/views/ClusterOverview/ClusterNodes.js
  src/components/Clusters/views/EditCluster/AuthenticationDropdown.js
  src/components/Extensibility/components-form/Jsonata.js
  src/components/Extensibility/components-form/MonacoRenderer.js
  src/components/Extensibility/components-form/SimpleList.js
  src/resources/RoleBindings/RoleForm.js
  src/resources/Secrets/SecretCreate.js
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/components/FormField.scss
  src/shared/ResourceForm/fields/MultiInput.js
  src/shared/ResourceForm/inputs/Checkboxes.js
  src/shared/ResourceForm/inputs/ComboboxInput.js
  src/shared/ResourceForm/inputs/Dropdown.js
  src/shared/ResourceForm/inputs/Number.js
  src/shared/ResourceForm/inputs/Switch.js
  src/shared/ResourceForm/inputs/Text.js
  src/shared/components/K8sResourceSelect.js
  src/shared/components/ResourceDetails/ResourceDetails.scss
  src/shared/components/ResourceRef/ExternalResourceRef.js
  tests/kyma/tests/namespace/test-dns-providers.spec.js
  tests/kyma/tests/namespace/test-issuers.spec.js
Labels: size/XL, lgtm, cla: yes

#3364 fix: incorrect redirect after new cluster is added
  src/components/Clusters/views/ClusterList.js
Labels: size/S, lgtm, cla: yes
