Repository kyma-project/busola, pull requests merged in 2024-04, with the labels that each got.

#2867 fix: UX adjustments cluster overview
  public/i18n/en.yaml
  src/components/Clusters/views/ClusterOverview/ClusterStats.js
  src/components/Clusters/views/ClusterOverview/ClusterStats.scss
  src/components/Clusters/views/ClusterStorageType.js
  src/header/NamespaceChooser/NamespaceChooser.tsx
  src/resources/Events/EventDetails.js
  src/resources/Events/EventList.js
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
  src/resources/Namespaces/ResourcesUsage.js
  src/shared/components/CountingCard/CountingCard.scss
  src/shared/components/CountingCard/CountingCard.tsx
  src/shared/components/GenericList/GenericList.js
  src/shared/components/Labels/Labels.scss
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceDetails/ResourceDetails.scss
  src/shared/components/ResourcesList/ResourcesList.js
  src/shared/components/UI5RadialChart/UI5RadialChart.js
  src/shared/components/UI5RadialChart/UI5RadialChart.scss
  tests/integration/tests/namespace/test-namespace-overview.spec.js
  tests/integration/tests/namespace/test-service-accounts.spec.js
  tests/lighthouse/lighthouse.spec.js
Labels: size/XL, lgtm, cla: yes

#2875 fix: fix edit cr
  src/resources/CustomResourceDefinitions/CRCreate.js
  src/shared/ResourceForm/useCreateResource.js
Labels: size/S, lgtm, cla: yes

#2871 fix: Ux changes in tables
  src/resources/LimitRanges/LimitRangeList.js
  src/resources/ResourceQuotas/ResourceQuotaList.js
  src/shared/components/EmptyListComponent/EmptyListComponent.scss
  src/shared/components/EmptyListComponent/EmptyListComponent.tsx
  src/shared/components/ExternalLink/ExternalLink.tsx
  src/shared/components/GenericList/components.js
  src/shared/components/Labels/Labels.js
  src/shared/components/PodTemplate/components.js
  src/shared/components/ResourceGraph/ResourceGraph.tsx
  src/shared/components/ResourcesList/ResourcesList.js
  src/shared/components/Selector/Selector.js
  src/shared/components/UI5Panel/UI5Panel.js
  src/styles/index.scss
Labels: size/M, lgtm, cla: yes

#2874 fix: link for SAP logo
  src/header/Logo/Logo.tsx
  tests/integration/tests/namespace/test-service-accounts.spec.js
Labels: size/XS, lgtm, cla: yes

#2870 fix: get/fetch errors
  src/components/App/NamespaceRoutes.tsx
  src/components/CustomResources/CustomResourcesOfType.js
  src/components/Extensibility/ExtensibilityDetails.js
  src/components/Extensibility/ExtensibilityList.js
  src/resources/CustomResourceDefinitions/CustomResources.details.js
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
  src/resources/helpers.js
Labels: size/M, lgtm, cla: yes

#2881 fix: code editor for service bindings and instances
  public/schemas/schema-form.yaml
  src/components/Extensibility/components-form/MonacoRenderer.js
Labels: size/S, lgtm, cla: yes

#2876 fix: UX adjustment - node info
  public/i18n/en.yaml
  src/components/Clusters/views/ClusterOverview/ClusterDetails.js
  src/components/Nodes/MachineInfo/MachineInfo.js
  src/components/Nodes/MachineInfo/MachineInfo.scss
  src/components/Nodes/NodeDetails/NodeDetails.js
  src/components/Nodes/NodeDetailsCard.js
  src/components/Nodes/NodeDetailsHeader.js
  src/components/Nodes/NodeResources/NodeResources.js
  src/resources/Namespaces/ResourcesUsage.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceDetails/ResourceDetailsCard.js
Labels: size/L, lgtm, cla: yes

#2882 fix: Extensibility Widgets data not updating after resource change
  src/components/Extensibility/components/Widget.js
  src/components/Extensibility/contexts/DataSources.tsx
  src/shared/components/RelatedPods.js
Labels: size/XS, lgtm, cla: yes

#2884 fix: create form column is not closing after creating namespace
  src/resources/Namespaces/NamespaceCreate.js
Labels: size/S, lgtm, cla: yes

#2885 fix: YAML form for namespaces is not working
  src/resources/Namespaces/NamespaceCreate.js
  src/resources/Namespaces/NamespaceCreate.scss
Labels: size/S, lgtm, cla: yes

#2888 feat: AI-banner & banner-carousel
  docs/extensibility/display-section.md
  package-lock.json
  package.json
  src/components/App/useInitTheme.ts
  src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  src/components/Extensibility/components/ExternalLinkButton.js
  src/components/Extensibility/components/FeaturedCard/BannerCarousel.js
  src/components/Extensibility/components/FeaturedCard/FeaturedCard.js
  src/components/Extensibility/components/FeaturedCard/FeaturedCard.scss
  src/components/Extensibility/components/FeaturedCard/assets/AI/AiIllustrationDark.svg
  src/components/Extensibility/components/FeaturedCard/assets/AI/AiIllustrationHCdark.svg
  src/components/Extensibility/components/FeaturedCard/assets/AI/AiIllustrationHClight.svg
  src/components/Extensibility/components/FeaturedCard/assets/AI/AiIllustrationLight.svg
  src/components/Extensibility/components/FeaturedCard/assets/Modules/modulesIllustration.svg
  src/components/Extensibility/components/FeaturedCard/assets/Modules/modulesIllustrationHC.svg
  src/components/Extensibility/helpers/jsonataWrapper.ts
  src/components/Preferences/ThemeChooser.tsx
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/state/preferences/themeAtom.ts
Labels: size/L, lgtm, cla: yes

#2883 Adjust upload yaml
  public/defaultConfig.yaml
  public/i18n/en.yaml
  src/resources/Namespaces/YamlUpload/FilteredResourcesDetails/FilteredResourcesDetails.scss
  src/resources/Namespaces/YamlUpload/ResourceValidationResult.js
  src/resources/Namespaces/YamlUpload/SeparatorLine.js
  src/resources/Namespaces/YamlUpload/SeparatorLine.scss
  src/resources/Namespaces/YamlUpload/ValidationSwitch.js
  src/resources/Namespaces/YamlUpload/ValidationSwitch.scss
  src/resources/Namespaces/YamlUpload/YamlResourceList.scss
  src/resources/Namespaces/YamlUpload/YamlResourcesList.js
  src/resources/Namespaces/YamlUpload/YamlResourcesList.scss
  src/resources/Namespaces/YamlUpload/YamlUpload.js
  src/resources/Namespaces/YamlUpload/YamlUploadDialog.js
  src/resources/Namespaces/YamlUpload/YamlUploadDialog.scss
  src/shared/components/MonacoEditorESM/Editor.js
  tests/integration/tests/namespace/test-resource-validation.spec.js
Labels: size/L, lgtm, cla: yes

#2895 fix: busola version and defaultConfig
  public/defaultConfig.yaml
  src/header/SidebarMenu/useGetBusolaVersion.ts
  src/resources/Events/EventDetails.js
  src/resources/Events/EventList.js
Labels: size/S, lgtm, cla: yes

#2896 add Oliwia as codeowner
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/XS, lgtm, cla: yes

#2897 fix: injections without name or order
  src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  src/components/Clusters/views/ClusterStorageType.js
  src/components/Extensibility/useGetInjection.js
Labels: size/S, lgtm, cla: yes
