Repository kyma-project/busola, pull requests merged in 2024-01, with the labels that each got.

#2711 Redesign ClusterOverview
  package-lock.json
  package.json
  public/i18n/en.yaml
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterDetails.js
  src/components/Clusters/views/ClusterOverview/ClusterNodes.js
  src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterNodes.scss
  src/components/Clusters/views/ClusterOverview/ClusterNodes/ClusterStats.js
  src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  src/components/Clusters/views/ClusterOverview/ClusterOverview.scss
  src/components/Clusters/views/ClusterOverview/ClusterOverviewHeader.js
  src/components/Clusters/views/ClusterOverview/ClusterStats.js
  src/components/Nodes/NodeResources/NodeResources.js
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
  src/resources/Namespaces/ResourcesUsage.js
  src/shared/components/CircleProgress/CircleProgress.js
  src/shared/components/CircleProgress/CircleProgress.scss
  src/shared/components/GenericList/test/GenericList.test.js
  src/shared/components/UI5RadialChart/UI5RadialChart.js
  src/shared/components/UI5RadialChart/UI5RadialChart.scss
  src/shared/hooks/useDeleteResource.js
  tests/integration/tests/cluster/test-cluster-validation.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-services.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/namespace/test-resource-upload.spec.js
  tests/integration/tests/namespace/test-resource-validation.spec.js
Labels: size/XXL, lgtm, cla: yes

#2713 remove snow feature
  package-lock.json
  package.json
  public/defaultConfig.yaml
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
  src/components/App/Snow/Snow.js
  src/index.js
Labels: size/M, lgtm, cla: yes

#2715 Change Service Account token generation
  resources/web/deployment.yaml
  src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.tsx
  tests/integration/support/helpers.js
  tests/integration/tests/namespace/test-service-accounts.spec.js
Labels: size/M, lgtm, cla: yes

#2718 ClusterOverview colors adjustment
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterStats.js
Labels: size/XS, lgtm, cla: yes

#2720 Fix lighthouse-test
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterNodes.js
  src/components/Extensibility/components/Badge.js
  src/components/Extensibility/components/tests/Badge.test.js
  src/components/Preferences/LanguageSettings.tsx
  src/components/Preferences/OtherSettings.tsx
  src/header/Header.tsx
  src/header/Logo/Logo.tsx
  src/header/NamespaceChooser/NamespaceChooser.tsx
  src/header/NamespaceDropdown/NamespaceDropdown.tsx
  src/header/SidebarSwitcher/SidebarSwitcher.tsx
  src/hooks/useMessageList.js
  src/resources/Events/EventList.js
  src/shared/components/Dropdown/Dropdown.js
  src/shared/components/GenericList/SortModalPanel.js
  src/shared/components/GenericList/components.js
  src/shared/components/ResourceGraph/ResourceGraph.tsx
  src/shared/components/ResourceStatus/ResourceStatus.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/shared/components/StatusBadge/StatusBadge.js
  src/shared/components/TooltipBadge/TooltipBadge.js
  src/shared/components/UI5Panel/UI5Panel.js
  src/shared/hooks/useDeleteResource.js
  src/sidebar/SidebarNavigation.tsx
  tests/integration/support/commands.js
  tests/integration/tests/cluster/test-cluster-configuration.spec.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/namespace/test-custom-resources.spec.js
  tests/lighthouse/lighthouse.spec.js
Labels: size/L, lgtm, cla: yes

#2712 Command Palette redesign
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/command-pallette/CommandPalletteUI/CommandPaletteUI.scss
  src/command-pallette/CommandPalletteUI/CommandPaletteUI.tsx
  src/command-pallette/CommandPalletteUI/ResultsList/Result.scss
  src/command-pallette/CommandPalletteUI/ResultsList/Result.tsx
  src/command-pallette/CommandPalletteUI/ResultsList/ResultsList.scss
  src/command-pallette/CommandPalletteUI/ResultsList/ResultsList.tsx
  src/command-pallette/CommandPalletteUI/components/components.scss
  src/command-pallette/CommandPalletteUI/components/components.tsx
  src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/crHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/crListHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/crdHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/helmReleaseHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/helpers.ts
  src/command-pallette/CommandPalletteUI/handlers/index.ts
  src/command-pallette/CommandPalletteUI/handlers/logsHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/namespacedResourceHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/nodesHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/nonResourceHandler.ts
  src/command-pallette/CommandPalletteUI/types.ts
  src/command-pallette/CommandPalletteUI/useSearchResults.tsx
  src/resources/Jobs/index.ts
  src/styles/index.scss
  tests/integration/tests/cluster/test-command-palette.spec.js
Labels: size/XL, lgtm, cla: yes

#2725 replaced Spinner-components
  resources/web/deployment.yaml
  src/components/CustomResources/GroupingListPage.js
  src/components/Extensibility/components/PendingWrapper.js
  src/resources/Namespaces/YamlUpload/FilteredResourcesDetails/FilteredResourcesDetails.js
  src/resources/Namespaces/YamlUpload/FilteredResourcesDetails/FilteredResourcesDetails.scss
  src/resources/RoleBindings/RoleForm.js
  src/shared/components/ResourceRef/ExternalResourceRef.js
  src/shared/components/Spinner/Spinner.tsx
  src/sidebar/Sidebar.tsx
Labels: size/M, lgtm, cla: yes

#2723 Sidenav permissions fix
  resources/web/deployment.yaml
  src/command-pallette/CommandPalletteUI/handlers/clusterResourceHandler.ts
  src/command-pallette/CommandPalletteUI/handlers/crdHandler.ts
  src/components/Clusters/shared.ts
  src/header/NamespaceDropdown/NamespaceDropdown.tsx
  src/resources/CustomResourceDefinitions/index.js
  src/resources/Namespaces/NamespaceList.js
  src/shared/constants.ts
  src/state/navigation/filters/shouldNodeBeVisible.ts
  src/state/permissionSetsSelector.ts
  src/state/resourceList/mapBusolaResourceToNavNode.ts
  src/state/types.ts
  tests/integration/tests/cluster/test-cluster-validation.spec.js
Labels: size/M, lgtm, cla: yes

#2731 override crypto-js and d3-color
  package-lock.json
  package.json
  resources/backend/deployment.yaml
  resources/web/deployment.yaml
Labels: size/M, lgtm, cla: yes

#2729 Don't display toolbar if actions are empty
  resources/web/deployment.yaml
  src/shared/components/GenericList/GenericList.js
  src/shared/components/GenericList/test/GenericList.test.js
Labels: size/S, lgtm, cla: yes

#2728 Display Timestamp in Dashboard
  resources/web/deployment.yaml
  src/shared/components/ReadableCreationTimestamp/ReadableCreationTimestamp.tsx
Labels: size/S, lgtm, cla: yes

#2719 ClusterOverview Counting cards
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterOverview.scss
  src/components/Clusters/views/ClusterOverview/ClusterStats.js
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloadsHelpers.js
  src/shared/components/CardWithTooltip/CardWithTooltip.js
  src/shared/components/CountingCard/CountingCard.scss
  src/shared/components/CountingCard/CountingCard.tsx
  src/shared/components/ProgressIndicatorWithPercentage/ProgressIndicatorWithPercentage.js
  src/shared/components/ProgressIndicatorWithPercentage/ProgressIndicatorWithPercentage.scss
  tests/integration/tests/cluster/test-cluster-validation.spec.js
  tests/integration/tests/cluster/test-command-palette.spec.js
Labels: size/L, lgtm, cla: yes

#2741 fix setting color of progressindicator
  resources/web/deployment.yaml
  src/shared/components/ProgressIndicatorWithPercentage/ProgressIndicatorWithPercentage.js
Labels: size/S, lgtm, cla: yes

#2737 Change widgets in NamespaceOverview
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterStats.js
  src/resources/Namespaces/AllNamespacesDetails.js
  src/resources/Namespaces/NamespaceDetails.js
  src/resources/Namespaces/NamespaceDetails.scss
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
  src/resources/Namespaces/ResourcesUsage.js
  src/shared/components/ProgressIndicatorWithPercentage/ProgressIndicatorWithPercentage.js
  tests/integration/tests/namespace/test-namespace-overview.spec.js
Labels: size/L, lgtm, cla: yes

#2739 Function's Form overflow fix
  resources/web/deployment.yaml
  src/shared/ResourceForm/components/ResourceForm.scss
  src/shared/components/ModalWithForm/ModalWithForm.js
  tests/integration/tests/cluster/test-cluster-validation.spec.js
Labels: size/S, lgtm, priority/critical, cla: yes

#2730 Redesign Empty List View
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/BusolaExtensions/BusolaExtensionList.js
  src/components/Clusters/views/ClusterList.js
  src/components/Extensibility/ExtensibilityList.js
  src/components/Extensibility/helpers/index.js
  src/components/HelmReleases/HelmReleasesList.js
  src/resources/ConfigMaps/ConfigMapList.js
  src/resources/CronJobs/CronJobList.js
  src/resources/CustomResourceDefinitions/CustomResourceDefinitionList.js
  src/resources/DaemonSets/DaemonSetList.js
  src/resources/Deployments/DeploymentList.js
  src/resources/Events/EventList.js
  src/resources/Ingresses/IngressList.js
  src/resources/Jobs/JobList.js
  src/resources/Namespaces/NamespaceList.js
  src/resources/NetworkPolicies/NetworkPolicyList.js
  src/resources/PersistentVolumeClaims/PersistentVolumeClaimList.js
  src/resources/PersistentVolumes/PersistentVolumeList.js
  src/resources/Pods/PodList.js
  src/resources/ReplicaSets/ReplicaSetList.js
  src/resources/RoleBindings/GenericRoleBindingList.js
  src/resources/Roles/GenericRoleList.js
  src/resources/Secrets/SecretList.js
  src/resources/ServiceAccounts/ServiceAccountList.js
  src/resources/StatefulSets/StatefulSetList.js
  src/resources/StorageClasses/StorageClassList.js
  src/shared/components/EmptyListComponent/EmptyListComponent.scss
  src/shared/components/EmptyListComponent/EmptyListComponent.tsx
  src/shared/components/GenericList/GenericList.js
  src/shared/components/ResourcesList/ResourcesList.js
  tests/integration/support/login-commands.js
  tests/integration/tests/cluster/test-cluster-validation.spec.js
  tests/integration/tests/cluster/test-invalid-kubeconfig.spec.js
  tests/integration/tests/cluster/test-multiple-context-kubeconfig.spec.js
  tests/lighthouse/lighthouse.spec.js
Labels: size/L, lgtm, cla: yes

#2743 Fix GenerateTokenModal Bug
  resources/web/deployment.yaml
  src/resources/ServiceAccounts/ServiceAccountDetails.js
  src/resources/ServiceAccounts/TokenRequestModal/TokenRequestModal.tsx
  src/resources/ServiceAccounts/TokenRequestModal/useGenerateTokenRequest.ts
Labels: size/M, lgtm, cla: yes

#2740 Fix search focus
  resources/web/deployment.yaml
  src/shared/components/GenericList/SearchInput.js
  src/shared/components/ResourceDetails/ResourceDetails.js
Labels: size/L, lgtm, cla: yes

#2734 Redesign of ResourceDetails and PodTemplateTable
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterDetails.js
  src/components/Clusters/views/ClusterOverview/ClusterOverview.scss
  src/components/Extensibility/ExtensibilityDetails.js
  src/components/Extensibility/components/Columns.js
  src/components/Extensibility/components/Tabs.js
  src/components/Extensibility/components/Widget.js
  src/resources/Namespaces/NamespaceDetails.js
  src/shared/components/PodTemplate/PodTemplate.js
  src/shared/components/PodTemplate/PodTemplate.scss
  src/shared/components/PodTemplate/PodTemplateRow.js
  src/shared/components/PodTemplate/components.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceDetails/ResourceDetails.scss
  src/shared/components/ResourceDetails/ResourceDetailsCard.js
  tests/integration/tests/cluster/test-dashboard-version.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/namespace/test-replica-sets.spec.js
  tests/lighthouse/lighthouse.spec.js
Labels: size/XL, lgtm, cla: yes

#2742 Make node view is similar to cluster view
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterNodes.js
  src/components/Clusters/views/ClusterOverview/ClusterStats.js
  src/components/Nodes/MachineInfo/MachineInfo.js
  src/components/Nodes/MachineInfo/MachineInfo.scss
  src/components/Nodes/NodeDetails/NodeDetails.js
  src/components/Nodes/NodeResources/NodeResources.js
  src/components/Nodes/nodeQueries.js
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
  src/shared/components/ProgressIndicatorWithPercentage/ProgressIndicatorWithPercentage.js
Labels: size/L, lgtm, cla: yes

#2745 Show full-screen icon only on last column
  resources/web/deployment.yaml
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
Labels: size/S, lgtm, cla: yes

#2754 add gardenlinux
  .github/workflows/cypress-tests.yml
Labels: size/XS, lgtm, cla: yes

#2749 create test-strategy document
  docs/contributor/testing-strategy.md
Labels: size/S, lgtm, cla: yes

#2750 adjust monitoring and health widgets
  public/i18n/en.yaml
  resources/web/deployment.yaml
  src/components/Clusters/views/ClusterOverview/ClusterOverview.scss
  src/components/Clusters/views/ClusterOverview/ClusterStats.js
  src/components/Nodes/MachineInfo/MachineInfo.js
  src/components/Nodes/MachineInfo/MachineInfo.scss
  src/components/Nodes/NodeDetails/NodeDetails.js
  src/components/Nodes/NodeDetails/NodeDetails.scss
  src/components/Nodes/NodeResources/NodeResources.js
  src/resources/Namespaces/AllNamespacesDetails.js
  src/resources/Namespaces/NamespaceDetails.js
  src/resources/Namespaces/NamespaceDetails.scss
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
  src/resources/Namespaces/ResourcesUsage.js
  src/shared/components/CountingCard/CountingCard.scss
  src/shared/components/CountingCard/CountingCard.tsx
  src/shared/components/ProgressIndicatorWithPercentage/ProgressIndicatorWithPercentage.scss
  src/shared/components/UI5RadialChart/UI5RadialChart.js
  src/shared/components/UI5RadialChart/UI5RadialChart.scss
  src/styles/index.scss
Labels: size/L, lgtm, cla: yes
