Repository kyma-project/busola, pull requests merged in 2025-03, with the labels that each got.

#3738 fix: Revert changes in genericlist
  src/shared/components/GenericList/GenericList.js
Labels: size/S, lgtm

#3727 feat: Enable AI assistant only for SAP users
  src/components/Extensibility/helpers/jsonataWrapper.ts
  src/header/Header.tsx
  src/hooks/useCheckSAPUser.ts
Labels: size/M, lgtm, cla: yes

#3730 fix: Prevent submitting acc results to AMP on PR
  .github/workflows/accessibility-tests.yml
  tests/integration/plugins/index.js
  tests/integration/tests/accessibility/test-acc-cluster.spec.js
  tests/integration/tests/accessibility/test-acc-cron-jobs.spec.js
  tests/integration/tests/accessibility/test-acc-custom-resoureces.spec.js
  tests/integration/tests/accessibility/test-acc-extensions.spec.js
  tests/integration/tests/accessibility/test-acc-modules.spec.js
  tests/integration/tests/accessibility/test-acc-namespace-overview.spec.js
  tests/integration/tests/accessibility/test-acc-performance.spec.js
  tests/integration/tests/accessibility/test-acc-pizzas.spec.js
Labels: size/M, lgtm, cla: yes

#3716 feat: Force delete
  public/i18n/en.yaml
  src/components/KymaModules/KymaModulesList.js
  src/components/KymaModules/deleteModulesHelpers.tsx
  src/components/KymaModules/support.ts
  src/shared/hooks/useDeleteResource.js
Labels: size/L, lgtm, cla: yes

#3711 feat: Update cpu and memory charts on namespace
  src/components/Clusters/views/ClusterOverview/ClusterStats.js
  src/components/Nodes/NodeResources/NodeResources.js
  src/components/Nodes/nodeQueries.js
  src/resources/Namespaces/AllNamespacesDetails.js
  src/resources/Namespaces/NamespaceDetails.js
  src/resources/Namespaces/ResourcesUsage.js
  src/resources/Pods/podQueries.ts
  src/resources/Pods/types.ts
  src/resources/ResourceQuotas/ResourceQuotaDetails.tsx
  src/resources/ResourceQuotas/ResourceQuotaLimits.tsx
  src/resources/ResourceQuotas/ResourceQuotaList.tsx
  src/resources/ResourceQuotas/ResourceQuotasList.tsx
  src/resources/ResourceQuotas/support.ts
  src/shared/helpers/resources.js
  tests/integration/tests/namespace/test-namespace-overview.spec.js
  tests/integration/tests/namespace/test-resource-quotas.spec.js
Labels: size/XL, cla: yes

#3712 feat: Command Palette in Header
  public/i18n/en.yaml
  src/command-pallette/CommandPaletteProvider.tsx
  src/command-pallette/CommandPalletteUI/CommandPaletteSearchBar.scss
  src/command-pallette/CommandPalletteUI/CommandPaletteSearchBar.tsx
  src/command-pallette/CommandPalletteUI/CommandPaletteUI.scss
  src/command-pallette/CommandPalletteUI/CommandPaletteUI.tsx
  src/command-pallette/CommandPalletteUI/ResultsList/ResultsList.scss
  src/command-pallette/CommandPalletteUI/components/components.tsx
  src/command-pallette/CommandPalletteUI/types.ts
  src/header/Header.scss
  src/header/Header.tsx
  src/header/HeaderMenu.tsx
  src/header/SnowFeature.scss
  src/header/SnowFeature.tsx
  src/styles/index.scss
  tests/integration/tests/cluster/test-command-palette.spec.js
  tests/integration/tests/cluster/test-edit-cluster.spec.js
  tests/integration/tests/extensibility/ext-test-pizzas.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/namespace/test-custom-resources.spec.js
Labels: size/XL, lgtm, cla: yes

#3733 fix: Add accessible names to Object Statuses
  src/resources/Events/EventDetails.js
  src/resources/Events/EventList.js
  src/resources/Namespaces/YamlUpload/ResourceValidationResult.js
Labels: size/S, cla: yes

#3734 fix: Adjust chart styles in high contrast theme
  public/themes/hcb.css
  public/themes/hcw.css
  src/shared/components/UI5RadialChart/UI5RadialChart.js
Labels: size/S, lgtm, cla: yes

#3691 feat: POST /conversations to companion backend
  backend/companion/TokenManager.js
  backend/companion/companionRouter.js
  backend/companion/getKcpToken.js
  backend/index.js
  public/i18n/en.yaml
  src/command-pallette/CommandPalletteUI/useSearchResults.tsx
  src/components/App/ExtensibilityRoutes.js
  src/components/BusolaExtensions/BusolaExtensionCreate.js
  src/components/BusolaExtensions/extensionsNode.ts
  src/components/Clusters/views/ClusterList.js
  src/components/Clusters/views/ClusterOverview/ClusterOverview.js
  src/components/CustomResources/customResourcesNode.ts
  src/components/HelmReleases/helmReleasesNode.ts
  src/components/KymaCompanion/api/getPromptSuggestions.ts
  src/components/KymaCompanion/components/Chat/Chat.tsx
  src/components/KymaCompanion/components/Chat/messages/Bubbles.scss
  src/components/KymaCompanion/components/Chat/messages/Bubbles.tsx
  src/components/KymaCompanion/components/KymaCompanion.tsx
  src/components/KymaCompanion/hooks/usePromptSuggestions.ts
  src/components/KymaModules/KymaModulesList.js
  src/components/KymaModules/kymaModulesNode.ts
  src/resources/LimitRanges/LimitRangesList.js
  src/resources/Namespaces/NamespaceCreate.js
  src/resources/Namespaces/namespaceOverviewNode.ts
  src/resources/ResourceQuotas/ResourceQuotasList.tsx
  src/resources/Roles/helpers.js
  src/resources/createResourceRoutes.js
  src/resources/other/BusolaExtensions.routes.js
  src/resources/other/CustomResourcesByGroup.routes.js
  src/resources/other/helmReleases.routes.js
  src/resources/other/kymaModules.routes.js
  src/shared/ResourceForm/useCreateResource.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/ResourceGraph/DetailsCard/DetailsCard.tsx
  src/shared/components/ResourcesList/ResourcesList.js
  src/sidebar/NavItem.tsx
  src/sidebar/SidebarNavigation.tsx
  src/state/columnLayoutAtom.ts
  src/state/navigation/externalNodesSelector.ts
  src/state/resourceList/mapBusolaResourceToNavNode.ts
  src/state/resourceList/mapExtResourceToNavNode.ts
  src/state/types.ts
Labels: size/XL, lgtm, cla: yes

#3745 fix: Column layout bug when create is opened
  src/shared/components/GenericList/GenericList.js
Labels: size/XS, lgtm

#3740 fix: Count of the associated resources and rename `Force delete` check
  public/i18n/en.yaml
  src/components/KymaModules/KymaModulesList.js
  src/components/KymaModules/deleteModulesHelpers.tsx
Labels: size/S, lgtm

#3746 chore: Use latest version of nginx
  Dockerfile.web
Labels: size/XS, lgtm

#3744 fix: Remove command palette from clusters list
  src/command-pallette/CommandPaletteProvider.tsx
  src/header/Header.tsx
Labels: size/S, lgtm

#3739 feat: Open id connect resource view
  docs/extensibility/120-resource-extensions.md
  kyma/environments/dev/extensions.json
  kyma/environments/prod/extensions.json
  kyma/environments/stage/extensions.json
  kyma/extensions/configuration-cluster/openid-connect.yaml
  src/components/Extensibility/ExtensibilityDetails.js
  src/shared/components/ResourceDetails/ResourceDetails.js
Labels: size/L, lgtm

#3747 feat: Worker-pools for nodes
  public/i18n/en.yaml
  src/components/Clusters/views/ClusterOverview/ClusterNodes.js
  src/components/Nodes/MachineInfo/MachineInfo.js
  src/components/Nodes/MachineInfo/MachineInfo.scss
  src/components/Nodes/NodeDetails/NodeDetails.js
  src/components/Nodes/NodeDetailsCard.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/components/ResourceDetails/ResourceDetails.scss
Labels: size/L, lgtm

#3756 fix: Fix IS_PR variable for Accessibility tests
  tests/integration/tests/accessibility/test-acc-cluster.spec.js
  tests/integration/tests/accessibility/test-acc-cron-jobs.spec.js
  tests/integration/tests/accessibility/test-acc-custom-resoureces.spec.js
  tests/integration/tests/accessibility/test-acc-extensions.spec.js
  tests/integration/tests/accessibility/test-acc-modules.spec.js
  tests/integration/tests/accessibility/test-acc-namespace-overview.spec.js
  tests/integration/tests/accessibility/test-acc-performance.spec.js
  tests/integration/tests/accessibility/test-acc-pizzas.spec.js
Labels: size/M, lgtm

#3751 fix: Allow force delete on modules details
  src/components/KymaModules/KymaModulesList.js
  src/components/KymaModules/deleteModulesHelpers.tsx
  src/components/KymaModules/support.ts
  src/resources/other/kymaModules.routes.js
Labels: size/L

#3726 fix: Reset layout after click on Navigation item
  src/components/App/ExtensibilityRoutes.js
  src/components/CustomResources/CustomResources.js
  src/resources/ClusterEvents/ClusterEventDetails.tsx
  src/resources/ClusterEvents/ClusterEventList.tsx
  src/resources/ClusterEvents/index.js
  src/resources/CustomResourceDefinitions/CRCreate.js
  src/resources/CustomResourceDefinitions/useCustomResourceUrl.js
  src/resources/Events/EventDetails.js
  src/resources/Events/EventList.js
  src/resources/createResourceRoutes.js
  src/resources/other.js
  src/resources/other/CustomResourceDetails.routes.js
  src/resources/other/CustomResourceListOfType.routes.js
  src/resources/other/CustomResources.routes.js
  src/shared/ResourceForm/useCreateResource.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/EventsList.js
  src/shared/components/GenericList/GenericList.js
  src/sidebar/NavItem.tsx
Labels: size/L, cla: yes

#3753 fix: Navigation and column layout problems
  src/components/App/ExtensibilityRoutes.js
  src/components/BusolaExtensions/BusolaExtensionCreate.js
  src/components/CustomResources/CustomResources.js
  src/components/KymaModules/KymaModulesEdit.js
  src/components/KymaModules/components/ModulesList.tsx
  src/resources/CustomResourceDefinitions/CRCreate.js
  src/resources/CustomResourceDefinitions/templates.js
  src/resources/createResourceRoutes.js
  src/resources/other/BusolaExtensions.routes.js
  src/resources/other/CustomResources.routes.js
  src/resources/other/helmReleases.routes.js
  src/resources/other/kymaModules.routes.js
  src/shared/ResourceForm/components/ResourceForm.js
  src/shared/ResourceForm/useCreateResource.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/Link/Link.tsx
  src/shared/components/ResourceCreate/ResourceCreate.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/shared/hooks/useDeleteResource.js
  src/shared/hooks/usePrepareLayout.js
  src/sidebar/NavItem.tsx
  src/state/useAfterInitHook.ts
Labels: size/L
