Repository kyma-project/busola, pull requests merged in 2025-01, with the labels that each got.

#3566 feat: Remove deprecated kubeProxyVersion property
  src/components/Clusters/views/ClusterOverview/ClusterNodes.js
  src/components/Nodes/MachineInfo/MachineInfo.js
Labels: size/XS, lgtm, cla: yes

#3565 fix: theme not working properly on initial render and after refresh
  src/components/App/App.tsx
  src/components/App/initTheme.ts
Labels: size/M, lgtm, cla: yes

#3567 fix: Fix for editor popover
  src/shared/components/MonacoEditorESM/Editor.scss
Labels: size/XS, lgtm, cla: yes

#3568 feat(Modules): Add beta check for ModuleReleaseMeta
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesCreate.js
  src/components/KymaModules/KymaModulesList.js
Labels: size/M, lgtm, cla: yes

#3571 Enable custom extensions: example
  examples/custom-extension/README.md
  examples/custom-extension/busola-config.yaml
Labels: size/S, lgtm, cla: yes

#3569 fix: Checking validity of the message for badge description
  src/components/Extensibility/components/Badge.js
Labels: size/S, lgtm, cla: yes

#3580 chore: set header limit to 24kB
  backend/package.json
Labels: size/XS, lgtm, cla: yes

#3581 chore: fix lighthouse tests by playwright upgrade
  tests/lighthouse/package-lock.json
  tests/lighthouse/package.json
Labels: size/M, lgtm, cla: yes

#3547 feat: Add documentation about busola in k8s and adjust k8s configs
  .github/scripts/setup_local_busola.sh
  .github/workflows/pull-integration-cluster-k3d.yml
  .github/workflows/pull-integration-namespace-k3d.yml
  .github/workflows/pull-kyma-integration-tests.yml
  .github/workflows/pull-lighthouse.yml
  Makefile
  README.md
  backend/.gitignore
  backend/Makefile
  examples/custom-extension/script.js
  resource-validation/rule-sets/datree/rules.yaml
  resource-validation/rule-sets/default/policies.yaml
  resource-validation/rule-sets/kubernetes-pod-security-standards/policies.yaml
  resource-validation/rule-sets/kubernetes-pod-security-standards/rules.yaml
  resource-validation/rulesetSchema.json
  resources/apply-resources-istio.sh
  resources/apply-resources.sh
  resources/base/backend/deployment.yaml
  resources/base/busola/deployment.yaml
  resources/base/busola/hpa.yaml
  resources/base/busola/kustomization.yaml
  resources/base/busola/service.yaml
  resources/base/extensions-patch/builtin-resource-extensions.configmap.yaml
  resources/base/extensions-patch/kustomization.yaml
  resources/base/extensions-patch/web-deployment.patch.yaml
  resources/base/kustomization.yaml
  resources/base/web/configmap.yaml
  resources/base/web/hpa.yaml
  resources/base/web/kustomization.yaml
  resources/base/web/service.yaml
  resources/ingress/ingress.tpl.yaml
  resources/ingress/ingress.yaml
  resources/ingress/ingressClass.yaml
  resources/istio/apirule.yaml
  resources/istio/destinationrule-busola-backend.yaml
  resources/istio/kustomization.yaml
  resources/istio/virtualservice-busola.tpl.yaml
  src/components/Gardener/useGardenerLoginFunction.tsx
  src/shared/hooks/BackendAPI/useFetch.ts
  src/shared/utils/env.ts
  src/shared/utils/getClusterConfig.js
  src/state/configuration/configurationAtom.ts
  src/state/navigation/extensionsAtom.ts
  src/state/utils/getBackendInfo.ts
  tests/lighthouse/lighthouse.spec.js
  vite.config.mts
Labels: size/XL, lgtm, cla: yes

#3558 chore: add unsafe eval for accessibility tests
  index.html
Labels: size/XS, lgtm, cla: yes

#3573 feat: Replace kyma extensions with Modules
  kyma/environments/dev/extensions.json
  kyma/environments/prod/extensions.json
  kyma/environments/stage/extensions.json
  kyma/extensions/kyma/kyma.yaml
  src/components/KymaModules/KymaModulesList.js
  src/resources/other/kymaModules.routes.js
  src/state/navigation/addAdditionalNodes.ts
Labels: size/L, lgtm, cla: yes

#3588 fix: ui5 combobox display strange value
  src/shared/components/K8sResourceSelect.js
Labels: size/XS, lgtm, cla: yes

#3583 fix: Command Palette shouldn't navigate when Form is edited
  src/command-pallette/CommandPalletteUI/ResultsList/ResultsList.tsx
  src/components/Extensibility/components/Badge.js
  src/shared/components/UnsavedMessageBox/UnsavedMessageBox.tsx
  tests/integration/package-lock.json
  tests/integration/package.json
  tests/integration/tests/cluster/test-command-palette.spec.js
Labels: size/L, lgtm, cla: yes

#3499 feat: Install busola on k3d and run tests against it
  .github/scripts/deploy_busola.sh
  .github/scripts/prepare_kubeconfig.sh
  .github/workflows/pull-integration-cluster-k3d.yml
  .github/workflows/pull-kyma-integration-tests.yml
  .github/workflows/pull-smoke-test-stage.yml
  backend/index.js
  resources/base/busola/deployment.yaml
Labels: size/M, lgtm, cla: yes

#3576 feat: Information about associated resources in delete modal for modules
  public/i18n/en.yaml
  src/components/KymaModules/KymaModulesList.js
  src/shared/hooks/BackendAPI/useGet.js
  src/shared/hooks/useDeleteResource.js
Labels: size/L, lgtm, cla: yes

#3595 fix: adjust styles in Modules view
  src/components/KymaModules/KymaModulesList.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
Labels: size/XS, lgtm, cla: yes

#3587 fix: fill existing resourceVersion if not provided for updates
  src/resources/Namespaces/YamlUpload/YamlResourceList.scss
  src/resources/Namespaces/YamlUpload/YamlResourcesList.js
  src/resources/Namespaces/YamlUpload/useUploadResources.js
Labels: size/S, lgtm, cla: yes

#3594 fix: open dropdown popover correctly
  src/components/Extensibility/components-form/KeyValuePairRenderer.js
  src/resources/Namespaces/MemoryQuotas.js
  src/resources/Namespaces/NamespaceCreate.js
  src/resources/Namespaces/Presets.js
  src/shared/ResourceForm/components/Presets.js
  src/shared/ResourceForm/inputs/Dropdown.js
  src/shared/components/Dropdown/Dropdown.cy.js
  src/shared/components/Dropdown/Dropdown.js
Labels: size/L, lgtm, cla: yes

#3596 fix: fix generating k8s yaml in release process
  .github/scripts/upload_assets.sh
Labels: size/XS, lgtm, cla: yes

#3599 fix: remove unused CSS and small adjustments
  src/components/App/ContentWrapper/ContentWrapper.scss
  src/shared/components/GenericList/components.js
  src/shared/components/Spinner/Spinner.tsx
  tests/integration/tests/cluster/test-navigation-features.spec.js
Labels: size/S, lgtm, cla: yes

#3589 fix: Inconsistent handling browser history routes
  src/components/App/ClusterRoutes.js
  src/components/App/NamespaceRoutes.tsx
  src/shared/components/ListActions/ListActions.js
  src/sidebar/NavItem.tsx
Labels: size/L, lgtm, cla: yes

#3590 fix: resoruces should be displayed correctly.
  src/components/Clusters/views/ClusterOverview/ClusterStats.js
  src/components/Nodes/NodeResources/NodeResources.js
  src/components/Nodes/nodeQueries.js
  src/components/Nodes/nodeQueries.test.js
  src/resources/Namespaces/ResourcesUsage.js
  src/shared/helpers/resources.js
  src/shared/helpers/siPrefixes.js
Labels: size/L, lgtm, cla: yes

#3597 fix: container selector
  src/components/Clusters/views/ClusterOverview/ClusterDetails.js
  src/components/Clusters/views/ClusterOverview/ClusterStats.js
  src/components/Clusters/views/ClusterOverview/ClusterStats.scss
  src/components/Extensibility/components-form/FormGroup.scss
  src/components/Extensibility/components/FeaturedCard/FeaturedCard.js
  src/components/Extensibility/components/FeaturedCard/FeaturedCard.scss
  src/components/Extensibility/components/RadialChart.js
  src/components/Extensibility/components/StatisticalCard.js
  src/components/KymaModules/KymaModulesAddModule.js
  src/resources/Namespaces/NamespaceWorkloads/NamespaceWorkloads.js
  src/resources/Namespaces/ResourcesUsage.js
  src/resources/other/kymaModules.routes.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
  src/shared/components/GenericList/Pagination/Pagination.scss
  src/shared/components/GenericList/Pagination/test/Pagination.cy.js
  src/shared/components/PodTemplate/PodTemplate.js
  src/shared/components/PodTemplate/PodTemplate.scss
  src/shared/components/ResourceDetails/ResourceDetails.scss
  src/shared/components/ResourceStatusCard/ResourceStatusCard.scss
  src/shared/components/UI5Panel/UI5Panel.scss
  tests/integration/tests/namespace/test-persistent-volume-claims.spec.js
Labels: size/L, lgtm, cla: yes

#3613 docs: improve docs regarding deploying busola in the K8s cluster
  README.md
Labels: size/XS, lgtm, cla: yes

#3609 test: adjust unit test workflow
  .github/workflows/pull-unit-tests.yml
Labels: size/XS, cla: yes

#3611 fix: fix accessibility tests
  .github/workflows/accessibility-tests.yml
Labels: size/S, lgtm, cla: yes

#3614 fix: accesibility tests choose correct k3d cluster
  .github/workflows/accessibility-tests.yml
Labels: size/XS, lgtm, cla: yes

#3579 feat: expose Monaco and Dynamic Page as Web Components
  docs/custom-extensions/assets/DynamicPage.png
  docs/custom-extensions/assets/MonacoEditor.png
  docs/custom-extensions/busola-web-components.md
  examples/busola-web-components/README.md
  examples/busola-web-components/busola-config.yaml
  examples/busola-web-components/general.yaml
  examples/busola-web-components/kustomization.yaml
  examples/busola-web-components/script.js
  examples/busola-web-components/ui.html
  src/components/App/App.tsx
  src/components/Extensibility/ExtensibilityList.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.js
  src/shared/components/MonacoEditorESM/autocompletion/useAutocompleteWorker.js
  src/web-components/DynamicPageWebComponent.jsx
  src/web-components/MonacoWebComponent.jsx
  src/web-components/createWebComponent.jsx
  src/web-components/eventListenerTracker.js
  src/web-components/htmlTojsx.js
  src/web-components/index.ts
Labels: size/XL, lgtm, cla: yes

#3617 fix: fix displaying namespace resource
  src/components/Nodes/nodeQueries.js
  src/resources/Namespaces/ResourcesUsage.js
  src/shared/helpers/resources.js
Labels: size/XS, lgtm, cla: yes

#3619 fix: UI5 adjust badges
  src/components/KymaModules/KymaModulesList.js
  src/shared/components/Labels/Labels.js
Labels: size/XS, lgtm, cla: yes

#3620 docs: Fix title in preset functions and fix links in list and details widgets
  docs/extensibility/101-preset-functions.md
  docs/extensibility/50-list-and-details-widgets.md
Labels: size/L, lgtm, cla: yes

#3608 feat: Condition list highlights
  docs/extensibility/50-list-and-details-widgets.md
  kyma/extensions/discovery-and-network/horizontal-pod-autoscalers.yaml
  src/components/Extensibility/components/Badge.js
  src/components/Extensibility/components/ConditionList.js
  src/components/Extensibility/helpers/index.js
  src/resources/Deployments/DeploymentDetails.js
  src/shared/components/ExpandableListItem/ExpandableListItem.tsx
Labels: size/L, lgtm, cla: yes

#3625 Customize empty list
  docs/extensibility/50-list-and-details-widgets.md
  src/components/Extensibility/components/EventList.js
  src/components/Extensibility/components/ResourceList.js
  src/components/KymaModules/KymaModulesList.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/ResourcesList/ResourcesList.js
Labels: size/M, lgtm, cla: yes

#3627 fix: adjust badges after overriding functionality
  src/components/Extensibility/components/tests/Badge.cy.js
  src/components/Extensibility/helpers/index.js
  src/components/KymaModules/KymaModulesList.js
  src/components/KymaModules/components/ModuleStatus.tsx
  src/resources/Deployments/DeploymentDetails.js
  src/shared/components/ExpandableListItem/ExpandableListItem.tsx
Labels: size/M, lgtm, cla: yes

#3607 fix: Resolve unknown badge type
  src/components/Extensibility/ExtensibilityDetails.js
  src/components/Extensibility/contexts/DataSources.tsx
  src/state/resourceConditionsAtom.ts
Labels: size/M, lgtm, cla: yes

#3598 fix: add modules shouldn't reset after some time
  src/components/KymaModules/KymaModulesAddModule.js
  src/resources/other/kymaModules.routes.js
Labels: size/M, lgtm, cla: yes

#3629 fix: Custom resources details wrong opening
  src/components/CustomResources/GroupingListPage.scss
  src/resources/other/CustomResourcesByGroup.routes.js
Labels: size/S, lgtm, cla: yes

#3630 docs: Fix links in the extensibility docs
  docs/extensibility/20-list-columns.md
  docs/extensibility/30-details-summary.md
  docs/extensibility/40-form-fields.md
  docs/extensibility/60-form-widgets.md
  docs/extensibility/70-widget-injection.md
  docs/extensibility/README.md
Labels: size/L, lgtm, cla: yes

#3637 refactor: Kyma Modules move queries to separate file
  src/components/Clusters/views/ClusterOverview/ClusterDetails.js
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesCreate.js
  src/components/KymaModules/KymaModulesList.js
  src/components/KymaModules/KymaModulesQuery.js
  src/components/KymaModules/kymaModulesQueries.js
  src/resources/other/kymaModules.routes.js
Labels: size/L, lgtm, cla: yes

#3633 fix: undefined in data sources
  src/components/Extensibility/contexts/DataSources.tsx
  tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
  tests/integration/tests/cluster/test-custom-resources.spec.js
  tests/integration/tests/namespace/test-navigation.spec.js
Labels: size/S, lgtm, cla: yes

#3631 feat: Add actions for checking title and description
  .github/workflows/pr-description-check.yml
  .github/workflows/pr-dod-check.yml
  .github/workflows/pr-linked-check.yml
  .github/workflows/pr-title-check.yml
  docs/contributor/testing-strategy.md
Labels: size/L, lgtm, cla: yes

#3643 chore: Add checkmarx one to sec-config
  sec-scanners-config.yaml
Labels: size/S, lgtm, cla: yes

#3635 feat: Add statics config with modules banner
  kyma/environments/dev/statics.json
  kyma/environments/prod/statics.json
  kyma/environments/stage/statics.json
  kyma/extensions/statics/modules-banner.yaml
Labels: size/M, lgtm, cla: yes

#3644 feat: Link to the release of the currently deployed version in kyma-dashboard version
  src/header/Header.tsx
  src/header/SidebarMenu/useGetBusolaVersion.ts
Labels: size/S, lgtm, cla: yes

#3645 docs: Fix docker run commands
  README.md
Labels: size/XS, lgtm, cla: yes

#3646 chore: Exclude .github dir for cxone
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#3647 chore: Exclude cypress dir for cxone
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#3639 refactor: Modules view
  src/components/Extensibility/helpers/jsonataWrapper.ts
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesEdit.js
  src/components/KymaModules/KymaModulesList.js
  src/components/KymaModules/ManagedWarnings.tsx
  src/components/KymaModules/ModulesCard.js
  src/components/KymaModules/components/ModuleStatus.tsx
  src/components/KymaModules/index.tsx
  src/components/KymaModules/support.ts
Labels: size/L, lgtm, cla: yes

#3648 fix: Buttons overlapping in Header
  src/header/Header.scss
  src/header/Logo/Logo.tsx
Labels: size/S, lgtm, cla: yes
