Repository kyma-project/busola, pull requests merged in 2025-02, with the labels that each got.

#3616 feat: Reuse POC's api and utils
  src/components/KymaCompanion/api/getChatResponse.ts
  src/components/KymaCompanion/api/getFollowUpQuestions.ts
  src/components/KymaCompanion/api/getPromptSuggestions.ts
  src/components/KymaCompanion/components/Chat/Chat.tsx
  src/components/KymaCompanion/components/Chat/messages/CodePanel.tsx
  src/components/KymaCompanion/components/Chat/messages/Message.tsx
  src/components/KymaCompanion/components/CompanionOpener.tsx
  src/components/KymaCompanion/utils/formatMarkdown.ts
  src/components/KymaCompanion/utils/parseNestedBrackets.ts
Labels: size/L, lgtm, cla: yes, kyma companion

#3655 fix: Additional tab stop after SideNav with screen reader
  src/shared/components/GenericList/SearchInput.js
  src/shared/components/ResourceDetails/ResourceDetails.js
  src/shared/contexts/YamlEditorContext/YamlEditorContext.js
Labels: size/L, lgtm, cla: yes

#3652 fix: Use correct paths for cluster urls
  src/components/CustomResources/CustomResources.js
  src/resources/CustomResourceDefinitions/CRCreate.js
  src/resources/CustomResourceDefinitions/useCustomResourceUrl.js
Labels: size/S, lgtm, cla: yes

#3656 docs: Adjust condition list docs
  docs/extensibility/50-list-and-details-widgets.md
  docs/extensibility/assets/display-widgets/ConditionListHighlights.png
Labels: size/M, lgtm, cla: yes

#3649 refactor: Tide the directories of modules
  src/components/Extensibility/helpers/jsonataWrapper.ts
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesEdit.js
  src/components/KymaModules/components/ChannelWarning.tsx
  src/components/KymaModules/components/ManagedWarnings.tsx
  src/components/KymaModules/components/ModulesCard.js
  src/components/KymaModules/components/UnmanagedModuleInfo.tsx
Labels: size/S, lgtm, cla: yes

#3661 chore: Add new PR prefix
  .github/pull-request-template.md
  .github/workflows/pr-title-check.yml
Labels: size/XS, lgtm, cla: yes

#3660 revert: "fix: Use correct paths for cluster urls"
  src/components/CustomResources/CustomResources.js
  src/resources/CustomResourceDefinitions/CRCreate.js
  src/resources/CustomResourceDefinitions/useCustomResourceUrl.js
Labels: size/S, lgtm, cla: yes

#3657 fix: Bump UI5 packages and add accessibleName for Tables
  package-lock.json
  package.json
  src/components/App/ContentWrapper/ContentWrapper.scss
  src/resources/Namespaces/YamlUpload/ResourceValidationResult.js
  src/shared/components/Dropdown/Dropdown.cy.js
  src/shared/components/GenericList/GenericList.js
  src/shared/components/ResourcesList/ResourcesList.js
  src/sidebar/Sidebar.scss
  src/styles/index.scss
  tests/integration/support/commands.js
  tests/integration/support/helpers.js
  tests/integration/tests/accessibility/test-acc-cron-jobs.spec.js
  tests/integration/tests/cluster/test-cluster-role-bindings.spec.js
  tests/integration/tests/cluster/test-command-palette.spec.js
  tests/integration/tests/extensibility/ext-test-extensibility.spec.js
  tests/integration/tests/extensibility/ext-test-variables.spec.js
  tests/integration/tests/kyma-namespace/a-run-before.spec.js
  tests/integration/tests/kyma-namespace/test-issuers.spec.js
  tests/integration/tests/namespace/a-run-before.spec.js
  tests/integration/tests/namespace/test-cron-jobs.spec.js
  tests/integration/tests/namespace/test-protected-resources.spec.js
  tests/integration/tests/namespace/test-resource-validation.spec.js
  tests/integration/tests/namespace/test-service-accounts.spec.js
  tests/integration/tests/namespace/test-settings.spec.js
Labels: size/XL, lgtm, cla: yes

#3664 chore: Rename fields in security config
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#3642 feat: Add job: Rebase Pull Requests
  .github/actions/merge/action.yml
  .github/workflows/accessibility-tests.yml
  .github/workflows/create-release.yml
  .github/workflows/lint-check-pr.yml
  .github/workflows/lint-markdown-links-daily.yml
  .github/workflows/lint-markdown-links-pr.yml
  .github/workflows/pull-integration-cluster-k3d.yml
  .github/workflows/pull-integration-namespace-k3d.yml
  .github/workflows/pull-kyma-integration-tests.yml
  .github/workflows/pull-lighthouse.yml
  .github/workflows/pull-smoke-test-prod.yml
  .github/workflows/pull-smoke-test-stage.yml
  .github/workflows/pull-unit-tests.yml
Labels: size/L, lgtm, cla: yes

#3666 chore: Remove hide-shadow
  src/sidebar/Sidebar.scss
  src/sidebar/SidebarNavigation.tsx
Labels: size/XS, lgtm, cla: yes

#3669 chore: Remove checking linked issues
  .github/workflows/pr-linked-check.yml
Labels: size/S, lgtm, cla: yes

#3665 fix: Sorting function in GenericList
  src/shared/components/GenericList/GenericList.js
Labels: size/XS, lgtm, cla: yes

#3650 feat: Adjust companion to new designs
  package-lock.json
  package.json
  public/i18n/en.yaml
  src/components/App/App.tsx
  src/components/KymaCompanion/components/Chat/Chat.scss
  src/components/KymaCompanion/components/Chat/Chat.tsx
  src/components/KymaCompanion/components/Chat/messages/Bubbles.scss
  src/components/KymaCompanion/components/Chat/messages/Bubbles.tsx
  src/components/KymaCompanion/components/Chat/messages/CodePanel.scss
  src/components/KymaCompanion/components/Chat/messages/CodePanel.tsx
  src/components/KymaCompanion/components/Chat/messages/ErrorMessage.tsx
  src/components/KymaCompanion/components/Chat/messages/Message.scss
  src/components/KymaCompanion/components/KymaCompanion.scss
  src/components/KymaCompanion/components/KymaCompanion.tsx
  src/state/preferences/themeAtom.ts
Labels: size/XL, lgtm, cla: yes

#3675 fix: UI5v2 styling issues in cluster wizard
  src/components/Clusters/components/AddClusterDialog.js
  src/components/Clusters/components/AddClusterWizard.js
  src/components/Clusters/components/AddClusterWizard.scss
  src/components/Clusters/components/ClusterPreview.scss
  src/components/Clusters/components/KubeconfigUpload/KubeconfigUpload.scss
  src/components/Extensibility/ExtensibilityWizard.js
  src/shared/ResourceForm/components/ResourceForm.scss
  src/shared/components/WizardButtons/WizardButtons.js
Labels: size/L, lgtm, cla: yes

#3663 docs: Update screenshots in List and Details Widgets and Form Widgets
  docs/extensibility/50-list-and-details-widgets.md
  docs/extensibility/60-form-widgets.md
  docs/extensibility/assets/display-widgets/Alert.png
  docs/extensibility/assets/display-widgets/Badge.png
  docs/extensibility/assets/display-widgets/Bagde2.png
  docs/extensibility/assets/display-widgets/CodeViewer.png
  docs/extensibility/assets/display-widgets/Columns.png
  docs/extensibility/assets/display-widgets/EventList-Hidden.png
  docs/extensibility/assets/display-widgets/EventList-InvolvedObject.png
  docs/extensibility/assets/display-widgets/EventList.png
  docs/extensibility/assets/display-widgets/EventListHiddenField.png
  docs/extensibility/assets/display-widgets/ExternalLink.png
  docs/extensibility/assets/display-widgets/ExternalLink2.png
  docs/extensibility/assets/display-widgets/ExternalLinks.png
  docs/extensibility/assets/display-widgets/JoinedArray.png
  docs/extensibility/assets/display-widgets/JoinedArray1.png
  docs/extensibility/assets/display-widgets/JoinedArray2.png
  docs/extensibility/assets/display-widgets/Labels.png
  docs/extensibility/assets/display-widgets/Lables.png
  docs/extensibility/assets/display-widgets/Panel.png
  docs/extensibility/assets/display-widgets/ResourceButton.png
  docs/extensibility/assets/display-widgets/ResourceLink.png
  docs/extensibility/assets/display-widgets/Table.png
  docs/extensibility/assets/display-widgets/Text.png
  docs/extensibility/assets/form-widgets/Alert.png
  docs/extensibility/assets/form-widgets/CodeEditor.png
  docs/extensibility/assets/form-widgets/Dropdown.png
  docs/extensibility/assets/form-widgets/Dropdown2.png
  docs/extensibility/assets/form-widgets/FormGroup.png
  docs/extensibility/assets/form-widgets/GenericList.png
  docs/extensibility/assets/form-widgets/KeyValue.png
  docs/extensibility/assets/form-widgets/MultiCheckbox.png
  docs/extensibility/assets/form-widgets/Name-DisableOnEdit.png
  docs/extensibility/assets/form-widgets/Name.png
  docs/extensibility/assets/form-widgets/Name2.png
  docs/extensibility/assets/form-widgets/Resource.png
  docs/extensibility/assets/form-widgets/ResourceRef.png
  docs/extensibility/assets/form-widgets/SimpleList.png
  docs/extensibility/assets/form-widgets/Switch.png
  docs/extensibility/assets/form-widgets/Text-Decoded.png
  docs/extensibility/assets/form-widgets/Text-Dropdown.png
  docs/extensibility/assets/form-widgets/Text-Info.png
  docs/extensibility/assets/form-widgets/Text.png
  examples/wizard/README.md
Labels: size/L, lgtm, cla: yes

#3668 fix: Adjust accessible names for form fields
  src/components/KymaModules/KymaModulesEdit.js
  src/resources/Jobs/ScheduleSection.js
  src/resources/Namespaces/MemoryQuotas.js
  src/shared/ResourceForm/components/FormField.js
  src/shared/ResourceForm/fields/KeyValueField.js
  src/shared/ResourceForm/fields/RuntimeResources.js
  src/shared/ResourceForm/inputs/ComboboxInput.js
Labels: size/S, lgtm, cla: yes

#3667 fix: Redirect in incorrect path
  src/components/App/IncorrectPath.js
Labels: size/S, lgtm, cla: yes

#3674 fix: SidebarNavigation margins
  src/sidebar/Sidebar.scss
  src/sidebar/SidebarNavigation.tsx
Labels: size/S, lgtm, cla: yes

#3677 fix: Adjust DynamicPage header margins and fix click
  src/shared/components/DescriptionHint/DescriptionHint.tsx
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
Labels: size/XS, lgtm, cla: yes

#3681 chore: Disable proxy endpoint
  backend/index.js
Labels: size/XS, lgtm, cla: yes

#3684 chore: Adjust informations in changelog
  .github/scripts/create_changelog.sh
Labels: size/S, cla: yes

#3685 Chore release messegaes 2
  .github/scripts/create_changelog.sh
Labels: size/XS, cla: yes

#3687 feat: Add check job
  .github/workflows/pr-all-checks-passed.yml
Labels: size/S, lgtm, cla: yes

#3689 chore: Release message
  .github/scripts/create_changelog.sh
Labels: size/S, lgtm, cla: yes

#3698 test: Fix logs and artifacts
  .github/workflows/busola-build.yml
  .github/workflows/pull-integration-cluster-k3d.yml
  .github/workflows/pull-integration-namespace-k3d.yml
  .github/workflows/pull-lighthouse.yml
  .github/workflows/pull-smoke-test-prod.yml
  .github/workflows/pull-smoke-test-stage.yml
  tests/integration/package.json
  tests/integration/tests/kyma-cluster/test-check-extensions.spec.js
  tests/integration/tests/namespace/test-deployments.spec.js
Labels: size/M, lgtm, cla: yes

#3676 feat: Add ability to expand manually added module to kyma
  src/components/KymaModules/KymaModulesAddModule.js
  src/components/KymaModules/KymaModulesEdit.js
  src/components/KymaModules/KymaModulesList.js
  src/components/KymaModules/components/ModulesCard.js
  src/components/KymaModules/support.ts
  src/shared/hooks/useDeleteResource.js
Labels: size/L, lgtm, cla: yes

#3695 feat: Add additional info on Module delete modal
  public/i18n/en.yaml
  src/components/KymaModules/KymaModulesList.js
  src/shared/hooks/useDeleteResource.js
Labels: size/M, lgtm, cla: yes

#3694 feat: Add unmanaged info on Modules List
  src/components/KymaModules/KymaModulesList.js
Labels: size/XS, lgtm, cla: yes

#3700 fix: Width of the buttons (ACC 282.1)
  src/shared/ResourceForm/components/ModeSelector.js
  src/shared/ResourceForm/components/ResourceForm.scss
  src/shared/components/ResourceCreate/ResourceCreate.js
  src/styles/index.scss
Labels: size/XS, lgtm, cla: yes

#3686 feat: Run dev k3d tests after build
  .github/workflows/pull-kyma-integration-tests.yml
Labels: size/S, lgtm, cla: yes

#3705 feat: Use workflow call to run integration tests after image build
  .github/workflows/busola-build.yml
  .github/workflows/pull-kyma-integration-tests.yml
Labels: size/S, lgtm, cla: yes

#3709 revert: Revert gh actions changes
  .github/workflows/busola-build.yml
  .github/workflows/pull-kyma-integration-tests.yml
Labels: size/S, cla: yes

#3699 feat: Add state of the Kyma modules in cluster overview
  public/i18n/en.yaml
  src/components/Clusters/views/ClusterOverview/ClusterDetails.js
  src/components/Clusters/views/ClusterOverview/ClusterModulesCard.tsx
  src/components/Clusters/views/ClusterOverview/ClusterOverview.scss
  src/components/KymaModules/support.ts
  src/shared/components/CountingCard/CountingCard.tsx
  tests/integration/tests/kyma-cluster/test-kyma-modules.spec.js
Labels: size/L, lgtm, cla: yes

#3707 fix: Improve Add Modules layout on small screens
  src/components/KymaModules/KymaModulesAddModule.scss
Labels: size/S, lgtm, cla: yes

#3713 chore: Bump Alpine and Node.js
  .github/workflows/accessibility-tests.yml
  .github/workflows/pull-integration-cluster-k3d.yml
  .github/workflows/pull-integration-namespace-k3d.yml
  .github/workflows/pull-kyma-integration-tests.yml
  .github/workflows/pull-lighthouse.yml
  .github/workflows/pull-smoke-test-prod.yml
  .github/workflows/pull-smoke-test-stage.yml
  .github/workflows/pull-unit-tests.yml
  Dockerfile
  Dockerfile.web
  README.md
  backend/Dockerfile
  kyma/README.md
Labels: size/M, lgtm, cla: yes

#3717 fix: Undefined in module name
  src/components/KymaModules/support.ts
Labels: size/XS, lgtm, cla: yes

#3718 chore: Update Sentry to newest version
  kyma/environments/dev/config.yaml
  kyma/environments/prod/config.yaml
  kyma/environments/stage/config.yaml
  kyma/package-lock.json
  kyma/package.json
  package-lock.json
  package.json
  public/defaultConfig.yaml
  src/hooks/useSentry.js
  src/hooks/useVersionWarning.ts
Labels: size/XL, lgtm, cla: yes

#3719 fix: Acc 264.4
  kyma/package-lock.json
  kyma/package.json
  src/shared/contexts/NotificationContext.tsx
Labels: size/XXL, lgtm, cla: yes

#3720 feat: Add replay session for sentry
  src/hooks/useSentry.js
Labels: size/M, lgtm, cla: yes

#3725 fix: Sentry replays
  src/hooks/useSentry.js
Labels: size/XS, lgtm, cla: yes

#3724 fix: Truncation of title and extension form
  src/components/BusolaExtensions/ExtensibilityStarterForm.scss
  src/resources/ReplicaSets/ReplicaSetDetails.js
  src/shared/components/DynamicPageComponent/DynamicPageComponent.scss
Labels: size/S, lgtm, cla: yes

#3728 chore: Disable snow feature
  kyma/environments/dev/config.yaml
  kyma/environments/stage/config.yaml
  public/defaultConfig.yaml
Labels: size/XS, lgtm, cla: yes

#3729 test: Run accessibility tests on PR
  .github/workflows/accessibility-tests.yml
  tests/integration/plugins/index.js
  tests/integration/tests/accessibility/test-acc-cluster.spec.js
  tests/integration/tests/accessibility/test-acc-cron-jobs.spec.js
  tests/integration/tests/accessibility/test-acc-custom-resoureces.spec.js
  tests/integration/tests/accessibility/test-acc-extensions.spec.js
  tests/integration/tests/accessibility/test-acc-modules.spec.js
  tests/integration/tests/accessibility/test-acc-namespace-overview.spec.js
  tests/integration/tests/accessibility/test-acc-performance.spec.js
  tests/integration/tests/accessibility/test-acc-pizzas.spec.js
Labels: size/L, cla: yes
